### ISSUE TITLE
Document what can go into config.ini

### ISSUE THREAD

**Issue by Hellowlol** [pkkid/python-plexapi#101]

**Comment by mjs7231** [comment]
I think adding an example config file might be a good idea (and also useful for testing), but auto-creating a default config file on import is probably a bad idea.

* We shouldn't assume we have write access to any directory on the system.
* We can't assume the user importing plexapi will even have a home directory.

Perhaps it would be a good idea to allow setting an environment variable for the location of the config file as well.  This way, they can set it to any directory (as ~/.congig/plexapi may not always be the correct choice).

**Comment by mjs7231** [comment]
Just added this which is worth mentioning..

commit 6e60d1107dddf4cbaf9fed28724a8b77e4bc0193
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Thu Jan 26 00:43:19 2017 -0500
Optional environment variable PLEX_CONFIG_PATH if you want something other than the default.

**Comment by Hellowlol** [comment]
we could just add example to the root dir. we can't expect the users to read the source code to figure out what to write in a config file.

**Comment by mjs7231** [comment]
I agree. I also plan on documenting it all as well.

**Comment by mjs7231** [comment]
Changing the title of this.  I think the request is less adding a default config file, and more to document exactly what can go in the config file. I'm planning to get to that this week in the documentation work.

**Comment by pkkid** [comment]
commit 4b1a5644092fcd7abacd2d89ef0f1a0105552cc0
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Sun Feb 19 22:18:23 2017 -0500
All config options can be set with environment variables
Update all os.environ calls to use CONFIG.get
Finish documenting configuration options.

http://python-plexapi.readthedocs.io/en/stable/configuration.html
