### ISSUE TITLE
Watchlist returns only the 20 first items due to default pagination

### ISSUE THREAD

**Issue by twolaw** [pkkid/python-plexapi#1012]
### Describe the Bug

The request to fetch watchlist items only returns the 20 first items because pagination is set to 20 by default.
Therefore, when user have more than 20 items in watchlist, the request doesn't return all items as expected.

https://github.com/pkkid/python-plexapi/blob/b919c20e69edfb6406844d29d4816ad36619720c/plexapi/myplex.py#L803

### Expected Behavior

Plex Desktop app sends request with 2 pagination parameters :

- X-Plex-Container-Start=0
- X-Plex-Container-Size=50

The full request is :
`https://metadata.provider.plex.tv/library/sections/watchlist/all?includeCollections=1&includeExternalMedia=1&includeAdvanced=1&includeMeta=1&X-Plex-Product=Plex Web&X-Plex-Version=4.89.1&X-Plex-Client-Identifier=<redacted>&X-Plex-Platform=Firefox&X-Plex-Platform-Version=103.0&X-Plex-Features=external-media,indirect-media,hub-style-list&X-Plex-Model=hosted&X-Plex-Device=Windows&X-Plex-Device-Screen-Resolution=1664x801,1664x936&X-Plex-Container-Start=0&X-Plex-Container-Size=50&X-Plex-Token=<redacted>&X-Plex-Provider-Version=5.1&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en`

I expect plexapi to use those pagination parameters and have a higher pagination limit (200 items ? seems a too high value returns _bad request_) to be able to fetch all watchlist items.

### Workaround

We cannot send the pagination limit as argument :
```python
my_watchlist = watchlist(X-Plex-Container-Size=200)
```
because hyphens are not allowed in variable names.
But we can send it as unpacked dict :
```python
param = {"X-Plex-Container-Size":200}
my_watchlist = watchlist(**param)
```

### Operating System and Version

Windows 10

### Plex Media Server Version

1.27.1.5916

### Python Version

3.9

### PlexAPI Version

4.12.1

**Comment by JonnyWong16** [comment]
#1009
