### ISSUE TITLE
plexapi.utils.download seems to be broken for images

### ISSUE THREAD

**Issue by HStep20** [pkkid/python-plexapi#1017]
### Describe the Bug

I am trying to download posters through the api, and it seems like any sort of image download is not working. Once downloaded, the image becomes unusable and unviewable with any tool. My code scans a library and downloads the poster beside the movie to 'poster.jpg', and yet no image comes out properly. Ive attached a link to what the download results in

https://user-images.githubusercontent.com/6693120/187123714-f604c7cf-1d84-405a-9fc5-eede935db857.jpg

### Code Snippets

```python
def download(self, url=None, filename=None, path=None):
        if not self.overwrite and os.path.isfile(path+'/'+filename):
            if self.verbose:
                print('SKIPPED:', path+'/'+filename)
            self.skipped += 1
        elif plexapi.utils.download(self.base_url, self.token, filename=filename, savepath=path):
            if self.verbose:
                print('DOWNLOADED:', path+'/'+filename)
            self.downloaded += 1
        else:
            print('DOWNLOAD FAILED:', path+'/'+filename)
            sys.exit()
```

### Expected Behavior

I expect the image to be downloaded as it displays in plex

### Operating System and Version

Windows 10, Ubuntu

### Plex Media Server Version

1.28.1.6104

### Python Version

3.8

### PlexAPI Version

4.11.2

**Comment by JonnyWong16** [comment]
What is `self.base_url`?

**Comment by HStep20** [comment]
self.base_url is the 'base url' of the server class being used in the script, which is the url of the plex server. So Im connecting to the server with `PlexServer(baseurl=base_url, token=token)`, getting the libraries, and scanning through each item in the library.

If a poster exists, it grabs the Path, which is the path to the movie file, appends /poster.jpg to it, and then 'downloads' the poster file to the path with the base_url and token of my server

**Comment by HStep20** [comment]
For reference, this is what the code looking for downloads looks like:

```python
items = plex.getAll()

    for item in items:
        if verbose:
            print('\nITEM:', item.title)

        path = plex.getPath(item)
        if path is None:
            print('ERROR:', 'failed to extract the path.')
            sys.exit()

        if (
            assets in {'all', 'posters'}
            and hasattr(item, 'thumb')
            and item.thumb != None
        ):
            plex.download(item.thumb, 'poster.jpg', path)
```

Assets is just a list of assets to be exported, and it checks for each individual ones

**Comment by JonnyWong16** [comment]
The download URL needs to be the URL to the image.

Example, you cannot have a download URL `https://github.com` with a filename `logo.png`. You have to download the full URL to the actual image `https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png`, then it will save it with a filename of `logo.png`.

You can get the full URL to posters/artwork using `.posterUrl` or `.artUrl`.

https://python-plexapi.readthedocs.io/en/stable/modules/mixins.html#plexapi.mixins.PosterUrlMixin.posterUrl

https://python-plexapi.readthedocs.io/en/stable/modules/mixins.html#plexapi.mixins.ArtUrlMixin.artUrl

**Comment by HStep20** [comment]
Wow, I feel stupid for not seeing that after a couple hours last night - I should have been using `self.base_url + url`, which was the actual url slug of the poster item, and not just base_url. Thanks
