### ISSUE TITLE
`show.seasons()` cut off at 19 seasons for Discover results

### ISSUE THREAD

**Issue by richardgetz** [pkkid/python-plexapi#1018]
### Describe the Bug

I am attempting to list all of the seasons within a watchlisted show. I cannot get it to go past 19. I have also tried first grabbing a shows child count, for example The Challenge has 38 seasons. This is correctly returned from show.childCount. I then manually call each season by using show.season(x). When I get to 20 it fails, even though I can see it correctly in Plex (both local and online metadata).

### Expected Behavior

I expect it to return all seasons within a show.

### Operating System and Version

macOS 12.5.1

### Plex Media Server Version

1.28.1.6104 

### Python Version

3.8.13

### PlexAPI Version

4.13.0

**Comment by JonnyWong16** [comment]
Edited your title to clarify this is for Discover results.

**Comment by richardgetz** [comment]
I believe this will fix it (it does for me) #1019
