### ISSUE TITLE
Choose Closest Thumbnail for Audio Tracks

### ISSUE THREAD

**Issue by pkkid** [pkkid/python-plexapi#102]
On the subject of music media thumbnails, is there value trying to pick the least distant non-NA thumbnail? Right now it uses the grandparent thumbnail (album, or artist?) but some of my media has only track thumbnails, artist thumbnails or album thumbnails. Picking the closest thumbnail in the hierarchy might be better than always punting to the same upper level.

**Comment by Hellowlol** [comment]
I cant see any trackthumb at all.

Cant we do something 
````
@property
def thumbUrl(self):
    """ Returns the URL thumbnail image for this track's album. """
    thumb = self.trackThumb or self.parentThumb or self.granparentThumb
    if thumb:
        return self.server.url(self.parentThumb)
````

**Comment by mjs7231** [comment]
That looks fine to me.

**Comment by pkkid** [comment]
commit 12406082ecef97369057f2f727848896244e98b4
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Wed Feb 15 00:13:22 2017 -0500
Choose Closest Thumbnail for Audio Tracks #102
