### ISSUE TITLE
Item cache of playlist after removing items is not updated

### ISSUE THREAD

**Issue by nkluge** [pkkid/python-plexapi#1030]
### Describe the Bug

After removing an item of a playlist, the item cache Playlist._items still holds the removed items.

### Code Snippets

```python
from plexapi.myplex import MyPlexAccount

PLEX_USER = ''
PLEX_PASSWORD = ''
PLEX_SERVER_NAME = ''

plex_account = MyPlexAccount(PLEX_USER, PLEX_PASSWORD)
plex_resource = plex_account.resource(PLEX_SERVER_NAME)
plex_server = plex_resource.connect()

# create a playlist with 3 entries
items = plex_server.search(query="love", mediatype='track', limit=3)
playlist = plex_server.createPlaylist(title="test", items=items)
print(len(playlist))  # =3

playlist.removeItems(items[0])

print(len(playlist))  # =3, but should be 2

# workaround:
playlist._items = None
print(len(playlist))  # =2
```

### Expected Behavior

see code snippet

### Operating System and Version

Windows 10

### Plex Media Server Version

1.28.1.6104

### Python Version

3.10.5

### PlexAPI Version

4.13.0

**Comment by JonnyWong16** [comment]
You need to reload objects.

```
print(len(playlist))  # =3

playlist.removeItems(items[0])

playlist.reload()

print(len(playlist))  # =2
```

**Comment by nkluge** [comment]
Thanks for the reply. This worked.

Maybe a hint in the doc string of `removeItems()` could be useful, that `reload()` should be called after removing items.

**Comment by JonnyWong16** [comment]
Well it's not just for playlists. Everything in PlexAPI requires reloading when changes are made. Adding that to every single method in the documentation seems excessive.
