### ISSUE TITLE
Missing X-Plex-Container-Size header on Collection request

### ISSUE THREAD

**Issue by the-jeffski** [pkkid/python-plexapi#1048]
### Describe the Bug

I've noticed recently a set of Missing X-Plex-Container-Size header. This will fail with status code 400 in the future.   errors appear in my plex server logs when the daily Plex-meta-manager run takes place.

Tracking this through the logs it occurs when a request is made to Plex for collections e.g. :
Nov 01, 2022 11:54:09.361 [0x7fe3d0bf0b38] DEBUG - Request: [192.168.90.10:58362 (WAN)] GET /library/collections/1663/children (3 live) #521 GZIP Signed-in Token (****) (a8247e23a735)
Nov 01, 2022 11:54:09.362 [0x7fe3d0bf0b38] WARN - [Req#521] Missing X-Plex-Container-Size header. This will fail with status code 400 in the future.

Having raised with them it seems to be coming back from the plexapi request for the Collection.items() method .   I don't see any mentioned of a change for this in Git but there was one made for some other calls. 

### Expected Behavior

No error in the log when a collection request is made.

### Operating System and Version

linux-x86_64 debian

### Plex Media Server Version

v1.29.1.6316-f4cdfea9c

### Python Version

3.10.8

### PlexAPI Version

4.12.1

**Comment by JonnyWong16** [comment]
Reference #990.

Plex is not going to publish a list of endpoints that will require the `X-Plex-Container-Size` header so we will need to address them one-by-one as they pop up.
