### ISSUE TITLE
Pass summary to playlist create

### ISSUE THREAD

**Issue by glensc** [pkkid/python-plexapi#1054]
### What is your feature request?

`Playlist` has `edit()` method that supports `summary`:
- https://python-plexapi.readthedocs.io/en/latest/modules/playlist.html#plexapi.playlist.Playlist.edit

Can the `summary` be added to `create()` method as well?

### Are there any workarounds?

make two API calls:

1. create playlist
2. edit playlist

**Comment by JonnyWong16** [comment]
Is this even possible when you manually create a playlist in Plex Web? If you can't then it's probably not possible.

**Comment by glensc** [comment]
Can't find a place where to create a playlist from the web. Seems you can only add items to "new playlist".

**Comment by JonnyWong16** [comment]
Right, so summary should be a separate `edit()`.
