### ISSUE TITLE
Error parsing settings enum values

### ISSUE THREAD

**Issue by OcifferAction** [pkkid/python-plexapi#1056]
### Describe the Bug

When attempting to add preroll to Plex by utilizing Plex-Meta-Manager or Rollarr I'm receiving the following error:

ValueError: not enough values to unpack (expected 2, got 1).

See detailed error log attached
[log.txt](https://github.com/pkkid/python-plexapi/files/10024589/log.txt)

### Code Snippets

```python
Traceback (most recent call last):                                                                 |
|   File "/app/pmm/plex_meta_manager.py", line 687, in run_collection
|     library.set_server_preroll(builder.server_preroll)
|   File "/app/pmm/modules/plex.py", line 481, in set_server_preroll
|     self.PlexServer.settings.get('cinemaTrailersPrerollID').set(preroll)
|   File "/usr/lib/python3.10/site-packages/plexapi/server.py", line 195, in settings
|     self._settings = Settings(self, data)
|   File "/usr/lib/python3.10/site-packages/plexapi/settings.py", line 20, in __init__
|     super(Settings, self).__init__(server, data, initpath)
|   File "/usr/lib/python3.10/site-packages/plexapi/base.py", line 56, in __init__
|     self._loadData(data)
|   File "/usr/lib/python3.10/site-packages/plexapi/settings.py", line 43, in _loadData
|     self._settings[id] = Setting(self._server, elem, self._initpath)
|   File "/usr/lib/python3.10/site-packages/plexapi/base.py", line 56, in __init__
|     self._loadData(data)
|   File "/usr/lib/python3.10/site-packages/plexapi/settings.py", line 119, in _loadData
|     self.enumValues = self._getEnumValues(data)
|   File "/usr/lib/python3.10/site-packages/plexapi/settings.py", line 142, in _getEnumValues
|     return {self._cast(k): v for k, v in [kv.split(':') for kv in enumstr.split('|')]}
|   File "/usr/lib/python3.10/site-packages/plexapi/settings.py", line 142, in <dictcomp>
|     return {self._cast(k): v for k, v in [kv.split(':') for kv in enumstr.split('|')]}
| ValueError: not enough values to unpack (expected 2, got 1)
```

### Expected Behavior

When running Rollarr or Plex-Meta-Manager to update Plex Preroll, the containers should be able to tell Plex to change the preroll paths based on a schedule.

### Operating System and Version

Unraid 6.11.3

### Plex Media Server Version

1.29.2.6364

### Python Version

3.10

### PlexAPI Version

4.13.1

**Comment by JonnyWong16** [comment]
Related discussion on Discord.

https://discord.com/channels/741380592104636467/803096038088114207/1034505845481939045

Conclusion: The `HardwareDevicePath` setting is missing a `key:value` pair in the `enum` values.

**Comment by jordanboucher42** [comment]
Hello,

Is #1057 going to be validated ? I have the same problem and friends too. This solution works.

Thanks for your job !
