### ISSUE TITLE
Security Alert when authorizing using Oauth2 in production.

### ISSUE THREAD

**Issue by Wamy-Dev** [pkkid/python-plexapi#1061]
### Describe the Bug

When authorizing Oauth2 using the built in [Oauth2](https://python-plexapi.readthedocs.io/en/latest/modules/myplex.html?highlight=oauth#plexapi.myplex.MyPlexPinLogin.oauthUrl) and going through the steps, you get this popup: ![alert](https://i.imgur.com/Towo6P2.jpg). Instead I would want it to show any name that I choose. ***THIS DOES NOT HAPPEN ON LOCAL HOST/DEV ENV***

### Code Snippets

```python
PlexAuth = MyPlexPinLogin(
        headers={
            'X-Plex-Client-Identifier': uuid,
            'X-Plex-Product': 'Mazi',
            'X-Plex-Version': 'Latest',
            'X-Plex-Platform': 'Plex Web',
            'X-Plex-Device': 'Linux',
            'X-Plex-Device-Name': 'Mazi'
        }, 
        oauth=True)
        return redirect(PlexAuth.oauthUrl(forwardUrl=f'https://api.mazi.pw/plexauth?email={email}'))

PlexAuth.run(callback=PlexAuth.stop(), timeout=60)
wait = PlexAuth.waitForLogin()
```

### Expected Behavior

I would want it to look like ![](https://i.imgur.com/nXtXgbv.png)

### Operating System and Version

NA

### Plex Media Server Version

NA

### Python Version

3.10.6

### PlexAPI Version

Latest

**Comment by JonnyWong16** [comment]
This is standard Plex security when the IP address used to generate the login code doesn't match the IP address trying to login. In other words, you will get the warning if the server has a different IP address than the client. The only way to avoid the warning is to do the login flow on the client side so the IP addresses match.

**Comment by Wamy-Dev** [comment]
Sounds good! Thanks for making that good point!

**Comment by JonnyWong16** [comment]
I haven't checked but maybe using the link code doesn't have the warning?

**Comment by Wamy-Dev** [comment]
Most likely won't, I can test it with mostly the same logic and get back to you. I most likely wouldn't use it anyways as oauth seems more seamless. Using it on the frontend to get the authorization token may be the way.
