### ISSUE TITLE
markPlayed and markUnplayed Error for medias from Plex Discover

### ISSUE THREAD

**Issue by twolaw** [pkkid/python-plexapi#1067]
### Describe the Bug

Plex Discover allows to get Movies and Shows that user don't have in PMS library.
Problem : the `markPlayed()` and `markUnplayed()` functions do not work for those medias found with `discover.provider.plex.tv` it raises a __plexapi.exceptions.NotFound__.

Movies and Shows (found from Plex Discover) watched status can be switched with Plex Client, we shoud be able to do it through Plex API too.

### Code Snippets

```python
>>> myMovie
<Movie:nan:Cairo-Conspiracy>
>>> myMovie.markPlayed()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\plexapi\mixins.py", line 274, in markPlayed
    self._server.query(key, params=params)
  File "C:\Users\me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\plexapi\server.py", line 705, in query
    raise NotFound(message)
plexapi.exceptions.NotFound: (404) not_found; https://metadata.provider.plex.tv/:/scrobble?key=nan&identifier=com.plexapp.plugins.library <Error error="Not Found" message="Not Found" statusCode="404"/>
```

### Expected Behavior

No error raised.
Just like items from user's PMS library.

### Additional Context

Requests to switch watched state of items from Plex Discover are :
```
https://discover.provider.plex.tv/actions/scrobble
https://discover.provider.plex.tv/actions/unscrobble
```

with data:
```
key=(ratingKey)
X-Plex-Token=(accessToken)
...
```

And we can check viewCount and lastViewdAt with request :
`https://metadata.provider.plex.tv/library/metadata/(ratingKey)/userState`

I think this uses the same Plex cloud database (linked to user account) to [sync PMS watched state and ratings](https://support.plex.tv/articles/sync-watch-state-and-ratings/).

### Operating System and Version

Windows 10

### Plex Media Server Version

1.29.2.6364

### Python Version

3.7

### PlexAPI Version

4.13.1

**Comment by RileyXX** [comment]
Using Plex Discover to mark items as played/unplayed is a clever way to do this. +1 for this issue

**Comment by glensc** [comment]
Started something:
- https://github.com/pkkid/python-plexapi/pull/1090

If you could test, would be awesome

**Comment by glensc** [comment]
@twolaw I think you should just use these methods in your project directly:
- https://github.com/pkkid/python-plexapi/blob/8652bee7fd87e37d098a15247259225a03119ce3/plexapi/myplex.py#L940-L959

later if https://github.com/pkkid/python-plexapi/pull/1090 gets merged can use the PlexApi methods.

**Comment by RileyXX** [comment]
Good work guys!
