### ISSUE TITLE
Feature request: Shuffle support for playlists

### ISSUE THREAD

**Issue by shenning00** [pkkid/python-plexapi#107]
It would be good to be able to play a shuffled playlist. 

Today I'm using the server playlist method to get access to the playlist. Then I pass that playlist off to the client playMedia method.

```
playlist = plex.playlist("Jazz Playlist")
client.playMedia(playlist)
```

I have no way to specify that I would like that playlist to be shuffled.

Inside the client playMedia() method a PlayQueue is created using createPlayQueue. The PlayQueue.create() method supports an option for setting shuffle=1. But there is not way to pass the option to the create() method. 

current...
```
    def playMedia(self, media, **params):
        if not self.server:
            raise Unsupported('A server must be specified before using this command.')
        server_url = media.server.baseurl.split(':')
        playqueue = self.server.createPlayQueue(media)
        self.sendCommand('playback/playMedia', **dict({
            'machineIdentifier': self.server.machineIdentifier,
            'address': server_url[1].strip('/'),
            'port': server_url[-1],
            'key': media.key,
            'containerKey': '/playQueues/%s?window=100&own=1' % playqueue.playQueueID,
        }, **params))
```

I could use the PlayQueue class to create a PlayQueue instance directly.

But, I can't pass playlist to the client playMedia() method.

The basic feature request is to be able to shuffle, repeat, etc. a playlist when played on a client.

The broader request might be to decouple the PlayQueue from the playMedia method. Or offer a new playMediaQueue (or some reasonable name) method.

Please let me know if I'm missing something and there is already a way to do this.

**Comment by mjs7231** [comment]
My current thinking is to add a new argument to `playMedia()` named something along the lines of `playqueue_options` where you could arbitrarily include kwargs that would in turn get passed through to `PlayQueue.create()`. These options would essentially be meaningless if playing a single media item, but shouldn't cause anything to break.

**Comment by shenning00** [comment]
@mjs7231 - That will work. A dictionary argument where it spelled out these are for the queue that is automatically created. 

But, it doesn't allow a developer to create their own PlayQueue then play it view the Client class.

Do you think it might also make sense to have a Client method for playQueue(queue) (or some reasonable name)? That way the developer can create, modify, etc. a queue. Then they could easily have a client play that queue with this method. I know you may not want to confuse the developer with two different ways to play content. To me this just seems more powerful.

Thanks.

**Comment by mjs7231** [comment]
Makes sense to me, good idea.

**Comment by Hellowlol** [comment]
Can't we just have a shuffle method and use random.shuffle to and pass that to play media?

**Comment by Hellowlol** [comment]
I can confirm that setshuffle works.

**Comment by mjs7231** [comment]
However, I don't think we have the ability to start playlist is shuffle mode if a user wishes.

**Comment by Hellowlol** [comment]
this commit allow you to manually set a playerque. This way you can shuffle on everything https://github.com/mjs7231/python-plexapi/pull/115/commits/53c12502569c97c9ba675127fda67fdb1875ac87

**Comment by pkkid** [comment]
commit 5e18776ee2a42c4bcee28127f52a0900a30c965c
Author: Hellowlol <hellowlol1@gmail.com>
Date:   Tue Feb 14 22:12:56 2017 +0100
add support to shuffle to createplayqueue and playlist.playqueue
See the tests for examples.

commit e93829f881f654fc20b322acfd440ccd3324c253
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Wed Feb 15 00:37:02 2017 -0500
Allow passing a playqueue to client.playMedia(); Default all mtype arguments to video.
