### ISSUE TITLE
Mis-use of __repr__

### ISSUE THREAD

**Issue by glensc** [pkkid/python-plexapi#1078]
### Describe the Bug

Please read the blog:
- https://www.digitalocean.com/community/tutorials/python-str-repr-functions

Which basically says:
> Well, the `__str__` function is supposed to return a human-readable format, which is good for logging or to display some information about the object. Whereas, the `__repr__` function is supposed to return an “official” string representation of the object, which can be used to construct the object again.

```py
class Person:

    def __init__(self, person_name, person_age):
        self.name = person_name
        self.age = person_age

    def __str__(self):
        return f'Person name is {self.name} and age is {self.age}'

    def __repr__(self):
        return f'Person(name={self.name}, age={self.age})'


p = Person('Pankaj', 34)

print(p.__str__())
print(p.__repr__())
```

```
Person name is Pankaj and age is 34
Person(name=Pankaj, age=34)
```

from this, looks like the `__repr__` should be renamed to `__str__` to match that convention, because these here mostly are in `<>`'s:

```py
    def __repr__(self):
        return f'<{self.__class__.__name__}:{self.ratingKey}>'

```

### Operating System and Version

Irrelevant

### Plex Media Server Version

Irrelevant

### Python Version

Irrelevant

### PlexAPI Version

4.13.2

**Comment by JonnyWong16** [comment]
You shouldn't be converting any object to a string in the first place.

https://docs.python.org/3/library/functions.html#repr

> Return a string containing a printable representation of an object. For many types, this function makes an attempt to return a string that would yield an object with the same value when passed to [eval()](https://docs.python.org/3/library/functions.html#eval); otherwise, **the representation is a string enclosed in angle brackets that contains the name of the type of the object together with additional information often including the name and address of the object.** A class can control what this function returns for its instances by defining a __repr__() method. If [sys.displayhook()](https://docs.python.org/3/library/sys.html#sys.displayhook) is not accessible, this function will raise [RuntimeError](https://docs.python.org/3/library/exceptions.html#RuntimeError).
