### ISSUE TITLE
Support Plex Webhooks?

### ISSUE THREAD

**Issue by pkkid** [pkkid/python-plexapi#108]
I wanted to start a discussion on Webhooks.

Plex announced Alexa integration today. While exciting, I don't think that we have much impact from this.  However, in the article about Alexa, they mentioned now supporting Webhooks for PlexPass members.  This sounds interesting to me..

Is this useful for API users in any way? -- I don't know much about it, but I imagine adding a method to supply a callback function when we notice a webhook event could be very useful. It would allow things like custom desktop notifications or taking some other action on events. Our API would simply make this integration easier to hook into.

https://www.plex.tv/blog/alexa-ask-plex-get-party-started/

**Comment by Hellowlol** [comment]
I'm excited about this too :)

**Comment by bendews** [comment]
Would definitely be a good feature to have!

**Comment by amazingr4b** [comment]
Plex's webhook action is great. I'm curious to see how you might integrate this. Since they added it I've been using the web.py library in a script that listens for plex webhook events and then uses your python api when reacting.

**Comment by pkkid** [comment]
commit 32a69db63e9508450678d5f3990e2bafe3128cee
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Sat Feb 25 01:56:12 2017 -0500
Support webhooks

4 new functions:
````python
MyPlexAccount.addWebhook(url)
MyPlexAccount.deleteWebhook(url)
MyPlexAccount.setWebhooks(urls)
MyPlexAccount.webhooks()
````
