### ISSUE TITLE
getstreamURL() seems to be broken

### ISSUE THREAD

**Issue by BenjaminOddou** [pkkid/python-plexapi#1116]
### Describe the Bug

When trying to stream videos from plex using the `getstreamURL()` function, the video starts correctly but when trying to move the slider (changing timecode) the media stops playing and it returns this error :

```shell
mkv demux error: cannot find any cluster or chapter, damaged file ?
prefetch stream error: cannot seek (to offset 179204)
```

This is happening for all my video files. I tried different sizes and type of files (`mkv`, `mp4`...) but didn't succeed to make it work.

### Code Snippets

```python
stream_url = media.getstreamURL()
vlc_instance = subprocess.Popen(['vlc', '-I', 'macosx', stream_url])
```

### Expected Behavior

I would expect the same behavior as running vlc with local medias.

### Operating System and Version

macOS 13.2.1 (22D68)

### Plex Media Server Version

1.31.1.6733

### Python Version

3.11.2

### PlexAPI Version

4.13.2

**Comment by JonnyWong16** [comment]
Try the dash protocol, but you also need to change the `.m3u8` to `.mpd`.

```python
stream_url = media.getStreamURL(protocol='dash').replace('.m3u8', '.mpd')
```

**Comment by BenjaminOddou** [comment]
Wow thank you soo much @JonnyWong16 ! It is working like a charm now ! 😄 Do you know if that's possible to include subtitles and / or audio tracks along with the video ? It doesn't seems to be shipped with the video.
