### ISSUE TITLE
Unclear how to use advancedFilters

### ISSUE THREAD

**Issue by BenjaminOddou** [pkkid/python-plexapi#1119]
### Describe the Bug

The advanced filters options as shown in the [docs](https://python-plexapi.readthedocs.io/en/latest/modules/library.html) doesn't seems to work properly on my side. It returns all movies of my library.

![doc](https://user-images.githubusercontent.com/85166574/223191866-e3fe2d1d-1181-4b46-bec3-e344345c0492.png)

### Code Snippets

```python
advancedFilters = {"and":[{"genre":325},{"genre":2160}]}
test = plex_instance.library.search(limit=15, libtype='movie', filters=advancedFilters)
```

### Expected Behavior

working like below:
"Correspond à tous les élements" => "all"
![test](https://user-images.githubusercontent.com/85166574/223190962-5bb20b29-c1dd-4d45-89b7-88975be17910.png)
![test2](https://user-images.githubusercontent.com/85166574/223190990-56374687-7541-4905-a6af-975399eb19f9.png)

### Operating System and Version

macOS 13.2.1 (22D68)

### Plex Media Server Version

1.31.1.6733

### Python Version

3.11.2

### PlexAPI Version

4.13.2

**Comment by JonnyWong16** [comment]
I cannot reproduce the issue. It is working fine for me.

```python
>>> advancedFilters = {"and": [{"genre": 3070}, {"genre": 3952}]} 
>>> plex.library.section("Movies (Test)").search(filters=advancedFilters)
[<Movie:2596:The-Dark-Knight>, <Movie:2595:Samurai-Cop>]
```
![image](https://user-images.githubusercontent.com/9099342/223206377-a254d102-610e-40c2-af8b-ce0e52ff8f01.png)
```xml
<Genre id="3070" filter="genre=3070" tag="Action"/>
<Genre id="3952" filter="genre=3952" tag="Crime"/>
```

**Comment by BenjaminOddou** [comment]
Oh I see ! I think the problem is that I need to search on a specific library section in order to use `advancedFilters`. It's not very clear in the docs though.

Here is the corrected syntax :
```python
advancedFilters = {"and":[{"genre":325},{"genre":2160}]}
test = []
for section in plex_instance.library.sections():
    if section.TYPE == 'movie':
        test.append(section.search(filters=advancedFilters))
```

returns:
```python
[[<Movie:321:Alien,-la-résurrecti>, <Movie:322:Alien,-le-huitième-p>, <Movie:318:Alien³>, <Movie:326:American-Nightmare>, 
<Movie:328:American-Nightmare-2>, <Movie:331:American-Nightmare-3>, <Movie:324:American-Nightmare-4>,
<Movie:333:Army-of-the-Dead>, <Movie:621:Doctor-Strange-in-th>, <Movie:57:Escape-Game>, 
<Movie:71:Glass>, <Movie:735:Pacific-Rim-:-Uprisi>, <Movie:305:World-War-Z>]]
```

**Comment by JonnyWong16** [comment]
The documentation for that `search()` method is under the `LibrarySection` class. The `search()` method under the `Library` class is different and has different documentaion.
