### ISSUE TITLE
retrieve guids is super slow

### ISSUE THREAD

**Issue by BenjaminOddou** [pkkid/python-plexapi#1128]
### Describe the Bug

When trying to retrieve guids from the api, the response become very slow.

retrieving movies guids :
```shell
61680 function calls (148385 primitive calls) in 0.401 seconds
```
retrieving movies genres :
```shell
151 function calls in 0.000 seconds
```

### Code Snippets

```python
import cProfile
from plexapi.server import PlexServer

plex_instance = PlexServer(baseURL, plexToken)
test = plex_instance.search('harry potter', mediatype='movie')

def myfunction():
    for m in test:
        print(m.guids) # replace by m.genres

cProfile.run('myfunction()')
```

### Expected Behavior

Same response time as other properties.

### Operating System and Version

macOS 13.2.1 (22D68)

### Plex Media Server Version

1.31.1.6733

### Python Version

3.11.2

### PlexAPI Version

4.13.4

**Comment by JonnyWong16** [comment]
This is expected.

A global Plex server search (hub search) doesn't provide `guids` in the response. This is equivalent to typing into the search box in Plex Web and displaying the results in the dropdown list. So to get the guids, PlexAPI has to make a second API call to `.reload()` the object (equivalent to clicking on one of the results in the dropdown list).

You should search in a specific library instead. This is equivalent to using the "Advanced Filters" in a library. This API response includes the `guids` so no additional API calls are required. 

```
plex.library.section('Movies').search('harry potter')
```

**Comment by BenjaminOddou** [comment]
Ok I see. In my case, I need a hub search so I was thinking querying `guids` only when needed by providing a unique identifier to the library section like so `plex_instance.library.sectionByID(int(sectionID)).getGuid(guid)` (guid can be retrived from hub search apparently). The drawback is that it will not work for agents like `hama`... Is there another unique identifier (except guid) that allows me to return a specific media in plex ?
