### ISSUE TITLE
Add ability to set progress on a media item without plex client

### ISSUE THREAD

**Issue by luigi311** [pkkid/python-plexapi#1130]
### What is your feature request?

Im hoping to get a setSeek(ms), or whatever name, similar to how you can use markWatched() and markUnwatched() on a media file from a library search. The goal of this is to allow external tools such as my tool JellyPlex-Watched to update the watch status of a tv show/movie to match what it is in another server be it plex or jellyfin. The goal is to set in progress status without needed to startup a plex client similar to how you can do complete watched status.

### Are there any workarounds?

Workarounds were developed utilizing get and put requests to plex endpoints and they also theorized methods of initiating a plexclient and then seeking to the time to update the watch status. More information can be found here on the endpoints, https://github.com/luigi311/JellyPlex-Watched/issues/47#issuecomment-1481879060

### Code Snippets

```python
GET - http://{plex-host}/:/timeline?ratingKey={ratingKey}&key={key}&state=stopped&time={time-in-milliseconds}&duration={duration-in-milliseconds}&X-Plex-Client-Identifier={plex-client-id}

PUT - http://{plex-host}/:/progress?key={key}&identifier=com.plexapp.plugins.library&time={time-in-milliseconds}&state=stopped&X-Plex-Token={plex-token}
```

**Comment by JonnyWong16** [comment]
Both update timeline and update progress are already implemented.

https://python-plexapi.readthedocs.io/en/stable/modules/base.html#plexapi.base.Playable.updateProgress

https://python-plexapi.readthedocs.io/en/stable/modules/base.html#plexapi.base.Playable.updateTimeline
