### ISSUE TITLE
Block out Plex Token

### ISSUE THREAD

**Issue by ravensorb** [pkkid/python-plexapi#1140]
### What is your feature request?

Add ability to blockout or obfuscate the Plex Token from all URLs in the plexapi object hierarchy.

### Are there any workarounds?

Manually iterating through all objects and properties and removing it manyally

### Code Snippets

```python
plexServer = PlexServer(serverUrl, token, hideToken=True)
```

### Additional Context

This would help for logging, diagnostics, and all around security.

**Comment by JonnyWong16** [comment]
Could you clarify what you are trying to achieve? This sounds like an [XY problem](https://xyproblem.info/).

**Comment by Hellowlol** [comment]
Yeah, really bad attempt imo.

There no way to remove the token. You can use the SecretsFilter if you want something removed from the logging
