### ISSUE TITLE
Include Extras when Fetching /library/metadata/<key> Items

### ISSUE THREAD

**Issue by pkkid** [pkkid/python-plexapi#116]
I just stumbled across a treasure trove of new information we could include by appending these items to the URL when fetching videos.  I am sure audio and possibly photos have similar arguments that can be added:

```checkFiles=1&includeExtras=1&includeRelated=1&includeRelatedCount=5&includeOnDeck=1&includeChapters=1&includePopularLeaves=1&includeConcerts=1&includePreferences=1```

**Comment by blacktwin** [comment]
I believe this can be closed. `video.reload()` addresses this.
