### ISSUE TITLE
PlexAPI In the Wild: Enhancement Requests

### ISSUE THREAD

**Issue by pkkid** [pkkid/python-plexapi#118]
There are a bunch of use cases in the wild where people are using PlexAPI, but we don't actually supply the functions they need to take actions.  Lets use this bug as a placeholder to track these and possibly open enhancements. **EDIT:** Removing complete items or items that already have their own bugs.

- [ ] [Library Management](https://www.reddit.com/r/PleX/comments/5tymws/automatically_create_an_imdb_top_250_movies/ddqhvqr/?st=iz5s38vo&sh=ecc0a61d) (Create, Update, Metadata)
- [ ] [Enable/Disable Remote Access](https://www.reddit.com/r/PleX/comments/5borsy/script_for_mediacom_isp_to_disable_remote_access/?st=iz5rvn4d&sh=a8ce9c5a)
- [ ] Edit, Add, Share Library
- [ ] Download Logs and Database
- [ ] Transcode Jobs
- [ ] Optimize Media
- [ ] Add/Delete users
- [x] Delete Indexes (delete to /library/sections/9/indexes?\<token\>)

**Comment by pkkid** [comment]
@Hellowlol - Can you elaborate on "Download pms log and database." a bit more? Is this something the PlexWeb client offers, or you wanted to dig into the filesystem to grab those?

**Comment by Hellowlol** [comment]
Yes, is something that's possible to do using the ui.

**Comment by Hellowlol** [comment]
So I thinking about adding setting. The idea is to make scrip that handles this for me.

I was think we should just mimic plex settings.
I would add a setting option to plex server, this just returns a base class with one property for each of settings tabs in each of this will return a class where the the elements attributes are lower case private attributes each for them will base a property matching plex API. Setting a property would do a http put request to prefs.

Thoughts?

**Comment by pkkid** [comment]
I agree we should having something like PlexServer.settings() that returns a new PlexSettings object where we can start to add the POST requests to update things. Seems like a rather large undertaking. I notice settings seem to be found here: `/:/prefs?X-Plex-Token=****`

**Comment by pkkid** [comment]
Moved Plex Settings duscussion to Bug #125.

**Comment by pkkid** [comment]
If you start a project would you mind make sure it has a bug and assigning it to yourself? I'll do the same.  I'm afraid to start working on a few things because I'm not sure if you started work on it yet or not. :D

**Comment by Hellowlol** [comment]
Will do :)

**Comment by pkkid** [comment]
This list is not very usable. Moving each item to its own bug.

**Comment by pkkid** [comment]
@Hellowlol Can you explain a bit more what you mean by "Transcode Jobs".  I'd like to get that into its own bug, but not really sure what to put.

**Comment by Hellowlol** [comment]
I was thinking about the converion tab.
