### ISSUE TITLE
Avoid partial match on .get() for show episodes

### ISSUE THREAD

**Issue by logictoad** [pkkid/python-plexapi#1193]
### Describe the Bug

Please excuse if I'm approaching this wrong, I'm quite new to python coding.

I'm using plexapi library section :
`local_lib_tv = plexlocal.library.section('TV Shows')`

I'm synchronizing data such as addedAt across shows and episodes between two plex servers, and when retrieving a show's episodes similar to this:
`episodes=local_lib_tv.get(videoentry.title).episodes()`

Example show tvtitle 'MasterChef Australia' will match episodes for 'Celebrity MasterChef'

I have no issues getting the show accurately using search but cannot iterate through episodes that way.
`videoentry=local_lib_tv.search(filters={"title=": tvtitle})[0]`

If that show is a partial match, how do I determine accurate results? Neither library seems to have any attributes that match between the servers other than the show title.

### Code Snippets

```python
(videoentry is result based on accurate .search result)

def local_tv_get_all_episodes(local_lib_tv, videoentry):
    print("Getting episodes for: ", videoentry)
    try:
        episodes=local_lib_tv.get(videoentry.title).episodes()
    except Exception:
        print(Exception)
    return(episodes)

>>> local_geteps=local_tv_get_all_episodes(local_lib_tv, videoentry)
Getting episodes for:  <Show:557653:MasterChef-Australia>
>>> print(local_geteps)
[<Episode:578856:Celebrity-MasterChef-s02e01>, <Episode:578857:Celebrity-MasterChef-s02e02>, <Episode:578858:Celebrity-MasterChef-s02e03>, <Episode:578859:Celebrity-MasterChef-s02e04>, <Episode:578860:Celebrity-MasterChef-s02e05>, <Episode:578870:Celebrity-MasterChef-s02e06>, <Episode:578910:Celebrity-MasterChef-s02e07>, <Episode:578914:Celebrity-MasterChef-s02e08>, <Episode:579000:Celebrity-MasterChef-s02e09>, <Episode:579045:Celebrity-MasterChef-s02e10>, <Episode:579095:Celebrity-MasterChef-s02e11>, <Episode:579099:Celebrity-MasterChef-s02e12>, <Episode:579223:Celebrity-MasterChef-s02e13>]
```

### Expected Behavior

Some sort of exact match / filtering for .get() that returns the right show for episode listing

### Operating System and Version

ubuntu-22.04

### Plex Media Server Version

Version 1.32.0.6973

### Python Version

3.10.6

### PlexAPI Version

4.14.0

**Comment by JonnyWong16** [comment]
`videoentry` is already a show object, so you can just call `videoentry.episodes()`.

**Comment by logictoad** [comment]
Where's that facepalm emoji?
