### ISSUE TITLE
NowPlaying 'live' thumbnail url

### ISSUE THREAD

**Issue by shenning00** [pkkid/python-plexapi#121]
Feature enhancement to provide a method of retrieving a transcode thumbnail of a video.

The NowPlaying view of Plex provides an updating view of a playing video. This is simply a transcoded (resized) frame at an offset into the video file.

![image](https://cloud.githubusercontent.com/assets/884816/23065412/245e5c04-f4db-11e6-8218-9df380a1596c.png)

Here's an example url: 

`http://192.168.1.211:32400/photo/:/transcode?url=http://127.0.0.1:32400/library/parts/239414/indexes/sd/833265&width=700&height=394&minSize=1`

The embedded url `(http://192.168.1.211:32400/library/parts/239414/indexes/sd/833265 `) is the offset frame into the video stream. The /status/sessions Video viewOffset attribute can be used as the index. (eg. `viewOffset="833265"`). 

It would be nice if there were two methods to do something similar in plexapi - 

1. plexserver.sessions() - could return an object that contains a url for transcoding an frame at the current offset into the video stream

2. a new utility function - provided a stream id and offset could return a transcode url

Lastly it might also be nice to have a method of retrieving the url as a png file.

I know this can be pieced together from the contents of sessions(), etc. But, for applications that don't have url formatting capabilities or don't support mechanisms for http GET processing - it might be nice to provide these convenience functions.

**Comment by Hellowlol** [comment]
Can't this be done today? There already exist a method to resize any image and there is a utility to download any file.

**Comment by shenning00** [comment]
@Hellowlol  - That would be great. I'm not trying to make this API into the "kitchen sink" of API's. So, if there is a way to put that together as part of the current API - that would work.

**Comment by Hellowlol** [comment]
Okei, so i was struggling with for a long time. I couldnt figure out why there was no indexes key. I mean like 30 minutes or so...

This is how you do it can do it after i have a sent a pr to add a pr to add indexes and some other shit.

````
for media in local_pms.sessions():
    url = None
    for part in media.iterParts():

        if part.indexes:
            url = '/library/parts/%s/indexes/sd/%s' % (part.id, media.viewOffset)

        if media.thumb:
            url = media.thumb

    if url:
        filename = 'session_transcode_%s_%s_%s' % (media.usernames[0], media._prettyfilename(), int(time.time()))
        url = local_pms.transcodeImage(url, height=100, width=100)
        download(url, filename=filename)
````

**Comment by shenning00** [comment]
Here's a copy of /status/session with a movie playing on one client.

```
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="1">
<Video addedAt="1478315807" art="/library/metadata/134642/art/1484208449" chapterSource="mixed" contentRating="PG" duration="6523947" guid="com.plexapp.agents.imdb://tt2948356?lang=en" key="
<Media id="<ID>" videoProfile="high" audioChannels="2" audioCodec="aac" bitrate="805" container="mp4" duration="6523947" height="360" optimizedForStreaming="1" protocol="dash" videoCodec="h2
<Part id="239414" indexes="sd" videoProfile="high" bitrate="805" container="mp4" duration="6523947" height="360" optimizedForStreaming="1" protocol="dash" width="720" decision="transcode" se
<Stream bitrate="549" codec="h264" default="1" duration="6523918" frameRate="29.969999999999999" height="360" id="376200" streamType="1" width="720" decision="copy" />
<Stream bitrate="256" bitrateMode="cbr" channels="2" codec="aac" default="1" duration="6523936" id="376201" language="English" languageCode="eng" selected="1" streamType="2" decision="transc
</Part>
</Media>
<Genre count="92" filter="genre=91" id="91" tag="Animation" />
...
<Director filter="director=29907" id="29907" tag="Byron Howard" />
...
<Writer filter="writer=29910" id="29910" tag="Jared Bush" />
...
<Producer count="2" filter="producer=9495" id="9495" tag="Clark Spencer" />
<Country count="510" filter="country=65" id="65" tag="USA" />
<Role count="2" filter="actor=10660" id="10660" role="Judy Hopps (voice)" tag="Ginnifer Goodwin" thumb="http://image.tmdb.org/t/p/original/vAH6j1A0L88R4UD9QX1nM9OLoYw.jpg" />
...
<User title="" />
<Player address="192.168.1.124" device="OSX" machineIdentifier="wisuhrx9rsg7amxl36wfm9sv" model="" platform="Firefox" platformVersion="51.0" product="Plex Web" profile="Firefox" remotePublic
<Session id="<REMOVED>" bandwidth="1594" location="lan" />
<TranscodeSession key="<REMOVED>" throttled="0" complete="0" progress="24.100000381469727" speed="18.399999618530273" duration="6523947" remaining="285" context="streaming" sourceVideoCodec=
</Video>
</MediaContainer>
```

**Comment by shenning00** [comment]
Here are the response headers for: `http://192.168.1.211:32400/photo/:/transcode?url=http://127.0.0.1:32400/library/parts/239414/indexes/sd/833265&width=700&height=394&minSize=1
`
```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Connection: Keep-Alive
Keep-Alive: timeout=20
Content-Length: 10222
Content-Type: image/jpeg
X-Plex-Protocol: 1.0
Cache-Control: max-age=259200
Date: Fri, 17 Feb 2017 23:14:14 GMT
```

**Comment by Hellowlol** [comment]
Thanks i wasnt sure what element had the indexer tag.

**Comment by shenning00** [comment]
@Hellowlol - not using http request is not so much a problem in general for me.

Recently I have been playing with Home Assistant. I added some custom components and modified some. One of the ones I modified was the plex component. I added the ability to direct a plex client to play a configured item (e.g. workout video). This tied with Alexa allows you to say - "Alexa, turn on workout video" - which in our house setup can invoke a script to turn on lights, whole home speakers, a TV, tune the Roku to the Plex app, and launch the workout video. This all works. And this plex component (that I did not write btw) is heavily reliant on plexapi.

I posted this update write-up on the Home Assistant forum and someone asked about being able to launch plex with a playlist. I wrote up how to modify the code to do that. Then they asked for shuffle support - one of the enhancements I requested here.

There is a new plexdevice component someone is working on to make the Home Assistant plex view look nicer. I decided it would be nice to add the live update and started playing with that. I had something working but knew it would be best if there was better support in plexapi.

I would like these Home Assistant components to use the plexapi as much as possible without having to parse xml directly or interface with requests separately. There might be tokens or headers that are missed or messed up. It just seems cleaner to go through a consistent interface.

**Comment by shenning00** [comment]
You can take a look at the "Workout Script w/ Plex Video Control" thread here:

https://community.home-assistant.io/t/workout-script-w-plex-video-control/

**Comment by Hellowlol** [comment]
I agree, some of my motivation for working on plex API is because I want to remove my own plex code in htpc manager. Btw it's very likely that your extensions will break with 3.0.0.

**Comment by Hellowlol** [comment]
Btw if you send a pr to allow query to allow http 204 it will be merged.

**Comment by shenning00** [comment]
@Hellowlol  - do you mean for plexapi? I haven't had an issue with a 204 in plexapi. The Roku API (python-roku) is where only the 200 is  being checked, not the 204.

I did post an issue with the jcarbaugh/python-roku. But, this not the project used by HA. So, I went to report an issue with his project bah2830/python-roku - and I can't find an option to submit an issue.  I'll probably send a pr on that project this weekend.

**Comment by Hellowlol** [comment]
I was referering to https://community.home-assistant.io/t/workout-script-w-plex-video-control/10849/7 i thought the 204 comment was about plexapi.

**Comment by shenning00** [comment]
Nope - plexapi is all good.

**Comment by pkkid** [comment]
commit e48a66e00c4dda576c0a851afe0f526341ecfc09
Merge: 228f049 049ef12
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Sun Feb 19 22:57:06 2017 -0500
Merge pull request #122 from Hellowlol/add_indexes
Add indexes. Closes https://github.com/pkkid/python-plexapi/issues/121

commit a546db6fe701f7b6132a4df2a25a1362fdbd74ac
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Sun Feb 19 23:05:33 2017 -0500
Function name in camelCase ot match rest of code

See `plexapi.utils.downloadSessionImages()`
