### ISSUE TITLE
Add ability to pull the Database Cache Size (MB) from the PlexAPI

### ISSUE THREAD

**Issue by bullmoose20** [pkkid/python-plexapi#1210]
### What is your feature request?

Add ability to read the Database Cache Size (MB) from the PlexAPI. Maybe even allow the api to set that value as well.

### Are there any workarounds?

none other than using the Plex Web UI | Settings | Show advanced and then scrolling down to the bottom of the page where you can see the value and modify it.
![image](https://github.com/pkkid/python-plexapi/assets/12549033/e727a826-576c-4309-974b-e52aaceccb87)

**Comment by JonnyWong16** [comment]
https://python-plexapi.readthedocs.io/en/latest/modules/server.html#plexapi.server.PlexServer.settings

```py
setting = plex.settings.get('DatabaseCacheSize')
setting.set(60)
plex.settings.save()
```

**Comment by bullmoose20** [comment]
Thanks!
I guess this was just added because I don't see the reference on that page as of yet?
![image](https://github.com/pkkid/python-plexapi/assets/12549033/bf316a49-a50d-4978-8d63-cf182995f1be)

**Comment by JonnyWong16** [comment]
![image](https://github.com/pkkid/python-plexapi/assets/9099342/13ea8616-95b5-43e9-ab20-25c517b2bd9b)

Readthedocs has weird page formatting for properties.

**Comment by bullmoose20** [comment]
Or maybe not:
```
>>> plex = PlexServer()
>>> setting = plex.settings.get('DatabaseCacheSize')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/Media-Scripts/.direnv/python-3.10.12/lib/python3.10/site-packages/plexapi/settings.py", line 54, in get
    raise NotFound(f'Invalid setting id: {id}')
plexapi.exceptions.NotFound: Invalid setting id: databaseCacheSize
```

**Comment by JonnyWong16** [comment]
You are connecting to the Plex server with an account that doesn't have permission to view settings (i.e. An account other than the admin).

**Comment by bullmoose20** [comment]
we are running as admin. I think that 1.29 does not expose this while 1.31 does
