### ISSUE TITLE
Respect timeout from server

### ISSUE THREAD

**Issue by glensc** [pkkid/python-plexapi#1225]
### What is your feature request?

Add support for `_server.timeout` being used instead (or addition to) global TIMEOUT

-----

PlexAPI may call `reload()` on property access, and that call is routed to server.query() which can only read the global TIMEOUT (because called with out timeout=xxx parameter):

```py
     def _reload():
        data = self._server.query(key)
```

Seems the problem is that each query method takes own timeout parameter, or uses global:
- https://github.com/pkkid/python-plexapi/blob/a7d29a3638bdbec6e223c373a47aeb36a2e60bd5/plexapi/server.py

and the global comes from config:
- https://github.com/pkkid/python-plexapi/blob/a7d29a3638bdbec6e223c373a47aeb36a2e60bd5/plexapi/__init__.py#L20

Reported in:
- https://github.com/Taxel/PlexTraktSync/issues/1455#issuecomment-1690624157

### Are there any workarounds?

Overwite the global `TIMEOUT` in `__init__.py`. Ugly but likely will work.

**Comment by JonnyWong16** [comment]
Probably easiest to change the `__init__` to `self.timeout = timeout or TIMEOUT`, then `query` to `timeout = timeout or self._timeout`.

PR welcome.

**Comment by glensc** [comment]
> `__init__` to `self.timeout = timeout or TIMEOUT`

that's not an issue. issue is in query. but probably makes sense for consistency.

but any ideas why overwriting TIMEOUT had no effect?
- https://github.com/Taxel/PlexTraktSync/issues/1455#issuecomment-1690631546
- https://github.com/Taxel/PlexTraktSync/issues/1455#issuecomment-1692621362

**Comment by JonnyWong16** [comment]
Because plexapi is importing `TIMEOUT` as a symbol in the local module. 

https://github.com/pkkid/python-plexapi/blob/b783a56edce87781ae83414d80f89ebed0685ab7/plexapi/server.py#L9

https://stackoverflow.com/a/3536638
