### ISSUE TITLE
Support Plex Settings

### ISSUE THREAD

**Issue by pkkid** [pkkid/python-plexapi#125]
Moving the discussion from another rollup bug..

**Hellowlol commented a day ago**
So I thinking about adding setting. The idea is to make scrip that handles this for me. I was think we should just mimic plex settings. I would add a setting option to plex server, this just returns a base class with one property for each of settings tabs in each of this will return a class where the the elements attributes are lower case private attributes each for them will base a property matching plex API. Setting a property would do a http put request to prefs.

**pkkid commented 26 minutes ago**
I agree we should having something like PlexServer.settings() that returns a new PlexSettings object or as you mentioned, maybe just a PlexServer.setting() function that returns a PlexSetting object that contains the methods needed to read or update the setting. The only problem with the latter is that it might cause us to have to fetch the settings URL every time we call it, rather than the standard fetch everything at once and call reload() to update it later if needed.

Seems like a rather large undertaking. I notice settings seem to be found here: /:/prefs?X-Plex-Token=****. Everything is returned as one giant XML response. Each settings seems to have a group attribute which might be useful to organize it in a similar way to the PlexWeb client layout. They also provide quite a few hints that could be very useful to making a generic PlexSetting() object that works for everything.

Why do you want to lower case all the attribute names? We don't really do it anywhere else.

**Comment by Hellowlol** [comment]
Because they are meant to be private. The property will also be renamed since the id attr in the Setting Element follow a CapitalOfAmerica naming so will force the first letter to lowercase

**Comment by pkkid** [comment]
Got it. I misunderstood.

**Comment by pkkid** [comment]
Going to start looking at this one tonight, if you already started something let me know and I'll stop.

**Comment by Hellowlol** [comment]
Gonna be busy for a couple of weeks so go for it.

**Comment by pkkid** [comment]
commit 91a8ab456331cae353057714e7a3d31c93b3c05a
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Thu Feb 23 01:33:30 2017 -0500
Checkpoint: Settings functionality works; Needs documentation

I have this working, it just needs documentation as well as a script to populate all the possible settings.  It'd be cool if I could ping our test server to auto-populate the available settings during the travis or readthedocs build, but I think we would have have a full PlexPass subscription to catch everything. Maybe it's worth sending them an email?

If you want to try it out, you can do something like the following:



```python
# List all settings
print(plex.settings.all())
print('My server is: %s' % plex.settings.friendlyName)

# Save some new values
plex.settings.friendlyName = 'My New Server Name'
plex.settings.collectUsageData = False
plex.settings.save()
```

**Comment by Hellowlol** [comment]
It looks really nice! 

> I have this working, it just needs documentation as well as a script to populate all the possible settings
I don't understand what you mean by this. What do you need to poplulate? Isnt that done by doing pms.settings ?

**Comment by pkkid** [comment]
This is what I meant by document everything. -- I still need to cleanup the sidebar a bit, not sure why all the setting categories are showing up there.
http://python-plexapi.readthedocs.io/en/stable/modules/settings.html#misc-settings

Settings definetly needs testing.  I only messed with 3 or 4 different actual settings (out of over 100). But it seems like everything will continue to work.

**Comment by Hellowlol** [comment]
Did you manually document this!?! Lol

**Comment by pkkid** [comment]
I didn't. I wrote a script in tools that iterates the settings and pulls out the label and summary fields.

**Comment by pkkid** [comment]
Closing this one; besides missing tests I'm happy.
