### ISSUE TITLE
rename isLatest()

### ISSUE THREAD

**Issue by BenjaminOddou** [pkkid/python-plexapi#1255]
### Describe the Bug

`isLatest()` return False when there is nothing to install and True when there is a new version available. I think it should be clearer to rename it (`isNewVersion()` ?) or to modify the function to return True when `canInstall` is 0 and False when `canInstall` is 1.

### Code Snippets

```python
plex_instance.isLatest()
```

### Operating System and Version

macOS 13.4.1

### Plex Media Server Version

1.32.5.7516

### Python Version

3.11.4

### PlexAPI Version

4.15.2

**Comment by JonnyWong16** [comment]
I should have caught that in #1253.

Just flip the return value.

**Comment by driiftkiing** [comment]
This isn't working anymore with dockerized plex (https://github.com/linuxserver/docker-plex).

when de update is installed:
<img width="567" alt="image" src="https://github.com/pkkid/python-plexapi/assets/8852364/93de1b42-e6b4-4fcd-a053-4473a63d18f2">

when the update is not installed:
<img width="1446" alt="image" src="https://github.com/pkkid/python-plexapi/assets/8852364/8a44f205-28fd-4af9-b578-54af42c62bba">

`canInstall` is always `0`

I'm handling the updates without the watchtower to make specific task before.

**Comment by JonnyWong16** [comment]
Maybe we should just revert #1253.

The reason `isLatest()` didn't work in #1252 was because Plex pulled a release. That should be a rare event and I don't think we should worry about working around it.
