### ISSUE TITLE
Plex 1.32.7 and above

### ISSUE THREAD

**Issue by JohnFawkes** [pkkid/python-plexapi#1261]
### Describe the Bug

Plex has changed the way it uses http requests. Using PUT requests is no longer allowed in 1.32.7.XXXX Requests are 404'd using PUT and now use GET instead.

### Additional Context

https://forums.plex.tv/t/refresh-endpoint-put-post-requests-started-throwing-404s-in-version-1-32-7-7484/853588
https://github.com/Cloudbox/autoscan/commit/e5575d5ffd35141615e9e144ff42d99aaa5b8af7
https://github.com/Cloudbox/autoscan/pull/219

### Operating System and Version

All

### Plex Media Server Version

1.32.7.XXXX

### Python Version

All

### PlexAPI Version

All

**Comment by JonnyWong16** [comment]
We already use `GET` to scan library file. 

https://github.com/pkkid/python-plexapi/blob/d5cad1fe1cc6cfcaa73795d3f750c72e058b5132/plexapi/library.py#L819

**Comment by JohnFawkes** [comment]
> We already use `GET` to scan library file.
> 
> https://github.com/pkkid/python-plexapi/blob/d5cad1fe1cc6cfcaa73795d3f750c72e058b5132/plexapi/library.py#L819

Thanks. I was asked by Sohjiro to raise an issue as PlexMetaManager was throwing the same errors as found in the plex thread on the fourms on 1.32.7.XXXX and we werent 100% sure that plexapi was using GET or PUT
