### ISSUE TITLE
Support Library Managment

### ISSUE THREAD

**Issue by pkkid** [pkkid/python-plexapi#127]
I have three requests to the server here that I couldn't find in your API wrapper:
https://gist.github.com/JonnyWong16/b1aa2c0f604ed92b9b3afaa6db18e5fd#file-plex_imdb_top_250_library-py-L36-L68

- [x] Creating a library
- [x] Updating a library (I could only find refresh all metadata)
- [ ] Changing the metadatas info fields

https://www.reddit.com/r/PleX/comments/5tymws/automatically_create_an_imdb_top_250_movies/ddqhvqr/?st=iz5s38vo&sh=ecc0a61d

**Comment by Hellowlol** [comment]
Updating a library is supported

**Comment by Hellowlol** [comment]
It's this done?

**Comment by blacktwin** [comment]
Just going through older issues looking to see if I can help. This one looks like it can be closed? @Hellowlol @pkkid
