### ISSUE TITLE
Support Add, Edit, Share Library

### ISSUE THREAD

**Issue by pkkid** [pkkid/python-plexapi#128]
This doesn't seem covered in basic settings, but is a common thing to want to manipulate.  We should support it. This should also cover adding and deleting users.

- [ ] Add, Delete Users
- [ ] Add, Edit, Share Library

**Comment by Hellowlol** [comment]
Ill take another stab on this one...

**Comment by Hellowlol** [comment]
I suggest we add a simple version of add library all advanced option should be passed as kwargs since we can't really show them to the user anyway.

Note to self: add a tourl or something on Settings.

**Comment by pkkid** [comment]
As long as its all documented, it sounds like a good idea to me.

**Comment by ninthwalker** [comment]
Was any of this ever added?
Specifically looking to edit an already shared users library.
ie: share library 'MyMovies' with existing user 'sally'

Tried with some general python POSTS but kept getting returned with:

`<Response code="400" status="You're already sharing this server with plexFriend. Please edit your existing share."/>`

Was using the following POST:

```
headers = {"X-Plex-Token": 'Ycx2134yTyaJHGFxKtgezn9',
           "Accept": "application/json"}
url = "https://plex.tv/api/servers/GUte86560eJHGa7fagde5j77dd4bjgrLGHT05/shared_servers"

payload = {"server_id": "GUte86560eJHGa7fagde5j77dd4bjgrLGHT05",
           "shared_server": {"library_section_ids": "[35723967]",
                                 "invited_id": "2120385"}
          }

r = requests.post(url, headers=headers, json=payload)
```

So I must have been doing the request wrong.
(Tokens in code all fake)

**Comment by pkkid** [comment]
We never looked into this yet, but will be in the coming weeks.

**Comment by Hellowlol** [comment]
Yes a good part of it was added in https://github.com/pkkid/python-plexapi/pull/139

**Comment by pkkid** [comment]
commit 624afd7082241fca06dea71ee8a0a85e1e96ec09
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Fri May 26 22:35:33 2017 -0400
Move share into MyPlexAccount.inviteFriend; Add abilities inviteFriend, updateFriend, RemoveFriend

A few notes:
* I removed the ability to share form the PlexLibrary object. The plex.tv API requires that we always send all the libraries we want to share (if its not included, it will be removed as a shared library). So if you tried to share a library it would remove all other shares for that user. I could have looked them up and append, but it would be more work than it was worth and require we run 3 or 4 queries just to get the information needed, then it got even more complicated when adding filters to a share.
* Also, my current thinking is that all communication to plex.tv should happen in the myplex.py module. It provides a clean way of thinking about the library and who is communicating with what.
