### ISSUE TITLE
Support Optimize Media

### ISSUE THREAD

**Issue by pkkid** [pkkid/python-plexapi#130]
This is a missing item that can be found in any Movie or TV Show Library's dropdown option.

**Comment by opsoyo** [comment]
With respect to priorities, has this feature been addressed? Thanks!

**Comment by Hellowlol** [comment]
Nope. The issue still open. I don’t think there any priorities. People tend to work and what they need. I think it would be easy to add support for this.

**Comment by opsoyo** [comment]
Well, I'm definitely interested in this feature. I am familiar with Python, but not with the structure of this project or how the Plex API operates. I would greatly appreciate anyone willing to work on this. 😄

**Comment by blacktwin** [comment]
Optimized and Conversions
GET
`http://127.0.0.1:32400/playlists/1111/items?type=42`

Reprocess Optimized
PUT
`http://127.0.0.1:32400/playlists/1111/items/55199/reprocess`

Delete Optimized
DELETE
`http://127.0.0.1:32400/playlists/1111/items/55199`

Create Optimized
PUT
`http://127.0.0.1:32400/playlists/1111/items?Item%5Btype%5D=42&Item%5Btitle%5D=The%20Meg&Item%5Btarget%5D=&Item%5BtargetTagID%5D=1&Item%5BlocationID%5D=-1&Item%5BLocation%5D%5Buri%5D=library%3A%2F%2F{librarySectionUUID}%2Fitem%2F%252Flibrary%252Fmetadata%252F107063%253FincludeExternalMedia%253D1&Item%5BPolicy%5D%5Bscope%5D=all&Item%5BPolicy%5D%5Bvalue%5D=&Item%5BPolicy%5D%5Bunwatched%5D=0&
`

**Comment by blacktwin** [comment]
Waiting on approval to merge.
