### ISSUE TITLE
Support Listing Conversions

### ISSUE THREAD

**Issue by pkkid** [pkkid/python-plexapi#131]
This can be accessed through Plex >> Status >> Conversion.  There may also be some options here to disable a conversion or such which would be nice to have as well.

**Comment by blacktwin** [comment]
GET
`http://127.0.0.1:32400/playlists/1111/items?type=42`
Looks like type 42 is set for conversions. `playlists/1111/items` seems to be the prefix for conversions and optimizing.

**Comment by blacktwin** [comment]
Remove conversion.
PUT
`http://127.0.0.1:32400/playlists/1111/items/55198/106724/disable`

`55198` was the ID for the conversion. Will need to confirm what `106724` is, maybe the mediaPart?

**Comment by blacktwin** [comment]
Other optimize and conversion related actions are listed in #130. This issue only stated listing conversions.

**Comment by blacktwin** [comment]
I believe this can be closed. Actions will be addressed for #130 with #426.
