### ISSUE TITLE
Add support for track genres in music libraries

### ISSUE THREAD

**Issue by jackctra** [pkkid/python-plexapi#1321]
### What is your feature request?

After the plex beta version 1.40.0.7775 enabled genres for tracks in music libraries it would be fantastic to be able to fetch and change genres for individual tracks analoguous to album genres. (This is all the more true as plex has so far only used genres as a filter without having added a corresponding field to the tracks.) 

### Are there any workarounds?

-

### Code Snippets

```python
-
```

**Comment by JonnyWong16** [comment]
#1318
