### ISSUE TITLE
locations is empty when casting to dict

### ISSUE THREAD

**Issue by luigi311** [pkkid/python-plexapi#1337]
### Describe the Bug

When you cast to a dictionary via __dict__ it looks like locations is an empty list. You can test this with a show, movie or episode class object and calling __dict__ on it and checking the locations key.  

### Code Snippets

```python
show_object.__dict__
```

### Expected Behavior

locations to be populated with a list containing dictionaries

### Operating System and Version

Windows 10

### Plex Media Server Version

1.32.8.7639-fb6452ebf

### Python Version

3.9.13

### PlexAPI Version

4.15.5

**Comment by JonnyWong16** [comment]
You have a partial object.

https://python-plexapi.readthedocs.io/en/latest/modules/base.html#plexapi.base.PlexPartialObject.isFullObject

You need to reload it to a full object.

https://python-plexapi.readthedocs.io/en/latest/modules/base.html#plexapi.base.PlexObject.reload

**Comment by luigi311** [comment]
That works perfectly and seems to fix the issue for show. Interesting about movie and episode, ill see if i can work around that then. Thank you
