### ISSUE TITLE
Infrastructure Improvements

### ISSUE THREAD

**Issue by Hellowlol** [pkkid/python-plexapi#136]
- [x] Add example config file.
- [ ] Add landscape.yml https://docs.landscape.io/configuration.html
- [x] See if adding the travis secrets to the travis file makes the builds more robust.
- [x] Add flake8 file

**Comment by pkkid** [comment]
Example config file is documented here: http://python-plexapi.readthedocs.io/en/stable/configuration.html

**Comment by Hellowlol** [comment]
Yeah, saw that. I still think we should include a sample file. Pretty much any other program does

**Comment by pkkid** [comment]
I don't think the secrets are what's causing the builds to error out.  It seems it always hangs after the tests are complete, but before the next command. I don't see the flake8 command being run when it halts.  I suspect it has something to do with the coverage reporting.

**Comment by Hellowlol** [comment]
Mine fails since there is no matching environment names. I think I have to update it.

**Comment by Hellowlol** [comment]
Oh, add Travis notifications to the slack channel.

**Comment by pkkid** [comment]
Ahh I see what you mean. If you make a fork off the main repo (pkkid) and then create branches from there, the builds will pass. The reason Travis doesn't include secrets with pull requests is because it's a security issue. Someone could make a pull request that simply prints the secrets then grab them from the public Travis logs.

**Comment by Hellowlol** [comment]
@pkkid Should travis release to pypi on tags and passing tests?

**Comment by pkkid** [comment]
I'm fine automating posting to pypi, do other projects do that?

Did I link to discord somewhere?  Didn't mean to.

**Comment by Hellowlol** [comment]
I have a couple of projects on pypi that does that. Dunno if its recommended, but that way i can update the package to pypi without having access to your password :)

**Comment by Hellowlol** [comment]
@pkkid Should Travis build and push new docs? Can you add a sample config file? I don't use a config file and assume you have one with all the options.

**Comment by pkkid** [comment]
The only config file for this is. I do not have anything special on my machines that is not checked in. https://github.com/pkkid/python-plexapi/blob/master/docs/conf.py
