### ISSUE TITLE
Add View History Manually

### ISSUE THREAD

**Issue by speedyflipper** [pkkid/python-plexapi#1365]
### What is your feature request?

With the recent update to Plex, calling MarkPlayed no longer creates a history record. I would like an option that would still create the record. 

I've tried setting the progress to >=90% and then marking played but the record was not created. The next idea which I haven't tried is to set the progress and "play" the video on a "virtual" client

### Are there any workarounds?

I have not found any workaround besides manually inserting a record in the database

**Comment by JonnyWong16** [comment]
This isn't possible to do using the API. Database editing is outside the scope of the PlexAPI library.

**Comment by speedyflipper** [comment]
I understand database editing is outside the scope. I'm looking for a solution that won't require any database editing.
