### ISSUE TITLE
createPlaylist does not guard smart=True and non-empty items

### ISSUE THREAD

**Issue by glensc** [pkkid/python-plexapi#1375]
### Describe the Bug

Seems `server.createPlaylist(self.name, items=items, smart=True, section=section)` does not guard `smart=True` and non empty `items`.

While other methods like `playlist.removeItems()` and `playlist.addItems()` guard that you do not add items with smart playlist.

The outcome is that created smart playlist doesn't actually contain the items, but something more (haven't figured out what yet, seems like the whole library is added to such smart playlist)

See details of this exploration:
- https://github.com/Taxel/PlexTraktSync/pull/1832#issuecomment-1962421451

### Operating System and Version

Irrelevant

### Plex Media Server Version

Irrelevant

### Python Version

Irrelevant

### PlexAPI Version

4.15.10

**Comment by JonnyWong16** [comment]
Thanks, can you submit a fix?

**Comment by glensc** [comment]
https://github.com/pkkid/python-plexapi/pull/1377
