### ISSUE TITLE
Connect to Resource Seems Broken

### ISSUE THREAD

**Issue by pkkid** [pkkid/python-plexapi#138]
I was trying to connect to a remote resource and it was failing.  The logs seem to make it look like we were connecting to the wrong URI. I want to dig into this a bit more.

**Comment by jvonhoff** [comment]
Possibly not the same issue, but when I follow the Plex account snippet from the README:

```
from plexapi.myplex import MyPlexAccount
account = MyPlexAccount('<USERNAME>', '<PASSWORD>')
plex = account.resource('<SERVERNAME>').connect()  # returns a PlexServer instance
```
When I run that (with user/pass & server names filled in, obviously), I'm getting 
```
  File "/usr/lib/python3.6/site-packages/plexapi/myplex.py", line 20, in __init__
    self.authenticationToken = data.attrib.get('authenticationToken')
AttributeError: 'str' object has no attribute 'attrib'
```

Is this related, am I doing something wrong, or should I open a new issue?

**Comment by pkkid** [comment]
Can you load this page and look for the `accessToken` attr in the server you're trying to connect to?  I suspect it's not there.

```bash
https://plex.tv/api/resources?includeHttps=1&X-Plex-Token=<TOKEN>
```

You can get your token from the account object you had above `account._token`

**Comment by jvonhoff** [comment]
I'm not sure what you mean about getting the token (last line).  But, I can load `https://plex.tv/api/resources?includeHttps=1` (without the X-Plex-Token parameter) and I see an XML response.  My buddy (Device name="Office") shows an accessToken (highlighted blue), but mine (Shockwave) does not. Could it be my httpsRequired?  I also have my server set to "Secure connections = Required".  Let me know if I redacted something that would help you, or if I should have redacted something else!

![image](https://cloud.githubusercontent.com/assets/8107932/25409915/4657c0c2-29d1-11e7-9361-b47a3a90bdb7.png)

**Comment by jvonhoff** [comment]
Just saw your edit... I'm running from pip.  I'll try the git master branch, too, but I'm assuming the missing token in my screenshot would be problematic.

**Comment by pkkid** [comment]
Looking at the error again, it seems very much like you are running the old pip version and using the documentation from the README on the new master branch. The API is changing slightly in the new version (yet to be released to pip).  You can see the old readme here:

https://pypi.python.org/pypi/PlexAPI/2.0.2

**Comment by jvonhoff** [comment]
Yep... I ran a git clone, and now I can connect just fine.  Thanks!

**Comment by pkkid** [comment]
Thanks for the update!
