### ISSUE TITLE
Using the .get function to differentiate between movies with the same title?

### ISSUE THREAD

**Issue by SamZako** [pkkid/python-plexapi#1385]
### What is your feature request?

Was wondering if it's possible to use the .get function to differentiate between movies with the same title from different years. In my library I've got 3 movies titled 'Halloween' (1977, 2007, 2018), below is what I'm running, trying to update the 2007 one specifically:

`plex.library.section('Movies').get('Halloween').rate(8.0)`

**Comment by JonnyWong16** [comment]
`LibrarySection.get()` accepts the same `kwargs` as `LibrarySection.search()`.

https://python-plexapi.readthedocs.io/en/latest/modules/library.html#plexapi.library.LibrarySection.get

```py
plex.library.section('Movies').get('Halloween', year=2018)
```
