### ISSUE TITLE
Get watch history for non-owner user

### ISSUE THREAD

**Issue by karan** [pkkid/python-plexapi#1392]
### What is your feature request?

`MyPlexAccount(token=TOKEN).history()` should return history for non-owner user. When the oauth token belongs to the owner, it works as expected. For other users it does not even though the token is valid.

### Are there any workarounds?

None that I can get to work. Pretty much every other API I tried seems to only work for owner.

### Code Snippets

```python
try:
            user_account = MyPlexAccount(token=userInputs.user_plex_token)
            logging.info("Connected to Plex account for %s", user_account.username)
        except Exception as e:
            logging.error("Plex Authorization error", e)
            return

        # Get all history for movies and shows
        logging.info("Starting watch history collection run...")
        all_history = user_account.history(maxresults=HISTORY_MAX_RESULTS)
```
```


### Additional Context

_No response_

**Comment by JonnyWong16** [comment]
Shared users do not have access to your Plex Dashboard. It's only accessible by the admin.

You need to get the history using your admin account and filter it using the user `accountID`.

**Comment by JonnyWong16** [comment]
Then you need to get the history from each individual server using the admin and filter it.

**Comment by karan** [comment]
I thought there would be a way to get history for an account (not Plex user) using oauth token, but I guess not. 

Thanks though, this seems like an upstream Plex API limitation.
