### ISSUE TITLE
Support saving remote playlist items

### ISSUE THREAD

**Issue by glensc** [pkkid/python-plexapi#1409]
### What is your feature request?

Reverse to https://github.com/pkkid/python-plexapi/pull/1335

Able to add remote server items to playlist.

I've inspected Network tab in browser, and it seems to make this `PUT` request (urldecoded for readability) 

- `http://localhost:32314/playlists/<playlist_id>/items?uri=server://<server_id>/com.plexapp.plugins.library/library/metadata/<key>`

**Comment by glensc** [comment]
I wonder how can you mix two servers in same request

For single server it's:
- `items?uri=server://<server_id>/com.plexapp.plugins.library/library/metadata/<key1>,<key2>`

repeat uri?
- `items?uri=server://<server1_id>/com.plexapp.plugins.library/library/metadata/<key1>,<key2>&uri=server://<server2_id>/com.plexapp.plugins.library/library/metadata/<key3>,<key4>`

**Comment by JonnyWong16** [comment]
My guess is Plex won't allow adding items from different servers in the same API call. You probably need to add from one server at a time.

**Comment by glensc** [comment]
With multiple calls, how can I ensure the order? Seems to become overly complex if need to split to multiple calls.

**Comment by glensc** [comment]
Could do move, so every "other server" items need to be moved:
- http://localhost:32314/playlists/21515/items/18725/move?after=18658

in above example I moved foreign server entry.

I foresee already problem with their implementation if they use key (and no server) as primary key in the playlist, i.e collision of same key value from different servers.

lucky guess, maybe bulk move also works:
- - http://localhost:32314/playlists/21515/items/18725,18726,18727/move?after=18658

**Comment by JonnyWong16** [comment]
I don't see any way to add items from multiple servers at the same time in Plex Web. The only way I can find to select items from multiple servers is using different hubs pinned on the homepage, but the "Add to Playlist" button disappears as soon as you multi-select from different servers. I really don't think Plex allows this in one single API call.

You would need to make two separate API calls:

```
PUT http://localhost:32314/playlists/<playlist_id>/items?uri=server://<server1_id>/com.plexapp.plugins.library/library/metadata/<key1>,<key2>
PUT http://localhost:32314/playlists/<playlist_id>/items?uri=server://<server2_id>/com.plexapp.plugins.library/library/metadata/<key3>,<key4>
```

Which results in the order `<key1>, <key2>, <key3>, <key4>`.

If you want `<key1>, <key3>, <key2>, <key4>`, then you would need to make 4 API calls.

We could handle multiple server item ordering automatically internally in the PlexAPI library (i.e. make the separate API calls for the user).

**Comment by JonnyWong16** [comment]
Try #1411
