### ISSUE TITLE
Problems with DELETE USER

### ISSUE THREAD

**Issue by OriginsTV** [pkkid/python-plexapi#1412]
### Describe the Bug

Does anyone have problems with the DELETE USER endpoint?

plextemp.myPlexAccount().removeFriend(email or user)

BadRequest: (410) gone; https://plex.tv/api/friends/333526617 <?xml version="1.0" encoding="UTF-8"?> <Response code="410" status="This endpoint was deprecated and removed"/>

### Operating System and Version

Ubuntu 20.04

### Plex Media Server Version

1.24.27.33

### Python Version

3.8.17

### PlexAPI Version

4.7.2

**Comment by JamsRepos** [comment]
We are getting the same thing with our project Wizarr. We are on the latest package however.

```
 name         : plexapi
 version      : 4.15.12
 description  : Python bindings for the Plex API.

dependencies
 - requests *
 ```
 
 It seems this endpoint is using v1 instead of v2.

**Comment by JonnyWong16** [comment]
Plex deprecated that endpoint.

**Comment by JamsRepos** [comment]
> Plex deprecated that endpoint. 

And is there a replacement? Or is that just it?

**Comment by JonnyWong16** [comment]
> And is there a replacement?

Presumably, but I don't know what it is yet.

**Comment by JamsRepos** [comment]
> > And is there a replacement?
> 
> Presumably, but I don't know what it is yet.

It looks to have changed to `https://clients.plex.tv/api/v2/sharings/65659334` instead.

**Comment by MrDynamo** [comment]
Any update on getting this fixed? I tested the linked PR and it resolves the issue.

**Comment by BoHoliday** [comment]
Any update?
