### ISSUE TITLE
Can't find Netcast device

### ISSUE THREAD

**Issue by triggz** [pkkid/python-plexapi#142]
I have an LG Plasma running plex for netcast v3.3. plexapi doesn't seem to find it at all. I can successfully find and control my other devices for example:

```
for client in plex.clients():
    print(client.title)
```

output with my phone connected:
```
V20
Process finished with exit code 0
```

output with my TV connected:
`
Process finished with exit code 0`

FYI plex itself has no problem finding the TV, the plex app seems to be working flawlessly

**Comment by pkkid** [comment]
I'm still learning how clients are seen by PlexServer myself.  Is the PlexServer on the same network as your TV?  If so, try connecting to PlexServer() with it's local IP address and not one of the domains served up by Plex.tv. It may be able to see it then.

**Comment by pkkid** [comment]
Closing as there is no response. Please reopen if you still need help.

**Comment by Hellowlol** [comment]
I think he cant see it as it isnt listed in /clients. I cant find plex for samsung in /clients atleast
