### ISSUE TITLE
LAN plex.direct domain does not match SSL certificate

### ISSUE THREAD

**Issue by nmaggioni** [pkkid/python-plexapi#143]
My Plex server runs in a separate subnet, with an address hereby reported as `plex.mylandomain`.
Whenever I try to connect to it the requests gets rerouted as it's supposed to, but the SSL certificate for the different domain (`*.plex.direct`) won't get accepted.

```python
plex = PlexServer("https://plex.mylandomain:32400", "mytoken")
```
```python
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 342, in connect
    _match_hostname(cert, self.assert_hostname or hostname)
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 352, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/lib/python3.6/ssl.py", line 325, in match_hostname
    % (hostname, dnsnames[0]))
ssl.CertificateError: hostname 'plex.mylandomain' doesn't match '*.953a734ff9e84d02bf374f28737b6304.plex.direct'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 630, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: hostname 'plex.mylandomain' doesn't match '*.953a734ff9e84d02bf374f28737b6304.plex.direct'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nmaggioni/.local/lib/python3.6/site-packages/plexapi/server.py", line 47, in _connect
    return self.query('/')
  File "/home/nmaggioni/.local/lib/python3.6/site-packages/plexapi/server.py", line 107, in query
    response = method(url, headers=headers, timeout=TIMEOUT, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname 'plex.mylandomain' doesn't match '*.953a734ff9e84d02bf374f28737b6304.plex.direct'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nmaggioni/.local/lib/python3.6/site-packages/plexapi/server.py", line 27, in __init__
    data = self._connect()
  File "/home/nmaggioni/.local/lib/python3.6/site-packages/plexapi/server.py", line 50, in _connect
    raise NotFound('No server found at: %s' % self.baseurl)
plexapi.exceptions.NotFound: No server found at: https://plex.mylandomain:32400
```

I'm running v2.0.2 pulled with pip. I'd eagerly help in fixing this, but I cannot locate the right entry point in the current source tree of the library when comparing the code to my local pip-pulled copy...

Disabling certificate validation could be a solution, but doing so by default would be unsafe. What about catching the exception and, if the received hostname matches a `\*\.[0-9A-Za-z]+\.plex.direct` regex of sort, re-execute the request with the SSL certificate checking disabled?

I suppose this would also enable [other products that use this library](https://github.com/home-assistant/home-assistant/issues/7422) to talk with a Plex Server with enforced encryption in place.

**Comment by pkkid** [comment]
As far as I know the certificates on the server are for the domains that plex.tv hands out.  They generally look something like: `https://1-2-3-4.bb76d8798f775bfb44c7d8f6.plex.direct:32400`. If you're trying to connect to it with a different domain, then the ssl cert plex provides will not be valid, you would need to provide your own certificate for your own domain.

If you try connecting via http instead of https does it work?

A few things we could do:
* Provide an option to ignore cert warning allowing you to connect to https anyway, not validating the cert.
* Better error handing here may be useful.

Lastly, you might want to pull the master branch and run that instead. This won't solve your problem, but a ton of misc stuff was fixed, it would be nice to use that as the base for future discussions. The API changed a bit and a big lot of misc bugs have been fixed. `pip install git+https://github.com/pkkid/python-plexapi.git`

**Comment by pkkid** [comment]
I'll add the disable cert verification option in tonight. It looks quite painless actually.

**Comment by Hellowlol** [comment]
Just use your own session object where verify=False

**Comment by pkkid** [comment]
Can you set `verify=False` on the session?  I didn't see it [on their docs page](http://docs.python-requests.org/en/master/user/advanced/).

@nmaggioni What he's saying is try this (on the master branch).

```
import requests
from plexapi.myplex import MyPlexAccount

session = requests.Session(verify=False)
plex = PlexServer("https://plex.mylandomain:32400", "mytoken", session)
```

**Comment by Hellowlol** [comment]
Im pretty sure, im on my phone so i to lazy to look it up. It not just set the property before passing it to plex server

**Comment by nmaggioni** [comment]
Sorry for the long wait.

@pkkid :
+ For security reasons HTTPS is enforced on my server, through Plex's settings.
+ The server is already reachable through a LAN hostname, and the `*.plex.direct` domains are correctly being mapped to the internal host by the router's NAT - [as advised in Plex's documentation in the "DNS Rebinding" section](https://support.plex.tv/hc/en-us/articles/206225077-How-to-Use-Secure-Server-Connections).

@Hellowlol : It works!

```python
>>> session = requests.Session()
>>> session.verify = False
>>> plex = PlexServer("https://plex.mylandomain:32400", "mytoken", session)
/home/myuser/.local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
>>> plex
<PlexServer:https://plex.mylandomain:32400>
>>> 
```

**Comment by Hellowlol** [comment]
@nmaggioni Awesome.You can disable the warnings by using ````requests.packages.urllib3.disable_warnings()```` @pkkid Thanks adding a session object!

**Comment by reconman** [comment]
I prefer this over the solution above:
```python
class HostNameIgnoringAdapter(HTTPAdapter):
    def init_poolmanager(self, connections, maxsize, block=..., **pool_kwargs):
        self.poolmanager = PoolManager(num_pools=connections,
                                       maxsize=maxsize,
                                       block=block,
                                       assert_hostname=False)
session = Session()
session.mount("https://", HostNameIgnoringAdapter())
plex = PlexServer("https://plex.mylandomain:32400", "mytoken", session)
```

This way, the certificate is validated and only the hostname check is skipped. It will produce 0 warnings.
