### ISSUE TITLE
Add async http?

### ISSUE THREAD

**Issue by Hellowlol** [pkkid/python-plexapi#145]
This probably would require some work...

**Comment by pkkid** [comment]
We sorta have this already with the `utils.threaded()` function. What did you have in mind with this request?

If you're referring to `MyPlexAccount.updateFriend()` sending off two requests to plex.tv one after the other, I think we can do this, I just wasn't sure it was worth it as it seemed fast enough when testing already.

**Comment by Hellowlol** [comment]
I was thinking more inline of aiohttp or some other library

**Comment by pkkid** [comment]
I think I still don't follow here. How would the plexapi library would benefit from this? It sounds to me like that might be something for the user's of this library to implement, not us.

**Comment by Hellowlol** [comment]
For speed. But im gonna close this, lets revisit this when requests 3.0 is out. (supports async.)
