### ISSUE TITLE
Support Home Support

### ISSUE THREAD

**Issue by rhillis2004** [pkkid/python-plexapi#146]
I have started using the plexapi today. I was able to create a script to upload my m3u playlists to the server. However, they were only created in my account. How do I access the other user accounts?

**Comment by pkkid** [comment]
I'm not sure you can without their login details. Perhaps hitting the database directly it can be done, but that's not something I have looked into. - A similar request was asked to see the watched status of other users connecting to the server that we never figured out.

**Comment by pkkid** [comment]
You might also want to try creating a collection instead of a playlist. Those may be shared across users.

**Comment by rhillis2004** [comment]
I think there is some confusion. I'm talking about the managed users. It's all the users I've created on my own account.

**Comment by pkkid** [comment]
You're right, I was confused. Unfortunately this library doesn't support managed users yet. Not for any reason, we just haven't got around to it.

**Comment by rhillis2004** [comment]
I'll be waiting.

**Comment by JonnyWong16** [comment]
You can access the API as any user on your server (friends, or Plex Home).

See my example here on how I sync playlists to shared users.
https://gist.github.com/JonnyWong16/2607abf0e3431b6f133861bbe1bb694e

**Comment by Hellowlol** [comment]
Thanks, we should be able to support home users with very little effort

**Comment by ukdtom** [comment]
Also this will be part of the next version of WebTools
https://github.com/ukdtom/WebTools.bundle/blob/translate/Contents/Code/playlistsV3.py#L127

**Comment by Hellowlol** [comment]
The resason why you can see watched status for other is because it seems to Linked the accesstoken they scrobbled from. We can jeg access to there accesstoken but it does not mean that you used that one when they scrobbled the mediafile. You have to login to using username and password

**Comment by gregier** [comment]
node-plex-api-credentials has support for managed users, perhaps it can be useful as a reference implementation.

[Add support for managed users.](https://github.com/phillipj/node-plex-api-credentials/commit/117108dbe2f679ae1b643417d45870f6d7afeeaa)
[Minor refactoring for managed user functionality.](https://github.com/phillipj/node-plex-api-credentials/commit/1079137e1d7b48ec90b1488a820db6cfd83d748e)

**Comment by blacktwin** [comment]
Not sure if this helps but you can access home/managed or any other shared user by using the following:

```python
plex = PlexServer(PLEX_URL, PLEX_TOKEN)
account = plex.myPlexAccount()
user_acct = account.user('USERNAME')
user_plex = PlexServer(PLEX_URL, user_acct.get_token(plex.machineIdentifier))
```
Because the `user_plex` is a server object you can do most of the same things you would be able to in the admin's server object (create, update, or delete playlists, mark watched or unwatched, etc.)

**Comment by blacktwin** [comment]
Sharing Playlists to users, creating and removing Home Users, and viewing user watch statuses are available. What is missing? If nothing, then can this be closed?

**Comment by pkkid** [comment]
Yep, lets close this. Thanks.
