### ISSUE TITLE
Artist `track()` fails if there is an apostrophe in the track name

### ISSUE THREAD

**Issue by andrewvaughan** [pkkid/python-plexapi#1474]
### Describe the Bug

When using the `Artist.track()` method, it fails if there is an apostrophe (`'`) in the track name.

### Code Snippets

```python
plex_artist: plexapi.audio.Artist = plex.library.section(library).get("One Direction")

# Raises a `plexapi.exceptions.NotFound` exception
plex_track: plexapi.audio.Track = plex_artist.track("I Ain't Worried")
```

### Expected Behavior

Return the track as-per normal.

### Operating System and Version

macOS Sequoia 15.0.1

### Plex Media Server Version

1.41.1.9057 (Docker)

### Python Version

Python 3.12.6

### PlexAPI Version

^4.15.16 (Poetry)

**Comment by andrewvaughan** [comment]
Doing some further digging into the Plex results, it looks like Plex is using "fancy quotes" in its results (gross).

I'm not sure how consistent this is across Plex, but I'll leave this insight here for your review.

**Comment by JonnyWong16** [comment]
The [source on MusicBrainz](https://musicbrainz.org/release-group/1e4bcbfa-3ffc-4686-a759-7000a492ef86) uses a smart quote.

PlexAPI searching is just a wrapper around the library filters and Plex's own filters don't consider smart quotes.

![image](https://github.com/user-attachments/assets/4f861998-3aa6-4b0e-a9d4-6ea101dbb919)

![image](https://github.com/user-attachments/assets/c42efccf-b976-4dde-93a2-3223b544a08a)
