### ISSUE TITLE
'PlexSonosClient' object has no attribute '_timeout'

### ISSUE THREAD

**Issue by UNICodehORN** [pkkid/python-plexapi#1490]
### Describe the Bug

Using the code snippet from the front page I can retrieve my sonos speaker and I was originally able to control it, but for some days whenever I try to execute a command I am facing the following error:

**AttributeError: 'PlexSonosClient' object has no attribute '_timeout'**

### Code Snippets

```python
from plexapi.myplex import MyPlexAccount
from plexapi.server import PlexServer

account = MyPlexAccount('<EMAIL>', '<PASSWORD>')
plex = account.resource('<PLEXINSTANCE>').connect()

# List available speakers/groups
for speaker in account.sonos_speakers():
    print(speaker.title)
    speaker.stop()
```

### Expected Behavior

Stop playing music on (any) sonos speaker.

### Additional Context

Tested this on a raspberry (with python 3.12.3) and from another ubuntu (python 3.11.11). Same error on all instances.

### Operating System and Version

Ubuntu 22.04.5 LTS

### Plex Media Server Version

1.41.3.9314

### Python Version

3.10.14

### PlexAPI Version

4.16.0

**Comment by JonnyWong16** [comment]
There is already PR #1489 to fix this.
