### ISSUE TITLE
Add support for editing metadata

### ISSUE THREAD

**Issue by JonnyWong16** [pkkid/python-plexapi#150]
A general function to edit metadata would be the easiest to implement. Similar to `plexapi.library.LibrarySection.edit(**kwargs)` (Reference #127) 

Example:
```
plexapi.video.Movie.edit(**kwargs)
```

```
class Movie(Video, Playable):

    def edit(self, **kwargs):
        """ Edit a movie.
            
            Parameters:
                kwargs (dict): Dict of settings to edit.
        """
        if 'id' not in kwargs:
            kwargs['id'] = self.ratingKey
        if 'type' not in kwargs:
            kwargs['type'] = utils.searchType(self.type)

        part = '/library/sections/%s/all?%s' % (self.key, urlencode(kwargs))
        self._server.query(part, method=self._server._session.put)
```

Example scripts where I have used this endpoint to manually update metadata:
* [Create a Plex collection from a text file list of rating keys](https://gist.github.com/JonnyWong16/148b5a5dc39211bd6a871cb8f9df8c48)
* [Removes ALL collections from ALL movies](https://gist.github.com/JonnyWong16/34878448ab45dfffffa930f5cf8c252a)

Ideally something like `plexapi.video.Movie.addCollection()`, `.addLabel()`, `.addGenre()`, etc. would be useful. (Reference #37)

```
class Movie(Video, Playable):

    def addCollection(self, collection=None, locked=True):
        """ Add the movie to a collection.
            
            Parameters:
                collection (str): Name of collection to add.
                locked (bool): True to lock the collection.
        """
        if collection is not None:
            collection_key = "collection[{key}].tag.tag".format(key=len(self.collections))
            data = {"collection.locked": utils.cast(int, locked),
                    collection_key: collection
                    }

            return self.edit(**data)
```

Edit: ... I should have just made this a pull request ...

**Comment by Hellowlol** [comment]
I like it.

**Comment by Hellowlol** [comment]
https://github.com/pkkid/python-plexapi/pull/151

**Comment by JonnyWong16** [comment]
As the next step to this, add support for editing all other metadata fields: `title`, `titleSort`, `year`, etc.

**Comment by Hellowlol** [comment]
I think we already supports this, however i don't think i'm gonna bother adding a method for every change. 

````
{'titleSort.value': 'oh please',
 'titleSort.locked: '1'}
````

**Comment by pkkid** [comment]
@Hellowlol Should this be closed or was there more you wanted to do?

**Comment by Hellowlol** [comment]
Closing this as it's implemented. It time we got the most common things to edit. Anything can be editable by passing them as kwargs
