### ISSUE TITLE
Unable to remove/invite friend

### ISSUE THREAD

**Issue by blacktwin** [pkkid/python-plexapi#156]
Following [documentation](http://python-plexapi.readthedocs.io/en/latest/modules/myplex.html?highlight=Share#plexapi.myplex.MyPlexAccount.removeFriend). Using Version: 3.0.0

```python
PLEX_URL = 'http://localhost:32400'
PLEX_TOKEN = 'xxxxx'
plex = PlexServer(PLEX_URL, PLEX_TOKEN)
plex.myPlexAccount().removeFriend('user_test')
```

produces this error: 
```
File "C:\Python27\lib\site-packages\plexapi\myplex.py", line 214, in removeFriend
    user = self.user(user)
  File "C:\Python27\lib\site-packages\plexapi\myplex.py", line 264, in user
    if username.lower() in (user.username.lower(), user.email.lower(), str(user.id)):
AttributeError: 'NoneType' object has no attribute 'lower'
```

user_test is a non-home/managed user. Tested home/managed user as well, same error.

**Comment by Hellowlol** [comment]
can you try this pr? https://github.com/pkkid/python-plexapi/pull/152/files

**Comment by blacktwin** [comment]
Nice. removeFriend and inviteFriend now work. Thanks!
