### ISSUE TITLE
Unable to remove/invite managed/home users

### ISSUE THREAD

**Issue by blacktwin** [pkkid/python-plexapi#157]
[issue 156](https://github.com/pkkid/python-plexapi/issues/156) was resolved with PR [#152](https://github.com/pkkid/python-plexapi/pull/152). However I did not test managed/home users prior to closing 156. This issue narrows the scope to managed/home users.

While using PR #152

```python
PLEX_URL = 'http://localhost:32400'
PLEX_TOKEN = 'xxxx'
plex = PlexServer(PLEX_URL, PLEX_TOKEN)


plex.myPlexAccount().removeFriend('home_test')
```
produces the following error:
```
  File "C:\Python27\lib\site-packages\plexapi\myplex.py", line 214, in removeFriend
    user = self.user(user)
  File "C:\Python27\lib\site-packages\plexapi\myplex.py", line 272, in user
    raise NotFound('Unable to find user %s' % username)
plexapi.exceptions.NotFound: Unable to find user home_test
```

**Comment by Hellowlol** [comment]
The real issue is there we dont handle managedusers and home users in def users (not to self)

**Comment by blacktwin** [comment]
So appending `.lower()` to [myplex.py line L265](https://github.com/pkkid/python-plexapi/blob/master/plexapi/myplex.py#L265)

```python
if username.lower() == user.title.lower():
```

Seems to resolve the issue.

**Comment by pkkid** [comment]
Thanks!
