### ISSUE TITLE
Cannot connect to any resource - 401

### ISSUE THREAD

**Issue by fuuman** [pkkid/python-plexapi#163]
```python
>>> from plexapi.myplex import MyPlexAccount
>>> a = MyPlexAccount.signin('user', 'password')
>>> p = a.resource(server_name).connect()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    p = a.resource("Lil' Bitch").connect()
  File "/home/marco/.virtualenvs/plex/lib/python3.6/site-packages/plexapi/myplex.py", line
 157, in connect
    raise NotFound('Unable to connect to resource: %s' % self.name)
plexapi.exceptions.NotFound: Unable to connect to resource: server_name

```
When I try to test the API from my webbrowser, it always gives me an 401 unauthorized error. But I am aware of the token change to the API and trying to send a GET request to the following URL: 
"http://public_ip_address:32400/status/sessions/history/all?X-Plex-Token=mytoken"

How can I authenticate to the server correctly?

**Comment by pkkid** [comment]
If you know the token, you can connect directly to a PlexServer with the following code (bypassing the MyPlex authentication step). Make sure you are running the version of plexapi from github (not pip).

```python
from plexapi.server import PlexServer
baseurl = 'http://plexserver:32400'
token = '2ffLuB84dqLswk9skLos'
plex = PlexServer(baseurl, token)```

**Comment by fuuman** [comment]
Okay, I had version 2 from pypi installed. Upgraded to 3.0.0 from Github now.
The code, that you just posted gives me the following exception: 

`plexapi.exceptions.BadRequest: (401) unauthorized;`

**Comment by pkkid** [comment]
You must have the wrong token. You can try connecting through MyPlexAccount again, or also try running the script `tools/list-tokens.py` to see if you can get the right one.

**Comment by fuuman** [comment]
The token was wrong, indeed. I got the right one via your mentioned tool. 
I can connect to the server now, but further calls like plex.library are returning 401 - unauthorized again. I tried both, login via token and via PlexAccount.

**Comment by Hellowlol** [comment]
Just get the token for a xml meta data URL inside plex web.

**Comment by fuuman** [comment]
What do you mean?

I also tried to send a POST request to https://plex.tv/users/sign_in.json. And yes I got a valid JSON object with a token. But this token is not working too...

**Comment by Hellowlol** [comment]
From the plex ui. Click some movie, click the three dots, click get info, click view xml. get the token from the url.

**Comment by fuuman** [comment]
I am sorry, but there is no "view xml" option. I got a different token from the dev tools in chrome, but even that is not working. I have no idea what to try..

**Comment by Hellowlol** [comment]
https://support.plex.tv/hc/en-us/articles/204059436-Finding-an-authentication-token-X-Plex-Token

**Comment by pkkid** [comment]
This is two weeks old and the user went silent, closing. If you still need help feel free to reopen.
