### ISSUE TITLE
Two new tests failing

### ISSUE THREAD

**Issue by pkkid** [pkkid/python-plexapi#166]
We just need to make them a bit more generic or update our server to support them.

**Comment by Hellowlol** [comment]
Atm we have two test server i dont see the point. Just mail me the url and apikey of your so i can test that one. Ill fix the tests. Should i just delete the the droplet on digital ocean?

**Comment by pkkid** [comment]
Not having private messaging is very annoying. I don't think I have your email anymore.

**Comment by Hellowlol** [comment]
hellowlol1 at gmail dot com

**Comment by pkkid** [comment]
I fixed these tests, one cant run on the test server without plexpass.

**Comment by pkkid** [comment]
I just sent you the updated details. The tests are passing or skipped because we don't have PlexPass on the account at this point, going to close this one.

**Comment by Hellowlol** [comment]
So this is testing againt your docker now? I can safely delete the droplet i have running?

**Comment by pkkid** [comment]
Yep! Save yourself the cost of a coffee each month. :D
