### ISSUE TITLE
Edit addedAt and lastPlayed?

### ISSUE THREAD

**Issue by stevezau** [pkkid/python-plexapi#168]
Hi,

I'm trying to edit addedAt and lastPlayed on episodes and movies.

I thought i could just do an edit as below but it does not work. Am i missing something here?

```epsiode.edit(addedAt=datetime.datetime.now())```

**Comment by Hellowlol** [comment]
I dont think you can edit that. Its it possible to change this via plex web? I havnt seen it atleast.

**Comment by stevezau** [comment]
I don't think you can via plex web. I thought you might be able to via the API.

To be honest, i can't even find clear API docs for Plex. It seems to be a mess

**Comment by Hellowlol** [comment]
There isnt official any docs.. The most comprehensive is probably plexapi. I  wish there way tho, it would make this much easier for us. The current method we do today is looking in dev tools what plexweb sends to the server or plex.tv :(

**Comment by pkkid** [comment]
IIRC I read somewhere that the best way to edit the added at date is to remove the library, set the created date of the actual video files then add the library back to Plex.  Its not the most ideal method, but should do the trick if you really really want these correct. -- I would definetly Google around to confirm this before destroying your current Plex libraries.

**Comment by stevezau** [comment]
I can do it via the db directly, just didn't want to if i didn't have too.. All good thanks.

**Comment by pkkid** [comment]
No problem. Editing the db directly is currently out of the scope of this project.
