### ISSUE TITLE
New Release to PyPI

### ISSUE THREAD

**Issue by droath** [pkkid/python-plexapi#169]
Awesome work on the PlexAPI, from what I can tell you've been enhancing the package on GitHub but the code on https://pypi.python.org/pypi/PlexAPI/2.0.2 is a bit outdated. Do you have plans on releasing a new version anytime soon?

**Comment by pkkid** [comment]
We do, sooner than later actually. I'll leave this open as a reminder.

**Comment by pkkid** [comment]
@Hellowlol You mentioned having travis auto-push to pypi in other projects. Lets do that! Did you have an example setup we could copy here?

**Comment by Hellowlol** [comment]
https://docs.travis-ci.com/user/deployment/pypi/

Example
https://github.com/Hellowlol/nrk_api/blob/master/.travis.yml

**Comment by pkkid** [comment]
I think I updated Travis to do this, but now Python3.6 is failing during coveralls installation.  Seems like an upstream problem. I'll look at it later tonight.

**Comment by pkkid** [comment]
It looks like the Python3.6 errors we're seeing are most likely these bugs:

https://github.com/pypa/setuptools/issues/1086
https://github.com/pypa/setuptools/issues/1101

**Comment by pkkid** [comment]
The workaround in the bugs posted are working, and Travis successfully submitted to Pypi.

**Comment by Hellowlol** [comment]
The PR should be includef in a new release btw

**Comment by pkkid** [comment]
Feel free to update the config, this is all new to me.
