### ISSUE TITLE
Where did Library.getByKey() go?

### ISSUE THREAD

**Issue by WyseNynja** [pkkid/python-plexapi#180]
I used to query items by the library key. Where did that method go?

**Comment by pkkid** [comment]
I'm on my phone now so can't give a better example. Look for `fetchItem()`. It was changed as we had a few functions with different names that all did the same thing before.

**Comment by pkkid** [comment]
http://python-plexapi.readthedocs.io/en/latest/modules/base.html

**Comment by verdel** [comment]
@WyseNynja, You could use **plex.fetchItem(ratingKey)** to fetch items by ratingKey
