### ISSUE TITLE
Objects are not JSON serializable

### ISSUE THREAD

**Issue by tdorsey** [pkkid/python-plexapi#190]
server = PlexServer()

json.dumps(server) fails because Servers contain Libraries, which contain Sections, etc. 

The easiest thing to do may be to implement custom json encoder/decoders for PlexObject

**Comment by Hellowlol** [comment]
PR welcome

**Comment by pkkid** [comment]
The is not something that is in the scope or spirit of this project. You could write helper functions on the side that convert these higher-level objects to dictionaries. Internally in plexapi I would like to keep things simpler and avoid a kitchen sink of features that may very easily become unmaintained.

I don't know what you're trying to do or why you need to convert all plexapi objects to json, but you could get pretty close by using the builtin `server.__dict__() function`. If you want to get fancy, you can take a look at how I recursively walked every object in the file `tools/plex-listattrs.py`.

**Comment by Hellowlol** [comment]
Or you can use the ElementTree.tostring(obj._data, encoding='utf8', method='xml') to get a xml string then use xmltodict to get a dict then use json dumps

**Comment by tdorsey** [comment]
@pkkid I'm writing a tool to do library comparisons and in the process of writing the web ui with flask, I tried to store the Library objects in the session as follows
```
from flask import session 
account = MyPlexAccount()
session['account'] = account
```
Which failed on behind the scenes JSON Encoding (apparently flask stores both session and the g object as a JSON'ed cookie)

As far as implementation goes, I think I can work around this by just recursively serializing the various dictionaries without much trouble, I just was unsure if this sort of thing should be a helper function on my end, or a PR on yours.

**Comment by Hellowlol** [comment]
If you write a helper it could be added to the utility.py file. I can see the use case.
