### ISSUE TITLE
Please add duplicate filtering for Episodes

### ISSUE THREAD

**Issue by l3uddz** [pkkid/python-plexapi#198]
Hey,

Love the project, would be greatly appreciated if the same duplicate=True search filtering that exists for Movie libraries can also be done for Episodes. e.g.:
```
plex.library.section("Movies").search(duplicate=True)
```
Which returns all the duplicate Movies. Would be handy to have 
```
plex.library.section("TV").search(duplicate=True)
``` 
and have it return all the duplicate Episodes (like you can do in the Plex Web Client for Episodes)

Thanks!

**Comment by Hellowlol** [comment]
I wasnt aware that was possible. I need this feature for a cli too Im working on so ill add this. Can you paste the url that plex web uses to do this?

**Comment by l3uddz** [comment]
Not sure on plex.tv/web, but can be done by visiting http://localhost:32400 e.g.:

```http://localhost:32400/library/sections/2/all?type=4&duplicate=1&X-Plex-Container-Start=0&X-Plex-Container-Size=50&X-Plex-Product=Plex%20Web&X-Plex-Version=3.20.8&X-Plex-Client-Identifier=20nd3nz3o6z80bu7hxteu7qi&X-Plex-Platform=Chrome&X-Plex-Platform-Version=61.0&X-Plex-Device=Windows&X-Plex-Device-Name=Plex%20Web%20%28Chrome%29&X-Plex-Device-Screen-Resolution=4096x2140%2C3072x1728&X-Plex-Token=TOKEN``` Hopefully you can replicate with that.

Basically go to your TV Section, click at the top where it says TV Shows, then click Episodes, then to the left you click All and click the Duplicates filter.

**Comment by Hellowlol** [comment]
That might be possible ATM. Can you try plex.library.section("TV").search(duplicate=True, libtype=episode) ?

**Comment by l3uddz** [comment]
Sure, I will try and get back to you shortly. I wasnt aware of the libtype parameter

**Comment by l3uddz** [comment]
Getting ```plexapi.exceptions.BadRequest: Unknown filter category: duplicate```

**Comment by Hellowlol** [comment]
There you go :) Pull from github
