### ISSUE TITLE
media item delete can fail.

### ISSUE THREAD

**Issue by Hellowlol** [pkkid/python-plexapi#201]
````
  File "c:\users\x\onedrive\dokumenter\github\plexcli\plexcli\cli.py", line 221, in remove_dupes
    media.delete()
  File "c:\users\x\onedrive\dokumenter\github\python-plexapi\plexapi\media.py", line 58, in delete
    return self._server.query(part, method=self._server._session.delete)
  File "c:\users\x\onedrive\dokumenter\github\python-plexapi\plexapi\server.py", line 345, in query
    raise BadRequest('(%s) %s; %s %s' % (response.status_code, codename, response.url, errtext))
plexapi.exceptions.BadRequest: (404) not_found; https:.....plex.direct:16667/library/sections/1/all?duplicate=1&X-Plex-Container-Size=50&X-Plex-Container-Start=0/media/243629&X-Plex-Token=<removed>
````
This fails since https://github.com/pkkid/python-plexapi/blob/484461b0ddc86766d8ae036ba45bf8fcd3c97318/plexapi/media.py#L56 uses the _initpart, that worked since if i used the key when i added this feature

**Comment by Hellowlol** [comment]
@pkkid Do you have any suggestion on how to fix this? My thought was to just inject the parent key as init key in https://github.com/pkkid/python-plexapi/blob/master/plexapi/video.py#L132 and

**Comment by Hellowlol** [comment]
Current workaround for my own project https://github.com/Hellowlol/plex-cli/blob/master/plexcli/cli.py#L190

**Comment by blacktwin** [comment]
Is this just for deleting mediaparts? what would be the difference in using the [`media.Media.delete()`](https://github.com/pkkid/python-plexapi/blob/master/plexapi/media.py#L65-L72) vs. [`base.PlexPartialObject.delete()`](https://github.com/pkkid/python-plexapi/blob/master/plexapi/base.py#L433-L440) ?

**Comment by Hellowlol** [comment]
Honestly I can’t remember. I have to recheck this issue

**Comment by MrTopCat** [comment]
I'm having this exact issue. As my script runs on my server my workaround is to iterate over the media/parts to get the path and use `os.remove`.
