### ISSUE TITLE
Add dunder methods to some classes to be more user friendly

### ISSUE THREAD

**Issue by Hellowlol** [pkkid/python-plexapi#202]
See http://www.diveintopython3.net/special-method-names.html
Only reasons i havnt started on this before is that there is dragons inside plexapi :D
Playlist is a nice place to start.

**Comment by pkkid** [comment]
Just avoid `__getattribute__`, `__getattr__`, `__setattr__`, `__delattr__` and you should avoid all dragons.

**Comment by Hellowlol** [comment]
added
