### ISSUE TITLE
TV Show labels (Show level) missing

### ISSUE THREAD

**Issue by iwascraig** [pkkid/python-plexapi#204]
When using object.labels on a show I get None.  However I could set labels in the web client

I found I could get the labels by going back to the detail..
raw_labels=show.findItems(video._data, Label)

Would be nice if they were exposed like the are for Video. (movie type)

**Comment by Hellowlol** [comment]
@iwascraig Why don't you send a pr so you get credit for discovering and fixing this?

**Comment by Hellowlol** [comment]
Wait what? Does we just return None for missing attributes? I have never tried one. Lol

**Comment by iwascraig** [comment]
Hey... yeah I'll look into it... I'm a little time poor at the moment.. but I'll look at it over the coming week when I find time.  I'll also look at why setting labels on the shows aren't working even when going to the lower classes like this.

**Comment by Hellowlol** [comment]
Okei. I'll do it then. It's a simple fix
