### ISSUE TITLE
Change how search batching works

### ISSUE THREAD

**Issue by Hellowlol** [pkkid/python-plexapi#213]
https://github.com/pkkid/python-plexapi/blob/master/plexapi/library.py#L503

Makes it impossible to set a higher value then default (not really but hard enough). I don't think that was the intention. Passed params should override default imo.

We are doing a lot of unneeded HTTP calls on large library's.

**Comment by pkkid** [comment]
Looks like a bug to me, good find.

**Comment by Hellowlol** [comment]
https://github.com/pkkid/python-plexapi/pull/464
