### ISSUE TITLE
Add speed ups

### ISSUE THREAD

**Issue by Hellowlol** [pkkid/python-plexapi#214]
Right now fetchitems is rather slow because 99% of the time we only use the etag so we should precheck that before calling _checkattrs, https://github.com/pkkid/python-plexapi/blob/master/plexapi/base.py#L135
Changing this with container size reduced my my function call by ca 50 sec

**Comment by pkkid** [comment]
@Hellowlol, can you provide a simple script that runs slow in this case. Is it essentially, get all items, look up each item by etag?

**Comment by Hellowlol** [comment]
I can’t even remember what the code was. Anyway speeding up the build is important but it would be even better if we could leverage pms filtering. Btw I noticed a /common command last time I opened dev tools in plex web
