### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by ukdtom** [pkkid/python-plexapi#217]
Seen people on Reddit, that want's to use this API directly from a Channel Plugin.

But doing so, will make the PMS framework log the token in the plugin log files => potential exposure when uploading logs to the forums or Reddit!

As such, consider moving the token from an url based parameter into the header instead, since then it'll not be logged!

Ref: https://github.com/pkkid/python-plexapi/blob/master/plexapi/myplex.py#L142

**Comment by ukdtom** [comment]
And funny enough, you do do it here :)

https://github.com/pkkid/python-plexapi/blob/master/plexapi/client.py#L128

So seems like a simple copy paste from above to myplex.py

**Comment by pkkid** [comment]
We should probably only put it in the header by default. However, are you using version 3 of plexapi? Now we mask the token in the log file by default unless you opt into it via a configuration option. That is done here: 

[1] https://github.com/pkkid/python-plexapi/blob/master/plexapi/__init__.py#L45
[2] https://github.com/pkkid/python-plexapi/blob/master/plexapi/utils.py#L22

**Comment by Hellowlol** [comment]
I still don't understand how the framework is logging this. Are you taking about http request to the plugin or the calls from plexapi to pms? Anyway is a trivial fix.

**Comment by ukdtom** [comment]
@Hellowlol 
If you use this in a plugin, you live under the framework, and as such, all networking calls are logged in the plugins/YourPlugin.log, and yes, a trivial fix
@pkkid Sorry, but not using it ;)
Just noticed a post in Reddit, where @Hellowlol also stepped in, warned about it, and then came here to verify my statement.
Then discovered it was as simple as to change a single line, and as such, created this GHI, hoping one of you will make a PR ;) (And yes, I could have done so myself, but since I don't know your API, I can't foreseen any consequences,  so would rather leave that for you guys

**Comment by Hellowlol** [comment]
@ukdtom Have you confirmed this? I just tested and there is no logging from plexapi in the framework at all. I have to check plexapis own log, and there its censored.

**Comment by ukdtom** [comment]
As said, not using your API, but seen it with every other 3.Party used from a channel...

So fail to see why yours should be different...

Seen it again and again, when devs are using the request module for one...

Sub-Zero had this issue, until I contacted Panni as well, and he imidiatly corrected it for one...

If launched from a channel, then the channel log should have an entry like "Networking" that shows the url called

Also do note, that you might only have this issue, if the query function is called, since that's the one using a param

And if I was mistaken here, then I'm fully sorry, and will naturally say so in the Reddit thread ;)

**Comment by ukdtom** [comment]
Ref: https://github.com/pannal/Sub-Zero.bundle/issues/148

**Comment by Hellowlol** [comment]
Oh, i dunno if what i did count as a channel. I just added plexapi to your webtools and did loads of calls and checked the the pms log, devtoolslog and setup log. Ill double check :)

**Comment by ukdtom** [comment]
Create a channel, import your API, and call the Query function

**Comment by Hellowlol** [comment]
I dont think this is a big issue, the plugin author has to inject the package dependencies into plex ````Log.level```` AND the user has to create a config file and set show secrets to true. But it better to be safe then sorry.

**Comment by Hellowlol** [comment]
And for the records plex does a shitty job documenting stuff. Its amazing that anybody wants to make plugins. So thanks @ukdtom :D

**Comment by Hellowlol** [comment]
fixed in https://github.com/pkkid/python-plexapi/commit/8de4ce7e205ea74279a91f469cdd83057f0a6687

Thanks for the report.
