### ISSUE TITLE
Add support for servers where SSL is enforced

### ISSUE THREAD

**Issue by cnf** [pkkid/python-plexapi#226]
On servers where `Secure connections` is set to `Required`, plexapi just fails.

Please add https support.

**Comment by Hellowlol** [comment]
Where/how this fail? Can you post the code you used and the traceback?  Did you pass your own session object?

**Comment by pkkid** [comment]
python-plexapi very much works with https. It's how we connect to our dev server when running on the tests on Travis-CI. If you need help getting it to work, please feel free to re-open and post the code example you were having trouble with.

**Comment by cnf** [comment]
It is not my code, but a problem I ran into with home-assistant. I haven't had time to look at it again yet, but if python-plexapi should support it I'll look further into the hass code to see where it goes wrong there, thanks.

**Comment by pkkid** [comment]
Last I checked, which was a while ago, Home Assistant was using a very old version of python-plexapi. I think a version even before Plex had support for https. Not sure if that’s still the case.

**Comment by Hellowlol** [comment]
They updated to 3.0.3 recently.
