### ISSUE TITLE
Lower Log Level When Loading Full Item

### ISSUE THREAD

**Issue by pkkid** [pkkid/python-plexapi#227]
This was reported downstream in Home-Assistant.  I think we should simply lower this log level from warning to info.

> Description of problem:
> Every time I play something in Plex, my log gets a lot of this kind of errors:
```
nov 07 19:38:03 VM42 hass[20418]: 2017-11-07 19:38:03 WARNING (Thread-2) [plexapi] Reloading Episode '<< name of the episode>>' for attr 'seasons'
nov 07 19:38:25 VM42 hass[20418]: 2017-11-07 19:38:25 WARNING (Thread-6) [plexapi] Reloading Episode '<<name of the episode>>' for attr 'seasons'`
```
https://github.com/home-assistant/home-assistant/issues/10438

**Comment by Hellowlol** [comment]
This should be fixed upstream. There are better ways to get the season number in the the newer version

**Comment by Hellowlol** [comment]
On second though they might not be possible if the item is a show.

**Comment by Hellowlol** [comment]
https://github.com/pkkid/python-plexapi/pull/229

**Comment by pkkid** [comment]
Merged.
