### ISSUE TITLE
Include the Server URL in 

### ISSUE THREAD

**Issue by ryanm101** [pkkid/python-plexapi#228]
Please
Add ArtURL and grandParentThumbUrl to session or add serverURL to session object.
Due to this missing info, I have to pass about the whole server object in order to images for some uses cases where i dont want to use thumbUrl for the image.

Adding the ServerURL to session / client info could negate the need for thumbURL allowing consistency for how ALL images are called. 
```python
            if (self.media_content_type is MEDIA_TYPE_TVSHOW
                    and not self.config.get(CONF_USE_EPISODE_ART)):
                thumb_url = self._server.url(
                    self._session.grandparentThumb)

            if thumb_url is None:
                _LOGGER.debug("Using media art because media thumb "
                              "was not found: %s", self.entity_id)
                thumb_url = self._server.url(self._session.art)
```

**Comment by Hellowlol** [comment]
What class/item  is self._session here? Its that a media item that is playing? Anyway the server injected pretty much anywhere. So if self._session is a movie etc you should be able to ```` self._session._server.url(self._session.grandparentThumb)```

**Comment by ryanm101** [comment]
```self._session = plexserverobj.session[X]```

We can't use the _server accessor as the linter flags that as accessing a "private" method/property and fails the build

**Comment by Hellowlol** [comment]
But your already using it for self._session ? disable the linter inline imo.

**Comment by Hellowlol** [comment]
https://github.com/pkkid/python-plexapi/pull/229

**Comment by pkkid** [comment]
Merged.
