### ISSUE TITLE
Log entries are not escaped/sanitized (Token visible/Page Redirects)

### ISSUE THREAD

**Issue by Nostang3** [pkkid/python-plexapi#231]
Posting per request of the plexpy issue #1146. 

Plex API Version: 3.0.3
Operating system: FreeNAS | FreeNAS-9.10.2-U6 (561f0d7a1)
Python version: 2.7.13

What you did?: Attempted to run ip_whitelist.py in PLexpy when playback starts via scripts.

What happened?: The script erred out most likely because my Plex Token had changed since I last attempted to use the script. This caused an error to post to the PlexPy logs that was not properly escaped and would cause redirects anytime the error was visible on the log page. You'd have to wait till enough entries pushed it off to a following page before you could access the log page again. Also, the Plex Token was visible in this error code.

How can we reproduce your issue?: I believe you would just need to run the script with a bad plex token value.

Link to logs: https://pastebin.com/xm3Z1825
The error will be at the bottom.

**Comment by Hellowlol** [comment]
To be fair this not logged by plexapi log. This is logged by plexpy log. When then that being said could could remove the token from the exception message. :)

**Comment by pkkid** [comment]
With the below change, this bug can be closed. We are now by default not including the token in any url GET arguments unless required (stream URLs, thumbnails, websockets).

commit 61ede66ad5e2d0d21cf9dd5895226b263b67a1d5 (HEAD -> master, origin/master, origin/HEAD)
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Thu Jan 4 21:44:35 2018 -0500
Don't include token in URLs unless show_secrets set in config.
All functions that return a URL such as stream urls and thumbnails still include token.
