### ISSUE TITLE
Bug with removeLabel and addLabel

### ISSUE THREAD

**Issue by daeks** [pkkid/python-plexapi#232]
Hi all,

it looks like I have found an issue:

Before:
![image](https://user-images.githubusercontent.com/3989440/32934971-42d5211c-cb6e-11e7-8b1d-6b7a5ae8e637.png)

```
for label in video.labels:
  video.removeLabel(label.tag)
video.addLabel('Checked')
```

After:
![image](https://user-images.githubusercontent.com/3989440/32934911-e89e9fca-cb6d-11e7-9b12-ae16e1286dd6.png)

But only using:

```
for label in video.labels:
  video.removeLabel(label.tag)
```

After:
![image](https://user-images.githubusercontent.com/3989440/32934945-1dca73d6-cb6e-11e7-8d74-3ee2b6f56ef7.png)

**Comment by Hellowlol** [comment]
That seems to correct. You looping every label and calling removeLabel. As a result all labels are removed.

**Comment by daeks** [comment]
yes exactly, although I am looping through all labels to remove them, the laben "new" is not removed

**Comment by Hellowlol** [comment]
I’ll take alook at this but I suspect it just happend to fast. Tried adding a sleep before adding a new label?

**Comment by daeks** [comment]
Unfortunately a sleep does not help. I tried it with 1-3 seconds.

**Comment by Hellowlol** [comment]
```
import logging
import time
from plexapi.server import PlexServer

logging.basicConfig(level=logging.INFO)

url = 'http://10.0.0.22:32400'
token = ''

pms = PlexServer(url, token)


video = pms.search('1408')[0]

assert 'new' in [z.tag.lower() for z in video.labels]
print(video.labels)

for label in video.labels:
    print('Removing %s' % label.tag)
    video.removeLabel(label.tag)

try:
    assert not len(video.labels)
except AssertionError:
    print('we have removed all the labels but plexapi cant see it since the object isnt reloaded.')
    video.reload()
    assert not len(video.labels)


try:
    print('Tried to add checked')
    video.addLabel('checked')
    assert 'checked' in [j.tag.lower() for j in video.labels]
except AssertionError:
    print('Checked DOES NOT EXIST YET. We didnt reload the object')
    # addLabel sends a refresh to the command.
    video.reload()
    assert 'checked' in [k.tag.lower() for k in video.labels]


video.reload()
for ll in video.labels:
    video.removeLabel(ll.tag)
video.addLabel('Checked2')
print(video.labels)  # there should be two checked here.. you will only find checked not checked2

video.reload()
print(video.labels)

```

**Comment by daeks** [comment]
video.reload() after removing the labels did the trick :) - thank you very much, I was not aware of that.

**Comment by Hellowlol** [comment]
This should probably be documented better. The user has to reload changes manually because it would be slow to reload on every single change.

**Comment by pkkid** [comment]
@Hellowlol - Not sure this is worth it, but we could track which fields have been updated on the object, and in `__getattribute__` if they request one of those fields, we auto-update. I imagine if we go this route things may get confusing fast; but maybe not. Thoughts?

**Comment by Hellowlol** [comment]
I think we should leave it as it is atm.

**Comment by pkkid** [comment]
OK, thanks.
