### ISSUE TITLE
media.py -> MediaPart media is missing

### ISSUE THREAD

**Issue by TimBB** [pkkid/python-plexapi#237]
hi,
in earlier version there was media in part to get the title like
part.media.video.title
in the documentation it still there, but not in code.
media (:class:`~plexapi.media.Media`): Media object this part belongs to.

how i get the title of a part?

Thx

**Comment by Hellowlol** [comment]
what version could you do this in?

**Comment by TimBB** [comment]
the change was made here

https://github.com/pkkid/python-plexapi/commit/6a35f50a437f23940cca65f3306bb3e04459fa9e#diff-a7fdc8e68f5c536ce8e881262243424d

-    def __init__(self, server, data, initpath, media):
-        self.server = server
-        self.initpath = initpath
-        self.media = media
+    def _loadData(self, data):
+        self._data = data

but how get i now the stream url of a MediaPart?
i iterate through the episodes get a part and want the url to stream

**Comment by Hellowlol** [comment]
We just added inheritage. Can you post the code you used before that isnt working anymore?

**Comment by TimBB** [comment]
first i read all parts, store them in a list.

for episode in plex.library.section("shows").get("something").episodes():
  for part in episode.iterParts():
    print("title s%" % part.media.video.title)

later I use the title 

movie = plex.library.section("shows").get("something").get(part.media.video.title)
link = movie.getStreamURL(videoResolution='800x600')

**Comment by Hellowlol** [comment]
I dont understand your use case. Just store a list of media items (movie or episode) and call getStreamURL directly on that. What are you trying to do? Maybe there is a simpler/better way to handle this.

**Comment by TimBB** [comment]
i store the parts in a list and in a frontend. 
arrRes = list()
arrRes.append(part)

when i click in the list I read out the part in the list with the index
and then generate the url for streaming

and

**Comment by Hellowlol** [comment]
What about something like ‘’’ [{“title”: “16 blocks”, “ratingkey: 1}] ‘’’ then you do just grab the item using the ratingkey

**Comment by TimBB** [comment]
'MediaPart' object has no attribute 'ratingkey'
but i found out that i get a url like that
episode._server.url('%s' % part.key)

**Comment by Hellowlol** [comment]
You don’t need to mess with the parts unless you need the info inside the parts like container, encoding etc. just stick the high level. http://python-plexapi.readthedocs.io/en/latest/modules/video.html
