### ISSUE TITLE
3.0.5 release?

### ISSUE THREAD

**Issue by ryanm101** [pkkid/python-plexapi#242]
Just wondering when the above version will be released as it's got fixes I need for home-assistant.

Regards,

Ryan

**Comment by Hellowlol** [comment]
Ill try to get it done in a couple of days.

**Comment by pkkid** [comment]
Thanks Hellowlol. Looks like the current failures are just metadata changes on a few of the movies.

**Comment by ryanm101** [comment]
@Hellowlol @pkkid Do you know if the following message is fixed in the next release:
"Reloading Episode 'Bedtime' for attr 'seasons'" appears to spam our logs in HA (i've had a few complains in our discord channel)

**Comment by Hellowlol** [comment]
It will still spam you. But it’s logging debug now not warning

**Comment by Hellowlol** [comment]
@ryanm101 Should be released by travis in like 10 min or so. (if no addition tests fail)
