### ISSUE TITLE
Reloading content still appearing as warning from plexapi

### ISSUE THREAD

**Issue by ryanm101** [pkkid/python-plexapi#243]
This is spamming our log files:

2018-01-02 09:26:24 WARNING (SyncWorker_11) [plexapi] Reloading Episode 'Tee Off, Mr. Bean' for attr 'contentRating'

I believe it was to be moved to a debug message in 3.0.5

**Comment by Hellowlol** [comment]
It is https://github.com/pkkid/python-plexapi/blob/master/plexapi/base.py#L282. Have home assistant changed to plexapi 3.0.5 ?

**Comment by ryanm101** [comment]
I'm the one doing the update, I've updated the api in my test env and was testing to see if anything broke when i saw this.

**Comment by Hellowlol** [comment]
Thats the only code that handles reload. Im one 100% sure that its fixed. Sure your using the correct version of plexapi?

**Comment by ryanm101** [comment]
hmm Something smells my end.. 
dir(self._session)
```
['TAG', 'TYPE', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_buildItem', '_buildItemOrNone', '_castAttrValue', '_checkAttrs', '_clean', '_data', '_edit_tags', '_getAttrOperator', '_getAttrValue', '_initpath', '_loadData', '_prettyfilename', '_seasonNumber', '_server', 'addCollection', 'addGenre', 'addLabel', 'addedAt', 'analyze', 'art', 'chapterSource', 'collections', 'contentRating', 'delete', 'directors', 'download', 'duration', 'edit', 'fetchItem', 'fetchItems', 'findItems', 'firstAttr', 'getStreamURL', 'grandparentArt', 'grandparentKey', 'grandparentRatingKey', 'grandparentTheme', 'grandparentThumb', 'grandparentTitle', 'guid', 'index', 'isFullObject', 'isPartialObject', 'isWatched', 'iterParts', 'key', 'labels', 'lastViewedAt', 'librarySectionID', 'listAttrs', 'listType', 'locations', 'markUnwatched', 'markWatched', 'media', 'originallyAvailableAt', 'parentIndex', 'parentKey', 'parentRatingKey', 'parentThumb', 'play', 'players', 'playlistItemID', 'rating', 'ratingKey', 'refresh', 'reload', 'removeCollection', 'removeGenre', 'removeLabel', 'season', 'seasonNumber', 'section', 'session', 'sessionKey', 'show', 'stop', 'summary', 'thumb', 'thumbUrl', 'title', 'titleSort', 'transcodeSessions', 'type', 'updatedAt', 'usernames', 'viewCount', 'viewOffset', 'viewedAt', 'writers', 'year']
```

A pip list on the venv shows:
PlexAPI (3.0.5)

yet i know when I execute python manually i can see your .url() method.. 

I'll dig deeper i think something on my system is getting very confused

**Comment by ryanm101** [comment]
Problem was my end.. Dont know how or why my venv is being polluted. Testing on a completely seperate box shows behaviour as expected.

**Comment by pkkid** [comment]
If you have a way to execute the code, try printing `plexapi.__file__` to see which file it's loading. It may also be worth deleting all .pyc files and __pycache__ directories. One of those three things usually gets to the root problem.

**Comment by ryanm101** [comment]
@pkkid Ty for the __file__ tip.. It was a cache of dependencies created by HA that had not been updated for some reason resulting in the confusion..
