### ISSUE TITLE
New Installation:ImportError: No module named server

### ISSUE THREAD

**Issue by 8bitgentleman** [pkkid/python-plexapi#250]
I just installed plexapi using pip. Right away when getting a server instance the script fails on line 1 of the example.
`from plexapi.server import PlexServer`

The error is `ImportError: No module named server`. I double checked with pip list and plexapi is installed. Just running `import plexapi` doesn't return any errors. Maybe I'm making a dumb mistake, what could be going on here?

**Comment by amazingr4b** [comment]
Is your script file named plexapi by chance?

**Comment by Hellowlol** [comment]
What bacon said :D.

**Comment by 8bitgentleman** [comment]
Well golly be it was. @amazingr4b @Hellowlol thanks for responding.  Error 1 fixed! 

Now when I run the same script (now renamed to something with no relation to the module) I get this error
  ```
File "/Library/Python/2.7/site-packages/plexapi/server.py", line 6, in <module>
    from plexapi.alert import AlertListener

File "/Library/Python/2.7/site-packages/plexapi/alert.py", line 4, in <module>
    import websocket

ImportError: No module named websocket
```

I checked with `pip list` again and I clearly have websocket as well as all of the other requirements installed.

**Comment by pkkid** [comment]
The package is called websocket-client (not just websocket). Did you install the requirements via pip?

`pip install -r requirments.txt`

**Comment by 8bitgentleman** [comment]
@pkkid I did install requirements via that pip command

**Comment by pkkid** [comment]
If you run `pip --version` is it running the same Python version that you are using to run the script?

**Comment by 8bitgentleman** [comment]
yup, both pip and the script say they're running 2.7.10

**Comment by Hellowlol** [comment]
Is websocket-client in the pip list?

**Comment by 8bitgentleman** [comment]
Websocket-client is listed in `pip list`. Is it possible that websocket-client was installed for a different version of python but still shows up in that list?

**Comment by amazingr4b** [comment]
I'm no expert, but this is what I'd check next:
If you open a python shell and try the import websocket what happens?
If you check "/Library/Python/2.7/site-packages/" is it listed there? I suppose if you have both python 2 and python 3 it is possible you have it for 3 but not 2. You could probably also do a find from your root directory and see where it is found.

**Comment by 8bitgentleman** [comment]
Running import websocket in the terminal returns an Import Error but trying to install it via pip (both pip and pip2) returns that it's already installed. I think I see the culprit but I'm not sure how to fix it. Both "/usr/local/lib/python2.7/site-packages" and "/Library/Python/2.7/site-packages/" are places where python modules are stored. Python in the terminal seems to access "/Library/Python/2.7/site-packages/" while pip and the official IDLE app access "/usr/local/lib/python2.7/site-packages". Could there be 2 different versions of python running here?

**Comment by pkkid** [comment]
It definitely sounds like you have two different version of python installed. Perhaps try the `__file__` thing with a default module to see which library you are using?

```python
import os
print(os.__file__)```

**Comment by 8bitgentleman** [comment]
Yup running that in the terminal returns 
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.pyc"
while running it in the IDLE returns
"/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.pyc"

So what do I do about it?

**Comment by pkkid** [comment]
You need to either have IDLE use the same python as pip, or make pip use the same python as IDLE.

* If you remember how you installed IDLE (homebrew?), maybe there is a similar install pip. Then you can call that pip install of the default system one.
* A hacky way could be to edit the first line of the pip file to point to the right python.

**Comment by pkkid** [comment]
Bug went quiet and seemed unrelated to plexapi and more about the user's environment. Closing. If you still need help, feel free to reopen.
