### ISSUE TITLE
Missing stuff

### ISSUE THREAD

**Issue by Hellowlol** [pkkid/python-plexapi#253]
- [x] relay /resources?includeHttps=1&relay=1
- [ ] related /hubs/metadata/'+ratingKey+'/related

**Comment by Hellowlol** [comment]
@pkkid should a reload of a media object include more stuff. I think there are alot of stuff thats missing.

**Comment by pkkid** [comment]
In my mind `reload()` is a full refresh of the object to populate any fields that a partial list (such as /all) may not include. If that requires multiple (but very few) calls into Plex to get everything, I wouldn't be against it.

**Comment by Hellowlol** [comment]
Cool. I need to be able to get the chapters for a personal project. It would be really cool if we could make chapters via edl (think i need to use a addon. unless there are some api that i dont know about.) The idea is to scan for intros in tvshows and add a chapter so the user can skip over that.
