### ISSUE TITLE
Not an Issue - more of a question

### ISSUE THREAD

**Issue by MickeMannen** [pkkid/python-plexapi#254]
Based on the documentation is should be possible to edit a record (video or episode). 
I can't figure out how to do this - would like to change the title, sortTitle for a video and episode

**Comment by Hellowlol** [comment]
You pass a dict to the object.edit

So say you want to add a collection to a movie.

You could do:
```
d =  {'type': 1,
         'id': movie.ratingKey,
          'collection[0].tag.tag': 'Super',
          'collection.locked': 0}
somemovie.edit(**d)
````
