### ISSUE TITLE
3.0.6 & a release schedule

### ISSUE THREAD

**Issue by ryanm101** [pkkid/python-plexapi#255]
Hi, 

Do we know when 3.0.6 will be released as I need it to implement a proper fix for https://github.com/home-assistant/home-assistant/issues/11581

Also are there any plans to release say once a month or any other regular? as this would give me the ability to make sure we have integration and and Idea of what is likely to "break" my side on an update.

**Comment by Hellowlol** [comment]
There are a couple of things I intend to add to plexapi before bumping the version but that nothing to wait for. I'll see if push 3.0.6 in the weekend.

**Comment by Hellowlol** [comment]
As for scheduled releases that would be up to @pkkid

**Comment by pkkid** [comment]
I don't mind scheduled releases, but not sure I'm active enough to stay on top of it. Would you be against being added a developer? Home-Assistant is easily the biggest user of this project, so it makes sense there. It would allow you the freedom to tag the branch and creating a release when you need it.

**Comment by ryanm101** [comment]
No i've no problem doing that, if you are happy enough. Do i need to do anything special to get it into pypi other than tag?

**Comment by Hellowlol** [comment]
With the setup we have its really simple.
````git tag 3.0.6` -m "3.0.6 is out, enjoy"
git push origin 3.0.6
```
Travis will upload a new build to pypi on every tag push as long as the tests is ok.

**Comment by ryanm101** [comment]
nice

**Comment by pkkid** [comment]
You are added. Also, thanks!

**Comment by ryanm101** [comment]
thanks.

**Comment by ryanm101** [comment]
@Hellowlol No worries I'll check back early next week

**Comment by Hellowlol** [comment]
I pushed a new tag but forgot to bump the __init__ file. I was sure plexapi used the scum version but clearly it didn't. I just have to figure out how to fix it 😂

**Comment by Hellowlol** [comment]
3.0.6 is out.

**Comment by ryanm101** [comment]
thanks
