### ISSUE TITLE
Set label for Music Album?

### ISSUE THREAD

**Issue by daeks** [pkkid/python-plexapi#256]
I am currently trying to set sharing label for an music album but failed. How could I set one?

```for artist in section.search(sort='addedAt:desc'):
  for album in artist.albums():
      album.addLabel(artist.title)

=> AttributeError: 'Album' object has no attribute 'labels'

**Comment by Hellowlol** [comment]
Hm, i dont think thats possible atm. I think we need to add 
`self.labels = self.findItems(data, media.Label)` inside https://github.com/pkkid/python-plexapi/blob/a51d0225d1aa9ddabd28c6258c6d820ce1c25a25/plexapi/audio.py#L42if you can add label to both artists and trackers. PR welcome :)

**Comment by daeks** [comment]
Thanks that helped! I have created a PR for that

**Comment by Hellowlol** [comment]
Thanks! I'll add a test after I merge 👍🏼
