### ISSUE TITLE
[Music library] add userRating

### ISSUE THREAD

**Issue by patzm** [pkkid/python-plexapi#259]
I found that the _ratingCount_ property of [plexapi.audio.Track](http://python-plexapi.readthedocs.io/en/latest/modules/audio.html#plexapi.audio.Track) does not hold the rating a user assigned to the track. It contains seemingly random, positive integer values.

The correct rating is however available in the __data.attrib['userRating']_ field of the object. The key 'userRating' is non-existent if the track is not rated, yet.

I propose to expose this attribute as a public variable and fix the documentation (see link above). What are your thoughts on this?

**Comment by Hellowlol** [comment]
I doubt plex will inject random stuff as we need to fixure out where that value comes from and documentet it. We should have userRating. Can you send a pr for it?

**Comment by MattMcDowall** [comment]
> we need to fixure out where that value comes from and documentet it.

The `ratingCount` property is a reflection of the listener counts on [Last.fm](https://last.fm). I suspected this for a while, but to confirm I looked at the numbers for one of my relatively obscure albums (_Geared & Primed_ by The Royal Court of China). Sure enough, the counts match exactly.

I get:
```
84	 1. Geared and Primed
113	 2. Half the Truth
63	 3. It Came Crashing down the Staircase
66	 4. Six Empty Bottles
4	 5. Mr. Indecision
4	 6. Tijuana Go!
57	 7. Dragon Park
61	 8. So, Yer Love Is True
61	 9. This Time Around
52	10. Take Me Down
```

And Last.fm shows:
![image](https://user-images.githubusercontent.com/51373511/171498298-1f11ce5c-668c-4129-ac7c-5f5bea207d7f.png)

If you've used Last.fm, you know it's susceptible to inconsistencies in artist names, track names, etc. This is why "Mr. Indecision" & "Tijuana Go!" have anomalously low ratings here.

But that's clearly where Plex is getting its ratingCount number from.

**Comment by patzm** [comment]
Cool! So you could actually update the docs now with this information right? Maybe PR it?

**Comment by MattMcDowall** [comment]
Honestly, I would love to, but I don't know how. I'm really just learning GitHub, and I haven't contributed to a project like this before. I'm familiar with the process of a PR, in theory, at least. But can you point me to where I can make a change to the docs?

**Comment by patzm** [comment]
fork this repo
![image](https://user-images.githubusercontent.com/5219726/171658343-c95c135c-efb2-4dfd-8ea8-81beff6625ff.png)

then you have a repo with the same name in your account. Make the changes there.

Create a PR. It will ask you whether you want to PR into the upstream repo (this one). Voila 🙂

**Comment by MattMcDowall** [comment]
Yeah, the forking & PR part I get. But where is the actual documentation that I should add this to? I can't find it in the files anywhere.

**Comment by patzm** [comment]
They are using sphinx to generate the docs. I think changing this line
https://github.com/pkkid/python-plexapi/blob/9e918a43a7263f4412f63290b53a5178dfe6e3b0/plexapi/audio.py#L425

to either use a short-style
```python
self.ratingCount = utils.cast(int, data.attrib.get('ratingCount'))  #: My documentation goes here.
```
or long-style
```python
self.ratingCount = utils.cast(int, data.attrib.get('ratingCount'))
"""My longer documentation goes here.

I can have line-breaks.

* some
* lists
* even
```
"""

Further reading here I guess: https://www.sphinx-doc.org/en/master/

**Comment by JonnyWong16** [comment]
Documentation is in the doc strings above.

https://github.com/pkkid/python-plexapi/blob/9e918a43a7263f4412f63290b53a5178dfe6e3b0/plexapi/audio.py#L393
