### ISSUE TITLE
Ability to Search by Rating

### ISSUE THREAD

**Issue by speedyflipper** [pkkid/python-plexapi#260]
I would like to be able to create a list of all the movies that I've giving ratings to and the rating that I gave.

**Comment by Hellowlol** [comment]
Is it possible to do this via plex web? I know we support rating but thats the imdb/rotten not the one you give yourself.

Anyway you just have to get all the things and loop them.

````
# 
all_movies = []
x = 5 # minimum rating.

all_over_five = [m for m i all_movies if m.userRating and m.userRating > x]
````

**Comment by speedyflipper** [comment]
you can do it using a custom filter .

i set the loop up now but it runs very slow which i assume has to do with just the amount of movies it would have to loop through

**Comment by Hellowlol** [comment]
Yeah, okei there are are a couple of options. Plex api has some filter abilites, they arnt as fast as plex but they can do alot more.  See http://python-plexapi.readthedocs.io/en/latest/modules/base.html#plexapi.base.PlexObject.fetchItem for more examples.

````
from plexapi.server import PlexServer
pms = PlexServer(url, token)
movies  = pms.library.section('Movies')

movies.all(userRating__gte=6.0)
[<Movie:31098:12-Years-a-Slave>]
````

**Comment by speedyflipper** [comment]
That worked perfectly, Thanks

**Comment by Hellowlol** [comment]
And if that's to slow you can drop lower in the api and use:

```pms.fetchItems('/library/sections/1/all?userRating=6')```

**Comment by Hellowlol** [comment]
Im closing this as filter already listed as a enchantment
