### ISSUE TITLE
Please add transcodeSessions.sourceVideoCodec

### ISSUE THREAD

**Issue by shawnsethi** [pkkid/python-plexapi#261]
The Plex XML returns a sourceVideoCodec for transcodes, but this is not included in the API.  Only videoCodec is available, which represents what the target format is, but the source format is not included.

Add to media.py:
`self.sourceVideoCodec = data.attrib.get('sourceVideoCodec')`

Thank you!

**Comment by Hellowlol** [comment]
Send a pr?

**Comment by Hellowlol** [comment]
Closing this since you fixed this your self. Thanks for the pr!
