### ISSUE TITLE
top level access to CollectionObject

### ISSUE THREAD

**Issue by DirtyCajunRice** [pkkid/python-plexapi#265]
Now that collections are a valid mediatype i propose an addition of access to the library search by collection objects instead of filterchoice.

Thoughts?

**Comment by Hellowlol** [comment]
We should still have filter choice imo. We shuld handle Collections too

**Comment by DirtyCajunRice** [comment]
Yeah I wasn’t meaning remove filterchoice just an addition. Since it is a top level endpoint like onDeck would it go in the base library object? And do the media.collections functions have to be reworked? I’d love to help I just am not quite sure where to start

**Comment by Hellowlol** [comment]
I haven’t looked at it but it I was thinking plexserver class. I don’t think we need to do any changes regarding media.collections.

**Comment by Hellowlol** [comment]
It should probably be in library.py file then. I would have added it to the movie tvshow sections class. But just do what you feel is right, we can always move it later.  Go for it, i don't have time to do it my self.

**Comment by blacktwin** [comment]
Not really sure where this was going but there has been lots of changes since this conversation started. Is [this](https://github.com/pkkid/python-plexapi/blob/master/plexapi/library.py#L1110 ) what you were referring to?

**Comment by DirtyCajunRice** [comment]
Hoooooly crap this is basically a necro thread call at this point hahaha. Yeah this was added eons ago just didnt reference "fixes #265" so it didnt close it. Will close.
