### ISSUE TITLE
How to delete individual file?

### ISSUE THREAD

**Issue by speedyflipper** [pkkid/python-plexapi#267]
I'm try to have a script delete one file from a movie or tv show.  When I run the below code I get "AttributeError: 'MediaPart' object has no attribute 'delete'"

        baseurl = "http://%s:%s" % (config('plex_server_host'), config('plex_server_port'))
        token = config('plex_server_api')
        plex = PlexServer(baseurl, token)
        movies  = plex.library.search(title)
        for movie in movies:
                for video in movie.iterParts():
                        if video.file  == filename:
                                print(video.delete())
                                print("Removing %s with file: %s from Plex" % (movie.title, video.file))

**Comment by Hellowlol** [comment]
The error message is pretty obvious. You need to use delete on media class.  See https://github.com/Hellowlol/plex-cli/blob/master/plexcli/cli.py#L198 for some work around I had to use

**Comment by speedyflipper** [comment]
I realized that but I wasn't sure how to get around it. But I looked at your code and once I was able to understand what was going on I was able to incorporate part of it into my script which now works exactly the way I wanted.

So Thank You Very Much
