### ISSUE TITLE
Update Progress Not Working for Managed User

### ISSUE THREAD

**Issue by speedyflipper** [pkkid/python-plexapi#269]
I'm writing a script which copies that status from one user to another. Whenever I try to take the progress from the main account run the updateProgress on the managed user I receive an unauthorized error. The exact function works when I change the token to the main account. 

I am able to run markWatched and markUnwatched on the managed account it just seems to have an issue with updateProgress

**Comment by Hellowlol** [comment]
Hey man. Can you post the code you used and the traceback?

**Comment by speedyflipper** [comment]
Below is a simplified version of the code. When the managed account api and the viewOffset is greater than 0, it errors. In every other scenario, it works 

```
from plexapi.server import PlexServer

api = '5K9LbzZfktFsf4LofJBN' #Managed Account
#api = '9yZyxU7RkyMiYRWrpfpC' #Main Account

guid = 'local://149332'
viewOffset = 50
baseurl = "http://%s:%s" % ('hostname', 32400)
movies  = PlexServer(baseurl, api).library.search(guid=guid)
for movie in movies:
        if viewOffset > 0:
                movie.updateProgress(viewOffset)
        elif viewOffset == 0:
                movie.markUnwatched()
        elif viewOffset == -1:
                movie.markWatched()

Traceback (most recent call last):
  File "lib/test.py", line 11, in <module>
    movie.updateProgress(viewOffset)
  File "/usr/local/lib/python3.5/dist-packages/plexapi/base.py", line 557, in updateProgress
    self._server.query(key)
  File "/usr/local/lib/python3.5/dist-packages/plexapi/server.py", line 346, in query
    raise BadRequest('(%s) %s; %s %s' % (response.status_code, codename, response.url, errtext))
plexapi.exceptions.BadRequest: (401) unauthorized; http://hostname:32400/:/progress?key=149332&identifier=com.plexapp.plugins.library&time=50&state=stopped <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
```

**Comment by Hellowlol** [comment]
Managed users dont seem to have access to this.
https://10-0-0-22.dc917a96cc3849428a10d411b00d2f69.plex.direct:32400/:/timeline?ratingKey=29937&key=%2Flibrary%2Fmetadata%2F29937&playQueueItemID=13349&state=buffering&hasMDE=1&time=4500000&duration=5791000&X-Plex-Product=Plex%20Web&X-Plex-Version=3.37.2&X-Plex-Client-Identifier=ffffff&X-Plex-Platform=Chrome&X-Plex-Platform-Version=65.0&X-Plex-Sync-Version=2&X-Plex-Device=Windows&X-Plex-Device-Name=Plex%20Web%20%28Chrome%29&X-Plex-Device-Screen-Resolution=1920x483%2C1920x1080&X-Plex-Token=xxxxxx&X-Plex-Provider-Version=1.1&X-Plex-Session-Identifier=yyyyy

i seems to be able to change the progress by changing the time param in the url over.

**Comment by speedyflipper** [comment]
Thanks but that doesn't seem feasible to do in a script
