### ISSUE TITLE
Baffled - how to play audio playlist to client?

### ISSUE THREAD

**Issue by mattpurnell** [pkkid/python-plexapi#273]
Hi - first of all, fantastic effort, just what Plex needs! With what they charge, you would think a good API would be very well supported.

Anyway - I can get as far as to authenticate, and programmatically pull down the playlist and client IDs  required. But I simply can't figure out how to play the playlist to the client.. I read somewhere that that a playqueue needs to be created then populated by a playlist, then it is the playqueue that is played - is that correct?

I am not exactly proficient in Python, so I am sure this is a factor in my issues - but I have seen plenty of Home Assistant users (and others) also failing to progress with Plex audio playlists via API. Apologies if there is something in the documentation, but I can't find it :)

Many thanks to anyone who can help out!

cheers
Matt

**Comment by Hellowlol** [comment]
Can you show some code of what you have tried so far? 

I thought it should be as easy as creating a playlist and use playMedia

**Comment by amazingr4b** [comment]
Do you need the c.connect()? I ask because I've never used that action, and I successfully play content, including playlists, using code like you have above, only with that omitted. I've tested mine with and without that line just now, and I see no difference in the behavior, but I could easily be missing something. No expert. 

This is my play playlist function as an example of how I use it- 
`
def playplaylist(playlist):
	plexlogin() #my plex login function
	playlist = playlist.lower() #lowercase playlist name to make matching easier
	PLEXMUSICCLIENT = musiccheck() #function that gets the name of my music client
	for plist in plex.playlists(): #find playlist in playlists
		if playlist == str(plist.title).lower():
			playlist = plist.title
			title = plex.playlist(playlist) #get playlist item from title match
                        client = plex.client(PLEXMUSICCLIENT) #initialize client
			client.playMedia(title) #play playlist
			return ("Now playing: " + playlist) #return what is playing
	return ("Error: " + playlist + " not found to play.") #return if no results found
`

**Comment by Hellowlol** [comment]
Im not sure if needed. I wouldnt be surprised it was needed for some client. Thanks for the tip btw! Why don’t you just pass plist directly to playMedia?

**Comment by socon** [comment]
I too am not proficient in python but I cobbled this script together.  This is for videos but should be the same for audio?  I have a bunch of arcade games in my garage.  When they turn on, a raspberry pi also turns on and boots into rasplex.  It calls this script which plays a bunch of music videos that are in a library.    I have not figured out how to create a playqueue directly from a library so I have a middle step of creating a playlist first.

`import sys, time, logging
sys.path.append("/storage/downloads/modules")
from plexapi.server import PlexServer
from plexapi import exceptions
#PLEX SERVER and TOKEN
baseurl = 'http://192.168.2.10:32400'
token = 'XXXXXXXXXXXXXXX'
logging.basicConfig(filename='/storage/.config/plex_video_player.log',format='%(asctime)s %(message)s', level=logging.DEBUG)

try:
    plex = PlexServer(baseurl, token)
except:
    logging.warning('No Plex server found at: {%s}', baseurl)
    print("Exiting script.")
    exit()

#PLEX LIBRARY WITH VIDEOS
library = '80sMTV'
#PLEX CLIENT TO PLAY VIDEOS
plexclient = 'RasPlex'
#PLAYLIST NAME  (Created on Plex Server by this script.  This will be deleted and re-created each time the script runs)
playlist_name = 'Rasplex Music Videos'

#pausing script for 30 seconds to let the raspberry pi boot up and get on network
time.sleep(30)    # pause 30 seconds

def main():
	client = plex.client(plexclient)
	#if playlist is leftover from last run, delete it.
	try:
		plex.playlist(playlist_name)
	except exceptions.NotFound:
		pass
	else:
		plex.playlist(playlist_name).delete()
		logging.info('Deleting %s from PlexServer playlists' , playlist_name)

	#Create list of videos from library
	logging.info('Creating list of videos from library: %s', library)
	videos =  plex.library.section(library).all()
	
	#Create a playlist containing all Videos in plex Library. 
	logging.info('Creating a playlist %s from list of videos', playlist_name)
	playlist = plex.createPlaylist(playlist_name, videos)
	
	#Create playqueue from playlist. API does not have a way to create playqueue from library or list of videos it seems.
	logging.info('Creating a playqueue from playlist')
	playq = plex.createPlayQueue(playlist, shuffle=1, repeat=1)
	
	#Play Videos on Client
	logging.info('Starting playqueue %s on plex client %s', playq.playQueueID, plexclient)
	player = client.playMedia(playq)

if __name__ == "__main__":
    main()
`

**Comment by mattpurnell** [comment]
> Hellowlol: Can you show some code of what you have tried so far?

Hi - I am very happy to see that there is an active and helpful community here - thanks for the prompt reply.

Well, this code (below) is mangled after some trial and error - but basically I had this (the 'Chilled' playlist already exists as a smart playlist, which is what I want to use):

```
from plexapi.server import PlexServer
from plexapi.playqueue import PlayQueue
from plexapi.playlist import Playlist

baseurl = 'http://______.ddns.net:32400'
token = '###################'
plex = PlexServer(baseurl, token)
for playlist in plex.playlists():
    if playlist.title == "Chilled":
        print ("Playing Chilled")
        try:
            client.setParameters(100, 1, 1, 'music')
        except:
            pass
        client.playMedia(playlist) 

```

I will play with your code, many thanks. Where would someone go, to find more examples (like yours here)?

If you know offhand, can you please indicate the best approach for a pre-existing Smart playlist?

**Comment by mattpurnell** [comment]
@amazingr4b  , @socon  and @Hellowlol  - thanks for the help, awesome. These snippets of code go a very long way toward getting us newbies over the learning curve.


Does anyone integrate with Home Assistant via ways other than the standard JSON HTTP sensors/commandline switches etc?

**Comment by Hellowlol** [comment]
.clients() returns a list so you need to get a client from within that list. You can find some code you just have to google for it. I use plexapi for plex-cli and bw_plex. There is also some scripts tautulli uses search for jbos. I have ha installed but I havnt had time to set it up properly. Only plex and ikea tråfri so far

**Comment by amazingr4b** [comment]
@mattpurnell sorry, don't use home assistant. I use the various apis for my home automation stuff. If you say what you are trying to do with that and plex we might be able to give you a suggestion.

**Comment by mattpurnell** [comment]
@amazingr4b  thanks for the kind offer of help, but I should be able to achieve my home automation goals once I get the python APIs working - from Home Assistant you can call commands and collect states easily enough. It is just that I saw hints elsewhere that some have integrated plexapi into the HA UI. I suspect it has perhaps influenced the inbuilt plex component in [Home Assistant.](https://github.com/home-assistant/home-assistant/blob/master/homeassistant/components/media_player/plex.py) Incidentally the Home Assistant approach (with Plex) does allow for playing playqueues and items etc, but multiple people are indicating that it has stopped working, and I can't get it to work either.

Can I please ask that you help diagnose my problem with using plexapi though?


Test code I am using:

```
from plexapi.server import PlexServer
from plexapi import exceptions
baseurl = 'http://serveraddress:32400'
token = '####################'
plex = PlexServer(baseurl, token)
client_name = "LOUNGEPC"
playlist_name = "Chilled"
playlist = plex.playlist(playlist_name)
client = plex.client(client_name) 
client.connect()
playq = plex.createPlayQueue(playlist, shuffle=1, repeat=1)
player = client.playMedia(playq)
```

...and the exception I get back below - seems to refer to a network timeout? ..but I can certainly confirm that the address and port are correct. I have double checked by using telnet to confirm that socket is definitely open. Client is the official Plex Media Client, running on a Win10 device.

```
>>> player = client.playMedia(playq)
Traceback (most recent call last):
  File "C:\Users\mattp\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\mattp\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\mattp\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\mattp\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\mattp\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\mattp\AppData\Local\Programs\Python\Python36-32\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mattp\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Users\mattp\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\mattp\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\mattp\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
    raise value
  File "C:\Users\mattp\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Users\mattp\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\mattp\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.2.61', port=32433): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mattp\AppData\Local\Programs\Python\Python36-32\lib\site-packages\plexapi\client.py", line 467, in playMedia
    }, **params))
  File "C:\Users\mattp\AppData\Local\Programs\Python\Python36-32\lib\site-packages\plexapi\client.py", line 195, in sendCommand
    return self.query(key, headers=headers)
  File "C:\Users\mattp\AppData\Local\Programs\Python\Python36-32\lib\site-packages\plexapi\client.py", line 160, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "C:\Users\mattp\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\mattp\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\mattp\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\mattp\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.2.61', port=32433): Read timed out. (read timeout=30)
>>>

```

**Comment by Hellowlol** [comment]
Your code works fine for me.  You should add logging to your script so you can see what url it fails on. Edit the plexapi config file or add the code below to your script.

````
import logging
logging.basicConfig(level=logging.DEBUG)

.... rest for your code.
````

**Comment by mattpurnell** [comment]
thanks @Hellowlol  - that's good confirmation that my code is OK.

I will try to capture some more info, but I suspect that I won't get more detail than the exception thrown as per above?

One more question - querying for plex clients never seems to bring up the Chromecast for me. does that work for you?

**Comment by pkkid** [comment]
Chromecast isn't really a Plex client. It won't be able to return a response when Plex is looking for clients on the network.

**Comment by mattpurnell** [comment]
Thanks @pkkid 

I just read https://github.com/pkkid/python-plexapi/issues/63 - did you manage to get it working via the methods in https://forum.xda-developers.com/android-tv/chromecast/plex-python-chromecast-t3520651/

**Comment by Hellowlol** [comment]
@mattpurnell The method he used in in one of the posts in #63

**Comment by inquanto** [comment]
@mattpurnell 
Did you manage to get the code working eventually?

I get exactly the same timeout error as you with the same code, im trying to cast the playlist to a raspberry pi running plex embedded. It works fine with music, but I cant get the playlist to play.

**Comment by mattpurnell** [comment]
@inquanto no - I gave up on calling ChromeCasts from Plex.

I ended up configuring some methods for calling playlists from Synology Audio Station instead.

However You can apparently call playlists using phlex, AKA Flex TV. It runs as a separate middleware between Google Home and Plex - but it can also be called using REST commands (so you don't need a Google Home to utilise it).

If I ever see some movement on this thread (https://forum.xda-developers.com/android-tv/chromecast/plex-python-chromecast-t3520651/page3) then I might revisit the subject..

**Comment by Hellowlol** [comment]
Pretty sure it works. Check out home assistant m, pretty sure they can do it there.
