### ISSUE TITLE
I need a little help with updateProgress

### ISSUE THREAD

**Issue by zombieagain** [pkkid/python-plexapi#274]
Hi,

thank you very much for the awesome API. I'm trying to synchronize two servers (the main one and one on the Shield TV, where I keep compressed versions of the movie and take with me when I travel).
I'm not good at all in python, and I'm stuck in trying to update the view offset.

`In [216]: plex.library.search('Death')
Out[216]: 
[<Episode:6605:Corporate-s01e02>,
 <Movie:6817:Happy-Death-Day>,
 <Episode:6975:Billions-s03e05>,
 <Episode:7326:Gomorrah-s03e02>,
 <Episode:7395:Walking-with-Dinosau-s01e06>]

In [217]: movie=plex.library.search('Death')[1]

In [218]: movie
Out[218]: <Movie:6817:Happy-Death-Day>

In [219]: type(movie)
Out[219]: plexapi.video.Movie

In [220]: movie.updateProgress(88888)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-220-4b43b259f8c1> in <module>()
----> 1 movie.updateProgress(88888)

/usr/lib/python3.6/site-packages/plexapi/base.py in __getattribute__(self, attr)
    271     def __getattribute__(self, attr):
    272         # Dragons inside.. :-/
--> 273         value = super(PlexPartialObject, self).__getattribute__(attr)
    274         # Check a few cases where we dont want to reload
    275         if attr == 'key' or attr.startswith('_'): return value

AttributeError: 'Movie' object has no attribute 'updateProgress'
`
So Movie object does not have that attribute, how do I do this? I see that updateProgress is in the class Playable, but I'm not sure how to go about it.

Sorry for the newbie question...

**Comment by zombieagain** [comment]
I also tried this method:

`movie.edit(**{"viewOffset":"322222"})`

I don't get any error back, but the value doesn't change in plex (I seem to be able to change most of the other attributes, but not the viewOffset)

I also tried this one but it gives me an error:

`movie.edit(**{"viewOffset.value":"322222"})`

Thanks!

**Comment by zombieagain** [comment]
For now I got around this using requests:

`requests.get(plex_url+':/progress?key='+str(movie.ratingKey)+'&identifier=com.plexapp.plugins.library&time='+str(new_offset)+'&X-Plex-Token='+token)
`

Still, I would like to know how to do this using the API, for cleaner code.

Thanks!

**Comment by Hellowlol** [comment]
Make sure you use the latest version as it should work. It should raise a attribute error as the method exist

**Comment by zombieagain** [comment]
Thanks! You were right, I was stupidly using 3.0.5 . All is working.
