### ISSUE TITLE
AttributeError: 'MyPlexAccount' object has no attribute 'password'

### ISSUE THREAD

**Issue by MichelfrancisBustillos** [pkkid/python-plexapi#277]
I have been working on my own fix for issue #272, using a POST request to get an authToken. I am trying to get the inputted username and password and have succeeded using account.username for the username, but am unable to do the same for the password. Using account.password yields a `AttributeError: 'MyPlexAccount' object has no attribute 'password'` error.

**Comment by Hellowlol** [comment]
The issue you linked to is about a script that isnt compatible with 3.0.6. What are you trying to do?

**Comment by MichelfrancisBustillos** [comment]
Fixed. This is intended API behavior. Proper syntax to pull authToken already exists (`account.authenticationToken`).
