### ISSUE TITLE
Where do I start?

### ISSUE THREAD

**Issue by ascheel319** [pkkid/python-plexapi#280]
I'm new to plexapi and also new to python, where do I start? I installed python and installed the api. I looked for the config.ini file and couldn't find it. What I want to do is to make it so that some on the shows on my plex to show a different pre-roll. I'm on Ubuntu Server 18.04 if that makes a difference.

**Comment by amazingr4b** [comment]
I'd recommend starting with the examples of how to play various items on the the examples. That config file is optional. Everything needed to find and play something was in them last I checked. 

`
from plexapi.server import PlexServer
baseurl = 'http://plexserver:32400'
token = '2ffLuB84dqLswk9skLos'
plex = PlexServer(baseurl, token)

cars = plex.library.section('Movies').get('Cars')
client = plex.client("Michael's iPhone")
client.playMedia(cars)
`

There isn't some flag you can just set or easy command you can send to do this, so you'll have to be a little creative. For example, if I wanted to use a script to play a preroll before watching show X, I'd have that script first have a play action for the preroll I wanted to play, and then a second action to play show X. There are numerous ways you can handle knowing when the preroll is done to have it then play the desired show. You could make use of the duration information available in the objects you play to sleep a certain amount of time between the plays. Other options include using the EventListener to react based on play/stop, or react to webhooks, provided you make something to listen for them. There are bound to be others. Using a sleep based on duration is probably the easiest to start with IMO, but someone else might feel different on that subject.

**Comment by ascheel319** [comment]
@amazingr4b That's about the logic that I thought of. Have the episode be 2nd and the pre-roll be first. So where would I make the file? Does it matter? Also would it run it anytime that the parameters are met?

**Comment by amazingr4b** [comment]
Having the file be on the same network as the client and server is easiest. The run anytime part really depends on what you make and how you make it. I'm not sure how people go about making things show and work as plugins from the webui. Maybe someone else will chime in on that front if that is your endgame. I never use the plexweb, so figuring that part out was never that important to what I do. The control script I use is a stand alone thing. Depending on how you do it there is likely a way to have it work only when certain parameters are met. If you are not opposed to using something independent of the plexweb you can have it do whatever you want. One of the devs of this api has a side project that detects and automatically skips intros and credits, for example. I had prerolls and playlists long before plex did. Once you know how to find and play content you can literally make something to do anything you can think of.

**Comment by amazingr4b** [comment]
Here's an example of the code I use to do this:

```
preply = getpreroll() #this is a custom function that returns the name of a preroll. ask to know more
plexclient() #function connects to my plex server and client. basically lines 1-4 and 6 from the previous examples
waitdur = int((preply.duration)/1000) + 1 #gets duration of preroll + 1 second
client.playMedia(preply) #plays preroll
time.sleep(waitdur) #waits time preroll plays
return (playme(upnext())) #client.playMedia with next up item + output for what it is playing. ask if want more info
```

**Comment by ascheel319** [comment]
@amazingr4b so it doesn't matter where I put it on my server just as long as it's there? It should still work if the client playing and the server aren't on the same network right? Like if a friend is playing something at their place and my server is at mine. I don't know much about python so sorry for any redundant questions, but I do have experience in other languages.

**Comment by amazingr4b** [comment]
Mine works no matter where it is. As far as the remote client part, maybe. It is unlikely you'll be able to influence your friends remote streams indirectly like it sounds like you are wanting, but anything is possible. It all comes down to how much work you want to put into it and how good you are. The api usually only shows clients local to the server, so you'd likely need to do customization to get past that unless your remote users are on board with using whatever you provide to control things.

**Comment by ascheel319** [comment]
Do you know if there is a way to impact the whole server and not just the individual user? I could see there being one and there not being one. I was able to get it to at least test stuff. I was able to login using the name and password way but not the way with the token.

**Comment by ascheel319** [comment]
@amazingr4b How would I test to see what show it playing? I've been looking around and can't find how I should do it.

**Comment by amazingr4b** [comment]
You want to see what is currently playing on the client? You'd use look at plex.sessions(). Here is one way:
```
for sess in plex.sessions():
   print (sess.players[0].title) #playername
   print (sess.title) #title of what is playing
```

**Comment by ascheel319** [comment]
@amazingr4b How can I get it so that it looks at the show that will be playing and puts a pre-roll before that? I just can't figure out how I can get it to work. If I could just get it to work so that there is a pre-roll for all shows then I can tinker around with it from there to get it to what I want.

**Comment by amazingr4b** [comment]
I use an external queue, and have mine setup so it always knows what will play next. It sounds like you are intending to use plex's own play queue. If that is the case look at the PlayQueue object and the playqueue.py file. Those should give you an idea of what to do if no examples exist. I believe you should be able to interact with the plex queue, but someone else would need to chime in on that front.
