### ISSUE TITLE
Forced transcoding by getStreamURL

### ISSUE THREAD

**Issue by DaaBraa** [pkkid/python-plexapi#281]
The _getStreamURL_ method in [base.py](https://github.com/pkkid/python-plexapi/blob/master/plexapi/base.py) is hard-coded to return URL with transcoded stream. This means that the only way to access the original video file URL is to start downloading it. I also feel like it's somewhat unintuitive - I'd expect that by default _getStreamURL_ would return untouched video file and transcoded video would be provided by overloaded or separate method.

I don't know my way around Plex API but I did some experimenting with PlexKodiConnect which allows to stream untouched files from Plex. This is the URL it uses for direct playback (domain name, token and client identifier redacted):

https://plex.example.com:443/library/parts/260/1524924117/file.mkv?X-Plex-Platform=Windows&X-Plex-Client-Platform=Windows&Connection=keep-alive&X-Plex-Device-Name=PlexKodiConnect&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-Plex-Token=xxxxxxxxxxxxxxxxxxxxxx&X-Plex-Client-Identifier=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&Accept=%2A%2F%2A&X-Plex-Device=PlexKodiConnect&X-Plex-Product=PlexKodiConnect&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=2.3.8

The relevant PKC methods are _getPlayUrl_ in [playutils.py](https://github.com/croneter/PlexKodiConnect/blob/master/resources/lib/playutils.py) and _transcode_video_path_ in [plex_api.py](https://github.com/croneter/PlexKodiConnect/blob/stable-version/resources/lib/plex_api.py)

**Comment by Hellowlol** [comment]
So whats the question?

If you need the untouched url just grab the parts key. See .download for a example
