### ISSUE TITLE
PyPI version of this library is too out of date (2018-03-02) to include userRating property

### ISSUE THREAD

**Issue by SirNavith** [pkkid/python-plexapi#284]
`Track.userRating` was added in #259, but that was before the last time [the library was pushed to PyPI ](https://pypi.org/project/PlexAPI/). 

Could another upload please be done, so that installs done through `pip` will reflect the repo here?

I would like this because I am making a small program (also going to be installed through `pip`) that uses this library and uses the `Track.userRating` property which wouldn't be available through a dependency install and would thereby have to be manually cloned.

Thank you.

**Comment by mikes-nasuni** [comment]
I agree we should update. In the meantime, you can add this line to your requirements pip file to install directly from github.

```git+https://github.com/pkkid/python-plexapi.git```

**Comment by andrey-yantsen** [comment]
Can we have a new release? [The tests are fine](https://travis-ci.org/pkkid/python-plexapi/builds/437136914) 😸

**Comment by pkkid** [comment]
https://pypi.org/project/PlexAPI/3.1.0/

**Comment by pkkid** [comment]
In my other project, they set things up to auto-upload to pypi if all tests pass in Travis. I don't know how they did it, but maybe I can look it up. We should do that here.

**Comment by andrey-yantsen** [comment]
That was quick, thank you! :)

> In my other project, they set things up to auto-upload to pypi if all tests pass in Travis. I don't know how they did it, but maybe I can look it up. We should do that here.

Actually we have this [configured here as well](https://github.com/pkkid/python-plexapi/blob/master/.travis.yml#L67-L80), the only thing you need to do — is to push a version tag to the repo.
