### ISSUE TITLE
Video Info

### ISSUE THREAD

**Issue by Ric878** [pkkid/python-plexapi#286]
Hi,

Sorry if this is the wrong place to ask this question. I did not see any information on where to post non "issue" type questions. If this should be posted somewhere else please let me know.

That said, could someone let me know if the following is possible? I would like to get information on specific Movies or TV Shows in a PMS library, specifically, I would like to know when the media file was added to the library.

What I'm trying to accomplish is creating a script that will automatically prune TV Shows after a predetermined amount of time based on when the file was added. For example, to delete all episodes that are older than 60 days based on when the media was added to my server, rather than when the episode aired or the file creation date on the file system.

Thanks,
Ric

**Comment by Ric878** [comment]
Thanks for the reply. Could you be so kind as to point me in the right direction on how to accomplish the video info aspect or provide an example. Been reading through the documentation but I have not found what I'm looking for yet. Thanks.

**Comment by Hellowlol** [comment]
Use the addedAt attribut to compare the Datetime objects. Iterate the parts and use .delete on them. Or use the location to delete the file using normal os calls.
