### ISSUE TITLE
Playable._prettyfilename() should sanitise filename

### ISSUE THREAD

**Issue by andrey-yantsen** [pkkid/python-plexapi#293]
It's expected that the method `_prettyfilename()` would return a valid filename, because of `filename` in its name and docstring :) But if you have an Artist named `Lovely/Bones`, with an Album named `very*very` and a track named `dev/\0` — you would be unpleasantly surprised when you try to save it under suggested name.

**Comment by Hellowlol** [comment]
I dont use the music feature. Feel Free to change it so It’s sanitized.

**Comment by andrey-yantsen** [comment]
I mean... it’s not only about the music, the problem exists for any kind of media :)

-- 
Andrey Yantsen
Badoo.com developer
Tel.: ‭‭+44 7564 966022‬‬
Skype: andrey_janzen

**Comment by Hellowlol** [comment]
The only reason I added it was that I wanted a way to get downloads in showname.sxex format. Ill fix this later.
