### ISSUE TITLE
Get a PlexObject by rating_key

### ISSUE THREAD

**Issue by Brianbrifri** [pkkid/python-plexapi#299]
I've read the docs and looked at the source code and, please correct me if I am wrong and point me in the right direction, but I did not see a way to get a PlexObject by it's rating key. 
I've been using a script to add a label to all recently added items and this works: 
```python
headers = {"X-Plex-Token": PLEX_TOKEN}
    params = {"type": 1,
              "id": rating_key,
              "label.locked": 1,
              "label[0].tag.tag": LABEL
              }

    url = "{base_url}/library/sections/{section_id}/all".format(base_url=PLEX_URL, section_id=section_id)
    r = requests.put(url, headers=headers, params=params)
```

I really like this plex api and I would like to be able to get a PlexObject via its rating_key like so:

```python
plex = PlexServer(baseurl, token)
item = plex.library.sectionByID(section_id).get(rating_key)
```
or
```python
plex = PlexServer(baseurl, token)
item = plex.library.sectionByID(section_id).getByRatingKey(rating_key)
```
or some way that is in line with your standards. 

Please let me know your thoughts. Thanks!

**Comment by Hellowlol** [comment]
This is already supported. Use fetchItem(1337)

**Comment by Brianbrifri** [comment]
Is that available off of any PlexObject? So if get a plex instance from base url and token, do I need to get the library and/or section?

**Comment by Brianbrifri** [comment]
Nice! Thanks...apparently I needed to convert the rating_key to an int from Tautulli as it sends as a string. 

And yes, I was aware of the addLabel function. Appreciate the help in making sure I was on the right track

**Comment by Brianbrifri** [comment]
I also was calling fetchItem off the incorrect object, so there's that

**Comment by Brianbrifri** [comment]
FWIW:
```python
plex = PlexServer(baseurl, token)

title = sys.argv[1]
section_id = sys.argv[2]
rating_key = sys.argv[3]
label = 'Family_Friendly'

item = plex.library.fetchItem(int(rating_key))
item.addLabel(label)
item.analyze()
print("The label '{label}' was added to '{title}'.".format(label=label, title=title))
```
