### ISSUE TITLE
Search with VideoResolution.

### ISSUE THREAD

**Issue by Zachary24** [pkkid/python-plexapi#304]
I'm new to python and the plew API, I'm trying to replicate the graphs that came with transmogrify... What I have so far is...

```python
from plexapi.server import PlexServer

baseurl = 'URL'
token = 'TOKENID'
plex = PlexServer(baseurl, token)
movies = plex.library.section('Movies')
shows = plex.library.section('TV Shows')

for video in shows.search():
    print(video.title)
```

I'm unsure of how to only get files of a certain resolution, I've read almost all of the documentation, and the only time I saw the resolution used is when syncing or streaming the URL... Any help would be appreciated

**Comment by amazingr4b** [comment]
Not sure if you can specifically search by that, but try adding something like this in place of your print(video.title)_** -
if video.media[0].videoResolution == "hd":
     print (video.title)

This page details the various attributes you can get:  https://github.com/pkkid/python-plexapi/blob/54b26fdc25137651fed57cb2120f11dc0a69da4d/plexapi/media.py

videoResolution might not be the best to use since it seems to report "hd" and "sd," but you might be able to use size/width or one of the others. 

The "view xml" section for a specific items info from within plex should also give you a good idea on what attributes might be the best to use there.

**Comment by Zachary24** [comment]
I've tried passing height/width, but I haven't gotten it to work..

**Comment by amazingr4b** [comment]
They work for me just fine.
`mvs = plex.library.section("Movies").search("Tremors")
print (mv.media[0].height)
print (mv.media[0].width)
`
344
720

If you want help I'd recommend including your code and what it returns.

**Comment by Hellowlol** [comment]
Your pretty close. You can find the correct docs https://python-plexapi.readthedocs.io/en/latest/modules/library.html#plexapi.library.LibrarySection.search look under ```**kwargs``` there is something called resolution.

**Comment by Zachary24** [comment]
Thank you! That worked perfectly. But, it only worked with my movie library, (not my shows)... Is it different for a Show Library? Here's the output I get when trying with shows..
_**Traceback (most recent call last):
  File "/Users/zacharysimpson/Desktop/Plex_Graph/Main.py", line 15, in <module>
    for video in show.search(resolution=['1080'], libtype='episode'):
  File "Packages/PlexAPI/plexapi/library.py", line 493, in search
    args[category] = self._cleanSearchFilter(category, value, libtype)
  File "Packages/PlexAPI/plexapi/library.py", line 514, in _cleanSearchFilter
    raise BadRequest('Unknown filter category: %s' % category)
plexapi.exceptions.BadRequest: Unknown filter category: resolution**_

**Comment by Hellowlol** [comment]
I thought this was added to plex when the new filters was added. This is not added to plexapi. Anyway you have to do this manually. Should be easy to implement for you. Let me know if you need some assistance.

**Comment by blacktwin** [comment]
Here is something you could try for shows:

```python
targetRes = ['1080']
shows = plex.library.section('TV Shows')
for show in shows.all():
    for video in show.episodes():
        if video.media[0].videoResolution in targetRes:
            print('{} - S{:0=2d}E{:0=2d} - {}'.format(
                    video.grandparentTitle, int(video.parentIndex),
                    int(video.index), video.title.encode('utf-8')))
```
Include whatever resolution you're looking for in `targetRes` list.

**Comment by Hellowlol** [comment]
@blacktwin you can’t help yourself 😂. Btw you can use _prettfilename() to get this as showname sxxeyy format

**Comment by Hellowlol** [comment]
Just checked there is a filter for this in plex web.
