### ISSUE TITLE
search **kwargs

### ISSUE THREAD

**Issue by hidaba** [pkkid/python-plexapi#306]
I'd like search for genre that contain a string. I want filter music that contain "Jazz" in genre like:  Jazz, Acid Jazz, Jazz Latin. I only managed to look for one genre at a time:

```python
music = plex.library.section('Musica')
for musica in music.search(title=None, sort=None, maxresults=1000,genre="Jazz"):
    ...
```

**Comment by blacktwin** [comment]
Is there an error when you attempt that code?

```python
print(plex.library.section('Music').search(genre='Jazz'))
```
This works fine for finding Jazz genre artist.

**Comment by pkkid** [comment]
@blacktwin - I believe he's trying to search multiple categories at once. -- @hidaba Plexapi doesn't let you wild card the search values, but you can use a list of exact matches. Try this:

```python
music = plex.library.section('Musica')
for musica in music.search(title=None, sort=None, maxresults=1000,genre=["Jazz", "Acid Jazz", "Jazz Latin"]):
    ...
```

**Comment by hidaba** [comment]
@pkkid Thank you, works perfectly!
