### ISSUE TITLE
markWatched() extremely slow and causing timeouts.

### ISSUE THREAD

**Issue by zetas** [pkkid/python-plexapi#312]
I wrote a script to keep watched status in sync with multiple plex servers and I have it as optimized as I can. I basically create a delta array of unwatched items and process only those to keep API calls to the minimum amount but there's no getting around making an API call for each markWatched() call and this call is extremely slow. To mark 300 movies watched can easily take 2 or 3 hours, and this is with a local server.  This might be ok if it was just movies but there could be thousands of items that need to be sync'd with the TV section :( 

Is there any way to speed this up? I've scoured the docs looking for some way to batch mark things as watched but it seems like I have no choice but to loop through Video objects and markWatched() on each one. Does anyone have any recommendations?

This is the code in question for syncing movies, obviously tv requires more logic:
```python
syncedCount = 0
    fullContent = masterLibrary.search(unwatched=False)

    masterWatchedTitles = []

    for content in fullContent:
        masterWatchedTitles.append(content.title)

    slaveWatchedContent= slave.library.section(library).search(unwatched=False)
    slaveUnwatched = {}
    slaveWatchedTitles = []

    for content in slaveWatchedContent:
        slaveWatchedTitles.append(content.title)
        
    s = set(slaveWatchedTitles)
    updateContentTitles = [x for x in masterWatchedTitles if x not in s]

    if len(updateContentTitles) > 0:
        slaveUnwatchedContent = slave.library.section(library).search(unwatched=True)
        for content in slaveUnwatchedContent:
            slaveUnwatched[content.title] = content
        with tqdm(total=len(updateContentTitles)) as pbar:
            for title in updateContentTitles:
                slaveContent = slaveUnwatched.get(title)
                if (slaveContent is None):
                    if verbose:
                        pbar.write('{} not found on {}!'.format(title, slave.friendlyName))
                    pbar.update(1)
                    continue
                if slaveContent.viewCount == 0:
                    if verbose or dryrun:
                        pbar.write('{} is watched on {} but not on {}.'.format(title,master.friendlyName,slave.friendlyName))
                    if not dryrun:
                        slaveContent.markWatched()
                        if verbose:
                            pbar.write('{} marked as watched on {}.'.format(title,slave.friendlyName))
                            pbar.write('--------')
                    syncedCount += 1
                pbar.update(1)
```

**Comment by Hellowlol** [comment]
if markWatched is slow you can submit that job to a thread pool.

**Comment by zetas** [comment]
You talking about using `plexapi.utils.threaded(callback, listargs)`?

**Comment by zetas** [comment]
Ah ok cool, thank you. That worked better for me. The `threaded` function is fairly confusing. It has a results variable inside that function but it seems to always be set to `None` no matter what I return from the function... 

Anyway I used the basic thread pool In python and that sped it up quite a bit so thanks for that suggestion. I will close this issue

**Comment by zetas** [comment]
Actually running `library.searchEpisodes(unwatched=False)` only took a second on my library of over 30,000 episodes. Maybe its been sped up since then? I did look at your example and I noticed you are using the `guid` as a way to figure out if it's the same item. I considered that but I assumed guid's were server specific, I will definitely look at that again. In the meantime I'm using the search method to find each episode by show, season, and episode. It obviously takes much longer heh.

**Comment by zetas** [comment]
Unfortunately it's basically useless due to the fact that the video has to be reloaded to access it so every time I want to look at the guid it's an additional API call. I spent like 3 hours last night trying to figure out why that info isn't included with the rest of the data in plexapi. When I visit the XML url manually it's always included so it's very confusing :(

**Comment by Hellowlol** [comment]
That’s because your accessing the info using the ratingkey. If you do the same using plexapi it doesn’t require a reload. Just reload the inside the thread pool.

**Comment by zetas** [comment]
I tried reloading inside a thread pool and it crashed my plex server lol. I tried getting the tv shows your way and the plexapi way:
```python
key = '/library/sections/{}/all?type=4&viewCount>=0'.format(masterLibrary.key)
fullContent = masterLibrary.fetchItems(key)
```

and 
```python
fullContent = masterLibrary.searchEpisodes(unwatched=False)
```

and then creating a thread pool to reload the guids:
```python
def updateGuid(*args, **kwargs):
    guids = []
    argList = list(args)

    currentIteration = argList.pop()
    returnVals = argList.pop()

    for arg in argList:
        guids.append(arg[0].guid)

    returnval[i] = guids

for content in fullContent:
    threadWork.append([content])

guids = threaded(updateGuid, threadWork)
```

**Comment by Hellowlol** [comment]
Mind posting the entire script? I’m sure we could make this simpler.

**Comment by zetas** [comment]
Sure, and yea, it's getting stupid complex... My initial attempt was to just grab a list of episodes by show and season and then filter them that way but that does not guarantee an exact match. If I can use guids that would be the best solution so I've spent the time to try to get it working. Here is what I have so far:

```python
def sync_tv(masterLibrary, master, slave, library):
        # key = '/library/sections/{}/all?type=4&viewCount>=0'.format(masterLibrary.key)
        # fullContent = masterLibrary.fetchItems(key)

    fullContent = masterLibrary.searchEpisodes(unwatched=False)
    syncResult = []
    masterWatchedGUIDs = []
    # New way to try to grab GUIDs faster:
    with tqdm(total=len(fullContent)) as pbar:
        pbar.write('Compiling list of watched content on master...')
        for content in fullContent:
             masterWatchedGUIDs.append([content, pbar])

        l = masterWatchedGUIDs
        n = 50
        threadWork = [l[i:i + n] for i in range(0, len(l), n)]
        threaded(updateGuid, threadWork)
        # pool = ThreadPool(8)
        # syncResult = pool.map(updateGuid, masterWatchedGUIDs)  
        # pool.close()
        # pool.join()

    print(vars(syncResult))
    return 0
    #Old Way:
    slaveWatchedContent = slave.library.section(library).searchEpisodes(unwatched=False)
    slaveWatchedGUIDs = []
    slaveUnwatched = {}

    with tqdm(total=len(slaveWatchedContent)) as pbar:
        pbar.write('Compiling list of watched content on slave...')
        for content in slaveWatchedContent:
            slaveWatchedGUIDs.append(content.guid) 
            pbar.update(1)

    s = set(slaveWatchedGUIDs)
    updateContentGUIDs = [x for x in masterWatchedGUIDs if x not in s]

    if len(updateContentGUIDs) > 0:
        slaveUnwatchedContent = slave.library.section(library).search(unwatched=True)
        for content in slaveUnwatchedContent:
            slaveUnwatched[content.guid] = content
        toMarkWatched = []
        with tqdm(total=len(updateContentGUIDs)) as pbar:
            for guid in updateContentGUIDs:
                slaveContent = slaveUnwatched.get(guid)
                if (slaveContent is None):
                    if verbose:
                        pbar.write('{} not found on {}!'.format(
                            guid, slave.friendlyName))
                    pbar.update(1)
                    continue
                if slaveContent.viewCount == 0:
                    if verbose or dryrun:
                        pbar.write('{}:{} - {} is unwatched on {}!'.format(
                            slaveContent.grandparentTitle, slaveContent.seasonEpisode, slaveContent.title, slave.friendlyName))
                    if not dryrun:
                        toMarkWatched.append([slaveContent, pbar])
                        # if verbose:
                        #     pbar.write('{} marked as watched on {}.'.format(title,slave.friendlyName))
                        #     pbar.write('--------')
                    # syncedCount += 1
            if verbose:
                pbar.write('Batch processing unwatched files...')
            # syncResult = threaded(markWatched, toMarkWatched)
            if len(toMarkWatched) > 0:
                pool = ThreadPool()
                syncResult = pool.map(markWatched, toMarkWatched)  
                pool.close()
                pool.join()
    return sum(syncResult)

**Comment by zetas** [comment]
Actually here's the entire script: https://github.com/zetas/PlexSimpleSync it's sync.py. The argparse help should be sufficient but here's the command I'm using: `python3 sync.py -dv myusername my password --libraries "TV Shows" --servers server1 server2`

**Comment by pkkid** [comment]
I'm taking a stab at this cleaning up this script; but its hard to tell the rules you set here.
1. Are you only syncing watched episodes on both servers?
2. Are you syncing bi-directionally, or one way?

**Comment by zetas** [comment]
The script is definitely not "done" it needs a lot of cleaning but I figured I'd get the nitty gritty implementation of the library out of the way first before doing that. To answer your questions:

1. I'm only syncing watched items
2. Syncing bi-directionally. If you pass the script 2 servers and 2 libraries it will run 4 sync events: server1 -> server 2 for library 1, server 1 -> server 2 for library 2, server 2 -> server 1 for library 1, server 2 -> server 1 for library 2.
3. It doesn't ever mark anything as "unwatched" so im not sure what you mean by mis-match but if the "master" server in a sync operation has content the "slave" does not it just skips it. My initial attempt was to look up movies simply by title and tv shows by show, season, and episode index (and if that failed, it would search for episode title as one last chance at a match). 

The problem is if I'm syncing content to a brand new server that has all my library data but not the watched status it has to update around 400 movies and around 5000 tv episodes. It can take 20-30 seconds per execution of "markWatched()" which is why I went down the road of using threads. That makes it much quicker. 

The next problem is @Hellowlol introduced me to using GUID's to match content instead of their titles and other meta data which seems like a much better matching system to be but for some damn reason the GUID's are never returned by the initial search, whenever I try to access them it does yet another API call, vastly increasing the amount of time it takes to do the lookups and marking watched so I'm kinda stuck at an impasse right now. 

If you look at the script you can see both methods of lookup, title and GUID and let me know which you think is better and If you do decide to submit a PR to make that script better, I'd definitely welcome it. Though I'm sure you're super busy with this library and other things so no hard feelings if you don't get to it or don't want to. 

Thanks for everything :)

**Comment by pkkid** [comment]
FWIW: Guid is not being returned in the /all listings for me either.
