### ISSUE TITLE
playlist: list tracks

### ISSUE THREAD

**Issue by hidaba** [pkkid/python-plexapi#313]
Hello all,
I want empty a specific playlist and I think the method is get the list of tracks in this playlist and after delete them from it.
my stupid question... I can't get list of tracks from playlist.

for playlist in plex.playlists():
    if playlist.key == '/playlists/82452' :
       myplaylist =  playlist

?? myplaylist.items()

**Comment by blacktwin** [comment]
@hidaba If you want to remove items from a playlist try:

```python
playlist = plex.playlist('Name of Playlist')
for item in playlist .items():
    playlist.remove(item)
```

**Comment by hidaba** [comment]
@blacktwin your example have an error in removeItem but now it works, thank you

miaplaylist = plex.playlist('Jazz')
for item in miaplaylist.items():
    miaplaylist.removeItem(item)
