### ISSUE TITLE
Return what players are playing what media

### ISSUE THREAD

**Issue by russellaugust** [pkkid/python-plexapi#315]
I can get all active sessions (return the active sessions, then return the offset for the playhead time).

But I'm having trouble getting the players that are currently playing the media.

I'd like to get get all of the players currently streaming, then what media they're streaming.  The goal is to present a list of all active media so a user can interact with it.

**Comment by pkkid** [comment]
It's a little unclear due to the inheritance, but the items returned from `plex.sessions()` all inherit from [Playable](https://python-plexapi.readthedocs.io/en/latest/modules/base.html#plexapi.base.Playable), which includes a self.players which is what you want.

```python
for item in plex.sessions():
    for player in item.players:
        print(player.device)
```

**Comment by russellaugust** [comment]
thanks, that solved my issue!
