### ISSUE TITLE
MusicSection Search - Cannot search by 'track.userRating'

### ISSUE THREAD

**Issue by jmlw** [pkkid/python-plexapi#317]
I am attempting to search the MusicSection by the `track.userRating` property defined in the Plex API. 

Examining the Plex Web Client's API call when defining a custom filter int he music section, it results results in a call like:
`https://x.x.x.x:32400/library/sections/10/all?type=8&track.userRating=10`

Attempting to use the `MusicSection.search` method with a kwarg dict containing `track.userRating` causes a `BadRequest` exception because it's not an allowed search parameter.

I've manipulated the python-plexapi source locally to add `track.userRating` to the `ALLOWED_FILTERS` tuple. This allows performing searches in the music library by a specific rating.

**Comment by hidaba** [comment]
try this:

music = plex.library.section('Musica')
for musica in music.search(title=None, sort=None, maxresults=9999, libtype="album") :
     plexTracks = musica.tracks()
     for p,track in enumerate(plexTracks):
         pTrack  = track.userRating
         if (pTrack == 10):
              print(track.title)

**Comment by jmlw** [comment]
@hidaba thank you for the suggestion. This is a possible approach which will work, however it is not an optimal solution; Plex Media Server has search by track rating functionality built in so utilizing a server side function would be much more efficient.

Plex server may also impose a limit on the number of results returned on the server side, so if a library were larger than that limit and no paging functionality available, it would not be possible to find all relevant results.
