### ISSUE TITLE
search **kwargs with also != > <

### ISSUE THREAD

**Issue by hidaba** [pkkid/python-plexapi#320]
Hello,
is it possible add the search not only for = but also for > or != or <  ?

example:
music = plex.library.section('Musica')
for musica in music.search(title=None, sort=None, maxresults=99999, libtype="album",genre != 'Pop') : #not

for musica in music.search(title=None, sort=None, maxresults=99999, libtype="album",genre = 'Pop') : #contain

for musica in music.search(title=None, sort=None, maxresults=99999, libtype="album",genre == 'Pop') : # equal

for musica in music.search(title=None, sort=None, maxresults=99999, libtype="album",year > 1970) : # major

**Comment by andrey-yantsen** [comment]
As for != you can use something like `search(title=None, **{'year!': 2000})` (not the most convenient way, but at least this), others aren't supported, afaik.

**Comment by Hellowlol** [comment]
We should add more filters so we can lean more on pms for searching. 

You also have fetchitems where you can use all kinds for operators

**Comment by Hellowlol** [comment]
The easiest way would be to use

````
all_pop_before_70 = music.all(genre__exact='pop', year__lte=1970)
````

**Comment by blacktwin** [comment]
> We should add more filters so we can lean more on pms for searching.

From #392 some of the filters that PMS uses are not able to be used with plexapi for some reason.
