### ISSUE TITLE
Download from shared library does not work

### ISSUE THREAD

**Issue by marcdieters** [pkkid/python-plexapi#321]
Hi,

Downloading from a shared library does not work. It exits out with:
<name of file>.mkv: 91.0B [00:00, ?B/s]

Downloading from my own library does work.

Can you please have a look at this ?

Thanks

**Comment by Hellowlol** [comment]
Logs and the code you used please.

**Comment by andrey-yantsen** [comment]
Seems like there are only 2 ways of downloading the content from shared servers: via getStreamURL or with MobileSync. Quote from https://support.plex.tv/articles/201018507-download-media/:
> Note: Downloading is not available for shared Libraries.

Also there is an old thread from the Plex forum: https://forums.plex.tv/t/download-media-from-shared-server/27939.
