### ISSUE TITLE
Play counts for audio

### ISSUE THREAD

**Issue by tarcus69** [pkkid/python-plexapi#322]
I'm trying to get a list of all unplayed audio tracks in ascending order of age but so far the "unwatched" filter and the "viewcount" filter aren't working. This may well be my inexperience.

Here's the relevant code snippets and the resulting error:
```
podcasts = plex.library.section('Podcasts')
for podcast in podcasts.search(sort="addedAt:asc",maxresults=100,libtype="track",unwatched=True):

Traceback (most recent call last):
  File "./podcastlist.py", line 25, in <module>
    for podcast in podcasts.search(sort="addedAt:asc",maxresults=100,libtype="track",unwatched=True):
  File "/usr/local/lib/python2.7/dist-packages/plexapi/library.py", line 496, in search
    args[category] = self._cleanSearchFilter(category, value, libtype)
  File "/usr/local/lib/python2.7/dist-packages/plexapi/library.py", line 520, in _cleanSearchFilter
    raise BadRequest('Unknown filter category: %s' % category)
plexapi.exceptions.BadRequest: Unknown filter category: unwatched
```

**Comment by tarcus69** [comment]
Drat, it looks like "unwatched" is not in the ALLOWED_FILTERS list for Music sections.. Back to the drawing board.

**Comment by blacktwin** [comment]
Plex does not have a filter for unplayed/unwatched. Can we close this issue?

**Comment by tarcus69** [comment]
I haven't used the library since the comment, so if the only person who cares is me then please go ahead. Plex does have the ability to filter by playcount, not sure if your library exposes that or not. It might be an idea to update the documentation to reflect that the filters aren't available to "all", but I haven't checked to see if that's already been done as I no longer use the library. Thanks for your time anyway.

**Comment by blacktwin** [comment]
Yes, viewCount is exposed with this library. 
```python
plex.library.section('Music').search(**{'track.viewCount':3})
```
However right now it seems that OPERATES (greater than, less than, etc) are not working when the filter has a `.` separator. See #392. So once that is resolved the code will look like this:

```python
plex.library.section('Music').search(**{'track.viewCount__gt':3})
```
For finding tracks that have greater than 3 plays.
