### ISSUE TITLE
Remote Access to Server

### ISSUE THREAD

**Issue by mutto233** [pkkid/python-plexapi#323]
As I am using the PlexAPI, I am noticing that I'd like to use the tool with a server that is outside the local network.  However, when I attempt to either play a video file, or connect with the Plex server, when I am outside the local network of the same Plex server, I am unable to connect or play the video.

I am wondering if the addition of Remote Access is a possibility for the PlexAPI, as it would do wonders in implementation with the setup I am running.

If it means anything, in my implementation I am running 3.0.4, and I know the code is up to 3.0.6.  Is this something that has been added in future releases?

**Comment by Hellowlol** [comment]
This is already supported. What have you done so far?

**Comment by mutto233** [comment]
Interesting.  So I haven't done a complete debugging of this yet on my end, but basically I have attempted to connect to play a movie and specified a client that was remote to the plex server. After nothing was played, I used the plexapi to query what clients were connected. Upon doing that, I noticed that the only listed clients were local ones.

**Comment by mutto233** [comment]
If you're interested in seeing this in context, I'm using the plexapi in conjunction with the pseudochannel repository.

**Comment by mutto233** [comment]
A couple things. First off, any idea when this started being supported. What commit or version? Second, any ideas of a test case that can possibly be run?

**Comment by mutto233** [comment]
Ahh interesting. Though tbh I'm not too surprised. In your experience has there been a decent work around for this? Or is it something we just have to chalk up to the limitations plex is setting for us?

**Comment by Hellowlol** [comment]
That outside the scope of the project. You would need do something like synclounge.
