### ISSUE TITLE
How to get the current playback position of a client

### ISSUE THREAD

**Issue by grayseagull** [pkkid/python-plexapi#327]
I want to get the time of the current playback position of a client. I use timeline() but only get the output below:

<Element 'MediaContainer' at 0x762521a0>

I don't understand this. Can anyone tell me what to do to get the time I want? Thanks.

**Comment by amazingr4b** [comment]
I use something like this:
`for mediatype in client.timeline():
		if int(mediatype.get('time')) != 0:
			print (mediatype.get('time'))`

**Comment by grayseagull** [comment]
> I use something like this:
> 
> ```
> for mediatype in client.timeline():  
> 		if int(mediatype.get('time')) != 0:  
> 			print (mediatype.get('time'))
> ```
> that gives it in something ms. I like to know minutes out of total minutes, so I add this to mine:
> 
> ```
> check = mediatype.get('time')
> check2 = mediatype.get('duration')
> check = int(check)/60000
> check2 = int(check2)/60000
> say = "We are at minute " + str(int(check)) + " out of " + str(int(check2)) + "."
> print (say)
> ```

Thank you very much for your help. Your answer solved my problem very well. Based on your code, I modified it to print more accurate playback time (for my goal I need more precise playback time to compare with the contents of the subtitle file). I put it underneath, in case other people need it too
```
vtime = 0
while True:
    for mediatype in client.sendCommand('timeline/poll',wait=0):
        if not mediatype.get('time') is None:
            oldvtime = vtime
            vtime = float(mediatype.get('time')) / 1000
            if vtime - oldvtime == 1:
                clock = time.time()
            else:
                print(time.time() - clock + vtime)
```
