### ISSUE TITLE
Add an addActors method

### ISSUE THREAD

**Issue by b1tninja** [pkkid/python-plexapi#328]
I tried _edit_tags('role', ['blah']) but for a 401/403

**Comment by b1tninja** [comment]
This might have actually been because the other video media type does not have actors, that might only be for things like movies. Feel free to close? But such methods are helpful for us newbs

**Comment by blacktwin** [comment]
```python
movie._edit_tags(tag="actor", items=["Blah"])
movie.refresh()
print(movie.roles)
# to remove
movie._edit_tags(tag="actor", items=["Blah"], remove=True)
movie.refresh()
print(movie.roles)
```
Roles is the listing of actors in a video.

@b1tninja Do you want to confirm this before I close it?
