### ISSUE TITLE
Fix when casting to ps4

### ISSUE THREAD

**Issue by Silvarilon** [pkkid/python-plexapi#330]
Hiya, apologies if this isn't the right place/method to report things, or if it's already reported. I'm totally new to git, just created an account so I could leave this message.

When I tried to use the library, it worked great when playing media to my phone, but couldn't play anything to the ps4 plex client. The python error was "read timed out", IIRC.

I managed to make it behave by editing client.py, and adding 'type': media.listType, to the sendCommand('playback/playMedia', ...) arguments.

I did see in various API documentation that the type is necessary for commands like play or pause, but shouldn't be necessary for playMedia - but it doesn't work for me without a type, and does work with it.

It still plays to my phone when including the type, so there doesn't seem to be any harm to clients that don't need it.

Please let me know if there's some formal way I should be submitting this suggestion.

Cheers!

(Also a huge thanks for this! I'd never used Python before either, and it was quick & easy to use. Without this api, I wouldn't have known where to start!)

**Comment by Hellowlol** [comment]
Thanks for this. Ill try to replicate and see this works on other clients or if its a workaround we only need for ps4.

**Comment by amazingr4b** [comment]
I added it in my setup. Didn't seem to negatively impact anything for me, though an interesting byproduct is now instead of the xbox1 client crashing for me it tries to play content but throws a codec error. I've not had a chance to look into the codec error part yet.

**Comment by Silvarilon** [comment]
I’m on the phone, but will try to get specifics when I’m home.

I haven’t yet figured how to control the ps4 generally with scripts, so I
need to manually start it and run the Plex client. The client then connects
to the Plex account and my two Plex servers.

I can then use python to connect to either server and see the ps4 Plex
client when I list clients. If I’m remembering correctly, it has no name,
but does have a description. I loop through the list and use the machine ID
to set the client. I could then send it pause commands without problems.

The ps4 Plex client ONLY appears when it’s already running and connected to
the servers. It occasionally would be running on the ps4 and not show in
the client list, I think because it timed out or something. Other times it
would sit idly for ages and still was listed.

After that my script ends, so I don’t know whether it has problems
maintaining a connection. I just search for the client each time I want to
pause or unpause.

When connecting via the Plex account rather than directly to my servers, I
could see the ps4 in the client history, but it didn’t seem to update
properly. I don’t think it’s changed at all since I first looked, so
there’s probably some issue there. Maybe it only updates when I first
logged into my account on the ps4? I don’t know if those tokens are out of
date.

When playing media, I needed to make that change to send the media type,
otherwise it worked like in your example.

I notice that if I start the movie from the ps4 I can use either python or
the ps4 controller to pause. If I start the movie from python then the ps4
controller can’t pause, but python still can.

Sorry for the infodump rather than a specific answer. Hopefully it’ll help.

Cheers,
Tony

**Comment by Silvarilon** [comment]
Here's the code that's (so far) working for me.

I'm using FLASK to run a web server, so that I can voice control using
Google Mini.

It'll throw an error about not finding the client if Plex isn't running on
the PS4, since I haven't done any check to make sure that we found the
client. But seems to work without problems if the Plex client is turned on.

I haven't yet set up anything to play a specific show or movie via voice,
so plexControlAPI.py only pauses/unpauses - but I've tested and can
successfully play movies and episodes using the code in test.py
(You can also see some of my other commented out attempts to debug and get
it working)

This was my first attempt writing Python, so I may well be doing things in
a really clumsy way.

Cheers,
Tony

**Comment by Hellowlol** [comment]
media.listType is added to playMedia()
