### ISSUE TITLE
How to change selected audio/subtitle streams

### ISSUE THREAD

**Issue by gstacks13** [pkkid/python-plexapi#333]
I'm attempting to set the "selected" flag on audio and subtitle streams through Python.  I'm able to access said streams of a video through this code:

```
episode = plex.library.section('TV Shows').get('Show').episodes()[0]
episode.reload()
episodePart = episode.media[0].parts[0]
audioStreams = episodePart.audioStreams()
subtitleStreams = episodePart.subtitleStreams()
```
And can even see which streams are selected through:
`audioStreams[streamNum].selected`

But as far as how to set specific streams as selected, I'm stumped.  I see that there's the setAudioStream() and setSubtitleStream() methods in the client class, but does that mean I have to connect to an existing client to set the flags?  Or am I missing something obvious that'll let me do it via the server API?

**Comment by Hellowlol** [comment]
What are you trying to do? Just changing one? Change during playback? Change all to some audio to some other lang?

**Comment by amazingr4b** [comment]
I don't have an answer for how to change the settings on the items in the library. I did this a little different and use something like the alertlistener to monitor what I am watching. If a show or movie is playing that for me needs subtitles is playing the listener sends a setsubtitleStream command to my client to enable whichever one matches "eng."

here's a snipit of what I use:

`psess = plex.sessions()
	for sess in psess:
		if (sess.players[0].title == PLEXCLIENT):
			sess.reload()
			for sub in sess.subtitleStreams:
				if sub.languageCode =="eng":
					client.setSubtitleStream(sub.id, mtype="video")
					`

Sure would be a lot easier if you could preset the option like you are hoping.

**Comment by Hellowlol** [comment]
I dont even know if its possible to preset this. Ill look into it.

**Comment by gstacks13** [comment]
That's not a bad solution at all @amazingr4b.  The problem for me, though, would be that my preferences for each show are vastly different. Some shows, for example, have English audio that I don't want to use.  Some have foreign audio and subtitles on by default, but for that show I want English audio and no subtitles.  There's really no universal setting that would work for me. 

That said, I could always combine the two ideas and modify my script to keep a database of seasons/shows and their preferred stream IDs, then set up the listener to switch to them when it detects them playing.  This may be the route I end up pursuing if I can't get my original idea working.

> 
> 
> I dont even know if its possible to preset this. Ill look into it.

Thank you so much - I greatly appreciate it!  I really hope to get this working, because I know I'm not the only one with this issue, so I'm sure others could make use of the script as well.

**Comment by andrey-yantsen** [comment]
Preset audio stream can be set by sending `PUT` request to `/library/parts/<PART_ID>?audioStreamID=<AUDIO_STREAM_ID>&allParts=1` and subtitles by `PUT` to `/library/parts/<PART_ID>?subtitleStreamID=<SUBTITLES_STREAM_ID>&allParts=1`. You can get all the placeholders from your `Media`-object, to be precise — `.parts` field of it, and then send the query with `server.query(URL, method=server._session.put)`.

**Comment by gstacks13** [comment]
Oh my gosh that worked!!! Thank you so much!  I can't to get this implemented in the script!

One final question for you - do you have the URL to deselect all subtitle streams?

**Comment by andrey-yantsen** [comment]
Just send 0 as `subtitleStreamID`.

**Comment by gstacks13** [comment]
That did it!  Thanks again @andrey-yantsen.  So glad to finally have this working!

**Comment by Hellowlol** [comment]
Send a pr if you think this needs to be in plexapi.
