### ISSUE TITLE
The Travis-CI builds aren't runs automatically

### ISSUE THREAD

**Issue by andrey-yantsen** [pkkid/python-plexapi#337]
https://travis-ci.org/pkkid/python-plexapi/builds

The last automatic build was on 21st of Jan, have you disabled it voluntarily or something went wrong?

**Comment by pkkid** [comment]
Builds are ran for every commit or pull request and then once a month if the code is static. Looks like the last one was 10 days ago, so I think it may not be broken, but it doesn't build very often on static code.

**Comment by pkkid** [comment]
I merged a few things yesterday tho, so it should have ran. ¯\_(ツ)_/¯

**Comment by andrey-yantsen** [comment]
Yeah, I know that there is not much changes in the repo here, but we have a bunch of untested commits in the master: 
![image](https://user-images.githubusercontent.com/629281/52381575-dbdae800-2a69-11e9-8875-e33d63c01cec.png)

**Comment by andrey-yantsen** [comment]
And the recent PRs aren't tested as well:
![image](https://user-images.githubusercontent.com/629281/52381587-f2813f00-2a69-11e9-9a06-4e3076081f97.png)

**Comment by pkkid** [comment]
Everything looked turned off in the settings on Travis. I think it's correct now.

**Comment by andrey-yantsen** [comment]
Yep, seems to work now, thanks!
