### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by andrey-yantsen** [pkkid/python-plexapi#338]
In the last build on Travis-CI (https://travis-ci.org/pkkid/python-plexapi/builds/485214005) we have 2 issues:

1. One from flake8:
```
utils.py:8:1: F401 'datetime.timedelta' imported but unused
```

2. And the second is a failing test `test_smart_playlist` on quite old PlexServer version, 1.3.2, which was released somewhere around Dec 2016, while smart playlists become available in late 2017 (not sure on this one, honestly). I see 3 options here:
    
    1. Choose a newer "oldest" version for testing, e.g. 1.9.7 from Nov 2017
    2. Abandon testing agains old version and test only against latest
    3. Add some magical pytests marker to prevent the test been ran on such an old version

    What do you think?

**Comment by Hellowlol** [comment]
i imo

**Comment by pkkid** [comment]
I vote #1 as well.

**Comment by pkkid** [comment]
The flake8 failure should be fixed now.
