### ISSUE TITLE
playMedia returning a Syntax Error

### ISSUE THREAD

**Issue by mjdgoldeneye** [pkkid/python-plexapi#344]
I ran into an issue while testing the API functionality. Here's my code:

```
from plexapi.myplex import MyPlexAccount
account = MyPlexAccount('REDACTED', '[REDACTED')
plex = account.resource('REDACTED').connect()

cars = plex.library.section('Movies').get('Cars')
client = plex.client("Pixel 2")
client.playMedia(cars)
```

**The video plays**, but I get this error:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Other Applications\Python 2.7\lib\site-packages\plexapi\client.py", line 467, in playMedia
    }, **params))
  File "E:\Other Applications\Python 2.7\lib\site-packages\plexapi\client.py", line 194, in sendCommand
    return self.query(key, headers=headers)
  File "E:\Other Applications\Python 2.7\lib\site-packages\plexapi\client.py", line 167, in query
    return ElementTree.fromstring(data) if data.strip() else None
  File "<string>", line 124, in XML
cElementTree.ParseError: syntax error: line 1, column 0

I'm unsure what's causing this.

**Comment by Hellowlol** [comment]
The xml response is junk

**Comment by mjdgoldeneye** [comment]
So, just disregard it?

**Comment by Hellowlol** [comment]
As long as the video starts, yes

**Comment by pkkid** [comment]
This looks like a bug in the Plex client, and not specifically in python-plexapi. They sent us bad XML which we cannot parse, and this stack trace is the result. While we may be able to add extra code on our end to not parse the XML response, or detect this bug and show something nicer, it's not really worth the effort when you consider the number of clients and constantly changing code on their end.
