### ISSUE TITLE
updateFriend() does not default to all libraries 

### ISSUE THREAD

**Issue by blacktwin** [pkkid/python-plexapi#346]
[Documentation](https://python-plexapi.readthedocs.io/en/latest/modules/myplex.html?highlight=updatefriend#plexapi.myplex.MyPlexAccount.updateFriend) suggests that not having the `sections=` attr will result in all libraries being selected by default when updating a Friend.

```python
plex = PlexServer(PLEX_URL, PLEX_TOKEN)
plex.myPlexAccount().updateFriend('username', plex)
```

This is the same when removing sections as well.
```python
plex = PlexServer(PLEX_URL, PLEX_TOKEN)
plex.myPlexAccount().updateFriend('username', plex, removeSections=True)
```

The result is that no update occurs. PR incoming.

**Comment by Hellowlol** [comment]
I only documented this to make users aware. Honesty I think it should be as it is now, but change the docs we state that the library has to be explicitly set.

**Comment by blacktwin** [comment]
Sounds good to me.
