### ISSUE TITLE
Not and Issue - Question for You guys

### ISSUE THREAD

**Issue by boivinx7** [pkkid/python-plexapi#349]
So hi, 
You have a great project on your Hands guys Congrats,
Personally I suck completely in Python but I'm pretty decent in Powershell. 
I've already started My Own thing, but im pretty much blocked at trying to edit Stuff.
Im trying to find out what you guys are doing, but its been 5 days, and I'm still so far away from anything. 
So Can someone just give me an exemple of the URL you use to do the WebRequest to Edit Metadata and/or Collections.

If you have anything in the way Plex has is on there site:
http://[PMS_IP_ADDRESS]:32400/library/sections/29/refresh?X-Plex-Token=YourTokenGoesHere
Would be Great.

Thanks

**Comment by Hellowlol** [comment]
See https://github.com/pkkid/python-plexapi/blob/master/plexapi/base.py#L325

**Comment by boivinx7** [comment]
Yeah that the section I have been spending my time on. I still dont get it.
So thanks but its not helpfull.

**Comment by Hellowlol** [comment]
Well that pretty much some of the simplest code, but I’ll try to explain it.

We take the parameters (se the example in the doc string) we url encode it and join it with the rest of the partial url (see the part variable) we then do a http put command using that url.

**Comment by boivinx7** [comment]
Yeah I get that, but I'm trying to do it in powershell
So if I could just get an example of a Final URL that you get it would help greatly.
it's easy for you to Get it you are Levels above me in Python, I read it and don't get most of it.

**Comment by boivinx7** [comment]
Ok Got it using this 
kwargs = {'type': 1,
                 'id': '281120',
                 'collection[0].tag.tag': 'Super',
                 'collection.locked': 0}
print(urlencode(kwargs))

Now I have to Convert your urlencode

**Comment by boivinx7** [comment]
Got it all.
God that bot a great api that plex has 😜
But anyway ill be able to publish a powershell module soon now.
