### ISSUE TITLE
Allow remote control through PlexAPI

### ISSUE THREAD

**Issue by sbaier1** [pkkid/python-plexapi#352]
As far as i can tell from the documentation and previous issues, it is currently not possible to remote control a PlexAPI based player through other Plex clients such as the mobile clients.

It would be extremely convenient if a PlexAPI client could register its state on the Plex server and allow the developer to implement callbacks/actors for Remote Control actions to perform appropriate logic so a third party player can be controlled by other 3rd party and native clients.

Is there any official / inofficial documentation on how this API works on the Plex side of things? I assume WebSocket is used for this purpose?

**Comment by pkkid** [comment]
> Is there any official / inofficial documentation on how this API works on the Plex side of things? I assume WebSocket is used for this purpose?
There is no documentation on how to use the Plex Server API. Everything we built here is from us using Chrome or Firefox to inspect the ajax calls being made from the Plex Web Client to the server and building logic around that. Websockets are only used for the notifications afaik. I haven't seen the Plex Web Client using it for anything else at least.

**Comment by sbaier1** [comment]
Alright then, i will see if i can figure anything out if i find the time.

**Comment by Hellowlol** [comment]
What do you mean by remote control? On another network?

**Comment by sbaier1** [comment]
Not necessarily on another network, i mean the general feature of the official Plex client where you can advertise a player as such and other clients (e.g. the android client) can connect to that client to control it, play certain items in the library, etc.

Apparently they use a [custom multicast protocol](https://github.com/NineWorlds/serenity-android/wiki/Good-Day-Mate) for this:

**Comment by Hellowlol** [comment]
You can control clients on your own network. (some stuff clients flaky) Se https://python-plexapi.readthedocs.io/en/latest/modules/client.html is this what your looking for?

**Comment by sbaier1** [comment]
I am aware of this, but what i am considering is the other way around, so plexapi would support this discovery / control mechanism as a "player", so official clients and the like can control plexapi based players

**Comment by Hellowlol** [comment]
I still dont get it. As for discovery that alreadly include in netdisco, its read only but it can find the server for you. plexapi isnt a player it acts as a controller. Can you give me a example of what you trying to do? You could use plexapi together with a webserver if you want third party integration.

**Comment by sbaier1** [comment]
I am using mopidy in conjunction with plexapi. This allows me to play music from my plex library using a mopidy frontend plugin. However, this is sometimes not optimal, because the mopidy frontends have a very different user interaction flow and the frontends each have some flaws in their design.

Therefore i was considering if plexapi could / should have support for being controlled by official clients as well, in the manner mentioned in the opening post.

**Comment by Hellowlol** [comment]
Ah i see, you want to advertice plexapi as a player, so you can select that in the dropdown in a official app. Any commands sent to this should be relayed to another client that your actually trying to control.
