### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by Hellowlol** [pkkid/python-plexapi#356]
This is just a list of features that I have noticed that are not possible with plexapi. If you have time to help out, we would love if you choose one of these areas.

- [x] Upload subtitles
- [ ] New stats page

**Comment by blacktwin** [comment]
For anyone who may want to start adding these.

POST Upload subtitles 
`http://127.0.0.1:32400/library/metadata/{RATING_KEY}/subtitles?title={SUB_FILE}.srt
&format=srt`

GET dashboard
`http://127.0.0.1:32400/statistics/bandwidth?timespan=6`

`http://127.0.0.1:32400/statistics/resources?timespan=6`

`http://127.0.0.1:32400/statistics/media?timespan=3`

`http://127.0.0.1:32400/library/all/top?type=2&viewedAt%3E=1565723660&limit=6`

**Comment by JonnyWong16** [comment]
Both #384 and #636 have been merged.
