### ISSUE TITLE
Update (maybe?) not working with 1.16.1.1291

### ISSUE THREAD

**Issue by brandonscript** [pkkid/python-plexapi#357]
(Cross-post: https://forums.plex.tv/t/plexapi-python-lib-not-updating-library-anymore/430555)

I've tested this a few times, but it appears that using PlexAPI `3.1.0` and Plex Server `1.16.1.1291` (on Synology NAS DSM 6.2.1-23824 Update 1), the Plex Server doesn't update.

Code I'm using to reproduce:

```
plex = PlexServer(baseurl=config.plex.baseurl, token=config.plex.token, timeout=10)

for section in (plex.library.section(section) for section in ["Movies"]):
    section.update()
```

Plex never updates here.

But I've tested using the npm version for Node ([v5.2.2](https://www.npmjs.com/package/plex-api)), and it appears to properly trigger the update.

Happy to troubleshoot more, but I'm not sure where to start? The Python lib doesn't return any errors (200 OK all the way).

Node code to reproduce a successful update: 

```
var PlexAPI = require("plex-api")
var client = new PlexAPI({
    hostname: "127.0.0.1",
    port: 32400,
    token: "xxxxxxxxxxxxx"
})
 
client.query("/library/sections").then(function(result) {
    let movies = result.MediaContainer.Directory.filter(obj => {
        return obj.title === 'Movies'
    })
    client.perform(`/library/sections/${movies[0].key}/refresh`).then(function () {
    }, function (err) { })

}, function (err) { })
```

**Comment by Hellowlol** [comment]
Thats a weird way to do this. 

You don’t you use use section() and check if the title is in your list?

Do you get any errors? If you look at the code you can see that we are doing the same as the node plexapi. I see no reason why this shouldn’t work.

Do you get error?

**Comment by brandonscript** [comment]
Admittedly a weird way to do that, but I'm pulling the list of sections from a config file, and it's an array. 

Even doing this, though, it still isn't working, and there are no errors (not even when I enable logging via config.ini). 

```
plex = PlexServer(baseurl=config.plex.baseurl, token=config.plex.token, timeout=10)
plex.library.section('Films').update()
```

But now I'm starting to wonder if it ever worked – when I use `refresh()` instead (which I now notice the endpoint on the Node version is using `/refresh` instead of `/update`, it works?! I've always assumed this was working, but maybe not 🤷‍♂

**Comment by Hellowlol** [comment]
What was the solution?

**Comment by brandonscript** [comment]
`refresh()` seems to work fine? So I'm not sure what `update()` was doing, but swapping that out made it work OK. I'm not sure how I wouldn't have noticed it not working for as long as I've been using it this way, but it's possible I just assumed it was working and never was?

**Comment by Hellowlol** [comment]
They shouldn’t do the same thing. Update should find new stuff added to the library while refresh also updates the metadata.

**Comment by brandonscript** [comment]
Hrm. OK, then we're back to square one where I don't know how to tell if update is working. Switching Node version to the /update endpoint also appears to not update Plex now.

**Comment by Hellowlol** [comment]
Your check the console in plex web or check if the scanner is running using some Linux tool
