### ISSUE TITLE
Unable to start a playlist on PlexMediaPlayer

### ISSUE THREAD

**Issue by inquanto** [pkkid/python-plexapi#358]
Hey there I know theres already a thread about pretty much this issue (#273) but i doesn't seem like it was resolved completely so I hope its okay im opening a new one.

Im trying to start playback of a music playlist on a rpi running plex embedded. Its working fine for movies, like in the example code or music, however I just cant get it to work for a playlist. Is there something im overlooking?

This works to play a song:

```python
from plexapi.server import PlexServer
import time

baseurl = 'my plex ip and port'
token = 'myplextoken'
plex = PlexServer(baseurl, token)
client = plex.client("Plex")
artist = plex.library.section('Music').get('Two Medicine')
album = artist.album('Astropsychosis')
track = album.track('Will Not')
client.playMedia(track)
```

**However This doesnt work to play a playlist:**

```python
from plexapi.server import PlexServer
import time

baseurl = 'my plex ip and port'
token = 'myplextoken'
plex = PlexServer(baseurl, token)
for playlist in plex.playlists():
    print(playlist.title)
client = plex.client("Plex")
music_playlist = "The title of my playlist"
client.playMedia(music_playlist)
```

Ive tried many variations of the code also from the other thread but just like the user there i get a timeout error...
Any help would be really appreciated!

**Comment by Hellowlol** [comment]
I assume that music_playlist is a actual playlist and not a string as in your example. You should enable some logging so we get some more details.

**Comment by inquanto** [comment]
Yes I've tried both playing the playlist item:
(plex.playlist("The title of my playlist")
as well as creating a playque with the playlist and playing that..

Heres the output from the logs:

`DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.178.222:32400
DEBUG:urllib3.connectionpool:http://192.168.178.222:32400 "GET / HTTP/1.1" 200 2881
DEBUG:urllib3.connectionpool:http://192.168.178.222:32400 "GET /clients HTTP/1.1" 200 343
DEBUG:urllib3.connectionpool:http://192.168.178.222:32400 "GET /playlists HTTP/1.1" 200 332
DEBUG:urllib3.connectionpool:http://192.168.178.222:32400 "GET /playlists HTTP/1.1" 200 332
DEBUG:urllib3.connectionpool:http://192.168.178.222:32400 "POST /playQueues?includeChapters=1&includeRelated=1&playlistID=19004&repeat=1&shuffle=1&type=audio HTTP/1.1" 200 1411
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.178.63:32433
DEBUG:urllib3.connectionpool:http://192.168.178.63:32433 "GET /player/timeline/subscribe?commandID=1&port=32400&protocol=http HTTP/1.1" 200 None`

**Comment by Hellowlol** [comment]
So the command timeout. Wft is plex embedded? What client is this? You can try to enable proxyThroughServer then do the playMedia cmd

**Comment by inquanto** [comment]
Plex embedded is a version of plex media player to run on the raspberry pi similar to rasplex. Like i said I have no problem starting playback of movies and songs on the same client, so I dont think that the connection is the issue, what exactly is proxy through server and where would I enable that?

**Comment by Hellowlol** [comment]
The connection is the issue... for some reason the client doesn’t respond and it fails. It’s right there in the traceback. It’s a method in the client class.

**Comment by inquanto** [comment]
I did some further testing and managed to play it on Plexamp running on my macbook, so this seems to be an issue with PlexMediaPlayer specifically as it wont work with both PMP running on my Raspberry Pi or PMP running on my Macbook...

**Comment by Hellowlol** [comment]
Closing this as it seems like a client issue
