### ISSUE TITLE
Feature Request: "Stations" Support

### ISSUE THREAD

**Issue by beville** [pkkid/python-plexapi#361]
Plex has recently add support for their "stations" feature to the web UI.  The stations are basically auto-generated playlists ("Library Radio", "Time Travel Radio", "Random Album Radio").  

Not sure if it's do-able, but I'm guessing for the folks working on this project it'd probably be pretty straight-forward to reverse-engineer and add support to this library.

Thanks!

**Comment by blacktwin** [comment]
POST:
```
http://127.0.0.1:32400/playQueues?type=audio&uri=server%3A%2F%2F{MACHINE_ID}2%2Fcom.plexapp.plugins.library%2Flibrary%2Fsections%2F27%2Fstations%2F1%3FincludeSharedContent%3D1&repeat=0&own=1&includeChapters=1&includeGeolocation=1&includeExternalMedia=1&X-Plex-Token={TOKEN}
```
