### ISSUE TITLE
Add ability to add/remove items from Collections

### ISSUE THREAD

**Issue by rkhwaja** [pkkid/python-plexapi#37]

**Comment by mjs7231** [comment]
Collections definition is here: https://support.plex.tv/hc/en-us/articles/201273953-Collections -- Shouldn't be too hard to add support, seems almost identical to playlists.

**Comment by mjs7231** [comment]
Collections are support in search with the following checking.  I would still like to list items in a collections as well as add/remove.

commit b10faf8560f19a5047bea5e0b117a1300ef5d58d
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Thu Mar 31 16:52:48 2016 -0400
Checkpoint: New implementation for search

**Comment by Hellowlol** [comment]
This feature was added some time ago.
