### ISSUE TITLE
Play video question

### ISSUE THREAD

**Issue by juvebogdan** [pkkid/python-plexapi#371]
Hello All,

I am sorry but this is the only way I found to ask the question about the API. What I wanted is to get the play path of a video from my Plex server and play it in vlc. This is what I did:

from plexapi.server import PlexServer
baseurl = 'http://ipaddress:32400'
token = 'mytoken'
plex = PlexServer(baseurl, token)

plex.library.all()[0].getStreamURL()

The URL I got from this works fine but when I tried watching this at the same time on another device they cut off. What am I missing here? 

I appreciate any help on this.

Thank you

**Comment by Hellowlol** [comment]
Are you trying to use the same url on two devices at the same time?

**Comment by juvebogdan** [comment]
Yes, I am. Is that not allowed? 
I found that token here https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/

**Comment by Hellowlol** [comment]
Dunno, I have never tried it. I don’t think this a plexapi issue.

**Comment by juvebogdan** [comment]
What is a client in plexapi? What does this piece of code do:

**Comment by Hellowlol** [comment]
That is a real client like ios, android, pht, pmp etc.
