### ISSUE TITLE
Make UI reload playlist items?

### ISSUE THREAD

**Issue by chrisknepper** [pkkid/python-plexapi#373]
Thanks for making this!

I'm using version 3.1.0 on macOS with Python 3.7.4.

I am wondering if it's possible to make the UI (particuarly the web UI) aware that a playlist has changed after using this API to add/move/delete items in a playlist.

For example, say I have the Plex web UI open in a browser tab and viewing an individual playlist. I then call the Python API to add an item to this playlist and again to delete a different item in the playlist. The web UI does not update (such as via Ajax), and even if I go to a different page in the UI and use the UI to navigate back into the playlist items view, the changes are not reflected. The only way to get the changes to reflect is to reload the entire page via the browser refresh button.

Yet, when CRUD is performed on a playlist via the web UI, the changes can generally be seen the next time the playlist is viewed, without having to reload the whole browser.

I've tried calling `reload()` on the playlist instance as well as `refreshSync()` on the server instance.

**Comment by Hellowlol** [comment]
Im not sure this will work, i guess the web ui watches the state of the playlist when you edit it using the web ui. You can check dev tools and see what info is sent to the server. Reload will not work, this a way to update the plexapi object with new info from pms.

I would checkout the methods in the client class, show media or refresh playque dunno if what will work.

**Comment by pkkid** [comment]
Pretty sure this is not possible from the server commands. Pretty sure there are no commands to tell a client to update it's UI either.
