### ISSUE TITLE
Error 422 when syncing to Windows app

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [pkkid/python-plexapi#374]
When I try to sync to my laptop (which uses the Windows Store app), I get the following Traceback:
```Traceback (most recent call last):
  File "<input>", line 3, in <module>
  File "<input>", line 2, in test_add_show_to_sync
  File "C:\Python37\lib\site-packages\plexapi\video.py", line 120, in sync
    return myplex.sync(sync_item, client=client, clientId=clientId)
  File "C:\Python37\lib\site-packages\plexapi\myplex.py", line 477, in sync
    }, params=params)
  File "C:\Python37\lib\site-packages\plexapi\myplex.py", line 176, in query
    raise BadRequest('(%s) %s %s; %s' % (response.status_code, codename, response.url, errtext))
plexapi.exceptions.BadRequest: (422) unprocessable_entity https://plex.tv/devices/24223038-d5d5-469d-93bc-44264ee24a93/sync_items?SyncItem%5Btitle%5D=Hitoribocchi+no+Marumaru+Seikatsu+-+Season+1+-+%28s01e06%29+Summer+Comes+in+5-7-5&SyncItem%5BrootTitle%5D=Summer+Comes+in+5-7-5&SyncItem%5BmetadataType%5D=episode&SyncItem%5BmachineIdentifier%5D=5e228d6cb5e2bbcae57507d19ffa5a3591caa603&SyncItem%5BcontentType%5D=video&SyncItem%5BPolicy%5D%5Bscope%5D=all&SyncItem%5BPolicy%5D%5Bunwatched%5D=0&SyncItem%5BPolicy%5D%5Bvalue%5D=0&SyncItem%5BLocation%5D%5Buri%5D=library%3A%2F%2Fe8fc35e6-f0fe-47ae-98d5-d48bed4c603e%2Fitem%2F%252Flibrary%252Fmetadata%252F14507&SyncItem%5BMediaSettings%5D%5BaudioBoost%5D=100&SyncItem%5BMediaSettings%5D%5BmaxVideoBitrate%5D=&SyncItem%5BMediaSettings%5D%5BmusicBitrate%5D=192&SyncItem%5BMediaSettings%5D%5BphotoQuality%5D=74&SyncItem%5BMediaSettings%5D%5BphotoResolution%5D=1920x1080&SyncItem%5BMediaSettings%5D%5BsubtitleSize%5D=&SyncItem%5BMediaSettings%5D%5BvideoQuality%5D=&SyncItem%5BMediaSettings%5D%5BvideoResolution%5D=; <?xml version="1.0" encoding="UTF-8"?> <errors>   <error>Expected X-Plex-Sync-Version: 1</error> </errors> 
```

Code snippet:
```show.sync(VIDEO_QUALITY_ORIGINAL, client=account.device('Laptop'))```

When using the same code to sync to any other of my devices, there are no issues whatsoever.
The interesting part seems to be **Expected X-Plex-Sync-Version: 1**.
Is it possible to somehow use Sync version 1, or would that require additional implementation?

**Comment by andrey-yantsen** [comment]
@CtrlAltDefeat94  Which Plex version are you using? Can you please share more code you're using? I have no idea about protocol for Sync-v1, current mobile apps are using 2nd version.

**Comment by CtrlAltDefeat94** [comment]
The desktop app is version 3.2.20.0.
I believe the app hasn't seen any updates since 2017, hence why it still uses version 1.
My server (for as far as that's relevant) automatically updates to the latest stable version whenever it is released.

I'm still using this desktop app because there's no alternative to sync to windows machines.

As for sharing more code. All I have is like 5 lines to find the shows I want to sync, and the line mentioned above to create the sync task.

**Comment by andrey-yantsen** [comment]
You could try to set the version manually:

```
plexapi.BASE_HEADERS['X-Plex-Sync-Version'] = '1'
```

Unfortunately I can’t help you here, I don’t have any old Plex clients nor Windows near me :(

If it wouldn’t work, I can suggest you to use my app [plexiglas](https://github.com/andrey-yantsen/plexiglas), with additional Plex server on your Windows machine.

**Comment by CtrlAltDefeat94** [comment]
Manually setting the version to 1 seems to have fixed the problem :)

This Windows client hasn't been updated in forever and can barely be called "functional".
I'm still using it because I could find no real alternative to sync some content to my laptop for watching on the go.

I'm still going to look into what I can do with your app. If I can use it for above mentioned, I'll switch over without a second thought :P
