### ISSUE TITLE
Results truncated

### ISSUE THREAD

**Issue by webleyg** [pkkid/python-plexapi#376]
When running the following command the results are truncated to 31 characters. 

```
testPlex = plex.library.section('TV Shows').all()
print(testPlex)
```

I'm not a python guy so this may be a python issue but any help that can be offered will be appreciated.

**Comment by pkkid** [comment]
You were seeing the string representation of the object which will be truncated.

```python
testPlex = plex.library.section('TV Shows').all()
for item in testPlex:
    print(item.title)
```
