### ISSUE TITLE
How should I scan or match media through the API? Please give some advice!

### ISSUE THREAD

**Issue by BH1NBN** [pkkid/python-plexapi#377]
I want to do the function of the two functions of serach() updata() in the official api function. Is this api able to achieve remote matching and scanning?

**Comment by Hellowlol** [comment]
Have you tried reading the docs https://python-plexapi.readthedocs.io/en/latest/ or the examples in the readme?

I’m not really sure if I understood you question correctly but it is possible to search for a media item on a server(both, local, remote and a shared server)
