### ISSUE TITLE
Return None when executing client.playMedia(playmedia)

### ISSUE THREAD

**Issue by BH1NBN** [pkkid/python-plexapi#380]
I am pretty sure that the content that this playmedia is present is <Movie:90235: Aladdin>
Below is my code：
*********************************************************************
global plex
global client

def plexlogin():
    global plex
    global client

    baseurl= 'http://192.168.2.102:32400'
    token='xxxxxxxxxxxxxxx'
    from plexapi.server import PlexServer

    plex = PlexServer(baseurl,token)

    client = plex.client("Chrome")

    movielist =  plex.library.section('电影 - 单片')

    mvlist = movielist.search('阿拉丁')

    playmedia=mvlist[0]
    print(playmedia.title)
    client.playMedia(playmedia)

plexlogin()

*********************************************************************
Console：
client.playMedia(playmedia)
None

**Comment by Hellowlol** [comment]
So whats the question? All the player commands returns None

**Comment by BH1NBN** [comment]
I watched the video on youtube. After the author directly executes this command, I can play the video on the client. I think I may not be right. Second, I also tried to modify the slogan of the media.
The way I use it is:
Media.tagline = 'xxx'
But I found that this has not changed on the server side.
This may be my technical ability, but I hope to get some help.
Also, I am using
Plex = PlexServer (baseurl, token)
For items in plex.clients():
Print (item.title)
The result is only chrome, but in fact I have many customers, such as tv, pc, android, etc.

**Comment by BH1NBN** [comment]
> 那么问题是什么？所有播放器命令都返回None
After trying to restart the server, I solved the above problem. I want to modify it via Media.tagline = 'xxx' and it still doesn't work. I am not sure if I am missing some steps

**Comment by BH1NBN** [comment]
> So whats the question? All the player commands returns None

After trying to restart the server, I solved the above problem. I want to modify it via Media.tagline = 'xxx' and it still doesn't work. I am not sure if I am missing some steps
