### ISSUE TITLE
How to modify media information?

### ISSUE THREAD

**Issue by BH1NBN** [pkkid/python-plexapi#381]
I saw a lot of variables in （plexapi.video.movie）: I tried to modify the value of the title and save it.
But my current operation is to use （media.title = 'moviename'）, the data on the server has not changed. Did I miss some operations? How do I modify the parameter values ​​and save them on the server side after using the code?

**Comment by blacktwin** [comment]
Here is an example.
```python
movie = plex.fetchItem(97419)
print(movie.title)
movie.edit(**{"title.value":"New name for thing"})
movie.reload()
print(movie.title)
```

If you want to lock the changed title then you'll need to add `'label.locked': 1` to the kwargs.

**Comment by BH1NBN** [comment]
> Here is an example.
> 
> ```python
> movie = plex.fetchItem(97419)
> print(movie.title)
> movie.edit(**{"title.value":"New name for thing"})
> movie.reload()
> print(movie.title)
> ```
> 
> If you want to lock the changed title then you'll need to add `'label.locked': 1` to the kwargs.

Thank you for your answer! A very effective example of this!
