### ISSUE TITLE
AlertListener broken due to strange change from a year ago in websocket-client

### ISSUE THREAD

**Issue by avayert** [pkkid/python-plexapi#383]
[This commit](https://github.com/websocket-client/websocket-client/commit/efcf31b30122e05701fb3f696b029baf8faa6d8e) in websocket-client seems to have broken  `AlertListener` as the [`_onMessage`](https://github.com/pkkid/python-plexapi/blob/68fc970d7a3eca76333fcfcbb0e01a51b6572526/plexapi/alert.py#L58-L66) method no longer receives the `ws` argument for some strange reason. You can see by the comments that other people are also frustrated with the change but the maintainer seemingly wants to do nothing to revert it.

But as this method doesn't seem to use `ws` anyway it could probably be changed to fit the new API or the dep could be pinned.

**Comment by Hellowlol** [comment]
I though we had pinned the correct version that don’t have this bug. Anyway for another project of mine I changed to Lomond as this handles reconnection automatically.

**Comment by Hellowlol** [comment]
We have pinned websocket-client==0.48.0 in requirements_dev.txt as the author didnt want websocket-client to be a hard dep.
