### ISSUE TITLE
Fix Broken Logic in Travis Testing

### ISSUE THREAD

**Issue by pkkid** [pkkid/python-plexapi#389]
Travis often gets stuck waiting for library scans to finish. This causes the testing to to fail more often than not, creating unreliable results we simply can't really trust or will ignore over time.

I think the logic waiting for scans to finish is wrong. Currently, we simply wait for the a specific number of scanned items to be logged. However, often times I believe we may have a timing issue where we start watching the logs after an item or two has already been scanned, thus we never see ourselves hit 100%, and wait indefinitely. 

A better approach would be to not track the number of scanned items at all and simply look for a "finished scanning items" log message come through. Secondly, if we find ourselves waiting too long, we should probably break out of the loop and just assume it completed successfully. After all, it's simply test-setup where we are failing and not the test itself.

* The logic I am referring to is located at [tools/plex-bootstraptest.py#L51](https://github.com/pkkid/python-plexapi/blob/master/tools/plex-bootstraptest.py#L51)
* [An example errored testrun](https://travis-ci.org/pkkid/python-plexapi/jobs/595434265).

**Comment by pkkid** [comment]
Now the tests are broken because they are having trouble downloading the media from various sites. I tempted to get generic song, video, image and check them into the repo for more reliable test data.

**Comment by Hellowlol** [comment]
What the finish scanning event?

**Comment by pkkid** [comment]
When I created this issue I found an event in the notification stream that said it was finished scanning things. I don't recall the exact message, but can dig in again if you need it. However, listening for that event didn't fix the issue. Sometimes the scanner simply didn't pick up and process an item. Later down the line, this would cause tests to fail that expect that item to be processed. I never got to the bottom of it and ended up scrapping my work to fix things because my effort didn't get any closer to a solution.

**Comment by jjlawren** [comment]
I think we're in a better place with this now with loading local media & polling for current activity before starting tests that rely on metadata. Close?
