### ISSUE TITLE
Image tagging question

### ISSUE THREAD

**Issue by quantumtrope** [pkkid/python-plexapi#399]
Does anyone have experience with tagging photos in plex albums? Is this possible with the API? I took a look at the code under photo albums and photos, but TAGS seems to refer to something completely different. Am I missing a name for the metadata tags that describe the picture? From some reading, it seems like Plex saves them to its own database, and not to the image. As a starting point, I'm wondering if it is possible to extract from the image and save to plex using this python API. I'm comfortable with python from work, but this would be a personal project and I'm not familiar with the Plex API and where to start looking. 

Any pointers / advice would be helpful!

**Comment by blacktwin** [comment]
```python
photo.edit(**{'tag[0].tag.tag': "testing", 'tag.locked': 1}
```
`photo` is a photo object. Looks like plexapi is not pulling the tag information. So you couldn't filter or search for your tags with plexapi, yet. I'll be creating a PR to add this.

**Comment by quantumtrope** [comment]
Thanks for the quick PR. Do I understand correctly with the way the API is written that your updates will also allow for writing the tags to Plex?

**Comment by blacktwin** [comment]
No, my update just allows for searching for tags within a Photo library. Similar to how it can be done from Plex's webUI. Editing tags, you could do that before my update using the first example I provided.

**Comment by blacktwin** [comment]
It would also appear that there is an issue with searching Photo libraries. For instance this will not produce any results when I know I have pictures that were taken on that date.

```python
for photo in plex.library.section("Photos").search(libtype='photo', originallyAvailableAt='2012-12-24'):
    print(photo.title)
# same for all()
for photo in plex.library.section("Photos").all(libtype='photo', originallyAvailableAt='2012-12-24'):
    print(photo.title)

```

**Comment by quantumtrope** [comment]
Oh ok, I misunderstood. Thanks for the clarification. I'm not quite sure I understand why tag is listed three times. From https://github.com/pkkid/python-plexapi/blob/37917083628c11059bab48e05b2c4890bc7b18b2/plexapi/base.py#L325 seems like the first tag is slightly arbitrary, and the other two are just some function of Plex. Does it allow for passing arrays of tags or multiple tags? From the edit function it seems like I can also remove tags or lock them. Not sure what those do specifically for the server side . Do you have a link I could look at for the syntax? The Plex website doesn't pop up too much that's useful, but I don't want to waste your time explaining things to me.

**Comment by blacktwin** [comment]
```python
photo.edit(**{'tag[0].tag.tag': "testing", 'tag.locked': 1})
# or
photo._edit_tags('tag[0].tag.tag', "testing")
```
I believe those should result in the same. 

As far as finding the fields and their values to edit, the best place to look is in Plex's webUI in a browser. Open an item you want to edit, go to the editing menu, open your browser's Inspect > Network > Clear (to clear all the preexisting network calls), then make an edit in a field that you want and press save. Look at your browser's Network calls for a POST (usually). parse through the Request URL string for the field your edited. Usually it'll be `{fieldname}.value` or `{fieldname}.tag` or something like that followed by whatever value to added. Take that `{fieldname}.{suffix}` and add it to your script or project to be able to mass update that field.

**Comment by quantumtrope** [comment]
Got it, browser spelunking it is. I very much appreciate you taking the time to explain!

**Comment by blacktwin** [comment]
@quantumtrope safe to close this?

**Comment by quantumtrope** [comment]
Yep, I'm slowly working through browser spelunking but I think I have what I need!

________________________________
