### ISSUE TITLE
required websocket-client==0.48.0 is old

### ISSUE THREAD

**Issue by onkelbeh** [pkkid/python-plexapi#401]
Hi,

Could you please update websocket-client==0.48.0 in requirements.txt.
0.48.0 one is from May 2018. There are 8 newer version available.

Home Assistant requires websocket-client==0.54.0.

Thanks in advance.

**Comment by Hellowlol** [comment]
Its old as the websocket-client had issues where the bug got added removed then added. Imo we should drop the entire library and use another one. (or atleast remove it from requirements.txt as its only needed for a small part.)

**Comment by onkelbeh** [comment]
Thanks, can not tell if 0.54.0 is buggy or not, just have lots of installation problems with hard run dependencies, especially for often used libraries (when they get older). I use it in my [Home Assistant Overlay for Gentoo Linux](https://github.com/onkelbeh/HomeAssistantRepository), where i have to take care of _some_ other dependencies, too ;-)

**Comment by zSeriesGuy** [comment]
I saw in issue #353 that there was an issue with the AlertListener callback unless websocket-client is pinned at 0.47 or 0.53.
I have been testing using 0.56 (latest release), and the "not getting called" issue is back, starting with 0.54. It raises an exception, something about missing 1 required positional parameter, message.

If I remove the "ws" from AlertListener._onMessage method def, the alert callbacks work correctly with the latest release of websocket-client. Probably needs to be removed from _onError also.

I don't know if this is an acceptable solution. But wanted to let you know in case you want to get past the pinning of websocket-client.

**Comment by Hellowlol** [comment]
Seems fine by me.
