### ISSUE TITLE
problem with .roles and .actors for movie library not show library

### ISSUE THREAD

**Issue by pperquin** [pkkid/python-plexapi#409]
hi,

I make a little scrip that extract data from plex to make file on external DD to use with my dune player.

All is working well except when i try to extract .roles or .actors for a movie library (it seem to work well with a show library)

the most time it return to me only 3 item with that code (same for .actors)

print(movie.roles)
print(len(movie.roles))

this strange because in the debugger movie.roles as a len of 24/94/...

I use plexapi 3.3
any idea ?

regards,

**Comment by pkkid** [comment]
Search results only show 3 items for each movie even if there are more. Plex does this to keep the giant list of results smaller. To get all of them you can call `movie.reload()` which will load the full details of the movie that search results do not populate.

**Comment by pperquin** [comment]
Hi pkkid,

you save me.

regards,
