### ISSUE TITLE
Adding actors to videos based on video description?

### ISSUE THREAD

**Issue by jcandresen** [pkkid/python-plexapi#412]
Funhaus puts the participants twitter links in the description.

[Image of description](https://aws1.discourse-cdn.com/plex/original/3X/b/0/b030d472e648369ff2462dbbc643367b248c081a.jpeg) 

I’d like to be able to add a hardcoded “actor” CSV file and have Plex add an actor to each video file.

http://twitter.com/adamkovic,Adam Kovic,https://pbs.twimg.com/profile_images/585096122223341568/eG2BrbeW_400x400.jpg

I’m using @ZeroQI’s youtube metadata downloader for the library, not sure if that matters.

What would be the best way to go about adding “actors” to video files based on if info appears in the description?

**Comment by blacktwin** [comment]
To get the summary of an item `movie.summary`. Use the main readme [Examples ](https://github.com/pkkid/python-plexapi#usage-examples)to create a Plex Media Object. From there you could parse the contents of the summary then dump it into a file in whatever format you want. Or you could parse the contents and add the actor to the item inside Plex. Adding actors to videos inside Plex was recently discussed [here](https://github.com/pkkid/python-plexapi/issues/328) and has an example.
