### ISSUE TITLE
Dependent package 'mock' is missing

### ISSUE THREAD

**Issue by andy-maier** [pkkid/python-plexapi#413]
The plexapi package has a dependency on the mock package when running on Python 2.7, but does not specify that as a dependency in its requirements.txt.

Relevant code from `plexapi/compat.py`:
```
try:
    from unittest.mock import patch, MagicMock
except ImportError:
    from mock import patch, MagicMock
```

"unittest.mock" is available only from Python 3.3 onwards, so this code attempts to import "mock" on Python 2.7.

The solution would be to add "mock" to requirements.txt using an according python_version conditional.

**Comment by Hellowlol** [comment]
Thanks, 10 hours to eol on py 2. :D

**Comment by andy-maier** [comment]
yes, I am working on the PR

**Comment by andy-maier** [comment]
Addressed in PR #414.

**Comment by andy-maier** [comment]
Thanks for merging PR #414. I created PR #415 which tests whether plexapi can be installed in the fresh virtual python environment provided by Travis. This would have caught the missing mock package on Python 2.7, so it is a good test for catching any future dependencies.

**Comment by andy-maier** [comment]
PR was merged. Closing the issue.
