### ISSUE TITLE
Flake8 fails

### ISSUE THREAD

**Issue by andy-maier** [pkkid/python-plexapi#416]
For example this run: https://travis-ci.org/pkkid/python-plexapi/jobs/631286180?utm_medium=notification&utm_source=github_status

Unless you are already working on this, I would provide a PR fixing them.

**Comment by andy-maier** [comment]
Fixed in PR #417.

**Comment by Hellowlol** [comment]
I'm busy with other projects atm, so feel free to send any pr that improves the library.

**Comment by andy-maier** [comment]
PR was merged. Closing the issue.
