### ISSUE TITLE
Trouble changing the "sort title" field of a movie and possible bug in LibrarySection.edit()

### ISSUE THREAD

**Issue by andy-maier** [pkkid/python-plexapi#419]
I try to set the "sort title" field of a movie in a PMS using the PlexAPI package. The movie already has metadata assigned, and I am just trying to change it. I am trying to do this using the [plexapi.library.LibrarySection.edit()](https://python-plexapi.readthedocs.io/en/latest/modules/library.html#plexapi.library.LibrarySection.edit) method. I am using a direct connection to the PMS, i.e. not via the plex.tv web site, but I think this does not matter for this issue.

Meanwhile I have the code running, but I think I found an error in the `LibrarySection.edit()` method that I would like to report.

When invoking the `edit()` method with the following keyword args, an exception is raised indicating HTTP status 400 with "'agent' is missing or invalid". This is consistent with the docs of edit() which states: "Edit a library (Note: agent is required). See Library for example usage.". The keyword args passed to `edit()` were:
```
{
  "titleSort.value": "Der Zug",
  "titleSort.locked": 1,
  "type": 1,
  "id": 50446,
}
```

So I added an item 'agent' to the keyword args as follows:
```
{
  "titleSort.value": "Der Zug",
  "titleSort.locked": 1,
  "type": 1,
  "id": 50446,
  "agent": "com.plexapp.agents.none"
}
```
Now, the edit() call succeeds, but does not change the sort field. Its value is still the old value, both within my program and in the web GUI.

The plexapi.log file shows the following URL for this PUT request (parms broken into lines):
```
http://192.168.0.12:32400/library/sections/8?
  type=1&
  titleSort.locked=1&
  titleSort.value=Der+Zug&
  id=50446&
  agent=com.plexapp.agents.none
```

When modifying the sort title field through the web GUI, the web GUI sends the following request (X-* parameters removed, parms broken into lines):
```
http://192.168.0.12:32400/library/sections/8/all?
  type=1&
  id=50446&
  includeExternalMedia=1&
  titleSort.value=Zugx&
  titleSort.locked=1&
```

Note the different base URL, which ends with '/all'. When I modify the code of edit() to add '/all' to the URL it uses, I can successfully change the sort title field and the changed value sticks.

Am I doing something wrong or is this a bug that should be fixed?

Also, what does the `type=1` mean?

**Comment by blacktwin** [comment]
Are you trying to edit a library or a movie? The `LibrarySection.edit()` you're referring to, is for editing the library not an individual item inside the library. For editing the metadata of an item (video or music) you would create the item object, then use the [`_edit_tags()`](https://github.com/pkkid/python-plexapi/blob/master/plexapi/base.py#L348) method. 

```python
movie = plex.library.section("Movies").get("The Train")
movie._edit_tags('titleSort.value', "Der Zug")
```
`_edit_tags()` automatically locks whatever field is being edited. 

I believe the `type` is in reference to the search type that Plex uses. These can be found [here](https://github.com/pkkid/python-plexapi/blob/master/plexapi/utils.py#L19).

```python
SEARCHTYPES = {'movie': 1, 'show': 2, 'season': 3, 'episode': 4, 'trailer': 5, 'comic': 6, 'person': 7,
               'artist': 8, 'album': 9, 'track': 10, 'picture': 11, 'clip': 12, 'photo': 13, 'photoalbum': 14,
               'playlist': 15, 'playlistFolder': 16, 'collection': 18, 'userPlaylistItem': 1001}
```

**Comment by andy-maier** [comment]
Thanks for the quick response. I somehow missed the  the _edit_tags() and edit() methods on PlexPartialObject.

**Comment by andy-maier** [comment]
I tried the [PlexPartialObject.edit()](https://github.com/pkkid/python-plexapi/blob/master/plexapi/base.py#L327) on movie, show and episode items and it works just fine. Thanks again!!

I'm closing this issue.

**Comment by andy-maier** [comment]
@blacktwin Just for the record: I have released the program I was working on, to Pypi: https://pypi.org/project/plexmediafixup/
