### ISSUE TITLE
Question: How to get title stored within the metadata of a movie file

### ISSUE THREAD

**Issue by andy-maier** [pkkid/python-plexapi#420]
I would like to get the title stored within the metadata of a movie file (e.g. .mp4 file), in order to compare it with the title of the corresponding movie item in the PMS library, but could not figure out from the PlexAPI docs and from inspecting some of the objects returned by it how to do that.

So far, I can get to the `MediaPart` object representing the movie file, and its `file` attribute shows the path name of the media file, but I have trouble figuring out how to get to the title.

PMS is able to set the title of movie items in its library from the title in the metadata of the movie file, or otherwise from the file name of the movie file, even when the PMS agent does not find metadata for the file, so PMS does have this title available at least internally, and I am hoping it would be accessible through the Plex API and ultimately in the PlexAPI package.

**Comment by Hellowlol** [comment]
I havnt seen anything about this, but I assume this is handled by the scanner and not by pms. I would double check vs the xml output from the details page in the webui and use mediainfo or ffmpeg to see if everything is there

**Comment by andy-maier** [comment]
Good hints... Looking at the output of MediaInfo shows that the movie file does have a title set, but looking at the XML data for the PMS movie item reveals that that title is not part of it. So I guess what I want to do is not possible using the PMS API. However, I can get to the file itself via the `MediaPart.file` attribute and work it that way.

For my example file:
* File name (on server): `/volume2/share/Movies/library/Spielfilme/T/(T)Raumschiff Surprise - Periode 1 (2004) - HQ.mp4`
* MediaInfo says Movie Title = `(T)Raumschiff Surprise - Periode 1`, so it is set in the file.
* PMS XML info for the movie item:
```
<MediaContainer size="1" allowSync="1" identifier="com.plexapp.plugins.library"
  librarySectionID="8" librarySectionTitle="Spielfilme"
  librarySectionUUID="1de7c617-3397-4b2b-9ad8-dca59b5a90f8"
  mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1571305071">
<Video ratingKey="54910" key="/library/metadata/54910"
  guid="com.plexapp.agents.imdb://tt0349047?lang=de"
  studio="Constantin Film" type="movie" title="(T)Raumschiff Surprise - Periode 1"
  librarySectionTitle="Spielfilme" librarySectionID="8"
  librarySectionKey="/library/sections/8" contentRating="de/6"
  summary="Wir schreiben das Jahr 2054; ..."
  rating="5.4" year="2004" thumb="/library/metadata/54910/thumb/1578021103"
  art="/library/metadata/54910/art/1578021103" duration="4843566"
  originallyAvailableAt="2004-07-14" addedAt="1577997567" updatedAt="1578021103"
  ratingImage="imdb://image.rating">
<Media id="52531" duration="4843566" bitrate="1460" width="720" height="576"
  aspectRatio="1.78" audioChannels="2" audioCodec="aac" videoCodec="h264"
  videoResolution="576" container="mp4" videoFrameRate="PAL" optimizedForStreaming="1"
  audioProfile="lc" has64bitOffsets="0" videoProfile="high">
<Part accessible="1" exists="1" id="53124" key="/library/parts/53124/1577997576/file.mp4"
  duration="4843566"
  file="/volume2/share/Movies/library/Spielfilme/T/(T)Raumschiff Surprise - Periode 1 (2004) - HQ.mp4" size="887307129"
  audioProfile="lc" container="mp4" deepAnalysisVersion="4" has64bitOffsets="0" indexes="sd"
  optimizedForStreaming="1" requiredBandwidths="2783,1983,1508,1475,1475,1475,1475,1475"
  videoProfile="high">
<Stream id="57749" streamType="1" default="1" codec="h264" index="0" bitrate="1308"
  anamorphic="1" bitDepth="8" chromaLocation="left" chromaSubsampling="4:2:0"
  frameRate="25.000" hasScalingMatrix="0" height="576" level="30" pixelAspectRatio="64:45"
  profile="high" refFrames="3" requiredBandwidths="2631,1831,1356,1323,1323,1323,1323,1323"
  streamIdentifier="1" width="720" displayTitle="480p (H.264)"/>
<Stream id="57750" streamType="2" selected="1" default="1" codec="aac" index="1"
  channels="2" bitrate="152" audioChannelLayout="stereo" profile="lc"
  requiredBandwidths="152,152,152,152,152,152,152,152" samplingRate="44100"
  streamIdentifier="2" displayTitle="Unknown (AAC Stereo)"/>
</Part>
</Media>
<Genre id="11105" filter="genre=11105" tag="Comedy"/>
. . . (more media tags) ...
<Extras size="0">
</Extras>
</Video>
</MediaContainer>
```

**Comment by andy-maier** [comment]
The solution I ended up with was to get the path name of the media file through PlexAPI, have a path name mapping to translate it into a local file path for use by the system the script runs, and access the media file's metadata using the ffprobe command (part of ffmpeg). I use ffmpy as a python library for running ffprobe. See https://github.com/andy-maier/plexmediafixup/blob/master/plexmediafixup/fixups/sync_title.py#L131. Thanks again for the help!
