### ISSUE TITLE
Count all albums and photos recursively

### ISSUE THREAD

**Issue by AndreiGavriliu** [pkkid/python-plexapi#423]
Hi,

First of all, great job!

I seem to not be able to find a solution to my small “problem”. I am writing a prometheus exporter for Plex and would like to count the photo albums and photos, recursively. Until now, I only managed to do this with loops. Is there by any chance a simpler solution? 

Thanks,
Andrei

**Comment by blacktwin** [comment]
I think it depends on how you have your Photo Library setup. 
```python
print(len(plex.library.section("Photos").search(libtype="photoalbum")))
```
This will only get you the top level albums (folders) but if you have albums (folders) nested then it won't grab those. I think your looping maybe the best solution. Care to share what you're running?
