### ISSUE TITLE
3.3.0 is not tagged on GitHub

### ISSUE THREAD

**Issue by colemickens** [pkkid/python-plexapi#424]
Hello.

While 3.3.0 is tagged on Pypi, it's not tagged here. I need to package from here since pypi doesn't redistribute test sources.

Can you tag 3.3.0 in git? Thanks!

**Comment by jjlawren** [comment]
Looks like commit https://github.com/pkkid/python-plexapi/commit/f473b95396d57e7980dedc046143976240f8ba9a is what you can target.
