### ISSUE TITLE
Unable to retrieve playlists

### ISSUE THREAD

**Issue by uswemar** [pkkid/python-plexapi#425]
Hi,

I've come across an odd issue in a python script of mine where I'm unable to retrieve the list/array of playlists on my Plex server. The script has worked fine in the past and I've made no changes to it since then. The only changes I've made is to upgrade the Plex server/docker image when there's been a new release. I've tried for days to figure out what could've caused it but I'm stuck, hoping anyone here can help.

The issue I'm having is that when I try to pull the list of playlists it returns an empty array, no exception is thrown. I have 1 Movies playlist and 2 Music playlists. I've tried to create a new playlist in Plex to see if it's due to format issues (old playlists, new Plex upgrades incompatibility) but even the new one is not visible/does not show up. I can connect fine and use the API for other requests e.g. searching so I know the actual connection is fine and that the API works in my script. It's just the `plists = plex.playlists()` (row 229) that doesn't seem to work any longer/returns an empty array.

Any advice would be much appreciated.

The script I'm using is:
https://github.com/uswemar/PlexPlaylistSorter

The Plex docker I'm using is:
https://hub.docker.com/r/linuxserver/plex

**Comment by blacktwin** [comment]
`plex.playlists()` returns playlist just fine for me. Have you updated plexapi recently? What version are you on? Did you create the playlist in the Admin's account or another user's account?

**Comment by uswemar** [comment]
> `plex.playlists()` returns playlist just fine for me. Have you updated plexapi recently? What version are you on? Did you create the playlist in the Admin's account or another user's account?

I was running an older version of PlexAPI but I upgraded it now (3.3.0) and it still doesn't work. The playlists were created on the admin account, and have been retrievable in the past.

**Comment by blacktwin** [comment]
Have you tested outside of the script?

**Comment by uswemar** [comment]
> Have you tested outside of the script?

Yes, I've tried writing a new, smaller, python script which just establishes a connection and runs the `plex.playlists()` command and prints the output - it still returns an empty array.

I took a look at the `Plex Media Server.log` for clues and from what I can see it accepts the command, finds 3 playlists, but no errors/explanation as to why they are then not returned.

> DEBUG - HTTP 200 response from GET https://plex.tv/media/providers?X-Plex-Token=xxxxxxxxxxxxxxxxxxxx
> VERBOSE - Comparing request from 192.168.1.11 against 192.168.1.0/255.255.255.0
> VERBOSE - Auth: We found auth token (xxxxxxxxxxxxxxxxxxxx), enabling token-based authentication.
> VERBOSE - Auth: tokens were refreshed recently enough
> DEBUG - Auth: authenticating user as guest
> DEBUG - Request: [192.168.1.11:41644 (Allowed Network (Subnet))] GET /playlists (3 live) TLS GZIP Signed-in Token ()
> VERBOSE -  * Host => 192.168.1.11:32400
> VERBOSE -  * User-Agent => python-requests/2.22.0
> VERBOSE -  * Accept-Encoding => gzip, deflate
> VERBOSE -  * Accept => */*
> VERBOSE -  * Connection => keep-alive
> VERBOSE -  * X-Plex-Platform => Linux
> VERBOSE -  * X-Plex-Platform-Version => 4.9.0-9-amd64
> VERBOSE -  * X-Plex-Provides => controller
> VERBOSE -  * X-Plex-Product => PlexAPI
> VERBOSE -  * X-Plex-Version => 3.3.0
> VERBOSE -  * X-Plex-Device => Linux
> VERBOSE -  * X-Plex-Device-Name => SERVER
> VERBOSE -  * X-Plex-Client-Identifier => *************
> VERBOSE -  * X-Plex-Sync-Version => 2
> VERBOSE -  * X-Plex-Token => xxxxxxxxxxxxxxxxxxxx
> VERBOSE - It took 0.0 sec to serialize a list with 0 elements.
> DEBUG - Completed: [192.168.1.11:41644] 200 GET /playlists (3 live) TLS GZIP 3ms 397 bytes (pipelined: 3)

**Comment by blacktwin** [comment]
> Auth: authenticating user as guest

Looks like your TOKEN is for the guest account?

> VERBOSE - It took 0.0 sec to serialize a list with 0 elements.

It's not finding any playlists.

Here is me logs:
```
Jan 28, 2020 10:57:56.866 [18536] DEBUG - Completed: [127.0.0.1:61310] 200 GET / (25 live) TLS GZIP 4ms 3512 bytes (pipelined: 1)
Jan 28, 2020 10:57:56.871 [18536] VERBOSE - Auth: We found auth token (xxxxxxxxxxxxxxxxxxxx), enabling token-based authentication.
Jan 28, 2020 10:57:56.872 [18536] DEBUG - Auth: authenticated user 1 as Blacktwin
Jan 28, 2020 10:57:56.872 [18536] VERBOSE - Auth: Came in with a super-token, authorization succeeded.
Jan 28, 2020 10:57:56.872 [17280] DEBUG - Request: [127.0.0.1:61310 (Loopback)] GET /playlists (25 live) TLS GZIP Signed-in Token (Blacktwin)
Jan 28, 2020 10:57:56.872 [17280] VERBOSE -  * Host => 127.0.0.1:32400
Jan 28, 2020 10:57:56.872 [17280] VERBOSE -  * Connection => keep-alive
Jan 28, 2020 10:57:56.872 [17280] VERBOSE -  * Accept-Encoding => gzip, deflate
Jan 28, 2020 10:57:56.872 [17280] VERBOSE -  * Accept => */*
Jan 28, 2020 10:57:56.872 [17280] VERBOSE -  * User-Agent => python-requests/2.22.0
Jan 28, 2020 10:57:56.872 [17280] VERBOSE -  * X-Plex-Platform => Windows
Jan 28, 2020 10:57:56.872 [17280] VERBOSE -  * X-Plex-Token => xxxxxxxxxxxxxxxxxxxx
Jan 28, 2020 10:57:56.872 [17280] VERBOSE -  * X-Plex-Platform-Version => 10
Jan 28, 2020 10:57:56.872 [17280] VERBOSE -  * X-Plex-Sync-Version => 2
Jan 28, 2020 10:57:56.872 [17280] VERBOSE -  * X-Plex-Device-Name => REDACT-REDACT
Jan 28, 2020 10:57:56.872 [17280] VERBOSE -  * X-Plex-Device => Windows
Jan 28, 2020 10:57:56.872 [17280] VERBOSE -  * X-Plex-Product => PlexAPI
Jan 28, 2020 10:57:56.872 [17280] VERBOSE -  * X-Plex-Client-Identifier => REDACT
Jan 28, 2020 10:57:56.872 [17280] VERBOSE -  * X-Plex-Provides => controller
Jan 28, 2020 10:57:56.872 [17280] VERBOSE -  * X-Plex-Version => 3.3.0
Jan 28, 2020 10:57:56.874 [17280] VERBOSE - It took 0.0 sec to serialize a list with 1 elements.
Jan 28, 2020 10:57:56.875 [10680] DEBUG - Completed: [127.0.0.1:61310] 200 GET /playlists (25 live) TLS GZIP 3ms 619 bytes (pipelined: 2)
```

**Comment by uswemar** [comment]
> > Auth: authenticating user as guest
> 
> Looks like your TOKEN is for the guest account?
> 
> > VERBOSE - It took 0.0 sec to serialize a list with 0 elements.
> 
> It's not finding any playlists.
> 

Ahh, there it is! The (admin) token, it has changed. That one worked fine back when I used the script last and I assumed it was still the admin token but double-checked and my admin token was now different. Updated my config with the new token and now it finds the playlists again. Thanks a mil!
