### ISSUE TITLE
Add a new Collection to a Movie

### ISSUE THREAD

**Issue by Noah-Rod** [pkkid/python-plexapi#427]
Hallo together

I tried to add a Collection to a Movie but it didn't worked. Is this actual possible or am I wrong?
Could someone help me please?

Best Regards Noah

**Comment by blacktwin** [comment]
@Noah-Rod can you share what you using to accomplish this? Share your code.

**Comment by Noah-Rod** [comment]
Yes of course here:
`    server = PlexServer(spez.PlexUrl, spez.PlexToken)
    library = server.library.section(spez.PlexMovieLibrary)
    movies = library.search()
    for movie in movies:
        print(movie.title)
        med = plexapi.media.MediaTag(server, None)
        med.tag = "Collection"
        med.FILTER = "collection"
        coll = plexapi.media.Collection(server, None)
        coll.tag = "1test"
        movie.collections.append(coll)`

**Comment by blacktwin** [comment]
Create your movie or video object then use the `_edit_tags()` method to update the Collection tag.
```python
test = plex.search("That One Movie")[0]
print(test.title)
test._edit_tags('collection',['Name of the Collection'])
test.reload() # only needed if you want to confirm in the next print
print(test.collections)
# to remove
# test._edit_tags('collection',['Name of the Collection'], remove=True)

```

**Comment by Noah-Rod** [comment]
Hey thank you a lot you saved my project. Have a nice day

**Comment by Hellowlol** [comment]
Why not use addCollection([name]) directly?

**Comment by blacktwin** [comment]
> Why not use addCollection([name]) directly?

🤕 I knew there was an add/remove... I just didn't find it... You're correct.

```python
test = plex.search("That One Movie")[0]
print(test.title)
test.addCollection('Name of the Collection')
test.reload() # only needed if you want to confirm in the next print
print(test.collections)
```

**Comment by Noah-Rod** [comment]
Just another Question how can I delete a Collection from the Library?

**Comment by blacktwin** [comment]
@Noah-Rod Try [this](https://gist.github.com/blacktwin/30e2826a49c33814e1cc61c34ff07465). Set the size of the collection to whatever you want. `collection.childCount < 2`

**Comment by Noah-Rod** [comment]
Thanks worked fine
