### ISSUE TITLE
Fewer hard dependencies

### ISSUE THREAD

**Issue by coleifer** [pkkid/python-plexapi#428]
First off, thank you very much for this *excellent* library.

I use plexapi for a number of scripts that I run as full-fledged applications on my system. This means that I need to install plexapi's dependencies where my system python can find them. There are two dependencies which I think could be made optional: `tqdm` and the `websocket` client.

`tqdm` is only needed if you use the download feature *and* show status. I've patched this locally as a proof of how easy it is to drop tqdm as a hard dependency.

The `websocket` client is only needed if you intend to subscribe to alerts. It would be nice if the absence of this library could be handled gracefully, as I have no interest in the alerts features and don't want to install this dep.

Here's a simple patch I'm using locally:

```diff
diff --git a/plexapi/alert.py b/plexapi/alert.py
index 38dc930..be78e7c 100644
--- a/plexapi/alert.py
+++ b/plexapi/alert.py
@@ -1,7 +1,10 @@
 # -*- coding: utf-8 -*-
 import json
 import threading
-import websocket
+try:
+    import websocket
+except ImportError:
+    websocket = None
 from plexapi import log
 
 
diff --git a/plexapi/utils.py b/plexapi/utils.py
index e8ff989..5b0a1a7 100644
--- a/plexapi/utils.py
+++ b/plexapi/utils.py
@@ -8,7 +8,10 @@ import zipfile
 from datetime import datetime
 from getpass import getpass
 from threading import Thread, Event
-from tqdm import tqdm
+try:
+    from tqdm import tqdm
+except ImportError:
+    tqdm = None
 from plexapi import compat
 from plexapi.exceptions import NotFound
 
@@ -287,6 +290,9 @@ def download(url, token, filename=None, savepath=None, session=None, chunksize=4
 
     # save the file to disk
     log.info('Downloading: %s', fullpath)
+    if tqdm is None:
+        showstatus = False
+
     if showstatus:  # pragma: no cover
         total = int(response.headers.get('content-length', 0))
         bar = tqdm(unit='B', unit_scale=True, total=total, desc=filename)
```

**Comment by pkkid** [comment]
I think the only thing I would add to these patches is a log and print message is `websocket is None` when trying to subscribe to alerts.

**Comment by coleifer** [comment]
If there's interest in such a patch, I'll be happy to submit a cleaned-up version. I just wanted to float the idea first.

**Comment by Montellese** [comment]
Similar to the above it would be great if we could move https://github.com/pkkid/python-plexapi/blob/master/plexapi/compat.py#L47-L50 out of the `plexapi` library and into the `tests/` part because it is only used for testing and not needed when just using the library itself.

**Comment by Hellowlol** [comment]
@coleifer thanks

**Comment by Hellowlol** [comment]
https://github.com/pkkid/python-plexapi/pull/468
