### ISSUE TITLE
WARNING:plexapi:Filter value not listed, using raw item value. 

### ISSUE THREAD

**Issue by kokozaurz** [pkkid/python-plexapi#430]
Hi, 

I'm trying to search by guid (imdb/tmdb id) and even though it returns the object it also gives out warning. 

```
list = ['tt1369706']
print(plex.library.section('Movies').search(guid=list))
```
it results to 

> WARNING:plexapi:Filter value not listed, using raw item value: tt1369706
[<Movie:38876:The-Ward>]

It finds the correct object, why warning? Is there a way to get the object back without the warning assuming I'm searching lists with 100+ objects (spams the console).

Thanks!

**Comment by blacktwin** [comment]
Check your PlexAPI version. I'm trying your snippet (tvdb instead) and it's working without issue or warning.

**Comment by blacktwin** [comment]
Sorry, I just checked my plexapi.log and now I see the warning.

**Comment by kokozaurz** [comment]
Yeah, right now to avoid this is to set an environment variable. However, for a tool that I intend to distribute, that's a lot to ask for. Looking for ways to suppress the warnings.

**Comment by Hellowlol** [comment]
Check if you can catch it with the warning module. I’m not familiar with this part of the code, why are we warning anyway? Are you search 100 of movies in the same query? Fx list=[“id1”, “id2”]

**Comment by kokozaurz** [comment]
> Check if you can catch it with the warning module. I’m not familiar with this part of the code, why are we warning anyway? Are you search 100 of movies in the same query? Fx list=[“id1”, “id2”]

yeah, searching multiple movies with same query but the error persists even if i just search for one.

**Comment by Hellowlol** [comment]
https://github.com/pkkid/python-plexapi/pull/465
