### ISSUE TITLE
video files in photo library ignored?

### ISSUE THREAD

**Issue by yangqi** [pkkid/python-plexapi#434]
Tried to use the api to get a list from photo library, but it does not return any video files. The video files do show in Plex client without any problem. Is this a bug somewhere?

**Comment by blacktwin** [comment]
> Tried to use the api to get a list from photo library, but it does not return any video files.

Photo library wouldn't have any video files. Can you please share the code you're using?

**Comment by yangqi** [comment]
Why not? The photo library is used in camera upload, all the photos and videos from the phone are uploaded to the library and display on plex web client fine.

The code just like below, and the results are missing video items.
```
photos = plex.library.sectionByID('26')

for photo in photos.all():
    print(type(photo))
```

**Comment by yangqi** [comment]
After some digging, I think I found the issue. The videos in the photo library has type="clip" and it seems like this type is not recognized by _buildItem() in base.py. Not sure how to fix this though.

```
<Video ratingKey="54858" key="/library/metadata/54858" guid="com.plexapp.agents.none://54858?lang=en" type="clip" title="2019-09-30 08.23.09" summary="" index="1" year="2019" thumb="/library/metadata/54858/thumb/1582645381" duration="9416" originallyAvailableAt="2019-09-30" addedAt="1569846189" updatedAt="1582645381" createdAtAccuracy="epoch,local" createdAtTZOffset="-14400">
<Media id="58298" duration="9416" bitrate="13728" width="1920" height="1080" aspectRatio="1.78" audioChannels="2" audioCodec="aac" videoCodec="h264" videoResolution="1080" container="mov" videoFrameRate="24p" optimizedForStreaming="0" audioProfile="lc" has64bitOffsets="0" videoProfile="high">
<Part id="63905" key="/library/parts/63905/1569846189/file.MOV" duration="9416" file="M:\Test\2019-09-30 08.23.09.MOV" size="16189122" audioProfile="lc" container="mov" has64bitOffsets="0" optimizedForStreaming="0" videoProfile="high"/>
</Media>
</Video>
```

**Comment by blacktwin** [comment]
There are currently two PRs where a `Clip` class has been created. #410 [here](https://github.com/pkkid/python-plexapi/pull/410/commits/fc28d7210f1afce93c309bb940472ec3a926f519) and #421  [here](https://github.com/pkkid/python-plexapi/pull/421/commits/3d5cb6c49b6d6dd4fbe3715e9786f92c4998e052). We can try either or, or wait for one to be approved and merged.

**Comment by Hellowlol** [comment]
Clip has been added so this should show up now. Reopen if needed
