### ISSUE TITLE
playMedia() on Nvidia Shield causes subscription failures

### ISSUE THREAD

**Issue by jjlawren** [pkkid/python-plexapi#435]
When sending a `Client().playMedia()` command, it seems that [this command](https://github.com/pkkid/python-plexapi/blob/c3e16b2d369968433048ae9a5678294041eb084d/plexapi/client.py#L479) (which only specifies the _server’s_ port) will cause the Plex app on Nvidia Shield devices to treat the `plexapi` request source as an actively listening controller. The Shield client will send POST requests back to the `plexapi` host on the server’s port which repeatedly fail.

Example logs from Shield:
```
02-26 21:58:39.517  i: [pms] /10.6.9.55:57992 - GET /player/timeline/subscribe
02-26 21:58:39.517  i: [Now Playing] New subscriber 0xcfe9033bf0a4 at 10.6.9.55:32400 with command id 23
02-26 21:58:39.519  i: Fetching [method:POST] http://10.6.9.55:32400/:/timeline?X-Plex-Token=...HBKU&includeExternalMedia=1
02-26 21:58:39.525  i: Time out fetching http://10.6.9.55:32400/:/timeline?X-Plex-Token=...HBKU.
02-26 21:58:39.667  i: [pms] /10.6.9.55:57996 - GET /player/playback/playMedia
02-26 21:58:43.325  i: Fetching [method:POST] http://10.6.9.55:32400/:/timeline?X-Plex-Token=...HBKU&includeExternalMedia=1
02-26 21:58:43.333  i: Time out fetching http://10.6.9.55:32400/:/timeline?X-Plex-Token=...HBKU.
02-26 21:58:44.383  i: Fetching [method:POST] http://10.6.9.55:32400/:/timeline?X-Plex-Token=...HBKU&includeExternalMedia=1
02-26 21:58:44.395  i: Time out fetching http://10.6.9.55:32400/:/timeline?X-Plex-Token=...HBKU.
02-26 21:58:45.382  i: Fetching [method:POST] http://10.6.9.55:32400/:/timeline?X-Plex-Token=...HBKU&includeExternalMedia=1
02-26 21:58:45.386  i: Time out fetching http://10.6.9.55:32400/:/timeline?X-Plex-Token=...HBKU.
02-26 21:58:46.384  i: Fetching [method:POST] http://10.6.9.55:32400/:/timeline?X-Plex-Token=...HBKU&includeExternalMedia=1
```

**Comment by jjlawren** [comment]
I don't see how the library can use the `/player/timeline/subscribe` command at all since it doesn't open a listening port for callbacks from the player.

From the Plex [remote control API doc](https://github.com/plexinc/plex-media-player/wiki/Remote-control-API#new-remote-control-commands), it seems we should always use the `/player/timeline/poll` command:

> This is an alternative to the subscribe command for controllers that cannot use persistent connections to receive updates from the player.

**Comment by Hellowlol** [comment]
I cant remember why this was needed. It was only a issue on pht. Just try to Replace it and see what happens

**Comment by jjlawren** [comment]
If I start a listening host before sending the `timeline/subscribe` command, the player delivers status updates for the next ~30s. I think using this subscribe command is incorrect for any player without providing a callback listener.

**Comment by jjlawren** [comment]
Skipping the `/player/timeline/subscribe` call avoids errors in the Shield client, but for some reason the playback status is not shown in the server's `/status/sessions` activity when playback is initiated from a `/player/playback/playMedia` call. I'm guessing a quirk of the client, but perhaps someone knows a workaround?

**Comment by blacktwin** [comment]
Probably something up with the client. Here another [example ](https://www.reddit.com/r/PleX/comments/fgdu3c/fyi_for_people_with_shields_that_now_crash_while/fk4vtan/)of the Shield acting funny.

**Comment by jjlawren** [comment]
Yes, I'm sure it's something with the client itself. That being said, I think the current behavior of `plexapi` is incorrect when following the remote control specifications. We request a callback from the client which we have no intention of properly handling.

**Comment by Hellowlol** [comment]
Let’s fix it then. We just need to test that the commands still work.

**Comment by jjlawren** [comment]
Starting remote media playback still works if I remove this block around the `timeline/subscribe` call: https://github.com/pkkid/python-plexapi/blob/c3e16b2d369968433048ae9a5678294041eb084d/plexapi/client.py#L477-L484

However, I haven't opened a PR yet since the Shield client still doesn't report its playback status to the Plex server and I'm unclear if it's related. Since the timeline functionality is what triggers playback status reports I feel like I'm still missing something.

**Comment by Hellowlol** [comment]
Try replacing it with self.sendCommand('timeline/poll', wait=0)

**Comment by jjlawren** [comment]
Maybe the timeline subscription should be removed there completely, and we add `Plex for Android (TV)` to the product list here: https://github.com/pkkid/python-plexapi/blob/c3e16b2d369968433048ae9a5678294041eb084d/plexapi/client.py#L193-L198

**Comment by Hellowlol** [comment]
That part intended for others things, in short all commands on some client fail unless we send a timeline request ever 80 sec (or was it 90) i cant remember. (not just playback)

**Comment by jjlawren** [comment]
In testing various fixes I noticed that in addition to no server sessions being reported, `timeline()` calls to Shield clients weren't returning correct data. I've opened a thread on the Plex forums here: https://forums.plex.tv/t/no-session-status-when-starting-playback-on-shield-over-remote-control-api/555067.

**Comment by blacktwin** [comment]
Just a thought, what are the `client.protocolCapabilities` for the Shield you're using?

**Comment by jjlawren** [comment]
```
['timeline', 'playback', 'navigation', 'mirror', 'playqueues', 'provider-playback']
```
It reports back a valid response, but always shows it as "stopped" when playback is started via the `/player/playback/playMedia` endpoint.

**Comment by blacktwin** [comment]
Have you uninstalled/installed Plex from the player? Unauthorized the device then authorized? Just want to rule out the player. 

For comparison, Chrome Web :  `['timeline', 'playback', 'navigation', 'mirror', 'playqueues']`

**Comment by jjlawren** [comment]
No, but I can as a sanity check. I started investigating the issue as another Home Assistant user reported the same problem with their Shield player's behavior.

**Comment by jjlawren** [comment]
Old versions of the Shield Plex client seem to behave fine. I updated the Plex forums issue linked above with more info.

Is there a possibility there's an issue with the `playMedia()` call? A new required parameter that we're not sending properly?

**Comment by blacktwin** [comment]
The `/status/sessions` endpoint shows LiveTV sessions, so the plexapi call reveals the same. Could be a HA issue.

**Comment by jjlawren** [comment]
I've been testing with each incremental Plex client version released for the Shield. No improvement in behavior yet.

**Comment by jjlawren** [comment]
Most of the discussion here about the Shield client appears to be a client problem ([Plex forum link in this comment](https://github.com/pkkid/python-plexapi/issues/435#issuecomment-599251348)). However, I believe the `timeline/subscribe` call is never appropriate unless we can also handle the callbacks sent by the client. Opened #489 to remove this call.

**Comment by jjlawren** [comment]
This was somewhat related to this recent fix: https://github.com/pkkid/python-plexapi/pull/826.
