### ISSUE TITLE
Getting collection items

### ISSUE THREAD

**Issue by nxfifteen** [pkkid/python-plexapi#438]
Is there a way to search for everything in a collection? I've got a star trek collection which is a mix of movies and TV shows, but I can't work out how to list everything in the collection.

I am able to get the collection object from the TV or movie sections. But the object doesn't appear to have a way of listing everything within it - like all() or items()

Is there a way of doing this?

**Comment by blacktwin** [comment]
Yes. Here is my quick and dirty to get it. Someone might have a better way.

```python
item = plex.fetchItem(80584)
collectionID = item.collections[0].filter
print(collectionID)
# collection=118687
collectionSplit = collectionID.split('=')
print(collectionSplit)
# ['collection', '118687']
collectionDict = {collectionSplit[0]: collectionSplit[1]}
print(collectionDict)
# {'collection': '118687'}
print(plex.library.search(**collectionDict))
[<Show:75853:Some-Show>, <Movie:80584:Some-Movie>, <Movie:107063:The-Movie>]
```

**Comment by pkkid** [comment]
Code golf. :D
```python
item = plex.fetchItem(80584)
plex.library.search(**dict([item.collections[0].filter.split('=')])
```

**Comment by konsumer** [comment]
If you want to look up collection by name, this works, too:

```py
movies = plex.library.section('Movies')
for video in movies.search(collection='Cyberpunk'):
    print(video.title)
```
