### ISSUE TITLE
Library settings is to limiting

### ISSUE THREAD

**Issue by Hellowlol** [pkkid/python-plexapi#450]
Atm is possible to get the settings of a library using 

pms.library.get("Movies")
this returns a list of settings, but you can really use the to anything, as there is no way to save the settings, this belongs to the Settings class.

**Comment by blacktwin** [comment]
I added some library setting stuff here 1d05304  with an example [here](https://github.com/pkkid/python-plexapi/pull/436#issuecomment-599684985). 

```python
enableBIF = plex.library.section("Movies").settings()[2].id
test = {'prefs[%s]' % enableBIF: 1}
plex.library.section("Movies").edit(**test)
```

Could use some more improvements to be sure.

**Comment by blacktwin** [comment]
More library related items added with #518 Hubs and Stations for music sections

**Comment by blacktwin** [comment]
@Hellowlol anything else you think needs added from Library settings? If not, lets close this.

**Comment by Hellowlol** [comment]
I think its good.
