### ISSUE TITLE
Retrieve random movie from 'Movies' section

### ISSUE THREAD

**Issue by jensenkd** [pkkid/python-plexapi#455]
I'm curious if there is a way, other than pulling down the entire list, of pulling a random item from the a section:

ex: plex.library.section('Movies')

Ideally I'd like to randomly grab 'n' # of items.

Is there a more performant way that i'm missing?

**Comment by Hellowlol** [comment]
What are you doing now?


random.choice(all_movies, k=n)

**Comment by jensenkd** [comment]
Exactly..takes forever on larger libraries

**Comment by Hellowlol** [comment]
How long time are we taking about?

**Comment by jensenkd** [comment]
33 seconds to retrieve entire movie list

start = time.time()
movies = plex.library.section('Movies').all() 
end = time.time()
print (end-start)

**Comment by pkkid** [comment]
If this is a call you are running often, I would suggest caching the result to list all movies for some reasonable interval and choose a random item off the cached list.

**Comment by jensenkd** [comment]
that was certainly my fallback and doable.  I was just trying to see if the sdk supported a different way.

**Comment by jensenkd** [comment]
~2000 items.. k = 5, although i'm not even running the random function yet...

Pulling back the same library in a .net plex api I wrote returns all 2000 items < 1 sec.

Caching happens to work in this situation, I was just wondering if there was something wrong with my call because 33 seconds seemed extremely long.

Thanks for the great library btw!

**Comment by Hellowlol** [comment]
I’ll try to do the same later. The problem with all is that is builds all items.

**Comment by jensenkd** [comment]
are the object graphs being populated from Plex via XML or json?

**Comment by Hellowlol** [comment]
Xml. I would just create a other query that do this for you. Query the server the get all rating key, do random choice then use _buildItem if the item is in the random list

**Comment by jensenkd** [comment]
That sounds like it would work!

**Comment by Hellowlol** [comment]
What about this one

```
# section is the section class
def random_n(section, n=50):
    pms = section._server
    result = []
    data = pms.query("/library/sections/%s/all" % section.key)
    randomz = random.choices([i.attrib.get("ratingKey") for i in data], k=n)
    for i in data:
        if i.attrib.get("ratingKey") in randomz:
            m = pms._buildItemOrNone(i)
            if m:
                result.append(m)

    return result
```

**Comment by jensenkd** [comment]
Awesome! < 2 seconds.  Thanks @Hellowlol
