### ISSUE TITLE
Paged requests

### ISSUE THREAD

**Issue by Montellese** [pkkid/python-plexapi#461]
While testing my code which e.g. loads all movies from a specific library I noticed that there's no way to "page" the requests i.e. retrieve the first 50 movies and then the next 50 and so on. Looking at the Plex interface this certainly is possible in the `library/sections/<section ID>/all` endpoint by using the `X-Plex-Container-Start` and `X-Plex-Container-Size` query parameters and reading the `size`, `offset` and `totalSize` properties of the `MediaContainer` response object.

Looking at the code this is already being used in `LibrarySection.search()` and `PlexServer.history()` but there's no way for developers to control it or even decide to only retrieve part of the result set. `LibrarySection.search()` supports a `maxresults` argument but it doesn't support a start offset. Furthermore there's no way to know / retrieve the total number of items available.

I've started implementing this but then realized that it's going deeper and deeper into library. The main issue is how to return the total number of items available back to the caller without breaking / changing the whole API. See e.g. https://github.com/Montellese/mediaimporter.plex/commit/046d2b44eb1f4f46c58a4b4e1dd33a06ee2b48e9#diff-1cd65a95cf8b988a1f041ec7ac8bce05R159 or https://github.com/Montellese/mediaimporter.plex/commit/794b3447d25e0a461ba0dbe24de13675c1d17841 for offset and result control.

So before I go any further I'd like to get some feedback on
* the general problem / idea
* if such a feature would be considered at all
* how to potentially integrate this into the existing API

**Comment by Hellowlol** [comment]
I really dont want to change change this. Its isn't worth the effort in rewriting the entire thing. However I can see that this might have some usage so me suggest something like this.



We modify
```
    def fetchItems(self, ekey, cls=None, **kwargs):
        """ Load the specified key to find and build all items with the specified tag
            and attrs. See :func:`~plexapi.base.PlexObject.fetchItem` for more details
            on how this is used.
        """
        batch = {}
        for key, value in dict(kwargs).items():
          if key and key.startswith("X-Plex-Container"):
              batch[key] = kwargs.pop(key)

        if ekey is None:
            raise BadRequest('ekey was not provided')
        data = self._server.query(ekey, **batch)
        items = self.findItems(data, cls, ekey, **kwargs)
        librarySectionID = data.attrib.get('librarySectionID')
        if librarySectionID:
            for item in items:
                item.librarySectionID = librarySectionID
        return items
```

This is untested..

But the point is that fetchItems is used by pretty much all http requests that might take a while. 
This make its possible to use 
```
LibrarySecion.all(**{"X-Plex-Container-Start":0, "X-Plex-Container-Size":100})
```

**Comment by Montellese** [comment]
> I really dont want to change this. Its isn't worth the effort in rewriting the entire thing. However I can see that this might have some usage so me suggest something like this.

That's why I'm asking :-) I have a user report where the library contains thousands of items so retrieving them all at once takes forever for the HTTP download and the code has no idea how long it is going to take so there's no way to show a reasonable progress bar. Furthermore due to the download being so big sometimes his PMS fails. Last but not least when `python-plexapi` was able to actually retrieve all the thousands of items it takes a while to process them and then some reload mechanism (which I don't quite understand) yet kicks in causes even more load on the server.

Being able to only retrieve some items at a time solves all of these problems:
* I can check how many items there are in total and show a progress bar
* Each HTTP request is much smaller and therefore doesn't put that much load on the server
* I can process all retrieved items without the reload mechanism kicking in

> As for the size can be added in the library sections method

OK so we add a separate method like https://github.com/Montellese/mediaimporter.plex/commit/0d774a80d7a3a2a2549fedae5b80a27e116a6914 to `LibrarySection` to only retrieve the total number of items.

To be able to share the same code in `fetchItems()` and `count()` (or whatever it will be named) we might have to refactor the existing `fetchItems()` into an internal method providing both items and total number of items but we keep the public interface of `fetchItems()` which just uses the internal method to only provide the items. Does that sound reasonable?

**Comment by Hellowlol** [comment]
Yeah, if we cant find the info some other way. I thought the size of the library was included somewhere. Ill check that, but my plan was to modify https://github.com/pkkid/python-plexapi/blob/master/plexapi/library.py#L32-L45

**Comment by Montellese** [comment]
Do you happen to know why `LibrarySection.search()` already uses batched retrieval while all the other API methods like `all()` don't?

**Comment by Hellowlol** [comment]
I’m not sure but by guess would be because expect search for be quick.

**Comment by Hellowlol** [comment]
The movie.all command takes less then 3 sec on 1372 movies for me. Batching them take like half seconds longer.

https://github.com/pkkid/python-plexapi/pull/464

**Comment by Montellese** [comment]
> The movie.all command takes less then 3 sec on 1372 movies for me. Batching them take like half seconds longer.

Is this on a local or a remote connection? IIRC the user mentioned that his connection sometimes has to be proxied over the Plex server which certainly makes things slower. But I'll ask for more details and add some runtime measurements to my code.


> #464

Wow you already looked into it, thanks. I was going to look into it this weekend.

**Comment by Hellowlol** [comment]
This was on a another computer on my local lan

**Comment by Hellowlol** [comment]
It might not be the all method that is slow. You need to be carefull what attributes you access as some require a reload (requesting pms for more or new info)

**Comment by Hellowlol** [comment]
https://github.com/pkkid/python-plexapi/pull/466
