### ISSUE TITLE
Create (Empty) Playlist

### ISSUE THREAD

**Issue by austin-millan** [pkkid/python-plexapi#463]
Hi,

I did a search of the issues on this project and wasn't able to come up with anything related to this issue, sorry if this is a duplicate.

It appears that the Playlist API assumes there's always library items passed in when creating a playlist. I'd like to propose the functionality to create an EMPTY playlist.

Currently, `plexapi.server.PlexServer.createPlaylist` will fail because the internal classmethod (`_create`) has an unhandled `IndexError` iterating over the empty list.

**Comment by Hellowlol** [comment]
Just pass a item then remove it.

**Comment by austin-millan** [comment]
Yeah that's a workaround, but it makes constructing playlists pretty messy.

**Comment by blacktwin** [comment]
Why are you making empty playlists? Wouldn't you be creating one with at least one item?

**Comment by Hellowlol** [comment]
I don’t see the problem. It would be trivial to make a function that does this for you. I’m gonna taf this as a enchantment however I don’t think this will be added unless someone makes a pr for it.

**Comment by austin-millan** [comment]
After looking into this a little further, it doesn't look like it's possible via the Plex dashboard to create an empty playlist.

I'll close this issue since there's not even native support for this feature.
