### ISSUE TITLE
studio error

### ISSUE THREAD

**Issue by BH1NBN** [pkkid/python-plexapi#477]
After setting the studio by mistake in the studio, the result is displayed at the director's position, but the director does not respond.

**Comment by Hellowlol** [comment]
I dont understand. Can you post some code?

**Comment by BH1NBN** [comment]
> I dont understand. Can you post some code?

``` python
mediaInfo={
        'id': movie.ratingKey,
        'studio[0].locked': 0,
        'studio[0].tag.tag': 'studio1',

        'studio[1].locked': 0,
        'studio[1].tag.tag': 'studio2',
}
movie.edit(**movieInfo)
movie.reload()
```
If the above code is correct, it will show Studio 1 and Studio 2 on the plex media page. But in fact, these two information will be displayed on the director position of the plex media page, which makes me wonder if it is my operation error or a bug

**Comment by BH1NBN** [comment]
@Hellowlol 
Hi, by the way, ask a question: Taking the above code as an example, after I successfully used edit () to add information, now I want to delete him. what should I do? I tried the following operations, but none of them had any delete effect:
``` python

    mediaInfo={        
        'id': movie.ratingKey,
        'country.locked': 0,
        'country[0].tag.tag': 'country1',
        'country[1].tag.tag': 'country2',
    }
    movie.edit(**mediaInfo)
    movie.reload()

    movie.countries.clear()
    movie.edit()
    movie.reload()
```
Please advise

**Comment by BH1NBN** [comment]
> @Hellowlol
> Hi, by the way, ask a question: Taking the above code as an example, after I successfully used edit () to add information, now I want to delete him. what should I do? I tried the following operations, but none of them had any delete effect:
> 
> ```python
>     mediaInfo={        
>         'id': movie.ratingKey,
>         'country.locked': 0,
>         'country[0].tag.tag': 'country1',
>         'country[1].tag.tag': 'country2',
>     }
>     movie.edit(**mediaInfo)
>     movie.reload()
> 
>     movie.countries.clear()
>     movie.edit()
>     movie.reload()
> ```
> 
> Please advise

@Hellowlol 
```python
def removeGenre(self, genres):
        """ Remove a genre(s). """
        self._edit_tags('genre', genres, remove=True)
```
I found this, I wonder if it is correct

**Comment by Hellowlol** [comment]
Im not sure how to remove this, but i assume this is used in the same way as genre.

Try using the _edit_tags directly
