### ISSUE TITLE
invalid titleSort setting

### ISSUE THREAD

**Issue by BH1NBN** [pkkid/python-plexapi#478]
'title.locked': 0,
'title.value': '标题',
'titleSort.locked': 0,
'titleSort.value': 'x'

**Comment by Hellowlol** [comment]
I dont understand.

**Comment by BH1NBN** [comment]
> I dont understand.
``` python
s={
 'id':'123',
 'titleSort.value':'a'
}
video.edit(**s)
video.reload()
```
Title sorting without sorting effect has not changed

**Comment by Hellowlol** [comment]
Tried locking it?

**Comment by BH1NBN** [comment]
> Tried locking it?

No, I do n’t need to lock it. I hope that the title sorting can be sorted according to the settings. However, when I modify the value, there is no change in it. Am I writing something wrong?

**Comment by blacktwin** [comment]
```python
item.edit(**{'titleSort.value': 'This is a better titleSort', 'titleSort.locked': 1})
```

**Comment by BH1NBN** [comment]
> ```python
> item.edit(**{'titleSort.value': 'This is a better titleSort', 'titleSort.locked': 1})
> ```

Thanks!
