### ISSUE TITLE
Change IMDb rating and edit plot summary

### ISSUE THREAD

**Issue by danz1995** [pkkid/python-plexapi#479]
Hey, 

I am not able to find on the documentation how to change IMDb ratings, since it is well-known that Plex has its issues with updating them. Also, I could not find a way to edit the plot summary.

Can you help?

Thanks!

**Comment by blacktwin** [comment]
```python
item.edit(**{'rating.value': 9.0, 'rating.locked': 1})
item.edit(**{'summary.value': 'This is a better summary', 'summary.locked': 1})
```

**Comment by BH1NBN** [comment]
Thanks!

> ```python
> item.edit(**{'rating.value': 9.0, 'rating.locked': 1})
> item.edit(**{'summary.value': 'This is a better summary', 'summary.locked': 1})
> ```

**Comment by danz1995** [comment]
Thanks!!

**Comment by danz1995** [comment]
> ```python
> item.edit(**{'rating.value': 9.0, 'rating.locked': 1})
> item.edit(**{'summary.value': 'This is a better summary', 'summary.locked': 1})
> ```

Hey, I am trying to understand a little better the kwargs parameters so I know how to change other things in the future. I could not find the possible parameters on plex api documentation, can you please advise?

I am currently trying to force de imdb id of movies that plex was not able to find (this happens usually with some documentaries).

Thanks in advance!
