### ISSUE TITLE
Question regarding labels in tv shows

### ISSUE THREAD

**Issue by richterro** [pkkid/python-plexapi#480]
Hello I would have several questions and did not know where these fit.

1st question: I have deposited a label in a TV show and would like to read it out. Unfortunately I always get an empty list back. (If I insert the value under Collection, this value is shown to me). In the xml document this can be read as the following substring: 
`...
<Collection id="76243" filter="collection=76243" tag="TheTVDB TV #295759"/>
...
<Role id="7452" filter="actor=7452" tag="Julie Gonzalo" role="Andrea Rojas" thumb="http://image.tmdb.org/t/p/original/hijoTFxL83zgUxoEMdilP8XIxSf.jpg"/>  
<Label id="76244" filter="label=76244" tag="TheTVDB TV #295759"/>  
<Field locked="1" name="contentRating"/>  
<Field locked="1" name="collection"/>  
<Field locked="1" name="label"/>  
...`

Do you know where I should look for the error? The structure of Collection seems identical.

2nd question: Is there already a way to set the above mentioned label using this API?

3rd question: When I output the attribute role of a show, only the first 3 are shown, but in the xml far more are transmitted. Why is that?

Thanks a lot.

**Comment by Hellowlol** [comment]
1. I'm not sure i understand. Have you added a label in the webui?
2. See [addLabel](https://python-plexapi.readthedocs.io/en/latest/modules/base.html?highlight=addlabel#plexapi.base.PlexPartialObject.addLabel)
3. We try to do as few http requests as possible. To get more info/updated info use `object.reload()`

**Comment by richterro** [comment]
I have added the label in the webui first to check if i can recive the information with this tool. I have added it here: https://prnt.sc/sao80w but if i print show.labels i get an empty list. Maybe this isn't the correct way for me to recive this information. Thank you for point 2/3 i will have a look into this.

**Comment by richterro** [comment]
With this reload feature i was able to recive the lable information. Thank you. It can be closed for all I care.
