### ISSUE TITLE
plex.settings.cinemaTrailersPrerollID string is cutting short

### ISSUE THREAD

**Issue by AndrewHolmes060** [pkkid/python-plexapi#494]
Hi there,

apologies if this is really obvious problem but for the life of me i cant work out what the issue is.

im trying to pull the text form for cinematrailerspreroll and amend it with another file location created earlier on. 

```
import requests
from plexapi.server import PlexServer
import re
baseurl = 'http://IP ADDRESS'
token = 'PLEX TOKEN'
plex = PlexServer(baseurl, token)


test = plex.settings.get('cinemaTrailersPrerollID')
test = str(test)
print (test)
plexsprerolllength = (len(test) - 1)
print (plexsprerolllength)
test = test[2:plexsprerolllength]
print (test)
filelocation = "FILE/LOCATION/Pulp Fiction Preroll.mp4"
input = ("{}, {}").format(test, filelocation)
print (input)
plex.settings.get('cinemaTrailersPrerollID').set(input)
plex.settings.save()
print(plex.settings.cinemaTrailersPrerollID)
```

I added a couple of prints in to see exactly where the cutting happened and it seemed to happen when stringifying "test" it seems to cut it after 50 characters.
so for example i input "testing1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20" into the settings textbox i then get the following output in terminal when i run the script:

```
b'testing1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20'
<Setting:CinemaTrailersPrerol:b'testing1,2,3,4,5,6>
50
etting:CinemaTrailersPrerol:b'testing1,2,3,4,5,6
etting:CinemaTrailersPrerol:b'testing1,2,3,4,5,6, FILE/LOCATION/Pulp Fiction Preroll.mp4
b'testing1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20'
```

While im sure im doing something stupid I cant for the life of me figure why its cutting off at 50 characters when being stringified.

any help would be greatly appreciated.

**Comment by Hellowlol** [comment]
Your trying to print out a Settings object. If you need the value you need to use ```test.value```

**Comment by AndrewHolmes060** [comment]
oh my god thank you. i was so bloody lost!
