### ISSUE TITLE
can't get to work MyPlexPinLogin()

### ISSUE THREAD

**Issue by eloyn** [pkkid/python-plexapi#503]
Hello, 

I don't know if I'm doing anything wrong but can't get to work MyPlexPinLogin() class...

Could you please paste an example on how to do it?

Had no issues with other classes...

**Comment by Hellowlol** [comment]
I have never used it. What have you tried so far?

**Comment by Montellese** [comment]
This code is from me. Please see https://github.com/Montellese/mediaimporter.plex/blob/e99c15df0c9459fce65f0e9c7c44cc41b166828f/lib/importer.py#L237-L270 for how I'm using this in a Kodi add-on where it works fine.

**Comment by JonnyWong16** [comment]
This should be fixed now after #620.

Example of using `MyPlexPinLogin` can be found here:
https://github.com/pkkid/python-plexapi/blob/master/plexapi/utils.py#L385-L406
