### ISSUE TITLE
Intro marker question

### ISSUE THREAD

**Issue by amazingr4b** [pkkid/python-plexapi#504]
**Describe the issue**
"AttributeError: 'NoneType' object has no attribute 'split'" when getting the intro markers for an episode with intro details. 
Not sure if this is a problem with how I am getting these values, or if this is a bug. 

**Code snipppets**
```
shows = plex.library.section(getshowsection())
theshow = shows.get(show).episodes()
for ep in theshow:
	if ((int(ep.seasonNumber) == int(Ssn)) and (int(ep.index) == int(Epnum))):
                for m in ep.markers:
		    if m.type == "intro":
				start = m.start
				end = m.end
				dur = end - start
				start = start / 1000
				end = end / 1000
				dur = dur / 1000
```
throws error:
File "C:\Users\amazi\Desktop\TBN-Plex v517\ToBePosted\plexapi\media.py", line 718, in _loadData
    _tag, _id = self.filter.split('=')
AttributeError: 'NoneType' object has no attribute 'split'

**Expected behavior**
No attribute error. 

I changed the _loadData function in the media.py file to be:
```
 def _loadData(self, data):
	self._data = data
	self.filter = data.attrib.get('filter')
	self.type = data.attrib.get('type')
	if (self.type != "intro"):
		_tag, _id = self.filter.split('=')
		self.tag = self.type + _tag.capitalize()
		self.id = _id
	self.start = cast(int, data.attrib.get('startTimeOffset'))
	self.end = cast(int, data.attrib.get('endTimeOffset'))
```

I no longer get that attribute error, and I get the into details as expected. Not sure if that change would affect anything else, though for the past week and a half I have not encountered any other issues related to this change.  

**Enviroment (please complete the following information):**
 - OS: [ Linux, Windows]
 - Plex version [1.19.4.2865]
 - Python Version [Python 3.8.0]
 - PlexAPI version [4.0.0]

**Additional context**
Add any other context about the issue here.

**Comment by Hellowlol** [comment]
I dont know why this happens. You should try to use episode(season=Xx, episode=ty). The only think i can think of is that the episode dont have the info it needs. You can check using hasIntroMarker (it will reload the object for you if needed)

**Comment by amazingr4b** [comment]
Before I posted my comment I tried using the hasIntroMarker first, and got the same results. As a second test just now I tried:

`	shows = plex.library.section(getshowsection())
	ep = shows.get(show).episode(season=int(Ssn), episode=int(Epnum))
	print (ep.hasIntroMarker)`
Which spits out:
C:\Users\FILEDIR>python myplextv_alt.py epdetails "the big bang theory" 1 4
 File "C:\Users\FILEDIR\plexapi\base.py", line 296, in __getattribute__
    value = super(PlexPartialObject, self).__getattribute__(attr)
  File "C:\Users\FILEDIR\plexapi\video.py", line 748, in hasIntroMarker
    self.reload()
  File "C:\Users\FILEDIR\plexapi\base.py", line 213, in reload
    self._loadData(data[0])
  File "C:\Users\FILEDIR\plexapi\video.py", line 712, in _loadData
    self.markers = self.findItems(data, media.Marker)
  File "C:\Users\FILEDIR\plexapi\base.py", line 186, in findItems
    item = self._buildItemOrNone(elem, cls, initpath)
  File "C:\Users\FILEDIR\plexapi\base.py", line 88, in _buildItemOrNone
    return self._buildItem(elem, cls, initpath)
  File "C:\Users\FILEDIR\plexapi\base.py", line 73, in _buildItem
    return cls(self._server, elem, initpath)
  File "C:\Users\FILEDIR\plexapi\base.py", line 49, in __init__
    self._loadData(data)
  File "C:\Users\FILEDIR\plexapi\media.py", line 715, in _loadData
    _tag, _id = self.filter.split('=')
AttributeError: 'NoneType' object has no attribute 'split'

I think it has to do with the loadData function trying to get a "filter" attribute that does not exist in the intro marker. For example, when I look at my server xml I see:

<Marker type="intro" startTimeOffset="196594" endTimeOffset="241747"/>

Which does not have a filter like chapters:
<Chapter id="47" filter="thumb=47" index="1" startTimeOffset="-1" endTimeOffset="0" thumb="/library/media/7349/chapterImages/1"/>

I think that is why I don't have any problems when using the loadData function with the if statement to on the filter if the type isn't an intro like I posted. 

When using the loadData function with the if statement from my original post I get:
C:\Users\FILEDIR>python myplextv_alt.py epdetails "the big bang theory" 1 4
True  

I should also mention that I only get that attribute error for episodes that have an intro marker. No marker I just get false as expected.

**Comment by blacktwin** [comment]
hmmm, maybe Plex changed something??? idk. I just reloaded an xml where the `filter` attribute was present and after reloading it was gone. So that can be removed.

**Comment by Hellowlol** [comment]
The filter was there in the xml response last time i checked. Ill check that later.

**Comment by blacktwin** [comment]
@amazingr4b can you try my update and confirm if it's working now?
@Hellowlol Have you had a chance to double check?

**Comment by Hellowlol** [comment]
No

**Comment by amazingr4b** [comment]
Seems to be working as expected.

**Comment by amazingr4b** [comment]
I believe this can be closed with the changes being merged.
