### ISSUE TITLE
Art attribute missing from season/collection objects

### ISSUE THREAD

**Issue by rg9400** [pkkid/python-plexapi#511]
**Describe the issue**
The art attribute is missing for season/collection objects even though they can have custom backgrounds. I tested episodes, shows, movies, artists, and albums. The art attribute was present on all of those objects.

**Code snipppets**
```
>>> collection.art
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Collections' object has no attribute 'art'
```
```
>>> season.art
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python38\lib\site-packages\plexapi\base.py", line 279, in __getattribute__
    """ Not all objects in the Plex listings return the complete list of elements
AttributeError: 'Season' object has no attribute 'art'
```

**Expected behavior**
Art attribute present for season/collection objects

**Enviroment (please complete the following information):**
 - OS: `Windows 10`
 - Plex version: `1.19.4.2902`
 - Python Version: `3.8.3`
 - PlexAPI version: `4.0.0`

**Comment by blacktwin** [comment]
I still have PR #509 open and could use it to add this attribute to the needed classes.

**Comment by blacktwin** [comment]
#509 was merged. Closing this issue.
