### ISSUE TITLE
Edit Collections "sortTitle".

### ISSUE THREAD

**Issue by harisris** [pkkid/python-plexapi#514]
I want to bulk edit collections sortTitle. (This helps me organize collections based on different types. eg. sort title = "theme-Survival" or "artist-Hans-Zimmer") As far as I have explored, I couldn't find/edit "sortTitle" attribute of Collection type in source. Possible to add that attribute as well? (Or guide me how to do that?) Thank you.

**Comment by blacktwin** [comment]
See #509

**Comment by blacktwin** [comment]
Sorry, that is only for adding the attribute. To edit anything in a Plex item you can use the `item.edit(**kwargs)` or `item._edit_tags()`

```python
item = plex.fetchItem(1234)
edits = {'titleSort.value': "The new Title Sort", 'titleSort.locked': 1}
item.edit(**edits) # waiting on PR509 to allow for editing Collection
item.reload()
print(item.titleSort) # waiting on PR509 for this attribute for Collection
```
Editing Collection: 9685b57
titleSort Attribute add: 3395547

**Comment by harisris** [comment]
Great. Thank you!

**Comment by blacktwin** [comment]
#509 was merged. Closing this.
