### ISSUE TITLE
Changelog? Migration guide?

### ISSUE THREAD

**Issue by glensc** [pkkid/python-plexapi#521]
there's 4.0.0 released, not can not anywhere migration guide or changelog. usually bumping major version includes breaking changes, so I'd like to review my application before upgrading. the release on github doesn't even have meaningful changes listed.

- https://python-plexapi.readthedocs.io/en/latest/
- https://github.com/pkkid/python-plexapi/releases/tag/4.0.0
- https://github.com/pkkid/python-plexapi/tree/4.0.0

**Comment by Hellowlol** [comment]
Your right, i didnt create any of them. You need to do a diff or just try and see that happens. The only thing i can remember was that py2 support was dropped

**Comment by glensc** [comment]
can you edit the tag then and fill at least that there: 
- https://github.com/pkkid/python-plexapi/releases/tag/4.0.0

**Comment by jjlawren** [comment]
Hey @glensc, we've been trying to maintain better [release notes](https://github.com/pkkid/python-plexapi/releases) recently. Hopefully this will be easier to manage moving forward.

**Comment by glensc** [comment]
@jjlawren super thanks. so far seems I've come around the 3.2.0 -> 4.3.1 gap, things appear to be working. but not merged due to project own management issues.
