### ISSUE TITLE
Add to Playlist : 'str' object has no attribute 'listType'

### ISSUE THREAD

**Issue by PiXAI** [pkkid/python-plexapi#522]
Hi.

I'm sorry if this is just a noob thingy but I'm not able to add items to an existing playlist.

As you can see below, I have the tracks in a list and try to add it to the playlist "OFF POP".
If I request the items from the playlist works fine. But adding them does not.
The following error occurs:

_Add to Playlist : 'str' object has no attribute 'listType'_

This is the function. It marks the "tracks" as error.
What am I supposed to deliver to this function else than a list?

`def addTrackToPlaylist(playlist, tracks):`
`PlexServer(url, token).playlist(playlist).addItems(tracks)`

This is the calling to the function.
`tracks = ['<Track:95076:Stir-It-Up-(From-"Be>', '<Track:95134:Call-On-Me-(Radio-Ed>']`
`methods.addTrackToPlaylist("OFF POP", tracks)`

Thanks for your help in advance!

**Comment by amazingr4b** [comment]
Not sure if you can use a list when adding to a playlist, but the way I add items to a playlist is:  

```
playlist = plex.playlist("playlistname")
movie = plex.library.section("Movies").get("Moviename")
playlist.addItems(movie)
``` 

When I work through a list of items, let's call them tracks and that the list is setup as you described, I use the following:   

```
playlist = plex.playlist("playlistname")
for t in tracks:
     playlist.addItems(t)
```

**Comment by PiXAI** [comment]
> playlist = plex.playlist("playlistname")
> movie = plex.library.section("Movies").get("Moviename")
> playlist.addItems(movie)
> ```

Thank you for your help!
Well, your solution works (kind of).
I have to get the artist first and then get the track.
That is (atm) the only possibility to add a track to a playlist.

```
def addTrackToPlaylist(playlist):
    playlist = plex.playlist(playlist)
    artist = plex.library.sectionByID(music_sectionID).get("Eric Prydz")
    track = artist.track("Call On Me (Radio Edit)")

    playlist.addItems(track)
    print(f"added {track} to playlist {playlist}")

```
It works if the title is exact! Else I would have to search with RegEx for a similar name.

But why can't I just add a track when I have the ID?
Like this:

```
<Track:95134:Call-On-Me-(Radio-Ed>
```

The Problem is that I do have a lot of mixes. Plex only saves 20 letters of a title.
So if I would have:
```
Call On Me (Radio Edit)
Call On Me (Radio Edit) - mixed by NRG
```
then both names would be saved as 
```
<Track:xxxxx:Call-On-Me-(Radio-Ed>
```
in Plex. If the artist is the same you can't differ both tracks. So the ID is actually necessary.

**Comment by Hellowlol** [comment]
Are you sure the title is limited to 20 chars? Tried using print instead of repr? You can get stuff by I’d, it’s covered in the docs.

**Comment by PiXAI** [comment]
> Are you sure the title is limited to 20 chars? Tried using print instead of repr? You can get stuff by id it’s covered in the docs.

Jup, every title I print with ```print(track)``` (or anything else I print which is over 20 chars -> ```print(any_element)```) only has 20 chars.
Always looks like this  ```<Track:xxxxx:Call-On-Me-(Radio-Ed>``` -> 20 chars
Its acutal name is ```Call On Me (Radio Edit)``` -> 23 chars

Or ```Stir-It-Up-(From-"Be``` -> 20 chars
Its actual name is ```Stir It Up - From "Beverly Hills Cop" Soundtrack``` -> 48 chars

---

> You can get stuff by id it’s covered in the docs.

Yes, thanks! Works by using ```track = plex.fetchItem(95076)```
And that track can be inserted into the playlist.
