### ISSUE TITLE
Question: How to pull movies with or without collections?

### ISSUE THREAD

**Issue by DutchyOven** [pkkid/python-plexapi#523]
So I can pull collections like this 

```
movies = plex.library.section('Movies') #Movies Section
collection = movies.search(collection='collection name') 

for movie in collection:
```

but I can't figure out how to pull either all movies with a collection or all movies without.

**Comment by blacktwin** [comment]
```python
for movie in movies:
    if movie.collection:
        print("This movie has a collection")
    else:
        print("This movie does not have a collection")
```
I think that should work. You may need to reload the movie before check the collection attribute.

**Comment by DutchyOven** [comment]
> I think that should work. You may need to reload the movie before check the collection attribute.

Yea that works and Ive been using something like that I was hoping there was a way to limit it up top. My other scripts where I can limit my population before the IF section run way faster than looping through each one. Its not a huge deal I just have a big library so any optimization goes a long way.

**Comment by Hellowlol** [comment]
Cant you use library.collection and just use that to see if a movie is in the collection list. This way you dont need to reload every movie.

**Comment by DutchyOven** [comment]
> library.collection
I'm looking at the documentation and I don't see how to limit using this. Looks like its for updating collection settings, unless I'm not looking at the right thing.
https://python-plexapi.readthedocs.io/en/latest/modules/library.html?highlight=library.collections#plexapi.library.Collections

I can do plexapi.library.MovieSection.collection() that gives me a list of all collections or I can do plexapi.library.MovieSection.search(collection=('name','of','collections','by','commas') but I'd have to list out all collection names and I have 806 so...yeah thats a lot.

**Comment by Hellowlol** [comment]
806, Collections is a lot. How many movies do you have? Use .children to get the items in that collection.

**Comment by DutchyOven** [comment]
> 
> 
> 806, Collections is a lot. How many movies do you have? Use .children to get the items in that collection.

8325 movies.

could you give me an example of using .children? its giving me list object has no children but i might be misunderstanding you.

**Comment by blacktwin** [comment]
```python
collection = plex.fetchItem(90024)
print(collection.children)
```

**Comment by DutchyOven** [comment]
> 
> 
> ```python
> collection = plex.fetchItem(90024)
> print(collection.children)
> 
> for collection in plex.library.section('Movies').collection():
>     print(collection.children)
> ```

This is a cool way of pulling it, I might incorporate it in other code, thanks.

But it still doesn't do what I was thinking of. Maybe If I actually show you the code that I have running it'll make more sense.

So I have a bunch of collections that fold movies into them. I don't want to set the collections to "Show" because I don't want 4 entries for 3 movies in a collection, I'd rather have [Iron Man Collection ](https://imgur.com/RsFZMF9) than have [Iron Man 1-3](https://imgur.com/g1Gc0YJ) showing.

The problem is some collections don't line up with the name of the movie. **Oldboy** is in **The Vengeance Trilogy**. If I was scrolling through my collection it'd look like Oldboy was missing, because its folded into the vengeance trilogy. 

So basically what the code below does is compares the sorting name of the collection with the sorting name of the title of the movie. 

If they do match up leave them alone, like Iron Man, if they don't match up like Oldboy then I need to add that movie to a collection I have called "Force Show" which keeps the movie in the collection but shows its own entry as well. There are a lot of movies like this, Pitch Black is in the Chronicles of Riddick collection for instance. 

I don't want to manually do this because screw scrolling through 806 collections, comparing names of each movie, then adding them to forced. I'd rather run this once a week.


```
import re
#from string import digits 
from fuzzywuzzy import fuzz
#https://github.com/seatgeek/fuzzywuzzy
from plexapi.server import PlexServer
baseurl = 'http://192.168.1.1:32400'
token = 'xxxxxxxxxxxxxxxx'
plex = PlexServer(baseurl, token)

movies = plex.library.section('Movies') #Movies Section
all_movies = movies.search(sort='titleSort') **#All Movies since I can't limit to only movies in collections**
str_coll =('384185','251654','393414','158516','392859','428861','391746','547246','348469','348471','394025','348753','381715','382446','382447','383686','383797','384234','386714','388517','428861','519538','520997','524299','420994','348461','135547','388900')
#A list of my custom collections, these are made by me and I don't want them included in this.
numbers = re.compile(r'\d+(?:\.\d+)?') #Using re to strip all symbols and letters below to leave only numbers
alpha = re.compile('[^A-Za-z0-9]+') #Using re to strip all symbols to leave only numbers

for movie in all_movies: #Only movies that are in a custom collection
    movie.reload()
    singlecoll = str(set(numbers.findall(str(movie.collections)))-set(str_coll)).replace("'",'').replace('}','').replace('{','') #Pulls out all my hand made custom collections, listed above and leaves only the number of the collection TMDB provided for this collection.
    singlecoll_str = str(singlecoll) #String version of above
    if "394025" in str(movie.collections): #If already in force show, do nothing
        continue
    if len(str(movie.collections)) < 3: #Meaning the movie does not exist in a collection.
	    continue
    if len(singlecoll_str) > 7 or "set" in singlecoll_str: #Means the movie is in two collections that are not one of my customs, I'll get to these later because I might have missed a custom collection
        continue
    coll = str(movie.collections).replace('A-','').replace('The-','').replace('An-','').replace('-',' ') #Gives me a clean name of the collections a movie is in
    out_coll = alpha.sub('', coll.split(singlecoll_str)[1].split()[0].lower()) #Takes the name of the collection using singlecoll, above, and getting the name after it
    len_coll = len(out_coll) #Will tell me later where cut the title, since I'm doing a fuzzy comparison I don't want to compare the entire collection name to the entire title, just the part I need
    title_str = alpha.sub('', (str(movie.titleSort)))[0:len_coll].lower() #Keep only the alphanumeric characters of the title
    fuzz_match = fuzz.ratio(out_coll,title_str) #Compares title to collection name, in the future I'm just going to scrap this part and compare the first two letters to each other
	
    if fuzz_match < 60:
	    print(str(movie.titleSort) +' '+ str(movie.collections)+' ---- ' + title_str + ' v. '+ out_coll + ' ' + str(fuzz_match))
```

**Comment by Hellowlol** [comment]
Your missing the point. You iterate over children adding to a list this way you only end up with movies that is in a collection.

**Comment by DutchyOven** [comment]
> 
> 
> Your missing the point. You iterate over children adding to a list this way you only end up with movies that is in a collection.

I am definitely missing the point, I thought the code BlackTwin wrote would fetch that collection number, then show me all movies in it. I just plugged it in and error plexapi.exceptions.NotFound: (404) not_found;. Even searching .children and python didn't really get me anywhere. A bunch of code on sorting actual children and parents etc...

Anywho I'm new to this stuff so I'll find a tutorial or something later this week and see what that can do. For now my code works even if it takes a little longer.
