### ISSUE TITLE
No .delete() method on Collection object, but there is .delete() on Library.Search(libtype=collection)

### ISSUE THREAD

**Issue by nalexander50** [pkkid/python-plexapi#524]
I do not see any support for deleting an object of type `plexapi.media.Collection` by calling a `.delete()` method. However, if I search for a collection using `plexapi.library.Library.search(libtype=collection)`, there is a `.delete()` method.

I would expect to be able to do the following:

`server.library.section('Movies').all()[n].collections[m].delete()`

Instead, it seems that I have to do the following:

`server.library.search(collection_name, libtype='collection')[0].delete()`

I am grateful that the delete functionality does ultimately exist, but the only reason that I accidentally found it was by getting a Google result for a different GitHub repo. It took some time digging through their code to see how they were doing it.

I'm guessing this is an artifact of Plex rather than the maintainer's explicit decision. Still, I thought I would ask to at least understand why this is the case.

**Comment by blacktwin** [comment]
`server.library.section('Movies').all()[n].collections[m].delete()` is attempting to delete the collection from the video. 
`server.library.search(collection_name, libtype='collection')[0].delete()` is attempting to delete the collection from the library. 

You cannot delete or load the Collection from a Video. You have to access the Collection from the library Collection. This currently emulates how the webUI operates. 

Use the webUI to view the XML for a video with a collection and then the collection. I think that should help with understanding why/how. Video collection's `id` (only after a `video.reload()`) matches the Collections' `index`. So you could add a way to connect the two, loading the library.Collections from the Video but this would cost a `reload()`, maybe two.
