### ISSUE TITLE
Get current playqueue

### ISSUE THREAD

**Issue by anaisaurus** [pkkid/python-plexapi#529]
Hello,

I am using Plex API with the Flask framework in order to have a Dashboard where Plex is featured.
 
Right now, I am trying to build a player which would be displaying the playback status of a given client.
So fat, I have no problem retrieving the media metadata, but I don't find any information about the playback status.

For example, I would like to know the following information:
- is the client playing something?
- is the media on pause?
- let's considering the client is playing music, is the shuffle mode enabled? What about the repeat mode?

From what I have understood, everything is inside the Playqueue class, but I didn't find any way to retrieve it.

Thanks in advance!

**Comment by Hellowlol** [comment]
https://python-plexapi.readthedocs.io/en/latest/modules/server.html#plexapi.server.PlexServer.sessions

Sendt fra min iPhone

**Comment by anaisaurus** [comment]
Hello Hellowlol,

Thank you for your quick reply!

I already got most of the information I need from the sessions() function, but it seems that is doesn't have every information I want.

While I could see whether a media was on pause, I didn't find anything about the shuffling mode and the repeating mode.

**Comment by Hellowlol** [comment]
I don’t know if that info is available in the xml. You can check the xml response. Maybe you can find something in the websocket info. I can’t remember the info it returns.

**Comment by darylkell** [comment]
I'm chasing the current time the user is at in the stream, or how many seconds remaining in the current stream kinda thing.

**Comment by amazingr4b** [comment]
I use the following to get current position:
`for mediatype in client.timeline():
		if int(mediatype.get('time')) != 0:
			check = mediatype.get('time')
			check2 = mediatype.get('duration')
			check = int(check)/60000
			check2 = int(check2)/60000
			say = "We are at minute " + str(int(check)) + " out of " + str(int(check2)) + "."
                        print (say)

`

**Comment by darylkell** [comment]
Thanks for the code snippet, amazingr4b. I was chasing information relating to the sessions() list (list of people streaming from a server) previously mentioned in the thread so unfortunately the snippet wasn't the answer I was looking for.
I have since learned that the 'viewOffset' attribute is the streamer's position in the current stream, and the 'duration' attribute is the length of the stream.

**Comment by amazingr4b** [comment]
That sounds right for sessions. There are a couple different ways to get that information depending on how you are going about getting it.

**Comment by jjlawren** [comment]
The updated `PlexClient.timeline()` can get you a bit more info if `sessions()` doesn't have enough.

Can we close this or do you need more info?

**Comment by anaisaurus** [comment]
Thank you for the update!
As far as I am concerned, I don't have any further questions :)
