### ISSUE TITLE
Question regarding using .sessions() on server instance.

### ISSUE THREAD

**Issue by saltydk** [pkkid/python-plexapi#532]
**Describe the issue**
.sessions() on a server object seems to be missing information that would allow you to identify the client like when you use the /status/sessions web api endpoint. Would it be possible to have this added or am I looking it the wrong place?

The use case is a friend that wants to lookup whenever client x is playing something and check something.

**Enviroment (please complete the following information):**
 - OS: Docker
 - Plex version 1.19.5.3035-864bbcbb7
 - Python Version 3.8.2
 - PlexAPI version 4.0.0

**Comment by amazingr4b** [comment]
The client is in the sessions details. Use the players object. You should get something like this:
<PlexClient:DESKTOP-BLAH1234>
With .title you get something like 
DESKTOP-BLAH1234

**Comment by jjlawren** [comment]
Check the `machineIdentifier` of the player associated with the session for a persistent unique ID.

**Comment by saltydk** [comment]
I might not be following you, fairly new at this, but when I call .sessions() I get a list of (for movies playing) Movie objects where they do have a key called players but that always has no values.
Checking the information by saving it like this. 
`server = PlexServer("https://domain.tld", "sometoken")
sesssions = server.sessions()`

Is that the wrong way to go about getting the information?

**Comment by blacktwin** [comment]
```python
for session in plex.sessions():
    for player in session.players:
        print(vars(player))
        print(player.machineIdentifier)
```

**Comment by saltydk** [comment]
Thanks!

**Comment by saltydk** [comment]
I don't suppose you have an example of how to change the audio stream of a session based on channels or the like?

**Comment by ovived** [comment]
How can you show the USER of the session.. ie a friend is watching something, is there a way to get the user associated with the active session? thanks
