### ISSUE TITLE
Iterating over section items very slow in 4.0.0

### ISSUE THREAD

**Issue by saltydk** [pkkid/python-plexapi#533]
**Describe the issue**
I have the below code in a for loop that iterates over a list of sectionids but if I upgrade from PlexAPI-3.6.0 to 4.0.0 the code takes forever without any errors. What change caused this to run so slowly?

**Code snipppets**
```
        section = server.library.sectionByID(sectionid)
        media = section.all()

        plexlibrary[sectionid] = [Plex(row.locations[0],
                                       row.guid,
                                       row.ratingKey,
                                       row.title) for row in
                                  media]
```

**Enviroment (please complete the following information):**
- OS: Docker
- Plex version 1.19.5.3035-864bbcbb7
- Python Version 3.8.2
- PlexAPI version 4.0.0

**Comment by Hellowlol** [comment]
I’m afk so I can’t measure, but I can’t remember any changes that should make things slower. I make a pr to make things faster. Can you Measure how long time it takes to collect the media?

**Comment by saltydk** [comment]
Using 3.6.0
Each iteration takes between 0,209-0,234 seconds.

Using 4.0.0
Each iteration takes between 0,005-0,015 seconds.

**Comment by blacktwin** [comment]
>  PlexAPI-3.6.0 to 4.0.0 the code takes forever without any errors

So 3.6.0 was faster with errors?

**Comment by saltydk** [comment]
No errors on either version.

**Comment by saltydk** [comment]
Upon further testing it only happens with a ShowSection.

**Comment by Hellowlol** [comment]
Iterations of what? Your list comp?

**Comment by saltydk** [comment]
Iteration of media into row in the example above. Media is a list of Show objects.
![image](https://user-images.githubusercontent.com/6587950/88090508-fa656e00-cb8d-11ea-91a4-d2a221d32866.png)

**Comment by Hellowlol** [comment]
Ok, I think I get it. The .all call is fast but your loop is slow. I don’t know the reason as both the old version and new should reload the object (makes a http call) you can turn on logging to see what happens.

**Comment by saltydk** [comment]
Yeah, sorry about that I was only talking about the bit after loading .all but included it since I wanted to indicate what the media variable contained.

The difference is:
3.6.0
`2020-07-21 21:09:30,359         base:306  DEBUG     Reloading Show 'The 100' for attr 'locations'
2020-07-21 21:09:30,360       server:424  DEBUG     GET https://domain.tld/library/metadata/259249`

4.0.0
`2020-07-21 21:10:41,846         base:306  DEBUG     Reloading Show 'The 100' for attr 'locations'
2020-07-21 21:10:41,846       server:430  DEBUG     GET https://domain.tld/library/metadata/259249?checkFiles=1&includeExtras=1&includeRelated=1&includeOnDeck=1&includeChapters=1&includePopularLeaves=1&includeMarkers=1&includeConcerts=1&includePreferences=1`

**Comment by Hellowlol** [comment]
As I suspected. We request more info from plex as the result the plex webserver uses longer time. You can try to use a threadpool.

**Comment by saltydk** [comment]
There is no way to toggle those extra bits? Seems overkill if you don't want them for your particular use case.

**Comment by Hellowlol** [comment]
Not directly no. A reload should get as much info possible. You need to patch this yourself or just create a wrapper of some kind.

**Comment by Hellowlol** [comment]
```python
from plexapi.video import Show
section = server.library.sectionByID(sectionid)
Show._include = "" # <-- need to be **_before_** the .all() call
media = section.all()
plexlibrary[sectionid] = [Plex(row.locations[0],
                                       row.guid,
                                       row.ratingKey,
                                       row.title) for row in
                                  media]

```

**Comment by saltydk** [comment]
That was exactly what I was looking for, thank you!
