### ISSUE TITLE
Question regarding guid changes in 1.20.0.3125

### ISSUE THREAD

**Issue by saltydk** [pkkid/python-plexapi#534]
With the release of Plex Beta version 1.20.0.3125 the new Plex Movie agent has changed to some funky looking guid format:
plex://movie/5d9f34ffb0262f001f6e9703

Is there any chance you guys know how or can help me convince Plex devs to add something to allow me to still identify which IMDB/TMDB ID is being used to match the file to metadata? For context I am using https://github.com/saltydk/matcharr to fix mismatches and would love to be able to use it on the new agent as well.

**Comment by blacktwin** [comment]
Use the matches method for any video object. You can input any available agent.

**Comment by saltydk** [comment]
Have you looked at their changes? You can no longer use any external IDs?

**Comment by Hellowlol** [comment]
I would prefer i kept the old ones :)

**Comment by blacktwin** [comment]
> You can no longer use any external IDs?

What do you mean? You mean search by the IMDB ID?

**Comment by saltydk** [comment]
Using the new movie agent? How?

**Comment by saltydk** [comment]
My reasoning is as follows
`section = server.library.sectionByID("8")
media = section.all()
match = media[0].matches()`
This returns something like
![image](https://user-images.githubusercontent.com/6587950/88398211-56fe9e00-cdc5-11ea-8725-daa872188dcf.png)

Which makes me unable to validate the match against anything other than the Plex metadata backend. So no IMDB/TMDB comparison point.

**Comment by blacktwin** [comment]
You would have to search with whatever agent you wanted. `media.matches(agent='imdb')`.

**Comment by saltydk** [comment]
I'm not sure you're following what my problem is, I may have been explaining it poorly. When I want to compare what the Plex agent has matched to using the new format I cannot compare it to IMDB/TMDB, overwriting it entirely is not really useful as I could just avoid the new agent then.

I want to look at the current metadata match information and compare it to data from and external source (sonarr/radarr) which I trust to have the right information.

**Comment by blacktwin** [comment]
`media.matches(agent='imdb')` doesn't overwrite anything. It just searches for matches based on the agent defined by the library or whatever agent you define in the kwarg. You would need to use the `fixMatch()` method to apply match. This emulates how the webui works. Find matches, select match, apply.

This isn't the best solution and is abusing the matching function from Plex. You might be better off using another tool for matching. There is a python library for TMDB. TMDB results give you the IMDB ID as well.

**Comment by saltydk** [comment]
The core issue is still identifying what the current metadata is from.

**Comment by blacktwin** [comment]
It's from Plex's new agent.  :) The guid is some concatenated or trimmed or concatenated and trimmed hash. What is used to create that hash and whether whatever that is, is useful for linking to external sources, who knows.

**Comment by saltydk** [comment]
I get it, I was just hoping someone smarter than me had a way around it or some choice words for Plex devs to change the functionality.

**Comment by blacktwin** [comment]
You aren't [alone](https://forums.plex.tv/t/new-plex-movie-agent-imdb-id-and-ratings/616685), unless this is also you.

**Comment by saltydk** [comment]
No, but I am the guy that got this [reply](https://forums.plex.tv/t/new-plex-movie-agent/616169/8?u=saltydk)

**Comment by saltydk** [comment]
With [this](https://forums.plex.tv/t/new-plex-movie-agent/616169/82?u=saltydk) being a clue that Plex is going in the wrong direction as far as I am concerned.

**Comment by blacktwin** [comment]
Thats up for debate but thats outside the scope of this project.

**Comment by saltydk** [comment]
Fair enough, thanks anyway :)

**Comment by saltydk** [comment]
Newest beta has updated the new agent to include TMDB/IMDB guid. Any chance you lads can look at it now?

**Comment by jjlawren** [comment]
Since you reported the issue and provided an example, could you validate the fix?

**Comment by saltydk** [comment]
They have added entries like 
```
<Guid id="tmdb://328644"/>
```
For any tmdb/imdb relations when requesting library/metadata item.

**Comment by Mnk3y** [comment]
[Plex Media Server 1.20.1.3252 is now available to everyone](https://forums.plex.tv/t/plex-media-server/30447/363)

**Comment by Mnk3y** [comment]
I think there is another problem. The Guid elements are not shown on the `/library/sections/X/all` page but only in the single view `/library/metadata/X` of an item. So you will not be able to find them using the search function, right?

**Comment by blacktwin** [comment]
Looks like #557 is very similar to this issue. #557 has some good information about what has happened and what can happen to address the impact this project has on other projects. I'd like to close this issue and continue the discussion in #557. Sound good?
