### ISSUE TITLE
Searching for duplicates

### ISSUE THREAD

**Issue by saltydk** [pkkid/python-plexapi#539]
**Describe the issue**
So I am using your, till now, wonderful search function to identify which items contain duplicates and came across this weird case.

The below code returns no duplicates in a section where I have manually created one for testing (Plex WEB GUI does not show split as an option on the item in question). This is the location data in the object:
![image](https://user-images.githubusercontent.com/6587950/89121008-6794cf80-d4bb-11ea-8365-b89e36dc30d2.png)

**Code snipppets**
```
section = server.library.sectionByID("12")
media = section.all()
dupes = section.search(libtype="show", duplicate=True)
```

**Expected behavior**

**Enviroment (please complete the following information):**
 - OS: Windows + Linux
 - Plex version 1.20.0.3133 
 - Python Version 3.8.2
 - PlexAPI version 4.0.0

**Comment by blacktwin** [comment]
```python
plex.library.section("Movies").search(duplicate=True) 
plex.library.section("TV Shows").search(duplicate=True)
plex.library.sectionByID('3').search(libtype="show", duplicate=True)
```
worked fine for me on PlexAPI version 4.1.0

**Comment by blacktwin** [comment]
@saltydk are you still observing this issue?

**Comment by saltydk** [comment]
I used a different approach since this didn't work for me at the time and haven't looked at it since.

**Comment by blacktwin** [comment]
Safe to close then?

**Comment by saltydk** [comment]
Sure, I'm not really using the library any time soon so won't be able to validate it being fixed or not.
