### ISSUE TITLE
How to make the media into a matched state？

### ISSUE THREAD

**Issue by BH1NBN** [pkkid/python-plexapi#542]
When I edit media information: title
I want the media to be matched, not unmatched
I executed the following code:
```
myMedia.edit(**{'id': 12345678, 'title.value': 'xxxx', 'title.locked': 1})
```

**Comment by blacktwin** [comment]
Matching is done by an agent. You editing a field is not using the agent. There is no tag or value for Matched or Unmatched. I would assume that if the guid is linked to an agent then it's matched, if the guid is local or none then it's unmatched.

**Comment by blacktwin** [comment]
Change the library agent to Personal Media.
