### ISSUE TITLE
section.search and section.all trigger timeouts

### ISSUE THREAD

**Issue by cburgard** [pkkid/python-plexapi#552]
I don't know if my server/connection is simply too slow, but I frequently get timeout exceptions when attempting to query the server for music tracks.
It would be nice if the `search` and `all` methods of the library sections would have customizable timeouts, ideally as an argument to be passed along, to make sure that people can flexibly handle connectivity issues.

**Comment by blacktwin** [comment]
Can you please provide a code snippet for what you're doing?

**Comment by Hellowlol** [comment]
You can patch a session object or see if you can pull less info from the server.

**Comment by cburgard** [comment]
Trying to make smaller/more specific requests seems to do the trick for me. However, I'd still love to know how to change the timeout when using something like this here:

```
    from plexapi.myplex import MyPlexAccount
    from plexapi.playlist import Playlist
    account = MyPlexAccount(args.account, args.password)
    plex = account.resource(args.server).connect()
    plexmusic = plex.library.section("Music")
    tracks = plexmusic.searchTracks(**{"track.title":title,"artist.title":artist})
```

**Comment by Hellowlol** [comment]
BTW, for the best performance you should connect directly to your server using the local ip.

**Comment by cburgard** [comment]
The server is not local in this case, but remote. Not sure if getting & using IP would be any faster in this case?

**Comment by Hellowlol** [comment]
I think so. 

Anyway you should be able to change the global timeout using this code.


````
import requests
class TimeoutAdapter(requests.adapters.HTTPAdapter):
    def __init__(self, timeout=None, *args, **kwargs):
        self.timeout = timeout
        super(TimeoutAdapter, self).__init__(*args, **kwargs)

    def send(self, *args, **kwargs):
        kwargs['timeout'] = self.timeout
        return super(TimeoutAdapter, self).send(*args, **kwargs)

s = requests.Session()
s.mount("http://", TimeoutAdapter(timeout=1337))
s.mount("https://", TimeoutAdapter(timeout=1337))

account = MyPlexAccount(args.account, args.password, session=s)
And the rest of your script.

````

**Comment by cburgard** [comment]
This seems to work. Very nice, thanks a lot! Would it be possible to add this to the documentation somewhere?

**Comment by Hellowlol** [comment]
I don’t think it worth it. They should google it or check any issues.
