### ISSUE TITLE
Some help with Optimize DB and CleanBundles.

### ISSUE THREAD

**Issue by DutchyOven** [pkkid/python-plexapi#559]
Just curious how should Cleanbundles and Optimize DB look?

when I do empty trash I write this...
`plex.library.section('Music').emptyTrash()`
and it works fine
But when I want to optimize or clean bundles I tried the ones below, by themselves in their own .py, it runs with no errors but I don't see Plex actually do anything.
```
plex.library.optimize()
plex.library.cleanBundles()
```

Am I writing this correctly? Should I see the little icon spinning like I do when I manually hit these?

**Comment by blacktwin** [comment]
Check your server console. I just ran the same commands and saw them immediately in the server console.

**Comment by DutchyOven** [comment]
Ok so yesterday I checked and you are correct it shows up in the console but it doesn't do anything.

When you press it in the UI and watch your database you'll see it chugging along optimizing and changing the size of your database. If you do it through plexapi, nothing db just sits there. 

If you have a second could you look at your db and see if it actually does anything.

**Comment by blacktwin** [comment]
Ok got it. Both methods need to be updated.

cleanBundles
`self._server.query('/library/clean/bundles?async=1', method=self._server._session.put)`

optimizeDB
`self._server.query('/library/optimize?async=1', method=self._server._session.put)`

**Comment by blacktwin** [comment]
@DutchyOven Can you please confirm the newest release resolves this issue? If so, please close.

**Comment by DutchyOven** [comment]
Ill update and check.

**Comment by DutchyOven** [comment]
Both working! Thanks a lot!
