### ISSUE TITLE
Can't determine how to get movie extras?

### ISSUE THREAD

**Issue by 13steinj** [pkkid/python-plexapi#564]
**Describe the issue**

The documentation makes note of a class `plex.video.Clip`, but I can't tell what this is for (movie extra?)

If not a movie extra, I can't find a way to get movie extras.

**Code snipppets**

```
server = PlexServer(...)
movie = server.library.section("Movies").all()[0]
# how to get movie extra?
```

**Expected behavior**
N/A / Extra is considered a Clip and it's not being found

**Enviroment (please complete the following information):**
 - OS: [e.g. Linux, Windows, Docker] Windows
 - Plex version [eg. version 1.19.3.2852] 1.20.something I don't believe it's relevant but if it is, just let me know where to find it
 - Python Version [e.g. 2.7.15, 3.6] 3.6.5
 - PlexAPI version [e.g. 3.6.0] 4.0.0

**Additional context**

If this is a case of just not being implemented, I'll gladly submit a full PR as long as a maintainer lets me know what features are wanted (besides the obvious regarding an object for the data).

Extras' response data is included in the film's XML response. Some extras are implemented as ones given from Plex with links to some external archive, so I don't know if those should be distinguished from plain extras on the filesystem or not.

**Comment by blacktwin** [comment]
#530 adds support for Extra, Reviews, and Online Media Sources (Tidal, etc.) Feel free to try it out.

**Comment by 13steinj** [comment]
#530 looks great, thanks! I'll check it out. Feel free to close, I'll leave it to you to decide whether to close this issue now or when that PR gets merged.
