### ISSUE TITLE
Playlist.addItems throws on empty list

### ISSUE THREAD

**Issue by jasmith79** [pkkid/python-plexapi#566]
**Describe the issue**
Creating an empty playlist throws an IndexError.

**Code snippets**
```python
# The relevant code from plexapi.playlist addItems method:
# line 95
uuid = items[0].section().uuid # IndexError thrown here, there is no check for empty list.
```

**Expected behavior**
The method should either be a no-op or throw a more meaningful error (e.g. asserting the input is a non-empty List/Tuple).

**Enviroment (please complete the following information):**
 - OS: MacOS Catalina
 - Plex version 1.20.1.3252
 - Python Version 3.8
 - PlexAPI version 4.1.0

Stumbled across this when someone [opened an issue about it](https://github.com/jasmith79/apple_playlist_plex_importer/issues/1#issuecomment-689255705) on my iTunes playlist importer.

**Comment by Hellowlol** [comment]
I think the exception is thats raised is pretty obvious. 

The create function documents the expected type. The line your referring to is add items. Isn’t unreasonable that adding a empty list raises a index error.

With that being said, if you want to make a PR for this go for it.

**Comment by jasmith79** [comment]
@Hellowlol [done](https://github.com/pkkid/python-plexapi/pull/567) and thanks, feel free to edit verbiage or change from assertion to a more appropriate error if desired. I didn't find a lot of custom errors in my quick search through the codebase so I went with that.

**Comment by blacktwin** [comment]
Please check other PRs #535 is very similar.
