### ISSUE TITLE
Thoughts on direct database access?

### ISSUE THREAD

**Issue by 13steinj** [pkkid/python-plexapi#568]
In my very short time using Plex, I have had issue after issue with cache / metadata / otherwise. For example just today all metadata retrieval broke. The only way I was able to fix it was by manually wiping the internal Metadata folder, and even then, it appears as though Plex has strange timing issues in regard to when things appear on the disk and when Plex retrieves them.

On the other hand, Plex's abilities to resolve / muck with the database aren't very robust. Quite literally, they only have an option for 2 buttons. 

If the database can be manually altered and/or accessed, then this python api can be improved if only by means of custom attributes being set. For example, People have for years wanted to [name their multi-version-movies](https://forums.plex.tv/t/having-multiple-versions-of-a-movie-how-to-show-version-when-pressing-play/605617), however current solutions are inadequate, On the other hand, one can manually edit the database as it is, adding a url-encoded string of `sr:target=NameOfVersion` to the extra_data column of the relevant version's `media_items` row, and setting the `proxy_type` to 42. Other transformations can be achieved as well,in a similar manner.

Given all of this, I was wondering if direct database/file access was within the scope of this package. I wanted to ask as to not step on any toes and just start making my own library for such tasks.

**Comment by Hellowlol** [comment]
Direct sql access is out of scope of the project. I’m sure others will find this useful so go a head and do your thing.
