### ISSUE TITLE
4.4.1 release broke compatibility with python <3.6

### ISSUE THREAD

**Issue by agaffney** [pkkid/python-plexapi#576]
**Describe the issue**

The `4.4.0` release worked fine on python 3.5 (included with Ubuntu Xenial), but the `4.4.1` release causes syntax errors. It's due to the format strings added in <https://github.com/pkkid/python-plexapi/commit/fb82bc402bd725220687b76c01a35008884b75ac>. These format strings were apparently added only for readability, not functionality, so they should be reverted to one of the older string formatting methods.

I would use an older release, but the latest version of `pychromecast` depends on the `4.4.1` release, and I need the fixes for playlists and playqueues in the latest versions of these.

**Code snippets**

```
$ ./chromecast.py 
Traceback (most recent call last):
  File "./chromecast.py", line 7, in <module>
    from plexapi.server import PlexServer
  File "/home/agaffney/.local/lib/python3.5/site-packages/plexapi/server.py", line 11, in <module>
    from plexapi import playlist as _playlist  # noqa: F401
  File "/home/agaffney/.local/lib/python3.5/site-packages/plexapi/playlist.py", line 8, in <module>
    from plexapi.playqueue import PlayQueue
  File "/home/agaffney/.local/lib/python3.5/site-packages/plexapi/playqueue.py", line 91
    f"{item} occurs multiple times in this PlayQueue, provide exact item"
                                                                        ^
SyntaxError: invalid syntax
```

**Expected behavior**

No syntax errors

**Enviroment (please complete the following information):**

N/A

**Additional context**

N/A

**Comment by agaffney** [comment]
I created #577 to fix this. It works locally with python 3.5 in basic tests

**Comment by jjlawren** [comment]
We can make a compatibility release for 3.5 but will require 3.6+ soon as 3.5 is already EOL as of this month.

**Comment by agaffney** [comment]
Even if 3.5 is EOL, there's no particular reason to explicitly break compatibility with it if you don't absolutely need 3.6+ features.

**Comment by jjlawren** [comment]
Yep and it wasn't intentional. However our CI setup is 3.6+ and it's easier to maintain with a smaller range of explicitly supported versions. We'll make a best effort to not break compatibility unless necessary.

**Comment by jjlawren** [comment]
Also note that `pychromecast` is 3.6+, so you may want to look into upgrading or creating a newer venv.

**Comment by agaffney** [comment]
With the changes in #577, the latest version of both works fine with Python 3.5.
