### ISSUE TITLE
Collection fields not pulling actual locked fields

### ISSUE THREAD

**Issue by rg9400** [pkkid/python-plexapi#587]
**Describe the issue**
When running `.fields` on a collection object, you get an empty list back (`[]`) each time, even if that collection does indeed have locked fields. Both the database and the XML display locked fields, so the bug seems to be isolated to plexapi

EDIT: I am using the latest commit version of plexapi from the `master` branch. When I downgraded to the last release (4.1.2), everything worked as intended.

**Code snipppets**
The below are different ways of pulling data for the same exact collection

From the Plex XML
```xml
<Field locked="1" name="summary"/>
<Field locked="1" name="thumb"/>
<Field locked="1" name="art"/>
```

From the DB
```
lockedFields=7|9|10
```

From the Plex Web UI
![image](https://user-images.githubusercontent.com/39887349/96646469-d2eb8200-12f1-11eb-9b37-78a43234b709.png)

From Python-PlexAPI
```python
>>> collections = plex.library.section("Movies").collection()
>>> collection = collections[0]
>>> collection.fields
[]
```

**Expected behavior**
`.fields` should give a list of fields that are locked for collection objects, like it does for other objects.

**Enviroment (please complete the following information):**
 - OS: plexapi on Windows 10, Plex in Docker
 - Plex version: 1.20.3.3437
 - Python Version: 3.9.0
 - PlexAPI version: 4.1.2 (commit 8ec0c4cf42b3e36e46d5f3504602b55c07eeb17d)

**Comment by JonnyWong16** [comment]
Bug caused by removal of `Field` from the list of `PLEXOBJECTS`.

3746b4ecb58a8e555ab852514609ae4ad8e3ee8b
