### ISSUE TITLE
API search function is different to the web interface function?

### ISSUE THREAD

**Issue by berrywhite96** [pkkid/python-plexapi#589]
I working with this API for about two weeks now and I noticed that the search results from the API differ to the ones from the Plex web interface.

For example: "Der Hobbit 1 - Eine unerwartete Reise"
On the web interface I found the movie, but the API does not. So I asked myself how to get the results from the web interface, because they seemed to be more accurate.

Enviroment (please complete the following information):
 - OS: Linux
 - Plex version: 4.12.3
 - Python Version: 3.8.6
 - PlexAPI version: ?

**Comment by Hellowlol** [comment]
What plexapi version are you using? Also post a code example. We use different search methods depending on what object you search from.

**Comment by berrywhite96** [comment]
> What plexapi version are you using? Also post a code example. We use different search methods depending on what object you search from.

`plex = PlexServer(URL, TOKEN)
result = plex.library.search(QUERY_TITLE)[0]`

I use the standard search function in the library module.

**Comment by blacktwin** [comment]
What plexapi version are you using?

```python
VERSION = '4.1.2'

plex.library.search('The Hobbit: An Unexpected Journey')
[<Movie:142:The-Hobbit:-An-Unexp>]


```

The web search may also include results from other servers. Using the `PlexServer` object isolates the search to the server and would not include search results from other shared servers.

**Comment by berrywhite96** [comment]
> What plexapi version are you using?
> 
> ```python
> VERSION = '4.1.2'
> 
> plex.library.search('The Hobbit: An Unexpected Journey')
> [<Movie:142:The-Hobbit:-An-Unexp>]
> ```
> 
> The web search may also include results from other servers. Using the `PlexServer` object isolates the search to the server and would not include search results from other shared servers.

I am using the newest version 4.1.2.
The search works also for me, but the movie title must be very specific. I want to match TMDB titles with titles in my library, so I need the results from the web interface search or maybe someone knows a different way.

**Comment by blacktwin** [comment]
It doesn't have to be specific but being more specific would reduce your results as it would be more accurate.
```python
plex.library.search('Hob')
[<Movie:142:The-Hobbit:-An-Unexp>, <Movie:161:The-Hobbit:-The-Batt>, <Movie:162:The-Hobbit:-The-Deso>, <Movie:163:Hobo-with-a-Shotgun>, <Album:48182:The-Hobbit>,...]
```

>  I want to match TMDB titles with titles in my library

Can you provide an example? Your initial example doesn't match the [TMDB title](https://www.themoviedb.org/movie/49051-the-hobbit-an-unexpected-journey?language=de).

**Comment by berrywhite96** [comment]
> It doesn't have to be specific but being more specific would reduce your results as it would be more accurate.
> 
> ```python
> plex.library.search('Hob')
> [<Movie:142:The-Hobbit:-An-Unexp>, <Movie:161:The-Hobbit:-The-Batt>, <Movie:162:The-Hobbit:-The-Deso>, <Movie:163:Hobo-with-a-Shotgun>, <Album:48182:The-Hobbit>,...]
> ```
> 
> > I want to match TMDB titles with titles in my library
> 
> Can you provide an example? Your initial example doesn't match the [TMDB title](https://www.themoviedb.org/movie/49051-the-hobbit-an-unexpected-journey?language=de).

That's correct, because it's the alternative title for german language. With the english title it is not possible to find movies in a german Plex library.

**Comment by Hellowlol** [comment]
Use plex.search as this is the closest to the web search.

**Comment by berrywhite96** [comment]
> Use plex.search as this is the closest to the web search. If you can’t find it that way you can search on other way. I’m pretty sure plex.search solves your problem

Thats it, it found the movie! Thank you thats exactly what I wanted, it seemed to be the exact same search as in the web interface.

Thank you all.
