### ISSUE TITLE
Can't connect to server on friend account.

### ISSUE THREAD

**Issue by Dr0bac** [pkkid/python-plexapi#593]
I can connect just fine with admin account (server owner). But if i try to connect to friend accout i get error:

```
Traceback (most recent call last):

  File "C:\Users\Boris\Desktop\proba.py", line 3, in <module>

    plex = account.resource('Plex').connect()

  File "C:\Users\Boris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\plexapi\myplex.py", line 963, in connect

    return _chooseConnection('Resource', self.name, results)

  File "C:\Users\Boris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\plexapi\myplex.py", line 1296, in _chooseConnection

    raise NotFound('Unable to connect to %s: %s' % (ctype.lower(), name))

plexapi.exceptions.NotFound: Unable to connect to resource: Plex
```

"Plex" is a server name. Both client and server are on local network.

**Comment by blacktwin** [comment]
Can you share the code snippet you're using? Does the friends account exist on the server and have a library shared?

**Comment by Dr0bac** [comment]
I just used the code from Readme page.

````
from plexapi.myplex import MyPlexAccount
account = MyPlexAccount('<USERNAME>', '<PASSWORD>')
plex = account.resource('<SERVERNAME>').connect()
````

Account that own server can connect to server, and friend cannot. Everything is on same local network.

Yes, server library is shared with friend account

![Untitled](https://user-images.githubusercontent.com/43797966/97538502-cb4a6e00-19c0-11eb-97c0-1a2b9e7e2745.png)

**Comment by blacktwin** [comment]
From the issue template, can you please provide the following:

- OS: [e.g. Linux, Windows, Docker]
- Plex version [eg. version 1.19.3.2852]
- Python Version [e.g. 2.7.15, 3.6]
- PlexAPI version [e.g. 3.6.0]

Can you sign in as the friend in the webUI to confirm the username and password?

**Comment by Dr0bac** [comment]
Server is on raspberry pi (Debian 10 Buster).
python-plexapi is on Windows 8.1 (I also installed python-plexapi on raspberry pi and tried there, but same error)
Plex Version is 1.20.3.3483 - up to date
Python version on Windows - 3.8.1
Python version on Debian - 3.7.3
plexapi version - 4.1.2

I can sign in as the friend in the webUI
![Untitled](https://user-images.githubusercontent.com/43797966/97578686-6f4c0d80-19f1-11eb-9887-58f3d6b875eb.png)

**Comment by blacktwin** [comment]
Can you share your plexapi.log? Preferably in a gist.

**Comment by Dr0bac** [comment]
Sorry, where does plexapi store log files? I don't see any information about log files in readme page

**Comment by blacktwin** [comment]
It can be found in the [documentation ](https://python-plexapi.readthedocs.io/en/latest/configuration.html)that is linked in the readme page. And unless changed it should be in the config path.

```python
# To find path
import plexapi
print(plexapi.CONFIG_PATH)
```

**Comment by Dr0bac** [comment]
I don't have config.ini generated on windows or raspberry pi. plexapi folder is not present. I tried to set the path of config.ini, but again no file is present. Tried the same steps with log file, without luck.

````
import plexapi                                                                  
PLEXAPI_CONFIG_PATH="/root/.config/plexapi/config.ini"                          
print(plexapi.CONFIG_PATH)                                                      
PLEXAPI_LOG_PATH="/tmp/plexapi.log"
````

**Comment by blacktwin** [comment]
By default it should be `~/.config/plexapi/`

**Comment by Dr0bac** [comment]
It's not there. Also on Windows `print(plexapi.CONFIG_PATH)` told me that config.ini is at `C:\Users\Boris\.config\plexapi\config.ini` again no plexapi folder there

**Comment by blacktwin** [comment]
On Windows the `.config` directory will be hidden. You would need to show hidden directories to see it. You could try changing the path in the [`__init__.py`](https://github.com/pkkid/python-plexapi/blob/master/plexapi/__init__.py#L12).

**Comment by Dr0bac** [comment]
Show hidden items is enabled.
So i tried on another windows 10 machine.
Python - 3.8.2
plexapi 4.1.2
Looked for config.ini in default location, than searched for it in "Search This PC"
Same result. Changed config path in __init__.py
Searched config.ini in "search This PC" no result again.
![init.png](https://user-images.githubusercontent.com/43797966/97779791-d3510c00-1b80-11eb-9426-7dc063aaaf0e.png)

![proba.png](https://user-images.githubusercontent.com/43797966/97779796-d77d2980-1b80-11eb-8d7e-03bb40bf3477.png)

![folder.png](https://user-images.githubusercontent.com/43797966/97779800-da781a00-1b80-11eb-920c-1729431cf76f.png)

**Comment by Hellowlol** [comment]
The config file needs to be created by the user.
Anyway you can use logging and just grab the console output.

Add this at the top of your script:

import logging
logging.basicConfig(level=logging.DEBUG)

**Comment by Dr0bac** [comment]
````
boki@DietPi:~# python3 proba.py                                                 DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): plex.tv:443
DEBUG:urllib3.connectionpool:https://plex.tv:443 "POST /users/sign_in.xml HTTP/1.1" 201 None
DEBUG:urllib3.connectionpool:https://plex.tv:443 "GET /api/resources?includeHttps=1&includeRelay=1 HTTP/1.1" 200 None
INFO:plexapi:Testing 0 resource connections..
Traceback (most recent call last):
  File "proba.py", line 7, in <module>
    plex = account.resource('Plex').connect()
  File "/usr/local/lib/python3.7/dist-packages/plexapi/myplex.py", line 963, in connect
    return _chooseConnection('Resource', self.name, results)
  File "/usr/local/lib/python3.7/dist-packages/plexapi/myplex.py", line 1296, in _chooseConnection
    raise NotFound('Unable to connect to %s: %s' % (ctype.lower(), name))
plexapi.exceptions.NotFound: Unable to connect to resource: Plex
````

**Comment by blacktwin** [comment]
`INFO:plexapi:Testing 0 resource connections..` Looks like that account has no servers shared, remote access is disabled or blocked, or the server is otherwise unavailable.

**Comment by Dr0bac** [comment]
I'm testing plexapi from the same server where plex server is installed, i tried with both remote access enabled and disabled.. plex server is shared properly, i can see that from plex web when i login into that friend account.. can you please try to replicate this? Can you make new account and share library to it and try to connect to that new account with plexapi?

**Comment by grogcw** [comment]
Hi ! same bug here :

I'm on OSX, Python@3.9.0, latest plexapi@4.2.0, and I can't login on my server.

I tried from a local or a distant point of view (I have a domain name attached to it), and neither http://192.168.0.XX:32400 nor http://mydomain.com:32400 calls work.

All dependencies are checked and installed, python3 works fine, osx is.....buggy as an OSX can be (but runs smoothly).

The snippet I want to run is :

`from plexapi.myplex import MyPlexAccount
from plexapi.server import PlexServer

account = MyPlexAccount('<mymail>', '<mypass>')
plex = account.resource(''http://<my_ip_or_domain:32400).connect()

movies = plex.library.section('Movies')
for video in movies.search(unwatched=True):
    print(video.title)
`

Am I missing something here ?

**Comment by blacktwin** [comment]
@Dr0bac I have a separate account that I've tested and can connect without issue.
```python
from plexapi.myplex import MyPlexAccount
account = MyPlexAccount('<USERNAME>', '<PASSWORD>')
print(vars(user_account))
print(account.resources())
```

@grogcw You select the resource by the server's name not IP.  See the snippets used above and found in the readme.

**Comment by Dr0bac** [comment]
with `print(vars(user_account))`  i got 
````
    print(vars(user_account))
NameError: name 'user_account' is not defined
````
after changing `(user_account)` to `(account)` it worked

````
{'_token': 'xxxxxxx', 
'_session': <requests.sessions.Session object at 0x766d74b0>, 
'_sonos_cache': [], 
'_sonos_cache_timestamp': 0, 
'_server': <MyPlexAccount:44226431:Test-Vesna>, 
'_data': <Element 'user' at 0x75d64510>, 
'_initpath': 'https://plex.tv/users/sign_in.xml', 
'_details_key': '', 
'_webhooks': [], 
'authenticationToken': 'xxxxxxx', 
'certificateVersion': '3', 
'cloudSyncDevice': '', 
'email': 'testvesna123@gmail.com', 
'guest': False, 
'home': False, 
'homeSize': 1, 
'id': '44226431', 
'locale': 'en', 
'mailing_list_status': 'unsubscribed', 
'maxHomeSize': 15, 
'queueEmail': 'queue+u5WWUxMyrxwQnhFGwxnr@save.plex.tv', 
'queueUid': '', 
'restricted': False, 
'scrobbleTypes': '', 
'secure': True, 
'thumb': 'https://plex.tv/users/081b455c5e24d472/avatar?c=1602250015', 
'title': 'Test Vesna', 
'username': 'Test Vesna', 
'uuid': '081b455c5e24d472', 
'subscriptionActive': False, 
'subscriptionStatus': 'Inactive', 
'subscriptionPlan': '', 
'subscriptionFeatures': ['home', 'adaptive_bitrate', 'collections', 'photos-metadata-edition', 'radio', 'tuner-sharing', 'photos-favorites', 'federated-auth', 'livetv', 'Android - PiP', 'unsupportedtuners', 'kevin-bacon', 'client-radio-stations', 'TREBLE-show-features', 'web_server_dashboard', 'conan_redirect_qa', 'conan_redirect_alpha', 'conan_redirect_beta', 'conan_redirect_public', 'news_local_now', 'transcoder_cache', 'live-tv-support-incomplete-segments', 'companions_sonos', 'exclude restrictions', 'signin_with_apple', 'drm_support', 'Android - Dolby Vision', 'spring_serve_ad_provider', 'conan_redirect_nightlies', 'conan_redirect_nightly', 'watch-together-invite', 'ios14-privacy-banner', 'amazon-loop-debug', 'vod_cloudflare'], 
'roles': [], 
'entitlements': [], 
'profile_settings': None, 
'services': None, 
'joined_at': None}

[<MyPlexResource:Plex>]
````

**Comment by blacktwin** [comment]
Sorry that was my variable name I was using. So now your server is showing as a resource. Can you now `.connect()` to it?

**Comment by grogcw** [comment]
Ok, I've figured this out myself.

In the server field, you need to put the ressource name.

In your case @Dr0bac, you'll need to specify "Plex", as your ressources statement is "[<MyPlexResource:Plex>]".

Cheers !

**Comment by Dr0bac** [comment]
I tried to enable remote access again on server, still nothing. Then I enabled relay setting in Network tab, and when i tried to connect it worked. Then i disabled remote access and again it didnt work.  When remote access and relay are enabled it is working, but very slow, here is output..

````
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): plex.tv:443
DEBUG:urllib3.connectionpool:https://plex.tv:443 "POST /users/sign_in.xml HTTP/1.1" 201 None
DEBUG:urllib3.connectionpool:https://plex.tv:443 "GET /api/resources?includeHttps=1&includeRelay=1 HTTP/1.1" 200 None
INFO:plexapi:Testing 4 resource connections..
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 79-101-87-221.cbf0739231f746e784dba7b00fe3f6de.plex.direct:32400
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 139-162-175-123.cbf0739231f746e784dba7b00fe3f6de.plex.direct:8443
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 79.101.87.221:32400
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 139.162.175.123:8443
ERROR:plexapi:http://139.162.175.123:8443: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
DEBUG:urllib3.connectionpool:https://139-162-175-123.cbf0739231f746e784dba7b00fe3f6de.plex.direct:8443 "GET / HTTP/1.1" 200 2476
ERROR:plexapi:http://79.101.87.221:32400: HTTPConnectionPool(host='79.101.87.221', port=32400): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x75df6bd0>, 'Connection to 79.101.87.221 timed out. (connect timeout=30)'))
ERROR:plexapi:https://79-101-87-221.cbf0739231f746e784dba7b00fe3f6de.plex.direct:32400: HTTPSConnectionPool(host='79-101-87-221.cbf0739231f746e784dba7b00fe3f6de.plex.direct', port=32400): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x75df6530>, 'Connection to 79-101-87-221.cbf0739231f746e784dba7b00fe3f6de.plex.direct timed out. (connect timeout=30)'))
INFO:plexapi:Resource connection ERR (30s): https://79-101-87-221.cbf0739231f746e784dba7b00fe3f6de.plex.direct:32400?X-Plex-Token=<hidden>
INFO:plexapi:Resource connection OK (0s): https://139-162-175-123.cbf0739231f746e784dba7b00fe3f6de.plex.direct:8443?X-Plex-Token=<hidden>
INFO:plexapi:Resource connection ERR (30s): http://79.101.87.221:32400?X-Plex-Token=<hidden>
INFO:plexapi:Resource connection ERR (0s): http://139.162.175.123:8443?X-Plex-Token=<hidden>
INFO:plexapi:Connecting to Resource: https://139-162-175-123.cbf0739231f746e784dba7b00fe3f6de.plex.direct:8443?X-Plex-Token=<hidden>
````

I don't use plex outside of my house (local network). Is there a way for friend account to see plex server without enabling remote access? I don't like to open ports to my network. Maybe some option in Network tab must be changed?

**Comment by grogcw** [comment]
@Dr0bac try this snippet filling the correct mail and passwd:

```
from plexapi.myplex import MyPlexAccount
account = MyPlexAccount('testvesna123@gmail.com', '<PASSWORD>')
plex = account.resource('Plex').connect()
```

**Comment by Dr0bac** [comment]
@grogcw yes it is working like i said in post before yours. But it is only working when i enable remote access (open my network port - 32400) and i'm accessing server 'Plex' from the same machine. I guess your server is also remote enabled?

**Comment by grogcw** [comment]
Yes, my server is remote access enabled, and I think it's a prerequisite for the api to access the server from mail accounts.

A wild guess of mine : You can try to pass the token like in the main page's exemple to see if your server accepts it locally only.

**Comment by blacktwin** [comment]
@Dr0bac  `MyPlexAccount` connects to Plex first, just like when you use `plex.tv`. Then it looks for the server. If you want to connect directly to your server with from a friends account you can use this snippet.

```python
plex = PlexServer(PLEX_URL, PLEX_TOKEN)  # Admin token
account = plex.myPlexAccount()
user_acct = account.user('USERNAME') # Friend's username
user_plex = PlexServer(PLEX_URL, user_acct.get_token(plex.machineIdentifier))
```

> `INFO:plexapi:Testing 0 resource connections..` Looks like that account has no servers shared, **_remote access is disabled_** or blocked, or the server is otherwise unavailable.

I mentioned remote access [before](https://github.com/pkkid/python-plexapi/issues/593#issuecomment-720480284). Some more information about accounts and tokens can be found in that same thread, [here](https://github.com/pkkid/python-plexapi/issues/393#issuecomment-545576414).

**Comment by Dr0bac** [comment]
Thank you @blacktwin 

For people who will search for similar questions in future:

First you need to find out server account token with:
````
from plexapi.myplex import MyPlexAccount
account = MyPlexAccount('<USERNAME>', '<PASSWORD>')   # Server Account username and password
plex = account.resource('<SERVERNAME>').connect()
print(vars(account))  # here you will find token
````
After that you can connect to the server that is shared with:
````from plexapi.server import PlexServer

PLEX_URL = 'http://plexserver_ip:32400'
PLEX_TOKEN = 'xxxxxxxxxxxxxxxxxxxxxx'  # token that you obtained from the server account

plex = PlexServer(PLEX_URL, PLEX_TOKEN)
account = plex.myPlexAccount()
user_acct = account.user('<USERNAME>') # Friend's username
user_plex = PlexServer(PLEX_URL, user_acct.get_token(plex.machineIdentifier))
````

**Comment by blacktwin** [comment]
Plex also provides an [article ](https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/)for how to find your token. Safe to close?

**Comment by Dr0bac** [comment]
Yes you can close it. Thank you again for your help.
