### ISSUE TITLE
No Option to Search by Audio or Subtitle Language

### ISSUE THREAD

**Issue by tkdrob** [pkkid/python-plexapi#599]
**Describe the issue**
Plex GUI allows search by Audio and Subtitle Language. This library does not currently offer that. 

**Expected behavior**
I use Home-assistant with Node-Red. I'd like to use this to return results with non-English material to automate the removal of foreign language streams with mkvtoolnix. 

**Enviroment (please complete the following information):**
 - OS: Docker
 - Plex version 1.20.5.3562
 - Python Version 3.8
 - PlexAPI version 4.1.1

**Comment by blacktwin** [comment]
It does in the latest release ([4.2.0](https://github.com/pkkid/python-plexapi/releases)).

```python
movies= plex.library.section("Movies")
print(len(movies.search(**{'audioLanguage': 'eng'})))
print(len(movies.search(**{'subtitleLanguage': 'eng'})))
print(len(movies.search(**{'audioLanguage!': 'eng'}))) # not eng
print(len(movies.search(**{'subtitleLanguage!': 'eng'}))) # not eng
```

**Comment by tkdrob** [comment]
Ok Thanks. Looks like @jjlawren is hard at work in getting HA to use it.

**Comment by jjlawren** [comment]
> Ok Thanks. Perhaps @jjlawren is hard at work in getting HA to use it. 

Not sure what you mean in the context of this issue?

**Comment by Hellowlol** [comment]
I would use appdaemon for this. That way you can use plexapi directly.
