### ISSUE TITLE
[help wanted] editing title, summary, and other metadata

### ISSUE THREAD

**Issue by bobbintb** [pkkid/python-plexapi#600]
I'm not sure if this is possible or I just can't seem to find it or figure it our from the documentation. I am trying to edit certain data from an item in the Plex library, such as video title, summary, actors, etc. Is this possible currently?

**Comment by blacktwin** [comment]
There should be plenty of examples in the Issues section and the documentation. What have your tried? Can you provide a code snippet? You've also not followed the Issue template, what version are you currently using for PlexAPI?

**Comment by bobbintb** [comment]
I hadn't really tried anything because I couldn't find anything in the documentation or issues for that specific item. I did eventually come up with the right key words and found a solution:
https://github.com/pkkid/python-plexapi/issues/479
