### ISSUE TITLE
2FA and myplex

### ISSUE THREAD

**Issue by ecov773** [pkkid/python-plexapi#609]
Hi,
Since the activation of the 2FA, the myplex is not working (understandably). Could you provide an alternative in plexapi to be able to get the playlists from myplex with 2FA enabled? I think that Plex has not enabled application passwords, right?
Thanks
Eric

**Comment by jjlawren** [comment]
Once you've obtained a token it will continue to work without an additional 2FA step.

**Comment by ecov773** [comment]
Thanks! I found also this link https://support.plex.tv/articles/two-factor-authentication/ that says that you can add the totp code at the end of your password.

Thanks

**Comment by jjlawren** [comment]
Good to know, thanks for sharing.
