### ISSUE TITLE
Displaying Photos in Nested Photoalbums

### ISSUE THREAD

**Issue by cmoulikus** [pkkid/python-plexapi#62]
I have photo album A which has two sub albums B and C. All the jpegs are inside B and C. How do I get plexapi to display photos in nested albums. It shows up fine in plex web client.

**Comment by cmoulikus** [comment]
I think I need to recurse on items returned by album.photos() to get nesting right. How do I know if the item returned by album.photos() is a photo or a photoalbum?

**Comment by pkkid** [comment]
Merging "Ability to Play Nested Photo Albums" request into this one. Not sure it can be done, but lets include the research or work as part of this bug as well.

**Comment by pkkid** [comment]
commit d41bf0fb898d5f3cafd8801a2dd8f50e9b4a55ca
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Sun Feb 26 00:17:41 2017 -0500
Add support to recursivly navigate photoalbums
