### ISSUE TITLE
search() mediatype filter BROKEN

### ISSUE THREAD

**Issue by TheRealVincentVanGogh** [pkkid/python-plexapi#621]
**Describe the issue**
plexapi.server.search()'s mediatype filter perameter has no effect.

**Code snipppets**
```
for media in plex.search("Wonder", mediatype='track', limit=1):
# Sample Output:
<Album:1910:Wonder>
<Track:1911:Wonder>
<Artist:645:Oh-Wonder>
```

**Expected behavior**
I expected only tracks to be outputed.
Ex:
```
<Track:1911:Wonder>
```

**Enviroment (please complete the following information):**
 - OS: Windows
 - Plex version 1.21.0.3711
 - Python Version 3.6
 - PlexAPI version 4.2.0

**Comment by Hellowlol** [comment]
This method just returns what ever response it gets from plex.

**Comment by TheRealVincentVanGogh** [comment]
Oh alright, I guess it's a problem on Plex's end then.
