### ISSUE TITLE
Support Casting to Chromecast

### ISSUE THREAD

**Issue by cmoulikus** [pkkid/python-plexapi#63]
Hi
My android smartphone client is connected to the plex media server.  It is ready to display media. When I use the Python plex api to play media using client.playMedia(item),  items displays correctly on my client screen. 

But I am unable to cast it on another screen using Chromecast. When I try casting, it tries and gives up.
All other content like youtube etc. Iam able to cast. It is only items playing via the Python API, I am not able to cast.

Any ideas?

**Comment by cmoulikus** [comment]
I have a come long way, thanks to Michael. There was time when nothing was working for me. Now I am stuck on the last part: how to chrome cast what is dispalying on the client using the cleint.playMEdia(item) call.

**Comment by mjs7231** [comment]
[This Reddit post](https://www.reddit.com/r/PleX/comments/4w0nh0/can_you_play_to_chromecast_through_the_http_api/?st=irk11ytq&sh=859fb45b) doesn't make it sound promising for the Chromecast. -- I believe we would need it to show up in the clients list to even think about getting it to work.

**Comment by mjs7231** [comment]
Marking this as an enhancement.  If the Plex Web Client and cast to a Chromecast, maybe we can add a new function to cast as well.

**Comment by mjs7231** [comment]
I just ordered a Chromecast, excited to make this one work. :P

**Comment by cmoulikus** [comment]
Great let me know how it works out.

-------- Original message --------

**Comment by Hellowlol** [comment]
https://github.com/balloob/pychromecast

**Comment by pkkid** [comment]
Interesting.  I was hoping we could add Chromecast support by calling some URL on the Plex Media Server, but that doesn't seem to be the case. When we connect to a Chromecast from the webapp, there is no ajax request sent anywhere, and it all seems to be handled via JS & Chrome Browser. This is also spit out in the logs, which may be useful:

```json
[Cast] Session: {"sessionId":"70f76413-f64e-4656-8f4e-43489c2766f3","appId":"9AC194DC","displayName":"Plex","statusText":"Plex","receiver":{"label":"rRckpLGcPLvz4_hkCyoxuFkBPANk.","friendlyName":"Chromecast3683","capabilities":["video_out","audio_out"],"volume":{"controlType":"attenuation","level":1,"muted":false,"stepInterval":0.05000000074505806},"receiverType":"cast","isActiveInput":null,"displayStatus":null},"senderApps":[],"namespaces":[{"name":"urn:x-cast:com.google.cast.broadcast"},{"name":"urn:x-cast:com.google.cast.media"},{"name":"urn:x-cast:plex"}],"media":[],"status":"connected","transportId":"70f76413-f64e-4656-8f4e-43489c2766f3"}
```

**Comment by pkkid** [comment]
Looks like some other people got this working..
https://forum.xda-developers.com/android-tv/chromecast/plex-python-chromecast-t3520651

**Comment by Hellowlol** [comment]
Can you make a official guide on how to make this work or does the example above work? I don't have chromecast. We could add it to the utility file with a inline import

**Comment by Hellowlol** [comment]
@pkkid Did you figure out how to cast somthing at chromecast?

**Comment by pkkid** [comment]
I never ended up trying.

**Comment by Hellowlol** [comment]
I got this working. Ill post an example and create a PR later👍

**Comment by pkkid** [comment]
Awesome, excited to try it out.

**Comment by Hellowlol** [comment]
You can use this branch to test support for chromecast. https://github.com/pkkid/python-plexapi/tree/chromecast

pychromecast does have some deps and are 3.4 only so dunno if we should merge it.

**Comment by aazimh** [comment]
@Hellowlol just wanted to say I've been breaking my head over this for weeks and just stumbled on to this and managed to get your PR working - thank you so much!

**Comment by Hellowlol** [comment]
@aazimh your welcome. Thanks for testing it

**Comment by aazimh** [comment]
@Hellowlol Okay, on some further testing maybe things aren't all that perfect :) it appears to work fine if the Plex Chromecast app is already up and running - however, if something else is casting, or even if the Chromecast is idle, all I get is the Plex splash screen saying 'ready to play', but the media in question doesn't end up playing.

I've tried reading through your code to debug it, but don't think I can be much help. All I can think of is adding some sort of delay between launching the Plex app and actually sending the play media command? I tried doing this myself but it looks like the 'play_media' command is what actually launches the app so not possible to add a delay anywhere.

Hope this is useful information for debugging!

**Comment by aazimh** [comment]
This is my code - `selection` is the result of a search, and `cast` is my Chromecast (these assignments have been done already):

```
cast.wait()
pc = PlexController()
cast.register_handler(pc)
cast.wait()
pc.play_media(selection)
```

I know I have an extra `wait()` since I thought that might help the Chromecast get ready to receive the play command, but it doesn't seem to make a difference.

**Comment by Hellowlol** [comment]
My example don’t handle this. That up the user. You can check if the current running app is plex, if not you can launch the app manually then do the play_media. I thought chromecast should handle the running app. Have try tried enabling som logging so you see what happens?

**Comment by Hellowlol** [comment]
I’m only on mobile atm but is seems like it it’s a bug in the pychomecast send_message, the call_back isn’t used.

**Comment by aazimh** [comment]
So I had some time to dig into this today and I think I have a hacky solution. I used your tip of checking the current app - if it is Plex already, I just use `play_media` normally. If not, then I start the app manually, wait 5 seconds (seems to be enough time for it to become ready) and then `play_media` and it works :) code below in case it helps:

```
		if cast.status.display_name == 'Plex':
			pc = PlexController()
			cast.register_handler(pc)
			pc.play_media(selection)
		else:
			cast.start_app('9AC194DC')
			pc = PlexController()
			cast.register_handler(pc)
			cast.wait()
			time.sleep(5)
			pc.play_media(selection)
```
I know you mentioned it being a bug in pychromecast not using a callback, and I tried looking into that but it went over my head :) if you're able to crack that I'd be more than happy to test out.

**Comment by pkkid** [comment]
If you ask for the `cast.status.display_name` in a loop, will it eventually say 'Plex' when it's ready?

**Comment by aazimh** [comment]
@pkkid Great suggestion :) it's definitely ready in less than 5 seconds so this works a lot better! Code below, but if there's a better way to loop let me know - thanks again for the tip!

```
		if cast.status.display_name == 'Plex':
			pc = PlexController()
			cast.register_handler(pc)
			pc.play_media(selection)
		else:
			cast.start_app('9AC194DC')
			pc = PlexController()
			cast.register_handler(pc)
			current_app = cast.status.display_name
			while current_app != 'Plex':
				current_app = cast.status.display_name
				time.sleep(1)
			pc.play_media(selection)
```

**Comment by Hellowlol** [comment]
I’m sure there is a better way to do this. I’ll looking into it when I try to recreate the launch issue.

**Comment by Hellowlol** [comment]
I have updated the branch with a new method called block_until_playing use this one if you want to ensure that the your program does not exit until the callback is done.

**Comment by Hellowlol** [comment]
Closing this a my PR was merged in pychromecadt
