### ISSUE TITLE
feature request: fuzzy matching

### ISSUE THREAD

**Issue by cburgard** [pkkid/python-plexapi#637]
I'm trying to write a script to synchronize my playlists from two different plex servers. However, I'm having trouble because of some metadata differences:
- capitalization is different ("Word up" vs. "Word Up")
- additional punctuation ("Word Up" vs "Word Up!")
- libraries use different types of apostrophes (single quotes) (' vs. ’)
- some spaces are present or not ("Evacute the Dance Floor" vs. "Evacuate the Dancefloor")
- some tracks contain additional text like "(radio edit)"
- perhaps other minute differences

To resolve this, it would be really nice to support a "fuzzy search" for artist/album/track names. Perhaps this is supported already, as the Plex WebUI can successfully find tracks also when using wrong capitalization and/or wrong apostrophes, but I can't find how to do this with the python API.

Is this supported already, and I just don't find it, or would this need to be added somewhere?

**Comment by Hellowlol** [comment]
It isn’t. Or you can use search that uses fuzzy weqch from the server, but that isnt what your looking for. Just use a Python package to handle this. Ex fuzzywuzzy

**Comment by blacktwin** [comment]
What are you trying to synchronize? If you both servers have the same content and same library agents then using the `guid` would help with exact matching. Please share your project when you can, sounds cool.

**Comment by cburgard** [comment]
Thanks for the replies!
I have several Plex servers that I try to keep in sync (locally on my laptop, locally in my home, and a remote server). The files themselves can be synced easily with `rsync`, but the playlists seem to be less compliant, as the absolute paths of the files are not identical.
I'm still trying to figure out what to do exactly, but here's the repo with my code. I was originally using GoogleMusic and am still in the process of migrating things to Plex. The code is 100% my own, so please feel free to steal any code if you find it useful.
https://gitlab.com/cburgard/python-music-tools

**Comment by Hellowlol** [comment]
Silly question, but why use the absolute paths of the files? Do you have control over all the servers (remote and local) Just asking since i don't understand why you use different server. What's the point?

BTW: if  `Casa?a89` is your password you should change it.

**Comment by Hellowlol** [comment]
As for syncing item you might want to look into https://github.com/andrey-yantsen/plexiglas

**Comment by cburgard** [comment]
> Silly question, but why use the absolute paths of the files? Do you have control over all the servers (remote and local) Just asking since i don't understand why you use different server. What's the point?
> 
> BTW: if XXX is your password you should change it.

Thanks for the pointer, I changed it and removed the mention in the file. Please also edit it out of your post, just in case I accidentally use the same password for another service somewhere (I honestly don't know, so let's not make this all too easy).

**Comment by cburgard** [comment]
> As for syncing item you might want to look into https://github.com/andrey-yantsen/plexiglas

thanks for the pointer, I'll look into this (even though I don't fully understand yet what that package intends to do)
