### ISSUE TITLE
[DOC] Small typo

### ISSUE THREAD

**Issue by reloxx13** [pkkid/python-plexapi#640]
See see

![grafik](https://user-images.githubusercontent.com/14855001/104050873-912ef100-51e7-11eb-962c-767b815e3531.png)

https://python-plexapi.readthedocs.io/en/latest/modules/library.html#plexapi.library.LibrarySection.analyze

https://github.com/pkkid/python-plexapi/blob/e62d9970f0704593257e6d443c52bd78d91f825e/plexapi/library.py#L561-L562

**Comment by Hellowlol** [comment]
Open a PR for this 👍
