### ISSUE TITLE
No clients found

### ISSUE THREAD

**Issue by nerdefierodiesserlo** [pkkid/python-plexapi#644]
hi i have a problem using clients() function
i don't get any clients, just an empty list...everything is inside my network
This is my simple code

```
from plexapi.server import PlexServer
token = 'xxxxxxxxxxxxxxxxxxx'
baseurl = 'http://192.168.1.114:32400'
plex = PlexServer(baseurl, token)
print(plex.clients())
```

is there any option to activate on plex?
I m using PMS on Raspberry (raspbian + docker), i don't know maybe there are some limitations with this configuration

**Comment by jjlawren** [comment]
This endpoint only returns actively running Plex clients that respond to GDM broadcasts from the PMS instance. These broadcasts will not cross subnets unless you have a UDP repeater or similar in place. This may also be blank if you've disabled GDM discovery in PMS.

**Comment by nerdefierodiesserlo** [comment]
thanks, i guess i understand the problem....chrome based client and plex plugin (for kodi) not working...probably there is no compatibility, instead i tried to use plex client for windows and it is worked like a charm.
I can close
