### ISSUE TITLE
Title name cut

### ISSUE THREAD

**Issue by mibj** [pkkid/python-plexapi#645]
Hi 
Why Do I get media title 'cut' ?

`plex = PlexServer(baseurl, token)
px_Section = plex.library.sectionByID(sectionID).all()
print ('\n'.join(map(str,px_Section)))`
output:
`<Show:88714:Dirk-Gently's-Holist>` , but the real title is : Dirk Gently's Holistic Detective Agency

There are others example here, maybe I missed something ?
Thank
Have a nice day Pkkid

**Comment by Hellowlol** [comment]
Your printing the repr of the object. If you need the title. Print the title

**Comment by mibj** [comment]
Sry , I read the doc but How Do I get that title from the 'plex.library'
Thank Hellolol

**Comment by mibj** [comment]
I did this
 px_Section = plex.library.section("TV")
    for video in px_Section.search('Dirk Gently's Holistic Detective Agency'):
            print(video.title)`
`
or
`
for video in plex.search('Game'):
    print('%s (%s)' % (video.title, video.TYPE))
`
but I already know the title .
When you don't know what media there are in the library How Do you print every media title ?Thank

**Comment by Hellowlol** [comment]
```
for show in plex.library.section("TV"):
    print(show.title)
    for episode in show.episodes():
        print(episode.seasonEpisode)
```

Read the docs at https://python-plexapi.readthedocs.io/en/latest/modules/video.html

**Comment by mibj** [comment]
Thanks Hellowlol
