### ISSUE TITLE
Modification of track mood of items in playlist

### ISSUE THREAD

**Issue by YoonAddicting** [pkkid/python-plexapi#646]
**Describe the issue**
I am trying to make a script that applies a given mood too all duplicate tracks in a smart playlist, because of the behavior Plex enforces on tracks (identical tracks share rating, so all copies of the same track is added to the smart playlist).
I've managed to get the mood tag by grabbing it from another song. I was wondering if there is any way to search the moods Plex recognizes, so you won't have to perform that workaround?

I am also having issues actually applying the moods to the tracks. I manage to grab the existing moods, add the mood signifying the duplicate, but nothing happens when I use the edit function.

**Code snipppets**
Current method for getting the wanted mood tag:
```python
playlist = plex.playlist("Duplicate Playlist")
for track in playlist.items():
    duplicateMood = track.moods[0]
```
Current method for saving the moods to the track:
```python
print("Applying mood to duplicates...")
for track in duplicateTracks:
    item = plex.fetchItem(track.ratingKey)
    existingMoods = item.moods
    existingMoods.append(duplicateMood)
    test = {"moods": existingMoods}
    item.edit(**test)
```

**Expected behavior**
I expected the script to save the tracks with the added mood, thus removing them from the smart playlist when it is set to exclude tracks with the given mood.

**Enviroment (please complete the following information):**
 - OS: Windows 10
 - Plex version: Version 1.21.1.3876
 - Python Version: 3.9
 - PlexAPI version: 4.2.0

**Comment by Hellowlol** [comment]
You don't have code example from the rest of the list. But remember that the playlist is static. You need to reload it to see any changes.

**Comment by YoonAddicting** [comment]
Here is the script in it's entirety:
```python
account = MyPlexAccount('REDACTED', 'REDACTED')
plex = account.resource('REDACTED').connect()  # returns a PlexServer instance

# Get the mood tag corrosponding to the name "Duplicate"
playlist = plex.playlist("Duplicate Playlist")
for track in playlist.items():
    duplicateMood = track.moods[0]
    
# Get the playlist to remove duplicates from
playlist = plex.playlist("TestDeduplication")

uniqueTracks = []
duplicateTracks = []

for track in playlist.items():
    if(any(t.guid == track.guid for t in uniqueTracks)):
        duplicateTracks.append(track)
    else:
        uniqueTracks.append(track)

print("Unique tracks:")
for track in uniqueTracks:
    #print(f'{track.title} - {track.parentTitle} - {track.guid}')
    pass

print("Duplicate tracks:")
for track in duplicateTracks:
    #print(f'{track.title} - {track.parentTitle} - {track.guid}')
    pass

print("Applying mood to duplicates...")
for track in duplicateTracks:
    item = plex.fetchItem(track.ratingKey)
    existingMoods = item.moods
    existingMoods.append(duplicateMood)
    test = {"moods": existingMoods}
    item.edit(**test)
```

I am attempting to confirm whether this works by simply inspecting the tags on the tracks on Plex, and no change is to be seen there at all.

**Comment by Hellowlol** [comment]
If you use reload on a item you should see changes to that object, it will still be a part the playlist tho as this playlist needs to be reloaded.

```python
account = MyPlexAccount('REDACTED', 'REDACTED')
plex = account.resource('REDACTED').connect()  # returns a PlexServer instance

# Get the mood tag corrosponding to the name "Duplicate"
playlist = plex.playlist("Duplicate Playlist")
for track in playlist.items():
    duplicateMood = track.moods[0]
    
# Get the playlist to remove duplicates from
playlist = plex.playlist("TestDeduplication")

uniqueTracks = []
duplicateTracks = []

for track in playlist.items():
    if(any(t.guid == track.guid for t in uniqueTracks)):
        duplicateTracks.append(track)
    else:
        uniqueTracks.append(track)

print("Unique tracks:")
for track in uniqueTracks:
    #print(f'{track.title} - {track.parentTitle} - {track.guid}')
    pass

print("Duplicate tracks:")
for track in duplicateTracks:
    #print(f'{track.title} - {track.parentTitle} - {track.guid}')
    pass

print("Applying mood to duplicates...")
for track in duplicateTracks:
    item = plex.fetchItem(track.ratingKey)
    existingMoods = item.moods
    existingMoods.append(duplicateMood)
    test = {"moods": existingMoods}
    item.edit(**test)

playlist.reload()
for i in playlist:
    for dup in duplicateTracks:
       if i.guid == dup.guid:
           print("dup still exist")
```

**Comment by YoonAddicting** [comment]
Alright so managed to figure out what was going wrong by inspecting some requests to the website by changing the mood manually and found out that the correct way to do it is with the following snippet of the loop:
```python
for track in duplicateTracks:
    data = {}
    count = 0
    data["mood.locked"] = 1
    for mood in track.moods:
            data["mood[" + str(count) + "].tag.tag"] = mood.tag
            count += 1
    data["mood[" + str(count) + "].tag.tag"] = "Duplicate"
    track.edit(**data)
    track.reload()
```
In other words, the correct way to set the mood is: `mood[INDEX].tag.tag`.
The above snippets add the tag "Duplicate" to the current list of mood tags and saves it.

**Comment by JonnyWong16** [comment]
PlexAPI has a tag helper.

```python
from plexapi.utils import tag_helper

for track in duplicateTracks:
    exiting_moods = [mood.tag for mood in track.moods]
    data = tag_helper("mood", exiting_moods + ["Duplicate"])
    track.edit(**data)
    track.reload()
```
