### ISSUE TITLE
Exception error when parentKey is unset in episode metadata

### ISSUE THREAD

**Issue by katekyonni** [pkkid/python-plexapi#655]
**Describe the issue**
I opened an issue at another repo that is using Python-PlexAPI and they recommended I report this here.
This log should help figure out if this is a bug: 
[_plexanisync_logs 21-02-04.txt](https://github.com/pkkid/python-plexapi/files/5929072/_plexanisync_logs.21-02-04.txt)

Please check out the issue for more details: https://github.com/RickDB/PlexAniSync/issues/47

**Expected behavior**
I'm using a different metadata provider (https://github.com/sachaw/anilist.bundle)
Error comes from its metadata creation however PlexAPI should handle it without breaking.

**Enviroment (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Plex version: 1.21.2.3943
 - Python Version: 3.9.1
 - PlexAPI version: 4.3.1

**Additional context**
https://github.com/RickDB/PlexAniSync/issues/47

**Comment by JonnyWong16** [comment]
Do you have seasons hidden for the show in Plex?
![image](https://user-images.githubusercontent.com/9099342/106977518-5ac59280-670f-11eb-9192-742d2e989f5d.png)

That would be related to this Plex bug that never got addressed.
https://forums.plex.tv/t/parentratingkey-not-in-episode-xml-when-seasons-are-hidden/300553

**Comment by katekyonni** [comment]
Yes, I do have seasons hidden for the whole library. That's probably it.
