### ISSUE TITLE
.search(unwatched=True) broken with recent PMS update

### ISSUE THREAD

**Issue by ParadoxGBB** [pkkid/python-plexapi#691]
**Describe the issue**

Even with the updates outlined in #623, these appear to be broken again with the recent update to Plex 1.22.0.4163. I'd appreciate someone confirming or denying that this is working.

**Code snippets**

for currentSection in plexServer.library.sections():
	if currentSection.type == 'movie':
		unwatchedLibraryItems = currentSection.search(unwatched=True)
	elif currentSection.type == 'video':
		unwatchedLibraryItems = currentSection.search(unwatched=True)
	elif currentSection.type == 'show':
		unwatchedLibraryItems = currentSection.searchEpisodes(**{'episode.unwatched':True})

This worked before.

**Expected behavior**

Successful search, results returned. Instead:

[3/10/2021 3:10:25 PM] [python.exe]:   File "C:\Python\lib\site-packages\plexapi\library.py", line 717, in _cleanSearchFilter
[3/10/2021 3:10:25 PM] [python.exe]:     raise BadRequest('Unknown filter category: %s' % category)
[3/10/2021 3:10:25 PM] [python.exe]: plexapi.exceptions.BadRequest: Unknown filter category: unwatched

**Enviroment (please complete the following information):**
 - OS: Windows 10
 - Plex version 1.22.0.4163
 - Python Version Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
 - PlexAPI version 4.3.1

**Additional context**

**Comment by Darthmiki** [comment]
All filters stopped working. filterFields() returns empty list.

**Comment by ParadoxGBB** [comment]
Seemed to be called out in #595, towards the bottom

**Comment by ParadoxGBB** [comment]
Patched 4.4.1 with the change in https://github.com/pkkid/python-plexapi/commit/16a1c610acc79b01b3148955dff509954e3e0417 and things work great on latest bits. Thanks!
