### ISSUE TITLE
Library search breaks early when using a PlexAPI operator

### ISSUE THREAD

**Issue by JonnyWong16** [pkkid/python-plexapi#694]
**Describe the issue**
The current library search loop breaks when no results are found.

https://github.com/pkkid/python-plexapi/blob/4.4.1/plexapi/library.py#L691

If a PlexAPI operator is used (e.g. `viewCount__gt=0`), the first batch of results may return 0 results (i.e. There are no items with a view count greater than 1 in the first 100 items (`container_size`)). This causes the loop to break without continuing the search through the rest of the items.

**Code snipppets**
```python
>>> library = plex.library.section("TV Shows")
>>> results = library.search(libtype='episode', container_size=1, viewCount__gte=0)
>>> print(len(results))
0
```
![image](https://user-images.githubusercontent.com/9099342/111120831-19ec4500-8529-11eb-8de7-cc2ae2af4634.png)

**Expected behavior**
Search should continue looping through the rest of the items.

Proposed solution is to add a check if the container exceeds the total number of items to exit the loop.

https://github.com/pkkid/python-plexapi/blob/4.4.1/plexapi/library.py#L707

```python
if container_start > self.totalSize:
    break
```

**Enviroment (please complete the following information):**
 - PlexAPI version: 4.4.1

**Comment by Hellowlol** [comment]
There is no way to check this without pulling all the info. So if plexapi operators is used we should just ignore and pull everything.

**Comment by JonnyWong16** [comment]
I can't think of any reason we would want to break early.

It should break when either
1. We reached the `maxresults` (`wanted_number_of_items <= len(results)`), or
2. We run out of items (`container_start > self.totalSize`).
