### ISSUE TITLE
removing a friend when they haven' accepted an invite, fails.

### ISSUE THREAD

**Issue by Jomack16** [pkkid/python-plexapi#767]
Found that the REMOVEINVITE variable in myplex.py had a URL of "'https://plex.tv/api/invites/requested/{userId}?friend=1&server=1&home=1'"

Because REMOVEINVITE is the alternative when evaluating user.friend to False on line 384 of myplex.py, the URL should read: "'https://plex.tv/api/invites/requested/{userId}?friend=1&server=1&home=0'"

Verified this by manually removing a user that hadn't accepted an invite, while watching the call that was made in DevTools.
An example of those request headers is attached.

[RemoveUserThatHasntAcceptedInvite-REQUEST HEADERS EXAMPLE.txt](https://github.com/pkkid/python-plexapi/files/6580912/RemoveUserThatHasntAcceptedInvite-REQUEST.HEADERS.EXAMPLE.txt)

**Comment by blacktwin** [comment]
I want to think that the params are relative to the the to be removed user. I thought I tested all the different combinations when I added/changed that and found that `True` for all params work universally.

**Comment by brianmiller** [comment]
So how do we remove a pending invite with plexapi?
