### ISSUE TITLE
Client TimeLine - empty response (All clients LG TV |  Plex Web etc)

### ISSUE THREAD

**Issue by IMCAgro** [pkkid/python-plexapi#769]
I had update plex to the lates version  1.23.2.4656
Now all clients return empty response in timeline function

Get Client form plex.clients() or from session

Besides if take client  from session :

Looks like Bug - maybe need add parametr - somethink like is_session_set : True | False for understanding is data actual
 client has wrong status,empty protocolCapabilities and all session params 
 need connect  it again  with baseurl , token for retriving actual data

```
` def get_lg_client(self, from_media=True):
        if from_media:
            for client in self.get_clients():
                if client.model == 'OLED65B9PLA': 
                    return client
            return None
        else:
            return self.get_from_session()`
```

Than just call
`lg.timelines(10)`

if make request (for example postMan) i had :

http://10.10.10.1:32400/player/timeline/poll?wait=0&commandID=1
200 with xml

Response code="400" status="Bad Request"

Via Plex API :

Inside Plex Server Logs :
 Request: [10.10.10.1:52596 (Subnet)] GET /player/timeline/poll?commandID=1&wait=0 (24 live) GZIP Signed-in Token
 Completed: [10.10.10.1:52596] 200 GET /player/timeline/poll?commandID=1&wait=0 (24 live) GZIP 0ms 303 bytes (pipelined: 3)

Response 
![image](https://user-images.githubusercontent.com/39766903/120903027-4d340100-c64c-11eb-8f64-7825ef941454.png)

**Enviroment (please complete the following information):**
 - OS: Linux
 - Plex version 1.23.2.4656
 - Python Version 3.7.8
 - PlexAPI version 4.5.2

**Comment by jjlawren** [comment]
The client timeline reporting is a bit iffy, especially with web-based clients. I normally see valid responses if the client is actively playing media, but it's not very reliable otherwise.

**Comment by IMCAgro** [comment]
In previous release its worked.I need this((( 

The main idea is generate color map each  second for smart led controller.

Where i can find that request ? Need capture local traffic? 
Inside web plex, menu  panel - i see ony /bandwidth and /session requests.And elipsed time is showing inside.

Maube its get data from socket ?

Have somebody seen  another point than :
ws://127.0.0.1:32400/:/websockets/notifications?X-Plex-Token

**Comment by IMCAgro** [comment]
UPD 
 Well sockets work great.

**Comment by Hellowlol** [comment]
I would use server.startAlertListener

**Comment by jjlawren** [comment]
Agree. Instead of polling every second use the websocket events to listen for updates.

What specific information do you need in realtime?

**Comment by IMCAgro** [comment]
Perfect if i had info about current played frame.
Current version work this way:
1) from timeline i take position of the current played video
2)  than pause player, start generate color map for next 20 seconds (its almost 2-3 seconds)
Color map is generated in next way
 From current video i take 20 frames( from each second).From each frame i get color pallete each side(up down left right)
When work is finish - i sync Tuya controller and player (its i called it :-) In real - just start plyer and Tuya at the same time)
Then in background work with frames until duration is over

**Comment by IMCAgro** [comment]
Strange
I make same api on PHP - and it return timeline from all clients (Web Lg )
If request make POST method - Its always give 400 - Bad Request
But GET is returned

**Comment by IMCAgro** [comment]
Confirm - Its really Plex bug.
