### ISSUE TITLE
Android TV client is not listed when querrying the connected client names

### ISSUE THREAD

**Issue by rockstar2020** [pkkid/python-plexapi#776]
**Describe the issue**
Hi,
I'm not able to see my plex client installed on Android TV when I run the following command.
For this reason I'm not able to play any media.
I can easily play contents on my FireTV but not on Android TV.
I used to have this problem with plex app on Samsung TV but I thought it's how the Samsung TV app is designed so didn't care back then.
I am pretty sure the client is already connected to the server.
Any help to troubleshoot this issue would be highly appreciated.

**Code snippets**
import logging
logging.basicConfig(level=logging.DEBUG)

baseurl = 'http://192.168.x.x:32400'
token = 'xxxxxxxxxxxxxxxxxxxx'
plex = PlexServer(baseurl, token)
for client in plex.clients():
    print ("Client: " + client.title)

**Expected behavior**
I expect tsee the Android TV client name listed after running this command.

**Enviroment (please complete the following information):**

 - OS: Server running on Ubuntu 20.04 and the client on Android TV
 - Plex version: 1.23.2.4656
 - Python Version: 3.7.3
 - PlexAPI version: 4.6.0

**Comment by jjlawren** [comment]
The `PlexServer.clients()` call only shows clients which are visible to the PMS instance via GDM discovery. This only works if GDM is enabled in PMS and if the client & server are on the same subnet. There are workarounds to relay the UDP broadcast packets across subnets, but that's an exercise for the reader.

There are other more involved methods for discovery, but easiest is probably just to use the IP of the Plex client directly:
```python
clienturl = 'http://10.1.2.3:32500'  # Default AndroidTV client port
token = 'YOUR_TOKEN'
androidtv = PlexClient(baseurl=clienturl, token=token)
androidtv.pause()
```

**Comment by rockstar2020** [comment]
Thanks for your quick reply @jjlawren,
I did try your code and seems to be working just fine.
Can you also suggest what command I can use to play specific media, similar to client.playMedia('xxxx') I used to use before?

**Comment by jjlawren** [comment]
Same calls will work. Look up the media from a `PlexServer` instance and pass that as an argument to `PlexClient.playMedia()`.

You may have to create the `PlexClient` instance with a `server` argument:
```python
server = PlexServer(...)
androidtv = PlexClient(server=server, baseurl=clienturl, token=token)
```

**Comment by rockstar2020** [comment]
Fantastic!
You're the best!
Thank you so much!
