### ISSUE TITLE
Error getting movie stream URL

### ISSUE THREAD

**Issue by ZePaiva** [pkkid/python-plexapi#794]
I'm currently trying to get a stream URL from a movie stored in plex with the following code but it is giving me an AttributeError:

```python
from plexapi.server import PlexServer

def get_movie_stream(token, name, host='http://127.0.0.1', port=32400):
    plex_addr=host+':'+str(port)
    server=PlexServer(plex_addr, token)
    movie=server.library.section('Movies').get(name)
    return movie.getStreamUrl()
``` 

The AttributteError Traceback I mentioned is this:
```
Traceback (most recent call last):
  File "src/main.py", line 61, in <module>
    main()
  File "src/main.py", line 57, in main
    plex_get.get_movie_stream(PLEX_TOKEN, 'movie1', host=HOST)
  File "/home/zero/Documents/tuts/plex/src/plex_get.py", line 7, in get_movie_stream
    return movie.getStreamUrl()
  File "/home/zero/.local/lib/python3.8/site-packages/plexapi/base.py", line 457, in __getattribute__
    value = super(PlexPartialObject, self).__getattribute__(attr)
AttributeError: 'Movie' object has no attribute 'getStreamUrl'
```

I looked a bit into the documentation and source and the method is supposed to work on playables and from what I understood the `Movie` class is descended from that same class so I do not understand what I'm doing wrong

I'm currently running on Ubuntu 20.04 with PlexAPI v4.6.1 and python 3.8.10

**Comment by Hellowlol** [comment]
Check the docs. Note the caps.

**Comment by ZePaiva** [comment]
@Hellowlol  didn't notice that, thanks and sorry for bothering

**Comment by Hellowlol** [comment]
No problem
