### ISSUE TITLE
Pre-load guids for sections.all()

### ISSUE THREAD

**Issue by glensc** [pkkid/python-plexapi#808]
**Describe the issue**

The library xml that contains all movie details, does have `guid`, but not `guids` attribute, so iterating such feed must always make sub-request to "reload" for "guids" attribute.

I.e. the feed XML like:
- http://localhost:32400/library/sections/5/all?type=1&X-Plex-Container-Size=100&X-Plex-Container-Start=0

contains:
```xml
    <Video
        ratingKey="1053" 
        key="/library/metadata/1053" 
        guid="plex://movie/5d776d18f617c900201863b0"
````

Code typically to process such feed is:

```py
for section in plex.library.sections():
	for movie in section.all():
		print(movie)
```

processing such feed is preferred performance-wise for when processing the whole library.

The reload could be avoided if the XML contains also XML nodes for guids.

Is it possible to pass some extra param for PMS, so it would include such details? could such support be requested from PMS if not yet possible?

**Additional context**

Originally thought this affects only Legacy Movie Agent:
- https://github.com/pkkid/python-plexapi/issues/807

**Comment by JonnyWong16** [comment]
There is no `include` parameter in the Plex Media Server API to include `<Guid>` in the `/all` response. That is something that should be requested from Plex.

**Comment by glensc** [comment]
Isn't there a generic one, like this?

`&includeFields=thumbBlurHash%2CartBlurHash`

**Comment by JonnyWong16** [comment]
There is no `include` parameter to include `<Guid>`. Unless there is one that I don't know about.

**Comment by glensc** [comment]
I as having in mind, that `includeFields` looks like generic one:

- `&includeFields=thumbBlurHash%2CartBlurHash`
- `&includeFields=guids`

I'm just guessing here.

**Comment by JonnyWong16** [comment]
There is no `include` parameter to include `<Guid>`.

**Comment by JonnyWong16** [comment]
I posted a feature request on the Plex Forums. You may vote on it.

https://forums.plex.tv/t/add-includeguids-url-parameter-to-return-external-guids/735620

**Comment by glensc** [comment]
@twolaw [said](https://github.com/Taxel/PlexTraktSync/discussions/469#discussioncomment-1334555):

> Yes, very good news!
> [confirmed](https://forums.plex.tv/t/implemented-add-includeguids-url-parameter-to-return-external-guids/735620/106) in Plex Media Server [1.24.3.5033](https://forums.plex.tv/t/plex-media-server/30447/462) (beta version)

**Comment by glensc** [comment]
1.24.3.5033-757abe6b4 seems to be out of beta, at least being updated in brew cask:
- https://github.com/Homebrew/homebrew-cask/pull/111529
