### ISSUE TITLE
Title names randomly reverting

### ISSUE THREAD

**Issue by burchill** [pkkid/python-plexapi#816]
I manage my library almost completely manually using `plexapi`.  I derive the title of each movie from the filename of each file, using my own naming schema, and I use plexapi to change the title in the metadata to reflect this derived name programmatically.  I also change the year in a similar manner.

I set the video's name with `movie.edit(**{"title.value":"<derived name>"})` and I then call `movie.reload()`.  This seems to work at first, and the movies have the right title when access with Python or viewed over Plex.

However, every so often, movie titles will convert to their original form (the base filename).  This appears to happen seemingly at random, and in between times when I use Plex.  Is this an issue with how `plexapi` sets the titles? If it helps, I have my media files on a separate hard drive, which I unplug occassionally.

**Comment by JonnyWong16** [comment]
Are you locking the field to prevent Plex from changing it when it does a metadata refresh?

![image](https://user-images.githubusercontent.com/9099342/129608564-0545f97e-161d-4b61-8eee-73aca4ff99df.png)

```py
movie.edit(**{
    "title.value": "<derived name>",
    "title.locked": 1
})
```

**Comment by JonnyWong16** [comment]
It should be the same thing, locking the Originally Available field.

![image](https://user-images.githubusercontent.com/9099342/130828382-39a07bc5-07fc-4db1-9fbf-2dcb2d1dd772.png)

```python
movie.edit(**{
    "title.value": "<derived name>",
    "title.locked": 1,
    "originallyAvailableAt.value": "2001-12-13",
    "originallyAvailableAt.locked": 1
})
```

**Comment by burchill** [comment]
Looks like that did the trick.  Do you know how to query the `originallyAvailableAt.locked` attribute of a video?

**Comment by JonnyWong16** [comment]
Accessing the `movie.fields` attribute will give you a list of locked Field` objects.
