### ISSUE TITLE
Streams list from MediaPart is empty

### ISSUE THREAD

**Issue by Damix48** [pkkid/python-plexapi#822]
**Describe the issue**

When call `.streams`, `.videoStreams()`, `.audioStreams()` or `.subtitleStreams()` from `plexapi.media.MediaPart` the return is a empty list. All other variables of `MediaPart` works.

**Code snippets**

```python
for show in tv_series_library.search("nadia"):
  print(show)
  for episode in show.episodes():
    print(episode.index)
    for media in episode.media:
      for part in media.parts:
        print(part.size)      # works
        print(part.streams)   # empty
```

**Expected behavior**

A list of `plexapi.media.MediaPartStream`

**Enviroment (please complete the following information):**

 - OS: [jupyter/base-notebook](https://hub.docker.com/r/jupyter/base-notebook)
 - Plex version 1.24.1.4931
 - Python Version 3.9.6
 - PlexAPI version 4.7.0

**Comment by JonnyWong16** [comment]
Your episode is only a partial object (anytime you get an item from `.all()` or `.search()`). You may need to `.reload()` the object to a full object for some attributes to be available.

```python
for show in tv_series_library.search("nadia"):
  print(show)
  for episode in show.episodes():
    episode.reload()
    print(episode.index)
    for media in episode.media:
      for part in media.parts:
        print(part.size)
        print(part.streams)
```

**Comment by Damix48** [comment]
Thank you!
