### ISSUE TITLE
How Can I Delete Subtitles which are stored in db etc

### ISSUE THREAD

**Issue by 666Warlock666** [pkkid/python-plexapi#823]
I'm trying to work out how to delete subtitles (as some subs are stored in DB?) after downloading

The idea is to download subtitles that have a title (usually this is created when plex to download sub) and retrieving this and deleting the DB version 

_(i'm aware theres no check for srt or sub file)_
```
from plexapi.server import PlexServer 
import plexapi

baseurl = 'http://192.168.1.24:32400'
token = 'abcdefgh'
plex = PlexServer(baseurl, token)
Movies =  plex.library.section('Movies')

title=input('ENTER PLEX MOVIE TITLE: - ')
for video in Movies.search(title):
    video = video.reload()
    path=video.media[0].parts[0].file.rsplit('/', 2)[1]
    for subtitle in video.subtitleStreams():
        print('Language = {}'.format(subtitle.languageCode))
        print('title = {}'.format(subtitle.title))
        print('Path = {}'.format(subtitle.key))
        print('Folder Path = {}'.format(path))
        #print(dir(subtitle.fetchItem))
        if not subtitle.title == None:
            print('DOWNLOAD SUBTITLE')
            plexapi.utils.download(baseurl+subtitle.key, token, filename=path+'.srt', savepath=path)
            #DELETE SUBTITLE

```

**Comment by blacktwin** [comment]
I don't believe that the subtitles are actually stored in the DB but rather the metadata folder. 

You could either download like you're doing, then delete the subtitle from the metadata folder and clean bundles. Or find the subtitle in the metadata folder and move it to the media location then clean bundles. I think.

**Comment by 666Warlock666** [comment]
According to Plex On demand subtitles are stored in the blob database?
https://support.plex.tv/articles/subtitle-search/

but i still not sure how to delete using the api

**Comment by 666Warlock666** [comment]
tried adding
```
   #DELETE SUBTITLE
   video.removeSubtitles(streamID=subtitle.id)
```

Bt this seems to ignore the ID given and delete all subtitles for movie?
