### ISSUE TITLE
`plexapi.library.MusicSection.search()` function returns entire library for a specific song title

### ISSUE THREAD

**Issue by XDGFX** [pkkid/python-plexapi#846]
### Describe the Bug

First I want to say thanks for creating and supporting this project! I can't believe I didn't find it sooner.

I'm using the `search()` function of a music library object to find if a song exists on my Plex server.

It works fine for most songs, however when searching for a specific song:

> Into Safety - Optimism In Negative Space,

the function returns every single song in my library.

### Code Snippets

```python
preferred_library = plex.library.sectionByID(int(preferred_library_id))

song = {
    'title': 'Into Safety - Optimism In Negative Space,',
    'artists': ['Thys'],
    'album': 'Thys Presents: ECCENTRIC O',
    'date': '2021-08-13',
    'isrc': 'NLCK41091014',
    'id': {'spotify': '4nFGUFbGKaKxsBBo2H2u0k'}
}

plex_songs = preferred_library.search(
    title=song["title"], libtype="track"
)
```

### Expected Behavior

The song doesn't exist in my library, so I would expect an empty list to be returned (`[]`).

### Additional Context

Searching in the Plex web interface returns no result for the title, as expected.

### Operating System and Version

Ubuntu 20.04 LTS (WSL)

### Plex Media Server Version

1.24.4.5081-e362dc1ee

### Python Version

3.8.5

### PlexAPI Version

4.7.2

**Comment by JonnyWong16** [comment]
That appears to be a bug in Plex with how they are handling trailing commas.

![image](https://user-images.githubusercontent.com/9099342/138575186-866d5f4e-910c-4bcd-8390-fdc74ecb45c4.png)

![image](https://user-images.githubusercontent.com/9099342/138575207-b2b83f42-cf07-4ec6-a200-4bd8f62f372a.png)

The `LibrarySection.search()` method in PlexAPI uses the Advanced Filters in Plex Web.
