### ISSUE TITLE
Add missing Track attributes

### ISSUE THREAD

**Issue by wdckwrth** [pkkid/python-plexapi#895]
### Describe the Bug

Found a few more atributes that are missing from Track.

lastSkippedAt
mood
mediaSize
mediaBitrate
trash
source
id

Trying to access any of these results in the following exception:

Exception has occurred: AttributeError
'Track' object has no attribute 'lastSkippedAt'
  ...

### Code Snippets

```python
import plexapi

plex = PlexServer(base_url, token, session)
music_section = plex.library.section('Music')

availableFields = [f.key.split('.')[-1] for f in music_section.listFields(libtype="track")]
print(f'Available fields: {availableFields}')
track = music_section.search(filters={"track.title": "What's Up"}, libtype="track")
print(f'Play Count: {track[0].viewCount}')
print(f'lastSkippedAt: {track[0].lastSkippedAt}')
print(f'mood: {track[0].mood}')
print(f'mediaSize: {track[0].mediaSize}')
print(f'mediaBitrate: {track[0].mediaBitrate}')
print(f'trash: {track[0].trash}')
print(f'source: {track[0].source}')
print(f'id: {track[0].id}')
```

### Expected Behavior

Available attributes should be returned.

### Operating System and Version

Debian GNU/Linux 10

### Plex Media Server Version

1.24.3.5033

### Python Version

3.7.3

### PlexAPI Version

4.9.2

**Comment by JonnyWong16** [comment]
Not all search filters are attributes.

* `lastSkippedAt` is not an attribute in the XML data on the Plex server. The search filter appears to be entirely computed server side.
* `mood` is a tag. Mood `MediaTag` objects are listed under `Track.moods`.
* `mediaSize` is a server side filter for the file size of the track. `size` is an attribute for the `MediaPart` object of a track (e.g. `Track.media[0].parts[0].size`).
* `mediaBitrate` is a server side filter for the bitrate of the track. `bitrate` is an attribute for the `Media` object of a track (e.g. `Track.media[0].bitrate`).
* `trash` is a server side filter to check if the file exists. `exists` is an attribute for the `MediaPart` object of a track (e.g. `Track.media[0].parts[0].exists`).
* `source` is a tag. I don't actually know what a track "source" is and it's not implemented in PlexAPI, but if it gets implemented they would be `MediaTag` objects listed under `Track.sources`.
* `id` is a server side filter for the rating key (e.g. `Track.ratingKey`).
