### ISSUE TITLE
Plex Watchlist

### ISSUE THREAD

**Issue by glensc** [pkkid/python-plexapi#923]
### What is your feature request?

Add API for Plex watchlist feature:
- [End the Streaming Struggle with Plex](https://www.plex.tv/blog/end-the-streaming-struggle-with-plex/) (Plex blog news 5-april-2022)
- [Universal Watchlist (beta)](https://support.plex.tv/articles/universal-watchlist-beta/) support page
- [Plex forum thread](https://forums.plex.tv/t/find-where-to-watch-something-with-discover-and-your-watchlist/782131) about this news
- [Discussion in PlexTraktSync](https://github.com/Taxel/PlexTraktSync/issues/876)

### Additional Context

I'm going to just leave it here, so there's a place to discuss it.

**Comment by technomensch** [comment]
If this is ever implemented, would it be possible for someone to please drop a note here too - https://forums.plex.tv/t/sync-watchlist-with-trakt/786101?  Thanks in advance.
