### ISSUE TITLE
Access watchlist of a Home user

### ISSUE THREAD

**Issue by twolaw** [pkkid/python-plexapi#957]
### What is your feature request?

Since #922 we can get the watchlist of a signed-in Plex user through `myPlexAccount.watchlist()`
Home users don't have a `myPlexAccount` so how can we get their watchlist ?

Just like signed-in Plex users, home users also have a watchlist stored on plex servers at _https://metadata.provider.plex.tv/library/sections/watchlist/all_

### Are there any workarounds?

not that i know

**Comment by JonnyWong16** [comment]
Plex Home users can have a `MyPlexAccount`.

1. For Plex.tv accounts in your Plex Home, just login using the account credentials.
2. For managed users in your Plex Home, user switching isn't implemented in PlexAPI yet, but here is a workaround for now:

```py
from plexapi.myplex import MyPlexAccount
account = MyPlexAccount('<USERNAME>', '<PASSWORD>')
user = account.user('Home Username')
data = account.query(f'https://plex.tv/api/home/users/{user.id}/switch', method=account._session.post)
homeAccount = MyPlexAccount(token=data.attrib.get('authenticationToken'))
homeAccount.watchlist()
```
