### ISSUE TITLE
Discover search is not working

### ISSUE THREAD

**Issue by gazpachoking** [pkkid/python-plexapi#969]
### Describe the Bug

The discover search always returns 0 results, even when it should.

### Code Snippets

```python
results = MyPlexAccount(**login).searchDiscover('Lightyear')
```

### Expected Behavior

The search should produce results.

### Additional Context

The current code expecting a `SearchResult` key in the `MediaContainer` dict. Instead, plex is returning a `SearchResults` key which has discovery results, as well as the free plex on demand results. The code needs to look one level deeper to get discovery results.
https://github.com/pkkid/python-plexapi/blob/650fbac312c09c5775761c6f388fc36c976a8621/plexapi/myplex.py#L846

### Operating System and Version

Windows 10

### Plex Media Server Version

1.26.2.5797

### Python Version

3.10.4

### PlexAPI Version

4.11.2

**Comment by JonnyWong16** [comment]
Plex changed their API response...

**Comment by heylookltsme** [comment]
I'm also running into this issue. Any chance the PR that fixes this will be merged soon? Thanks!
