### ISSUE TITLE
String filter: "!=" for "does not contain" is turning into "!==" for "is not" 

### ISSUE THREAD

**Issue by cardonas** [pkkid/python-plexapi#989]
### Describe the Bug

When creating smart collection with advanced query. Filter for "does not contain" (!=) does not work properly when asking for movies that do not contain a string in the title. Instead it is being interpreted as (!==) which is the value for "is not". I'm creating the collection by parsing out a Python dictionary to the arguments of createCollection(). I'm trying to filter out the Alien vs. Predator movies from the my Alien collection but they are still showing up.

### Code Snippets

```python
def create_collections(lib_section: LibrarySection):
    collections = get_collections_config()
    for collection in collections:
        new_collection = lib_section.createCollection(
            collection["collection_title"],
            smart=collection["smart"],
            sort="year:asc",
            libtype="movie",
            filters=collection["filters"],
        )
        print([item.title for item in new_collection.items()])

  {
    "collection_title": "Aliens Collection",
    "smart": true,
    "filters": {
      "and": [
        {
          "title": "Alien"
        },
        {
          "title!=": "Predator"
        },
        {
          "genre!=": "Animation"
        }
      ]
    }
  }
```

### Expected Behavior

I expected to see "does not contain" in the filter box of the web app for that collection and that specific filter and the Alien vs. Predator movies not to appear in the collection.

### Additional Context

I had located the lines that is causing this to happen in plexapi.library._validateFieldOperator. Lines 1042 & 1043. The if block is adding an additional '=' if the operator is '=' or '!='. But if you do that it makes the operator '!==' which is 'is not' according to the documentation and does will never allow anyone to do 'does not contain' which is '!=' according to the documentation. I commented out these lines and it worked as expected. 

### Operating System and Version

MacOS 12.5 Monterey

### Plex Media Server Version

1.28.0.5998

### Python Version

3.10.5

### PlexAPI Version

4.11.2

**Comment by JonnyWong16** [comment]
Drop the trailing `=` for all filters.
```py
"filters": {
  "and": [
    {
      "title": "Alien"
    },
    {
      "title!": "Predator"
    },
    {
      "genre!": "Animation"
    }
  ]
}
```

The documentation should be updated from

> The trailing `=` on the operator may be excluded.

to say

> The trailing `=` on the operator should be excluded.

The examples in the documentation are correct since they do not show any trailing `=` signs.

**Comment by cardonas** [comment]
The the example are correct but you wouldn't know that based list of operators. If it is not required to put the trailing `=` sign then I believe it should be removed from the list of operators in the documentation. And the line in the documentation: "The trailing = on the operator may be excluded." Is miss leading as it say "may" not that you have to in order for the operator to work as intended.

**Comment by JonnyWong16** [comment]
Yeah, I agree. Which is why I said that sentence should be updated.

**Comment by cardonas** [comment]
Oh sorry, that was my fault there. I didn't read far enough. But think if would be better to just remove it form the operator list as some people might not read far enough to see that line just before the examples.

**Comment by JonnyWong16** [comment]
When I originally wrote the documentation for the operators, I figured a "blank" for `is` looked weird.

* : is
* `!`: is not

vs. 

* `=`: is
* `!=`: is not

I do understand how that can be confusing though.

**Comment by cardonas** [comment]
I honestly prefer to define the operator entirely myself instead of having a function added change the operator like that because will lead to confusion and debug issues in the long run. I still honestly believe that there is not need to append a `=` sign with in the python code. Makes it clearer to the user of the api because the are using exactly what you define instead of having to worry about if something else is happening in the background that can mess up what they are doing.

**Comment by JonnyWong16** [comment]
I think it should be fine if the documentation is updated. The user doesn't really need to know the internals of how the Plex Media Server API expects the operators. If the documentation had just said

* `!`: is not
* `!=`: does not contain

you would have never known that the Plex Media Server API actually uses `!==` internally.

To change the behaviour of the extra `=` at this point would break a lot of existing code. I don't think this issue is big enough to implement such a large breaking change when it can be solved with a documentation update.

**Comment by cardonas** [comment]
but changing the documentation to say that would be backwards because currently the documeantion is:

- `!==`: is not
- `!=`: does not contain

so instead the documentation should be 

- `!=`: is not
- `!`: does not contain.

That would preserve the current functionality.

**Comment by cardonas** [comment]
Anyway, Yes the documentation should be changed to reflex more what the user exactly needs to use.

**Comment by JonnyWong16** [comment]
Yes, I just made a typo above.

**Comment by JonnyWong16** [comment]
Is this acceptable?

![image](https://user-images.githubusercontent.com/9099342/180668694-2caa3e96-3ffc-4df7-a042-5ea4b29200de.png)

**Comment by cardonas** [comment]
Looks good to me.
