### ISSUE TITLE
Feature request: download, notifications, etc.

### ISSUE THREAD

**Issue by Hellowlol** [pkkid/python-plexapi#99]
I'll probably end up doing this myself, I just wanted to write it down as a reminder 

- [x] download
- [x] notifications https://github.com/mjs7231/python-plexapi/commit/6b1ae844c5112a2d7ce6f3febad3f436221d1a12
- [ ] transcode jobs
- [ ] optimize media
- [ ] share/unshare
- [x] delete https://github.com/mjs7231/python-plexapi/pull/110
- [ ] add/delete users

**Comment by mjs7231** [comment]
Juts curious, whats the difference between sync (which someone added years ago) and download?

**Comment by Hellowlol** [comment]
Sync doesn't seem to download the files, only listing the synced items and telling the server some thing is synced. I could be wrong tho.

**Comment by Hellowlol** [comment]
Added in https://github.com/mjs7231/python-plexapi/pull/100/commits/0c987d6a73e3d4da243603e5d208212824fbc366

**Comment by mjs7231** [comment]
Be careful with delete. If the server doesn't validate that delete is enabled, maybe we should get the setting and validate it on our end.

Not sure what events are, but it sounds interesting.

**Comment by Hellowlol** [comment]
I haven't really looked into how to delete a item. I was hoping I could send a http delete request and pms would send http 405 if it wasn't enabled. And we could just handle it from there. I'll start on this today.

**Comment by mjs7231** [comment]
You should probably work on the 3.0.0 branch (or a fork if you wish), or we're never have it conflict free. :D

**Comment by Hellowlol** [comment]
I forked of 3.0.0 and targeted that branch for the pr.

**Comment by pkkid** [comment]
I realized I basically recreated the same type of bug which is a list of enhancements. Merging the two now.
