### ISSUE TITLE
playlist.uploadPoster broken in 4.12.0 

### ISSUE THREAD

**Issue by rnagabhyrava** [pkkid/python-plexapi#991]
### Describe the Bug

playlist.uploadPoster doesn't work as expected and throws NotFound error in 4.12 release. I remember playlist.edit(summary) throwing error aswell but I am unable to reproduce it now. I read the release notes but doesn't look like it is listed as a breaking change.

### Code Snippets

```python
# Read some playlist
myPlaylist = plex.playlist("playlist name")

# This throws NotFound Error in 4.12 whereas in previous releases it updates the playlist post without any errors.
myPlaylist.uploadPoster("https://some-url/")
```

### Expected Behavior

uploadPoster should upload the given url as poster but fails now.

### Operating System and Version

debian 11.4 and python:3.10-alpine (docker)

### Plex Media Server Version

1.27.2.5929

### Python Version

3.10

### PlexAPI Version

4.12

**Comment by JonnyWong16** [comment]
I screwed up 4094678e0da79bd1e587eb5062c539b30cd65bca, my bad. I will fix it. Thanks for the bug report.
