### ISSUE TITLE
Automatically sharing and revoking library access through API.

### ISSUE THREAD

**Issue by Wamy-Dev** [pkkid/python-plexapi#997]
### What is your feature request?

I would like to automatically share a library with an email so they can have access to my libraries. This would make a lot of things easier.

### Are there any workarounds?

Using the webui to manually share.

**Comment by JonnyWong16** [comment]
This is already implemented in PlexAPI.

https://python-plexapi.readthedocs.io/en/stable/modules/myplex.html#plexapi.myplex.MyPlexAccount.inviteFriend
